# utils/recommendation_intelligence.py - evidence-backed recommendation wording
from __future__ import annotations

from collections.abc import Mapping

import pandas as pd

from config import THRESHOLDS

from .helpers import safe_float, safe_int


def _row_value(row: Mapping | pd.Series | dict, *keys: str, default: object = "") -> object:
    if row is None:
        return default
    for key in keys:
        try:
            if isinstance(row, pd.Series):
                if key in row.index:
                    return row.get(key, default)
                upper = key.upper()
                if upper in row.index:
                    return row.get(upper, default)
                title = key.title()
                if title in row.index:
                    return row.get(title, default)
            elif isinstance(row, Mapping):
                if key in row:
                    return row.get(key, default)
                upper = key.upper()
                if upper in row:
                    return row.get(upper, default)
                title = key.title()
                if title in row:
                    return row.get(title, default)
        except Exception:
            continue
    return default


def _text(row: Mapping | pd.Series | dict, *keys: str, default: str = "") -> str:
    value = _row_value(row, *keys, default=default)
    if value is None:
        return default
    try:
        if pd.isna(value):
            return default
    except Exception:
        pass
    return str(value).strip()


def _num(row: Mapping | pd.Series | dict, *keys: str, default: float = 0.0) -> float:
    return safe_float(_row_value(row, *keys, default=default), default)


def _entity(rec: Mapping | pd.Series | dict) -> str:
    return _text(rec, "Entity", "ENTITY", "ENTITY_NAME", "WAREHOUSE_NAME", "TASK_NAME", default="the affected object")


def _source_key(rec: Mapping | pd.Series | dict) -> str:
    return " ".join([
        _text(rec, "Source", "SOURCE"),
        _text(rec, "Category", "CATEGORY"),
        _text(rec, "Finding", "FINDING"),
        _text(rec, "Entity Type", "ENTITY_TYPE"),
    ]).upper()


def _money(value: float) -> str:
    return f"${value:,.0f}/mo" if abs(value) >= 1 else "$0/mo"


def harden_recommendation(rec: Mapping | pd.Series | dict) -> dict:
    """Return a recommendation with DBA decision fields and evidence guardrails."""
    out = dict(rec)
    source_key = _source_key(out)
    entity = _entity(out)
    finding = _text(out, "Finding", "FINDING", default="Finding generated by OVERWATCH")
    savings = _num(out, "Estimated Monthly Savings", "EST_MONTHLY_SAVINGS")
    proof_query = _text(out, "Proof Query", "PROOF_QUERY", "Verification Query", "VERIFICATION_QUERY")

    decision = "Triage evidence before changing settings"
    action = _text(out, "Action", "RECOMMENDED_ACTION", default="Open the owning OVERWATCH workflow and validate the finding.")
    evidence = f"{finding}; estimated value {_money(savings)}."
    safe_next = action
    proof = "Attach before/after evidence from the provided proof query before closing the action."
    do_not = "Do not close the item from the recommendation text alone."
    owner_route = _text(out, "Owner", "OWNER", default="DBA")
    confidence = "Medium - actionable finding with verification query required"
    decision_gate = "Investigate"

    if "IDLE" in source_key and "WAREHOUSE" in source_key:
        idle_hours = safe_int(_row_value(out, "IDLE_HOURS", "Idle Hours", default=0))
        idle_credits = _num(out, "Baseline Value", "BASELINE_VALUE", "Current Value", "CURRENT_VALUE", default=0.0)
        suspend_minutes = safe_int(THRESHOLDS.get("idle_warehouse_minutes", 5), 5)
        decision = "Implement suspend control"
        action = (
            f"Set {entity} AUTO_SUSPEND to {suspend_minutes} minutes and keep AUTO_RESUME enabled after checking "
            "that it is not an approved always-on service warehouse."
        )
        evidence = (
            f"{entity}: {idle_hours:,} idle hour(s), {idle_credits:,.4f} idle credits, "
            f"{_money(savings)} estimated avoidable spend."
        )
        safe_next = (
            f"Run the proof query, confirm zero-query metering hours, then apply AUTO_SUSPEND={suspend_minutes * 60} "
            "through DBA change control."
        )
        proof = "After 7 days, rerun the idle proof query and close only if idle credits and idle hours dropped."
        do_not = "Do not disable the warehouse or downsize it based only on idle-hour evidence."
        confidence = "High - direct warehouse metering joined to query activity"
        decision_gate = "Ready to change"

    elif "SPILL" in source_key:
        spill_gb = _num(out, "Current Value", "REMOTE_GB", "REMOTE_SPILL_GB")
        decision = "Investigate memory pressure before resizing"
        action = (
            f"For {entity}, pull the top spilling query profiles and tune repeated joins/sorts first; resize only "
            "if the same workload still spills after query-level review."
        )
        evidence = f"{entity}: {spill_gb:,.2f} GB remote spill in the recommendation window."
        safe_next = (
            "Open Warehouse Health > Capacity Brief, identify the query IDs causing spill, and decide between SQL tuning, "
            "workload isolation, or a one-step warehouse size test."
        )
        proof = "Show remote spill GB and queue time trend lower after the change; attach top query IDs used for diagnosis."
        do_not = "Do not upsize blindly; remote spill can be caused by SQL shape and may just multiply cost."
        confidence = "Medium - spill is real, but the correct fix depends on query profile evidence"
        decision_gate = "Evidence required before change"

    elif "TASK" in source_key and "FAIL" in source_key:
        failures = _num(out, "Current Value", "MEASURED_DELTA", "FAILURES")
        decision = "Open a reliability incident"
        action = (
            f"Treat {entity} as a task reliability incident: identify the latest failure signature, confirm owner, "
            "fix root cause, then retry only after the blocker is cleared."
        )
        evidence = f"{entity}: {failures:,.0f} failed run(s) in the loaded window."
        safe_next = "Open Workload Operations > Task graphs, inspect TASK_HISTORY and downstream impact, then attach owner approval."
        proof = "Close only with a successful TASK_HISTORY run after the fix plus recovery notes in the action queue."
        do_not = "Do not EXECUTE TASK repeatedly until the failure category and dependency blocker are understood."
        owner_route = _text(out, "Owner", "OWNER", default="Data Engineering")
        confidence = "High - task failure count is direct operational evidence"
        decision_gate = "Incident"

    elif "QUERY FAILURE" in source_key or ("FAILED QUER" in source_key and "WAREHOUSE" in source_key):
        failures = _num(out, "Current Value", "FAILURES")
        decision = "Route repeated error signatures"
        action = (
            f"For {entity}, group failed queries by error code and owner, then route the top repeated signature to "
            "the owning team with sample query IDs."
        )
        evidence = f"{entity}: {failures:,.0f} failed query event(s) in the loaded window."
        safe_next = "Open Workload Operations > Query diagnosis filtered to this warehouse and capture the top error code."
        proof = "Attach before/after failure counts and sample query IDs; close only after the repeated signature stops."
        do_not = "Do not change warehouse size for failed queries unless queue/spill evidence also points to capacity pressure."
        confidence = "Medium - failure count is specific, root cause requires error-code detail"
        decision_gate = "Route owner"

    out["Decision"] = decision
    out["Action"] = action
    out["Evidence Packet"] = evidence
    out["Safe Next Action"] = safe_next
    out["Proof Required"] = proof
    out["Do Not Do"] = do_not
    out["Owner Route"] = owner_route
    out["Confidence"] = confidence
    out["Decision Gate"] = decision_gate
    if proof_query:
        out["Proof Required"] = f"{proof} Proof query is attached."
    out.setdefault("Verification Status", "Pending")
    out.setdefault("Recovery Evidence", out["Proof Required"])
    out.setdefault("Owner Evidence", out["Evidence Packet"])
    return out


def harden_recommendation_rows(recs: list[dict]) -> list[dict]:
    return [harden_recommendation(rec) for rec in recs or []]


def warehouse_sizing_decision(row: Mapping | pd.Series | dict) -> dict:
    """Classify Warehouse Health sizing evidence without generic upsize advice."""
    warehouse = _entity(row)
    size = _text(row, "WAREHOUSE_SIZE", "Warehouse Size", default="unknown size")
    spill = _num(row, "REMOTE_SPILL_GB", "Remote Spill GB")
    queue_sec = _num(row, "AVG_QUEUE_SEC", "Avg Queue Sec")
    credits = _num(row, "TOTAL_CREDITS", "Total Credits")
    queries = safe_int(_row_value(row, "TOTAL_QUERIES", default=0))
    cache_pct = _num(row, "AVG_CACHE_PCT", "Avg Cache Pct")
    spill_threshold = safe_float(THRESHOLDS.get("spill_warning_gb", 5), 5)

    evidence = (
        f"{warehouse} ({size}): {queries:,} queries, {credits:,.2f} credits, "
        f"{queue_sec:,.2f}s avg queue, {spill:,.2f} GB remote spill, {cache_pct:,.1f}% cache."
    )
    if spill > spill_threshold and queue_sec > 5:
        return {
            "DECISION": "Capacity incident: test isolation or one-step scale-up",
            "EVIDENCE_PACKET": evidence,
            "SAFE_NEXT_ACTION": "Capture top spilling query IDs, then run a controlled one-size-up or multi-cluster test for the same workload window.",
            "PROOF_REQUIRED": "Queue seconds and remote spill GB both decline for the same workload class after the change.",
            "DO_NOT_DO": "Do not leave the larger setting permanent without before/after proof.",
        }
    if spill > spill_threshold:
        return {
            "DECISION": "Memory pressure: tune query shape first",
            "EVIDENCE_PACKET": evidence,
            "SAFE_NEXT_ACTION": "Inspect query profiles for joins, sorts, and scans that repeatedly spill before changing WAREHOUSE_SIZE.",
            "PROOF_REQUIRED": "Top spilling query IDs show lower spill after SQL, clustering, or warehouse-isolation work.",
            "DO_NOT_DO": "Do not upsize blindly; spill alone is not proof of under-sized compute.",
        }
    if queue_sec > 5:
        return {
            "DECISION": "Concurrency pressure: adjust scaling, not memory",
            "EVIDENCE_PACKET": evidence,
            "SAFE_NEXT_ACTION": "Check burst windows and MAX_CLUSTER_COUNT; prefer multi-cluster for concurrency if spill is low.",
            "PROOF_REQUIRED": "Queued overload time drops without a matching credit spike outside the target window.",
            "DO_NOT_DO": "Do not upsize just to reduce queueing when the symptom is concurrent demand.",
        }
    if credits < 1 and size.upper() not in {"", "X-SMALL", "XSMALL", "UNKNOWN SIZE"}:
        return {
            "DECISION": "Downsize candidate",
            "EVIDENCE_PACKET": evidence,
            "SAFE_NEXT_ACTION": "Ask the owner whether the workload is latency-sensitive, then test one size down during the same usage window.",
            "PROOF_REQUIRED": "Runtime and failure rate stay stable while credits drop after the test.",
            "DO_NOT_DO": "Do not downsize shared or SLA-sensitive warehouses without owner approval.",
        }
    return {
        "DECISION": "No sizing change from this evidence",
        "EVIDENCE_PACKET": evidence,
        "SAFE_NEXT_ACTION": "Keep monitoring; route only if queue, spill, or cost deltas cross thresholds.",
        "PROOF_REQUIRED": "No proof needed unless a future setting change is proposed.",
        "DO_NOT_DO": "Do not create a change ticket from a clean sizing row.",
    }


def duplicate_query_decision(row: Mapping | pd.Series | dict) -> dict:
    signature = _text(row, "QUERY_SIG", "Query Sig", default="query pattern")
    executions = safe_int(_row_value(row, "EXECUTION_COUNT", default=0))
    users = safe_int(_row_value(row, "USER_COUNT", default=0))
    wasted_sec = _num(row, "TOTAL_WASTED_SEC", "Total Wasted Sec")
    cloud_credits = _num(row, "CLOUD_CREDITS", "Cloud Credits")
    return {
        "DECISION": "Materialize or cache only if the same result is reused",
        "EVIDENCE_PACKET": (
            f"{executions:,} executions across {users:,} user(s), {wasted_sec:,.0f}s repeated runtime, "
            f"{cloud_credits:,.4f} cloud-services credits; signature: {signature[:120]}"
        ),
        "SAFE_NEXT_ACTION": "Confirm literals and result reuse, then choose result cache hygiene, dynamic table, or materialized view.",
        "PROOF_REQUIRED": "Execution count and total elapsed seconds drop for the same query signature.",
        "DO_NOT_DO": "Do not create a materialized view until the repeated query has stable semantics and owner demand.",
    }
