-- OVERWATCH synthetic 5TB-scale simulation data
-- Default mode: lightweight metadata simulation plus bounded synthetic rows.
-- This script does NOT physically materialize 5TB.

USE DATABASE DBA_MAINT_DB;
USE SCHEMA OVERWATCH;
USE WAREHOUSE COMPUTE_WH;

CALL SP_PERF_TEST_GUARDRAIL_CHECK('LIGHTWEIGHT_METADATA', FALSE);

CREATE OR REPLACE TABLE PERF_TEST_TABLE_INVENTORY AS
SELECT
    'PERF_TEST_DB_' || LPAD(MOD(SEQ4(), 8)::VARCHAR, 2, '0') AS TABLE_CATALOG,
    'PERF_TEST_SCHEMA_' || LPAD(MOD(SEQ4(), 20)::VARCHAR, 2, '0') AS TABLE_SCHEMA,
    'PERF_TEST_FACT_' || LPAD(SEQ4()::VARCHAR, 4, '0') AS TABLE_NAME,
    ROUND(5 * 1024 * 1024 * 1024 * 1024 / 240, 0) AS ACTIVE_BYTES,
    UNIFORM(10000000, 800000000, RANDOM()) AS ROW_COUNT,
    CASE
        WHEN MOD(SEQ4(), 9) = 0 THEN 'CUSTOMER_PII'
        WHEN MOD(SEQ4(), 7) = 0 THEN 'CLAIMS'
        WHEN MOD(SEQ4(), 5) = 0 THEN 'POLICY'
        ELSE 'OPERATIONS'
    END AS DATA_DOMAIN,
    CASE WHEN MOD(SEQ4(), 6) = 0 THEN 'HIGH' ELSE 'NORMAL' END AS SKEW_PROFILE,
    CURRENT_TIMESTAMP() AS GENERATED_AT
FROM TABLE(GENERATOR(ROWCOUNT => 240));

CREATE OR REPLACE TABLE PERF_TEST_QUERY_HISTORY AS
WITH base AS (
    SELECT
        SEQ4() AS N,
        DATEADD('second', -UNIFORM(0, 2592000, RANDOM()), CURRENT_TIMESTAMP()) AS START_TIME,
        CASE
            WHEN MOD(SEQ4(), 35) = 0 THEN 'FAILED_WITH_ERROR'
            ELSE 'SUCCESS'
        END AS EXECUTION_STATUS
    FROM TABLE(GENERATOR(ROWCOUNT => 250000))
)
SELECT
    'PERF_TEST_Q_' || LPAD(N::VARCHAR, 12, '0') AS QUERY_ID,
    START_TIME,
    DATEADD('second', UNIFORM(1, 900, RANDOM()), START_TIME) AS END_TIME,
    CASE
        WHEN MOD(N, 10) IN (0, 1, 2, 3) THEN 'WH_ALFA_PROD_ETL'
        WHEN MOD(N, 10) IN (4, 5) THEN 'WH_ALFA_BI'
        WHEN MOD(N, 10) = 6 THEN 'WH_ALFA_ACTUARY'
        WHEN MOD(N, 10) = 7 THEN 'WH_TRXS_BI'
        WHEN MOD(N, 10) = 8 THEN 'COMPUTE_WH'
        ELSE 'DOC_AI_WH'
    END AS WAREHOUSE_NAME,
    CASE
        WHEN MOD(N, 12) IN (0, 1, 2, 3, 4, 5) THEN 'ALFA_EDW_PROD'
        WHEN MOD(N, 12) IN (6, 7) THEN 'ALFA_EDW_DEV'
        WHEN MOD(N, 12) = 8 THEN 'ALFA_EDW_SAN'
        WHEN MOD(N, 12) = 9 THEN 'TRXS_EDW_PROD'
        ELSE 'ADMIN'
    END AS DATABASE_NAME,
    'USER_' || LPAD(MOD(N, 350)::VARCHAR, 4, '0') AS USER_NAME,
    CASE
        WHEN MOD(N, 18) = 0 THEN 'SNOW_ACCOUNTADMINS'
        WHEN MOD(N, 18) = 1 THEN 'SNOW_SYSADMIN'
        WHEN MOD(N, 5) = 0 THEN 'ALFA_ANALYST_ROLE'
        ELSE 'ALFA_APP_ROLE'
    END AS ROLE_NAME,
    EXECUTION_STATUS,
    IFF(EXECUTION_STATUS = 'FAILED_WITH_ERROR', '100183', NULL) AS ERROR_CODE,
    UNIFORM(150, 900000, RANDOM()) AS TOTAL_ELAPSED_TIME,
    UNIFORM(0, 120000, RANDOM()) * IFF(MOD(N, 20) = 0, 1, 0) AS QUEUED_OVERLOAD_TIME,
    UNIFORM(0, 20000, RANDOM()) * IFF(MOD(N, 33) = 0, 1, 0) AS QUEUED_PROVISIONING_TIME,
    UNIFORM(0, 2000000000000, RANDOM()) AS BYTES_SCANNED,
    UNIFORM(0, 600000000000, RANDOM()) * IFF(MOD(N, 24) = 0, 1, 0) AS BYTES_SPILLED_TO_REMOTE_STORAGE,
    UNIFORM(0, 100, RANDOM()) AS PERCENTAGE_SCANNED_FROM_CACHE,
    'HASH_' || LPAD(MOD(N, 18000)::VARCHAR, 8, '0') AS QUERY_HASH,
    CASE
        WHEN MOD(N, 9) = 0 THEN 'OVERWATCH|ALFA|Cost & Contract|historical|PERF:LIGHT'
        WHEN MOD(N, 9) = 1 THEN 'OVERWATCH|ALFA|Warehouse Health|recent|PERF:LIGHT'
        WHEN MOD(N, 9) = 2 THEN 'OVERWATCH|ALFA|Workload Operations|recent|PERF:LIGHT'
        ELSE 'BI_TOOL'
    END AS QUERY_TAG
FROM base;

CREATE OR REPLACE TABLE PERF_TEST_WAREHOUSE_METERING_HISTORY AS
WITH base AS (
    SELECT
        SEQ4() AS N,
        DATEADD('hour', -SEQ4(), DATE_TRUNC('hour', CURRENT_TIMESTAMP())) AS START_TIME,
        ROUND(UNIFORM(1, 200, RANDOM()) / 10, 3) AS CREDITS_USED
    FROM TABLE(GENERATOR(ROWCOUNT => 720))
)
SELECT
    START_TIME,
    DATEADD('hour', 1, START_TIME) AS END_TIME,
    CASE
        WHEN MOD(N, 6) = 0 THEN 'WH_ALFA_PROD_ETL'
        WHEN MOD(N, 6) = 1 THEN 'WH_ALFA_BI'
        WHEN MOD(N, 6) = 2 THEN 'WH_ALFA_ACTUARY'
        WHEN MOD(N, 6) = 3 THEN 'WH_TRXS_BI'
        WHEN MOD(N, 6) = 4 THEN 'COMPUTE_WH'
        ELSE 'DOC_AI_WH'
    END AS WAREHOUSE_NAME,
    CREDITS_USED,
    ROUND(CREDITS_USED * 3.68, 2) AS ESTIMATED_DOLLARS
FROM base;

CREATE OR REPLACE TABLE PERF_TEST_TASK_HISTORY AS
WITH base AS (
    SELECT
        SEQ4() AS N,
        DATEADD('minute', -UNIFORM(0, 43200, RANDOM()), CURRENT_TIMESTAMP()) AS SCHEDULED_TIME,
        CASE WHEN MOD(SEQ4(), 22) = 0 THEN 'FAILED' ELSE 'SUCCEEDED' END AS STATE
    FROM TABLE(GENERATOR(ROWCOUNT => 50000))
)
SELECT
    'PERF_TEST_TASK_' || LPAD(MOD(N, 700)::VARCHAR, 4, '0') AS NAME,
    SCHEDULED_TIME,
    DATEADD('second', UNIFORM(1, 7200, RANDOM()), SCHEDULED_TIME) AS COMPLETED_TIME,
    STATE,
    CASE WHEN STATE = 'FAILED' THEN 'Synthetic task graph failure' ELSE NULL END AS ERROR_MESSAGE,
    'ALFA_EDW_PROD' AS DATABASE_NAME,
    'TASKS' AS SCHEMA_NAME,
    CASE WHEN MOD(N, 9) = 0 THEN 'ROOT' ELSE 'CHILD' END AS GRAPH_POSITION
FROM base;

CREATE OR REPLACE TABLE PERF_TEST_PROCEDURE_EXECUTION AS
WITH base AS (
    SELECT
        SEQ4() AS N,
        DATEADD('minute', -UNIFORM(0, 43200, RANDOM()), CURRENT_TIMESTAMP()) AS START_TIME,
        CASE WHEN MOD(SEQ4(), 28) = 0 THEN 'FAILED' ELSE 'SUCCEEDED' END AS STATUS
    FROM TABLE(GENERATOR(ROWCOUNT => 20000))
)
SELECT
    'PERF_TEST_PROC_' || LPAD(MOD(N, 250)::VARCHAR, 4, '0') AS PROCEDURE_NAME,
    START_TIME,
    DATEADD('second', UNIFORM(1, 5400, RANDOM()), START_TIME) AS END_TIME,
    STATUS,
    CASE WHEN STATUS = 'FAILED' THEN 'Synthetic procedure timeout' ELSE NULL END AS ERROR_MESSAGE,
    'ALFA_EDW_PROD' AS DATABASE_NAME,
    'PROCS' AS SCHEMA_NAME,
    'WH_ALFA_PROD_ETL' AS WAREHOUSE_NAME
FROM base;

CREATE OR REPLACE TABLE PERF_TEST_USER_ACTIVITY AS
SELECT
    'USER_' || LPAD(SEQ4()::VARCHAR, 4, '0') AS USER_NAME,
    CASE WHEN MOD(SEQ4(), 13) = 0 THEN 'SERVICE' ELSE 'PERSON' END AS USER_TYPE,
    DATEADD('day', -UNIFORM(0, 120, RANDOM()), CURRENT_TIMESTAMP()) AS LAST_LOGIN,
    CASE WHEN MOD(SEQ4(), 17) = 0 THEN 'NO_MFA' ELSE 'MFA_OK' END AS MFA_STATE,
    CASE WHEN MOD(SEQ4(), 19) = 0 THEN 'PRIVILEGED' ELSE 'STANDARD' END AS ACCESS_TIER
FROM TABLE(GENERATOR(ROWCOUNT => 1000));

CREATE OR REPLACE VIEW PERF_TEST_SCALE_SUMMARY_V AS
SELECT
    'metadata_simulation' AS MODE,
    ROUND(SUM(ACTIVE_BYTES) / POWER(1024, 4), 2) AS SIMULATED_TB,
    COUNT(*) AS SYNTHETIC_TABLES,
    (SELECT COUNT(*) FROM PERF_TEST_QUERY_HISTORY) AS QUERY_ROWS,
    (SELECT COUNT(*) FROM PERF_TEST_TASK_HISTORY) AS TASK_ROWS,
    (SELECT COUNT(*) FROM PERF_TEST_PROCEDURE_EXECUTION) AS PROCEDURE_ROWS,
    (SELECT COUNT(*) FROM PERF_TEST_USER_ACTIVITY) AS USER_ROWS
FROM PERF_TEST_TABLE_INVENTORY;

CREATE OR REPLACE VIEW PERF_TEST_EXPENSIVE_QUERY_CANDIDATES_V AS
SELECT
    WAREHOUSE_NAME,
    DATABASE_NAME,
    USER_NAME,
    ROLE_NAME,
    COUNT(*) AS QUERIES,
    ROUND(SUM(BYTES_SCANNED) / POWER(1024, 4), 3) AS TB_SCANNED,
    ROUND(SUM(BYTES_SPILLED_TO_REMOTE_STORAGE) / POWER(1024, 3), 2) AS REMOTE_SPILL_GB,
    ROUND(AVG(TOTAL_ELAPSED_TIME) / 1000, 2) AS AVG_ELAPSED_SEC,
    ROUND(PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY TOTAL_ELAPSED_TIME) / 1000, 2) AS P95_ELAPSED_SEC,
    SUM(IFF(EXECUTION_STATUS <> 'SUCCESS', 1, 0)) AS FAILED_QUERIES
FROM PERF_TEST_QUERY_HISTORY
GROUP BY WAREHOUSE_NAME, DATABASE_NAME, USER_NAME, ROLE_NAME
ORDER BY TB_SCANNED DESC, REMOTE_SPILL_GB DESC
LIMIT 500;

-- Medium mode:
-- If you need more pressure without physical 5TB, change the generator rowcount
-- values above and re-run after recording approval in PERF_TEST_RUNS. Keep row
-- caps at or below PERF_TEST_RUN_CONTROL.MEDIUM_ROW_CAP unless DBA approves.
