-- OVERWATCH performance-test cleanup
-- Drops only PERF_TEST_* objects in DBA_MAINT_DB.OVERWATCH.

USE DATABASE DBA_MAINT_DB;
USE SCHEMA OVERWATCH;

DROP VIEW IF EXISTS PERF_TEST_PRODUCTION_READINESS_V;
DROP VIEW IF EXISTS PERF_TEST_COST_ESTIMATE_V;
DROP VIEW IF EXISTS PERF_TEST_SNOWFLAKE_QUERY_REPORT_V;
DROP VIEW IF EXISTS PERF_TEST_APP_USAGE_REPORT_V;
DROP VIEW IF EXISTS PERF_TEST_EXPENSIVE_QUERY_CANDIDATES_V;
DROP VIEW IF EXISTS PERF_TEST_SCALE_SUMMARY_V;
DROP VIEW IF EXISTS PERF_TEST_CONTROL_SUMMARY_V;

DROP PROCEDURE IF EXISTS SP_PERF_TEST_GUARDRAIL_CHECK(VARCHAR, BOOLEAN);

DROP TABLE IF EXISTS PERF_TEST_5TB_PHYSICAL_FACT;
DROP TABLE IF EXISTS PERF_TEST_USER_ACTIVITY;
DROP TABLE IF EXISTS PERF_TEST_PROCEDURE_EXECUTION;
DROP TABLE IF EXISTS PERF_TEST_TASK_HISTORY;
DROP TABLE IF EXISTS PERF_TEST_WAREHOUSE_METERING_HISTORY;
DROP TABLE IF EXISTS PERF_TEST_QUERY_HISTORY;
DROP TABLE IF EXISTS PERF_TEST_TABLE_INVENTORY;
DROP TABLE IF EXISTS PERF_TEST_RISK_REGISTER;
DROP TABLE IF EXISTS PERF_TEST_BENCHMARK_RESULTS;
DROP TABLE IF EXISTS PERF_TEST_RUNS;
DROP TABLE IF EXISTS PERF_TEST_RUN_CONTROL;
