-- Validate that retired owner-routing database fields and objects are gone.
-- Expected result for each query: zero rows.

SELECT TABLE_NAME, COLUMN_NAME
FROM DBA_MAINT_DB.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'OVERWATCH'
  AND UPPER(COLUMN_NAME) IN (
    'OWNER_ROUTE',
    'OWNER_GAP',
    'OWNER_ID',
    'OWNER_NAME',
    'OWNER_APPROVAL_STATUS',
    'OWNER_APPROVAL_BY',
    'OWNER_APPROVAL_AT',
    'OWNER_APPROVAL_NOTE',
    'OWNER_EMAIL',
    'ONCALL_PRIMARY',
    'ONCALL_SECONDARY',
    'APPROVAL_GROUP',
    'ESCALATION_TARGET',
    'OWNER_SOURCE',
    'OWNER_EVIDENCE',
    'OWNER_APPROVAL_GAP_ROWS',
    'COST_OWNER'
  );

SELECT TABLE_NAME
FROM DBA_MAINT_DB.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'OVERWATCH'
  AND UPPER(TABLE_NAME) IN (
    'MART_OPERATIONAL_OWNER_COVERAGE',
    'DIM_COST_OWNER_TAG'
  );

SELECT SOURCE_KEY, SOURCE_OBJECT
FROM DBA_MAINT_DB.OVERWATCH.OVERWATCH_SECTION_COMMAND_SOURCE_CONFIG
WHERE LOWER(SOURCE_KEY) LIKE '%owner%'
   OR UPPER(SOURCE_OBJECT) LIKE '%OWNER%';
