-- Validate OVERWATCH v2 first-paint mart contract.

WITH required_objects AS (
  SELECT * FROM VALUES
    ('TABLE', 'MART_V2_EXECUTIVE_SUMMARY'),
    ('TABLE', 'MART_V2_DBA_MORNING_COCKPIT'),
    ('TABLE', 'MART_V2_SOURCE_FRESHNESS'),
    ('TABLE', 'MART_V2_ALERT_INTELLIGENCE'),
    ('TABLE', 'MART_V2_TASK_STATUS_DAILY'),
    ('TABLE', 'MART_V2_WAREHOUSE_DAILY_CREDITS'),
    ('TABLE', 'MART_V2_COST_FORECAST'),
    ('TABLE', 'MART_V2_CONTRACT_BURN_DOWN'),
    ('TABLE', 'MART_V2_LOGIN_SECURITY_DAILY'),
    ('TABLE', 'MART_V2_QUERY_ERROR_SUMMARY'),
    ('TABLE', 'MART_V2_STORAGE_DAILY'),
    ('TABLE', 'MART_V2_CORTEX_CODE_USAGE_DAILY'),
    ('TABLE', 'MART_V2_COST_ALLOCATION_DAILY'),
    ('TABLE', 'MART_V2_OVERWATCH_APP_SELF_COST_DAILY'),
    ('VIEW', 'V_EXECUTIVE_SUMMARY'),
    ('VIEW', 'V_DBA_MORNING_COCKPIT'),
    ('VIEW', 'V_SOURCE_FRESHNESS'),
    ('VIEW', 'V_ALERT_INTELLIGENCE'),
    ('VIEW', 'V_TASK_STATUS_DAILY'),
    ('VIEW', 'V_WAREHOUSE_DAILY_CREDITS'),
    ('VIEW', 'V_COST_FORECAST'),
    ('VIEW', 'V_CONTRACT_BURN_DOWN'),
    ('VIEW', 'V_LOGIN_SECURITY_DAILY'),
    ('VIEW', 'V_QUERY_ERROR_SUMMARY'),
    ('VIEW', 'V_STORAGE_DAILY'),
    ('VIEW', 'V_CORTEX_CODE_USAGE_DAILY'),
    ('VIEW', 'V_COST_ALLOCATION_DAILY'),
    ('VIEW', 'V_OVERWATCH_APP_SELF_COST_DAILY')
  AS obj(object_type, object_name)
),
existing_tables AS (
  SELECT 'TABLE' AS object_type, TABLE_NAME AS object_name
  FROM INFORMATION_SCHEMA.TABLES
  WHERE TABLE_SCHEMA = CURRENT_SCHEMA()
),
existing_views AS (
  SELECT 'VIEW' AS object_type, TABLE_NAME AS object_name
  FROM INFORMATION_SCHEMA.VIEWS
  WHERE TABLE_SCHEMA = CURRENT_SCHEMA()
),
existing AS (
  SELECT * FROM existing_tables
  UNION ALL
  SELECT * FROM existing_views
),
view_defs AS (
  SELECT TABLE_NAME, VIEW_DEFINITION
  FROM INFORMATION_SCHEMA.VIEWS
  WHERE TABLE_SCHEMA = CURRENT_SCHEMA()
    AND TABLE_NAME IN (
      'V_EXECUTIVE_SUMMARY', 'V_DBA_MORNING_COCKPIT', 'V_SOURCE_FRESHNESS',
      'V_ALERT_INTELLIGENCE', 'V_TASK_STATUS_DAILY', 'V_WAREHOUSE_DAILY_CREDITS',
      'V_COST_FORECAST', 'V_CONTRACT_BURN_DOWN', 'V_LOGIN_SECURITY_DAILY',
      'V_QUERY_ERROR_SUMMARY', 'V_STORAGE_DAILY', 'V_CORTEX_CODE_USAGE_DAILY',
      'V_COST_ALLOCATION_DAILY', 'V_OVERWATCH_APP_SELF_COST_DAILY'
    )
)
SELECT
  'V2_OBJECT_EXISTS' AS CHECK_NAME,
  COUNT_IF(e.object_name IS NULL) AS OBSERVED_VALUE,
  IFF(COUNT_IF(e.object_name IS NULL) = 0, 'PASS', 'FAIL') AS STATUS
FROM required_objects r
LEFT JOIN existing e
  ON e.object_type = r.object_type
 AND e.object_name = r.object_name
UNION ALL
SELECT
  'V2_VIEW_DEFINITIONS_DO_NOT_REFERENCE_RAW_ACCOUNT_USAGE',
  COUNT_IF(UPPER(VIEW_DEFINITION) LIKE '%SNOWFLAKE.ACCOUNT_USAGE%'),
  IFF(COUNT_IF(UPPER(VIEW_DEFINITION) LIKE '%SNOWFLAKE.ACCOUNT_USAGE%') = 0, 'PASS', 'FAIL')
FROM view_defs
UNION ALL
SELECT
  'V2_ALERT_INTELLIGENCE_NO_CORRELATED_SUBQUERY_PATTERN',
  COUNT_IF(UPPER(VIEW_DEFINITION) LIKE '%SELECT%SELECT%' AND UPPER(VIEW_DEFINITION) LIKE '%WHERE%=%'),
  IFF(COUNT_IF(UPPER(VIEW_DEFINITION) LIKE '%SELECT%SELECT%' AND UPPER(VIEW_DEFINITION) LIKE '%WHERE%=%') = 0, 'PASS', 'FAIL')
FROM view_defs
WHERE TABLE_NAME = 'V_ALERT_INTELLIGENCE'
UNION ALL
SELECT
  'V2_REQUIRED_COLUMNS_PRESENT',
  COUNT_IF(column_name IS NULL),
  IFF(COUNT_IF(column_name IS NULL) = 0, 'PASS', 'FAIL')
FROM (
  SELECT * FROM VALUES
    ('MART_V2_COST_FORECAST', 'BUDGET_CREDITS'),
    ('MART_V2_COST_FORECAST', 'LOWER_BOUND_CREDITS'),
    ('MART_V2_COST_FORECAST', 'UPPER_BOUND_CREDITS'),
    ('MART_V2_CONTRACT_BURN_DOWN', 'BUDGET_SOURCE'),
    ('MART_V2_COST_ALLOCATION_DAILY', 'ALLOCATION_CONFIDENCE'),
    ('MART_V2_LOGIN_SECURITY_DAILY', 'SOURCE_LATENCY')
  AS required(table_name, column_name)
) required
LEFT JOIN INFORMATION_SCHEMA.COLUMNS c
  ON c.TABLE_SCHEMA = CURRENT_SCHEMA()
 AND c.TABLE_NAME = required.table_name
 AND c.COLUMN_NAME = required.column_name
UNION ALL
SELECT
  'V2_EXECUTIVE_SUMMARY_ROW_COUNT',
  COUNT(*),
  IFF(COUNT(*) > 0, 'PASS', 'WARN')
FROM MART_V2_EXECUTIVE_SUMMARY
UNION ALL
SELECT
  'V2_SOURCE_FRESHNESS_ROW_COUNT',
  COUNT(*),
  IFF(COUNT(*) > 0, 'PASS', 'WARN')
FROM MART_V2_SOURCE_FRESHNESS
UNION ALL
SELECT
  'V2_COST_FORECAST_ROW_COUNT',
  COUNT(*),
  IFF(COUNT(*) > 0, 'PASS', 'WARN')
FROM MART_V2_COST_FORECAST
UNION ALL
SELECT
  'V2_SOURCE_FRESHNESS_MAX_AGE_MINUTES',
  COALESCE(MAX(DATEDIFF('minute', LATEST_SOURCE_TS, CURRENT_TIMESTAMP())), 999999),
  IFF(COALESCE(MAX(DATEDIFF('minute', LATEST_SOURCE_TS, CURRENT_TIMESTAMP())), 999999) <= 360, 'PASS', 'WARN')
FROM MART_V2_SOURCE_FRESHNESS;
