#!/usr/bin/env python
"""Safe OVERWATCH dashboard load runner.

This runner measures HTTP response behavior for the Streamlit app without
creating Snowflake objects. Snowflake-side cost/query evidence is generated by
the SQL scripts in perf_tests/sql after query logging and detailed query tags
are enabled in the app.
"""

from __future__ import annotations

import argparse
import concurrent.futures
import dataclasses
import datetime as dt
import json
import math
import pathlib
import statistics
import time
import urllib.error
import urllib.request
import uuid


DEFAULT_OUTPUT_DIR = pathlib.Path(__file__).resolve().parent / "results"


@dataclasses.dataclass
class Sample:
    user_id: int
    iteration: int
    status_code: int
    elapsed_ms: float
    bytes_read: int
    ok: bool
    error: str = ""


def percentile(values: list[float], pct: float) -> float:
    """Return nearest-rank percentile for deterministic small-sample reports."""
    clean = sorted(float(value) for value in values if value is not None)
    if not clean:
        return 0.0
    if pct <= 0:
        return clean[0]
    if pct >= 100:
        return clean[-1]
    rank = math.ceil((pct / 100.0) * len(clean)) - 1
    return clean[max(0, min(rank, len(clean) - 1))]


def fetch_once(url: str, timeout: float, user_id: int, iteration: int, run_id: str) -> Sample:
    request = urllib.request.Request(
        url,
        headers={
            "User-Agent": f"OVERWATCH-PERF-TEST/{run_id}",
            "Cache-Control": "no-cache",
            "X-OVERWATCH-PERF-RUN-ID": run_id,
        },
    )
    started = time.perf_counter()
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            payload = response.read()
            elapsed_ms = (time.perf_counter() - started) * 1000
            status = int(getattr(response, "status", response.getcode()) or 0)
            return Sample(
                user_id=user_id,
                iteration=iteration,
                status_code=status,
                elapsed_ms=elapsed_ms,
                bytes_read=len(payload),
                ok=200 <= status < 400,
            )
    except urllib.error.HTTPError as exc:
        elapsed_ms = (time.perf_counter() - started) * 1000
        return Sample(
            user_id=user_id,
            iteration=iteration,
            status_code=int(exc.code or 0),
            elapsed_ms=elapsed_ms,
            bytes_read=0,
            ok=False,
            error=str(exc)[:500],
        )
    except Exception as exc:
        elapsed_ms = (time.perf_counter() - started) * 1000
        return Sample(
            user_id=user_id,
            iteration=iteration,
            status_code=0,
            elapsed_ms=elapsed_ms,
            bytes_read=0,
            ok=False,
            error=str(exc)[:500],
        )


def summarize(samples: list[Sample], total_elapsed_sec: float, *, fail_p95_ms: float, fail_error_rate: float) -> dict:
    elapsed = [sample.elapsed_ms for sample in samples]
    ok_count = sum(1 for sample in samples if sample.ok)
    error_count = len(samples) - ok_count
    error_rate = error_count / len(samples) if samples else 1.0
    p95_ms = percentile(elapsed, 95)
    p99_ms = percentile(elapsed, 99)
    throughput = ok_count / total_elapsed_sec if total_elapsed_sec > 0 else 0.0
    first_iteration = [sample.elapsed_ms for sample in samples if sample.iteration == 1]
    steady_state = [sample.elapsed_ms for sample in samples if sample.iteration > 1]
    first_iteration_p95 = percentile(first_iteration, 95)
    steady_state_p95 = percentile(steady_state, 95) if steady_state else first_iteration_p95
    cold_start_gap_pct = 0.0
    if steady_state_p95 > 0:
        cold_start_gap_pct = max(0.0, ((first_iteration_p95 - steady_state_p95) / steady_state_p95) * 100.0)
    iteration_p95 = {
        iteration: percentile([sample.elapsed_ms for sample in samples if sample.iteration == iteration], 95)
        for iteration in sorted({sample.iteration for sample in samples})
    }
    worst_iteration = max(iteration_p95, key=iteration_p95.get) if iteration_p95 else 0
    largest_payload_kb = max((sample.bytes_read for sample in samples), default=0) / 1024
    score = 100
    if p95_ms > fail_p95_ms:
        score -= min(35, int((p95_ms - fail_p95_ms) / max(fail_p95_ms, 1) * 35) + 10)
    if p99_ms > fail_p95_ms * 1.8:
        score -= 10
    if error_rate > fail_error_rate:
        score -= min(40, int((error_rate - fail_error_rate) * 100) + 15)
    if throughput < 1 and ok_count >= 5:
        score -= 5
    score = max(0, min(100, score))
    if score >= 95 and error_rate <= fail_error_rate and p95_ms <= fail_p95_ms:
        state = "PASS"
    elif score >= 85:
        state = "WATCH"
    else:
        state = "FAIL"
    return {
        "requests": len(samples),
        "ok": ok_count,
        "errors": error_count,
        "error_rate": round(error_rate, 4),
        "min_ms": round(min(elapsed), 2) if elapsed else 0.0,
        "p50_ms": round(statistics.median(elapsed), 2) if elapsed else 0.0,
        "p95_ms": round(p95_ms, 2),
        "p99_ms": round(p99_ms, 2),
        "max_ms": round(max(elapsed), 2) if elapsed else 0.0,
        "avg_ms": round(statistics.mean(elapsed), 2) if elapsed else 0.0,
        "first_iteration_p95_ms": round(first_iteration_p95, 2),
        "steady_state_p95_ms": round(steady_state_p95, 2),
        "cold_start_gap_pct": round(cold_start_gap_pct, 2),
        "worst_iteration": int(worst_iteration),
        "largest_payload_kb": round(largest_payload_kb, 2),
        "bytes_total": sum(sample.bytes_read for sample in samples),
        "throughput_ok_per_sec": round(throughput, 3),
        "total_elapsed_sec": round(total_elapsed_sec, 3),
        "readiness_score": score,
        "readiness_state": state,
        "fail_p95_ms": fail_p95_ms,
        "fail_error_rate": fail_error_rate,
    }


def run_load(args: argparse.Namespace) -> tuple[list[Sample], float]:
    samples: list[Sample] = []
    started = time.perf_counter()
    with concurrent.futures.ThreadPoolExecutor(max_workers=args.users) as pool:
        for iteration in range(1, args.iterations + 1):
            futures = []
            for user_id in range(1, args.users + 1):
                if args.ramp_seconds > 0:
                    time.sleep(args.ramp_seconds / max(args.users, 1))
                futures.append(
                    pool.submit(fetch_once, args.url, args.timeout, user_id, iteration, args.run_id)
                )
            for future in concurrent.futures.as_completed(futures):
                samples.append(future.result())
    total_elapsed_sec = time.perf_counter() - started
    return samples, total_elapsed_sec


def sample_to_dict(sample: Sample) -> dict:
    return dataclasses.asdict(sample)


def build_recommendations(summary: dict, samples: list[Sample], mode: str) -> list[str]:
    """Return concrete next actions based on the observed run profile."""
    recommendations: list[str] = []
    if summary.get("errors", 0):
        recommendations.append(
            "Treat every non-2xx/3xx response as a release blocker until the failing URL, section, and server log are explained."
        )
    if float(summary.get("p95_ms", 0)) > float(summary.get("fail_p95_ms", 0)):
        recommendations.append(
            "The HTTP p95 is above threshold. Profile the first loaded section and move startup Snowflake calls behind an explicit user action."
        )
    if float(summary.get("cold_start_gap_pct", 0)) >= 25:
        recommendations.append(
            "Cold-start latency is materially slower than steady state. Keep import-time work, saved-view loading, and metadata probes lazy."
        )
    if float(summary.get("largest_payload_kb", 0)) >= 512:
        recommendations.append(
            "The largest HTML payload is heavy. Look for large default dataframes, verbose hidden markdown, or eagerly rendered tab content."
        )
    if float(summary.get("throughput_ok_per_sec", 0)) < 2 and int(summary.get("ok", 0)) >= 10:
        recommendations.append(
            "Throughput is low for a local app shell. Check CPU-bound Python work, Streamlit rerun churn, and long sidebar initialization."
        )
    if mode == "metadata":
        recommendations.append(
            "This was a shallow app-shell test. Run the section smoke runner and Snowflake report views before claiming 5 TB readiness."
        )
    if not samples:
        recommendations.append("No samples were collected. Re-run with a reachable URL before making release decisions.")
    return recommendations or ["No immediate HTTP bottleneck detected. Move to section navigation and Snowflake-side query evidence."]


def write_reports(args: argparse.Namespace, samples: list[Sample], summary: dict) -> tuple[pathlib.Path, pathlib.Path]:
    output_dir = pathlib.Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    recommendations = build_recommendations(summary, samples, args.mode)
    payload = {
        "run_id": args.run_id,
        "created_at": dt.datetime.now(dt.timezone.utc).isoformat(),
        "url": args.url,
        "mode": args.mode,
        "users": args.users,
        "iterations": args.iterations,
        "summary": summary,
        "recommendations": recommendations,
        "samples": [sample_to_dict(sample) for sample in sorted(samples, key=lambda item: (item.iteration, item.user_id))],
    }
    json_path = output_dir / f"{args.run_id}.json"
    md_path = output_dir / f"{args.run_id}.md"
    json_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    slowest = sorted(samples, key=lambda item: item.elapsed_ms, reverse=True)[:10]
    failures = [sample for sample in samples if not sample.ok][:10]
    md = [
        f"# OVERWATCH Performance Run {args.run_id}",
        "",
        f"- URL: `{args.url}`",
        f"- Mode: `{args.mode}`",
        f"- Users: `{args.users}`",
        f"- Iterations per user: `{args.iterations}`",
        f"- Readiness: **{summary['readiness_state']}** ({summary['readiness_score']}/100)",
        f"- Requests: {summary['requests']} total, {summary['errors']} errors ({summary['error_rate'] * 100:.2f}%)",
        f"- Latency: p50 {summary['p50_ms']} ms, p95 {summary['p95_ms']} ms, p99 {summary['p99_ms']} ms, max {summary['max_ms']} ms",
        f"- Cold-start profile: first-iteration p95 {summary['first_iteration_p95_ms']} ms, steady-state p95 {summary['steady_state_p95_ms']} ms, gap {summary['cold_start_gap_pct']}%",
        f"- Throughput: {summary['throughput_ok_per_sec']} successful responses/sec",
        f"- Largest payload: {summary['largest_payload_kb']} KB",
        "",
        "## Interpretation",
        "",
        "- This runner measures Streamlit HTTP response behavior. It does not click every in-app page.",
        "- Use `perf_tests/sql/04_benchmark_report.sql` with detailed query tags and query logging for Snowflake-side cost, spill, partition, and cache evidence.",
        "- Treat p95 over the fail threshold or any error rate above threshold as a release blocker until explained.",
        "",
        "## Recommended Next Actions",
        "",
    ]
    md.extend(f"- {item}" for item in recommendations)
    md.extend([
        "",
        "## Slowest Requests",
        "",
        "| User | Iteration | Status | Elapsed ms | Bytes | Error |",
        "|---:|---:|---:|---:|---:|---|",
    ])
    for sample in slowest:
        md.append(
            f"| {sample.user_id} | {sample.iteration} | {sample.status_code} | "
            f"{sample.elapsed_ms:.2f} | {sample.bytes_read} | {sample.error[:120]} |"
        )
    md.extend(["", "## Failures", ""])
    if failures:
        md.extend(["| User | Iteration | Status | Elapsed ms | Error |", "|---:|---:|---:|---:|---|"])
        for sample in failures:
            md.append(f"| {sample.user_id} | {sample.iteration} | {sample.status_code} | {sample.elapsed_ms:.2f} | {sample.error[:160]} |")
    else:
        md.append("No request failures.")
    md.extend([
        "",
        "## Next Evidence To Attach",
        "",
        "- `PERF_TEST_APP_USAGE_REPORT_V` for app section/query events.",
        "- `PERF_TEST_SNOWFLAKE_QUERY_REPORT_V` for p95 query runtime, spill, partition scans, cache, and failures.",
        "- `PERF_TEST_COST_ESTIMATE_V` for estimated shared-warehouse cost during the run.",
        "- `PERF_TEST_PRODUCTION_READINESS_V` for the Snowflake-side readiness score.",
    ])
    md_path.write_text("\n".join(md) + "\n", encoding="utf-8")
    return json_path, md_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run a safe local load test against OVERWATCH.")
    parser.add_argument("--url", default="http://localhost:8501/", help="Dashboard URL to test.")
    parser.add_argument("--users", type=int, default=5, help="Concurrent simulated users.")
    parser.add_argument("--iterations", type=int, default=3, help="Requests per simulated user.")
    parser.add_argument("--timeout", type=float, default=30.0, help="Per-request timeout in seconds.")
    parser.add_argument("--ramp-seconds", type=float, default=0.0, help="Ramp delay across users for each iteration.")
    parser.add_argument("--mode", choices=["metadata", "medium", "full_5tb"], default="metadata", help="Benchmark mode label.")
    parser.add_argument("--allow-full-5tb", action="store_true", help="Required acknowledgement for full_5tb mode label.")
    parser.add_argument("--output-dir", default=str(DEFAULT_OUTPUT_DIR), help="Directory for JSON and Markdown reports.")
    parser.add_argument("--run-id", default=f"PERF_TEST_{dt.datetime.now().strftime('%Y%m%d_%H%M%S')}_{uuid.uuid4().hex[:6]}")
    parser.add_argument("--fail-p95-ms", type=float, default=5000.0, help="Fail threshold for p95 HTTP latency.")
    parser.add_argument("--fail-error-rate", type=float, default=0.02, help="Fail threshold for HTTP error rate.")
    args = parser.parse_args()
    if args.users < 1 or args.iterations < 1:
        parser.error("--users and --iterations must be positive integers.")
    if args.mode == "full_5tb" and not args.allow_full_5tb:
        parser.error("--mode full_5tb requires --allow-full-5tb. This runner still does not create Snowflake data.")
    return args


def main() -> int:
    args = parse_args()
    samples, total_elapsed_sec = run_load(args)
    summary = summarize(
        samples,
        total_elapsed_sec,
        fail_p95_ms=args.fail_p95_ms,
        fail_error_rate=args.fail_error_rate,
    )
    json_path, md_path = write_reports(args, samples, summary)
    print(json.dumps({
        "run_id": args.run_id,
        "readiness_state": summary["readiness_state"],
        "readiness_score": summary["readiness_score"],
        "p95_ms": summary["p95_ms"],
        "error_rate": summary["error_rate"],
        "json_report": str(json_path),
        "markdown_report": str(md_path),
    }, indent=2))
    return 0 if summary["readiness_state"] in {"PASS", "WATCH"} else 2


if __name__ == "__main__":
    raise SystemExit(main())
