-- OVERWATCH Snowflake Mart Drop
-- Purpose:
--   Drop every deployable object created by snowflake/OVERWATCH_MART_SETUP.sql
--   so the mart/schema can be rebuilt cleanly after DDL logic, naming, or scope
--   changes.
--
-- Run before rerunning OVERWATCH_MART_SETUP.sql when you intentionally want a
-- destructive rebuild of OVERWATCH app objects.
--
-- This script does not drop the database, schema, warehouse, resource monitor,
-- or access roles by default. Optional full-reset statements are listed at the
-- bottom and should stay commented unless you really want to remove the runtime
-- containers too.

USE DATABASE DBA_MAINT_DB;
USE SCHEMA OVERWATCH;

-- -----------------------------------------------------------------------------
-- 1. Stop scheduled work before dropping dependencies.
-- -----------------------------------------------------------------------------

ALTER TASK IF EXISTS OVERWATCH_SECTION_COMMAND_BRIEF_REFRESH SUSPEND;
ALTER TASK IF EXISTS OVERWATCH_EXECUTIVE_OBSERVABILITY_REFRESH SUSPEND;
ALTER TASK IF EXISTS OVERWATCH_AUTOMATION_REFRESH SUSPEND;
ALTER TASK IF EXISTS OVERWATCH_COST_SAVINGS_VERIFY SUSPEND;
ALTER TASK IF EXISTS OVERWATCH_COST_MONITORING_REFRESH SUSPEND;
ALTER TASK IF EXISTS OVERWATCH_REFRESH_CONTROL_ROOM SUSPEND;
ALTER TASK IF EXISTS OVERWATCH_LOAD_CORTEX SUSPEND;
ALTER TASK IF EXISTS OVERWATCH_LOAD_TASK_CRITICAL_PATH SUSPEND;
ALTER TASK IF EXISTS OVERWATCH_LOAD_SNAPSHOTS SUSPEND;
ALTER TASK IF EXISTS OVERWATCH_LOAD_PROCEDURE_RUN SUSPEND;
ALTER TASK IF EXISTS OVERWATCH_LOAD_TASK_RUN SUSPEND;
ALTER TASK IF EXISTS OVERWATCH_LOAD_OBJECT_CHANGE SUSPEND;
ALTER TASK IF EXISTS OVERWATCH_LOAD_QUERY_DETAIL SUSPEND;
ALTER TASK IF EXISTS OVERWATCH_LOAD_QUERY_HOURLY SUSPEND;
ALTER TASK IF EXISTS OVERWATCH_LOAD_HOURLY SUSPEND;
ALTER TASK IF EXISTS OVERWATCH_LOAD_DAILY SUSPEND;
ALTER TASK IF EXISTS OVERWATCH_ANOMALY_CHECK SUSPEND;

-- -----------------------------------------------------------------------------
-- 2. Drop task graph children before roots.
-- -----------------------------------------------------------------------------

DROP TASK IF EXISTS OVERWATCH_SECTION_COMMAND_BRIEF_REFRESH;
DROP TASK IF EXISTS OVERWATCH_EXECUTIVE_OBSERVABILITY_REFRESH;
DROP TASK IF EXISTS OVERWATCH_AUTOMATION_REFRESH;
DROP TASK IF EXISTS OVERWATCH_COST_SAVINGS_VERIFY;
DROP TASK IF EXISTS OVERWATCH_COST_MONITORING_REFRESH;
DROP TASK IF EXISTS OVERWATCH_REFRESH_CONTROL_ROOM;
DROP TASK IF EXISTS OVERWATCH_LOAD_CORTEX;
DROP TASK IF EXISTS OVERWATCH_LOAD_TASK_CRITICAL_PATH;
DROP TASK IF EXISTS OVERWATCH_LOAD_SNAPSHOTS;
DROP TASK IF EXISTS OVERWATCH_LOAD_PROCEDURE_RUN;
DROP TASK IF EXISTS OVERWATCH_LOAD_TASK_RUN;
DROP TASK IF EXISTS OVERWATCH_LOAD_OBJECT_CHANGE;
DROP TASK IF EXISTS OVERWATCH_LOAD_QUERY_DETAIL;
DROP TASK IF EXISTS OVERWATCH_LOAD_QUERY_HOURLY;
DROP TASK IF EXISTS OVERWATCH_LOAD_HOURLY;
DROP TASK IF EXISTS OVERWATCH_LOAD_DAILY;
DROP TASK IF EXISTS OVERWATCH_ANOMALY_CHECK;

-- -----------------------------------------------------------------------------
-- 3. Drop views before tables.
-- -----------------------------------------------------------------------------

DROP VIEW IF EXISTS OVERWATCH_AUTOMATION_HEALTH_V;
DROP VIEW IF EXISTS OVERWATCH_COST_SAVINGS_VERIFICATION_HEALTH_V;
DROP VIEW IF EXISTS OVERWATCH_OWNER_DIRECTORY_ACTIVE_V;
DROP VIEW IF EXISTS OVERWATCH_PLATFORM_FUTURES_CONTROL_COVERAGE_V;
DROP VIEW IF EXISTS OVERWATCH_PLATFORM_FUTURES_EVIDENCE_LATEST_V;
DROP VIEW IF EXISTS OVERWATCH_COMPLIANCE_READINESS_V;
DROP VIEW IF EXISTS OVERWATCH_ALERT_TRIAGE_V;
DROP VIEW IF EXISTS ALERT_NATIVE_DEPLOYMENT_REVIEW_V;
DROP VIEW IF EXISTS OVERWATCH_WORKLOAD_RECOVERY_AUDIT_LATEST_V;

-- -----------------------------------------------------------------------------
-- 4. Drop procedures and functions before backing tables.
-- -----------------------------------------------------------------------------

DROP PROCEDURE IF EXISTS SP_OVERWATCH_SEND_ALERT_DIGEST(VARCHAR, VARCHAR, VARCHAR, BOOLEAN);
DROP PROCEDURE IF EXISTS SP_OVERWATCH_STAGE_ALERT_REMEDIATION_DRY_RUN(NUMBER, VARCHAR);
DROP PROCEDURE IF EXISTS SP_OVERWATCH_REFRESH_AUTOMATION(VARCHAR, VARCHAR, BOOLEAN);
DROP PROCEDURE IF EXISTS SP_OVERWATCH_VERIFY_COST_SAVINGS();
DROP PROCEDURE IF EXISTS SP_OVERWATCH_REFRESH_COMMAND_CENTER();
DROP PROCEDURE IF EXISTS SP_OVERWATCH_REFRESH_CLOSED_LOOP_OPERATIONS();
DROP PROCEDURE IF EXISTS SP_OVERWATCH_REFRESH_CHANGE_INTELLIGENCE();
DROP PROCEDURE IF EXISTS SP_OVERWATCH_REFRESH_FORECASTING();
DROP PROCEDURE IF EXISTS SP_OVERWATCH_REFRESH_EXECUTIVE_SCORECARD();
DROP PROCEDURE IF EXISTS SP_OVERWATCH_REFRESH_PRODUCTION_READINESS();
DROP PROCEDURE IF EXISTS SP_OVERWATCH_REFRESH_ENTERPRISE_OPERATING_MODEL();
DROP PROCEDURE IF EXISTS SP_OVERWATCH_REFRESH_SECTION_COMMAND_BRIEFS();
DROP PROCEDURE IF EXISTS SP_OVERWATCH_REFRESH_EXECUTIVE_OBSERVABILITY();
DROP PROCEDURE IF EXISTS SP_OVERWATCH_REFRESH_COST_MONITORING();
DROP PROCEDURE IF EXISTS SP_OVERWATCH_REFRESH_CONTROL_ROOM();
DROP PROCEDURE IF EXISTS SP_OVERWATCH_LOAD_CORTEX();
DROP PROCEDURE IF EXISTS SP_OVERWATCH_LOAD_DAILY();
DROP PROCEDURE IF EXISTS SP_OVERWATCH_LOAD_HOURLY();
DROP PROCEDURE IF EXISTS SP_OVERWATCH_LOAD_HOURLY_UNIT(VARCHAR, NUMBER, NUMBER);
DROP PROCEDURE IF EXISTS SP_OVERWATCH_PRUNE();

DROP FUNCTION IF EXISTS OVERWATCH_DATABASE_ENVIRONMENT(VARCHAR);

-- -----------------------------------------------------------------------------
-- 5. Drop mart, fact, dimension, audit, alert, recon, and settings tables.
-- -----------------------------------------------------------------------------

DROP TABLE IF EXISTS MART_EXECUTIVE_OBSERVABILITY;
DROP TABLE IF EXISTS MART_SECTION_COMMAND_BRIEF;
DROP TABLE IF EXISTS MART_SECTION_COMMAND_METRIC;
DROP TABLE IF EXISTS MART_SECTION_COMMAND_EXCEPTION;
DROP TABLE IF EXISTS MART_SECTION_COMMAND_ACTION;
DROP TABLE IF EXISTS MART_SECTION_COMMAND_SOURCE;
DROP TABLE IF EXISTS MART_SECTION_DECISION_CURRENT;
DROP TABLE IF EXISTS MART_EXECUTIVE_DECISION_INBOX;
DROP TABLE IF EXISTS OVERWATCH_SECTION_COMMAND_SOURCE_CONFIG;
DROP TABLE IF EXISTS MART_DBA_CONTROL_ROOM;
DROP TABLE IF EXISTS MART_EXECUTIVE_FORECAST_SUMMARY;
DROP TABLE IF EXISTS OVERWATCH_FORECAST_HISTORY;
DROP TABLE IF EXISTS OVERWATCH_FORECAST_CONFIG;
DROP TABLE IF EXISTS MART_COMMAND_CENTER_SUMMARY;
DROP TABLE IF EXISTS OVERWATCH_COMMAND_CENTER_RECOMMENDATION;
DROP TABLE IF EXISTS OVERWATCH_COMMAND_CENTER_EVIDENCE;
DROP TABLE IF EXISTS OVERWATCH_COMMAND_CENTER_FINDING;
DROP TABLE IF EXISTS OVERWATCH_COMMAND_CENTER_QUESTION;
DROP TABLE IF EXISTS MART_CLOSED_LOOP_OPERATIONS_SUMMARY;
DROP TABLE IF EXISTS OVERWATCH_ACTION_EVIDENCE;
DROP TABLE IF EXISTS OVERWATCH_ACTION_VERIFICATION;
DROP TABLE IF EXISTS OVERWATCH_ACTION_EXECUTION_PLAN;
DROP TABLE IF EXISTS OVERWATCH_ACTION_APPROVAL;
DROP TABLE IF EXISTS OVERWATCH_ACTION_WORKFLOW;
DROP TABLE IF EXISTS MART_CHANGE_INTELLIGENCE_SUMMARY;
DROP TABLE IF EXISTS OVERWATCH_CHANGE_CORRELATION;
DROP TABLE IF EXISTS OVERWATCH_CHANGE_EVENT;
DROP TABLE IF EXISTS OVERWATCH_CHANGE_RULE;
DROP TABLE IF EXISTS MART_EXECUTIVE_SCORECARD_SUMMARY;
DROP TABLE IF EXISTS OVERWATCH_EXECUTIVE_SCORECARD_HISTORY;
DROP TABLE IF EXISTS OVERWATCH_EXECUTIVE_SCORECARD_CONFIG;
DROP TABLE IF EXISTS MART_PRODUCTION_READINESS_SUMMARY;
DROP TABLE IF EXISTS OVERWATCH_PRODUCTION_VALIDATION_STATUS;
DROP TABLE IF EXISTS OVERWATCH_PRIVILEGE_READINESS_REQUIREMENT;
DROP TABLE IF EXISTS OVERWATCH_ROLE_READINESS_REQUIREMENT;
DROP TABLE IF EXISTS OVERWATCH_PRODUCTION_CHECKLIST;
DROP TABLE IF EXISTS MART_APP_OBSERVABILITY_SUMMARY;
DROP TABLE IF EXISTS OVERWATCH_APP_OBSERVABILITY;
DROP TABLE IF EXISTS MART_EXECUTIVE_VALUE_LEDGER;
DROP TABLE IF EXISTS OVERWATCH_VALUE_LEDGER;
DROP TABLE IF EXISTS MART_OPERATIONAL_OWNER_COVERAGE;
DROP TABLE IF EXISTS OVERWATCH_OPERATIONAL_OWNER_MAP;
DROP TABLE IF EXISTS MART_DATA_TRUST_SUMMARY;
DROP TABLE IF EXISTS OVERWATCH_DATA_TRUST_STATUS;
DROP TABLE IF EXISTS OVERWATCH_DATA_TRUST_SOURCE;

DROP TABLE IF EXISTS FACT_COST_INCIDENT_TIMELINE;
DROP TABLE IF EXISTS FACT_COST_MONITORING_SIGNAL;
DROP TABLE IF EXISTS FACT_COST_SOURCE_HEALTH_DAILY;
DROP TABLE IF EXISTS FACT_COST_DAILY;
DROP TABLE IF EXISTS FACT_CORTEX_DAILY;
DROP TABLE IF EXISTS FACT_COPY_LOAD_DAILY;
DROP TABLE IF EXISTS DIM_TABLE_SNAPSHOT;
DROP TABLE IF EXISTS FACT_STORAGE_DAILY;
DROP TABLE IF EXISTS FACT_GRANT_DAILY;
DROP TABLE IF EXISTS FACT_CHANGE_CONTROL_OPERABILITY_DAILY;
DROP TABLE IF EXISTS FACT_OBJECT_CHANGE;
DROP TABLE IF EXISTS FACT_LOGIN_DAILY;
DROP TABLE IF EXISTS FACT_PROCEDURE_RUN;
DROP TABLE IF EXISTS DIM_PROCEDURE_SNAPSHOT;
DROP TABLE IF EXISTS DIM_TASK_SNAPSHOT;
DROP TABLE IF EXISTS FACT_TASK_CRITICAL_PATH;
DROP TABLE IF EXISTS FACT_TASK_RUN;
DROP TABLE IF EXISTS DIM_COST_OWNER_TAG;
DROP TABLE IF EXISTS FACT_CHARGEBACK_DAILY;
DROP TABLE IF EXISTS FACT_QUERY_DETAIL_RECENT;
DROP TABLE IF EXISTS FACT_QUERY_HOURLY;
DROP TABLE IF EXISTS FACT_ACCOUNT_HEALTH_OPERABILITY_DAILY;
DROP TABLE IF EXISTS FACT_SECURITY_OPERABILITY_DAILY;
DROP TABLE IF EXISTS FACT_WAREHOUSE_OPERABILITY_DAILY;
DROP TABLE IF EXISTS FACT_WAREHOUSE_HOURLY;

-- Retired compatibility cleanup. These objects are no longer created by setup,
-- but older deployments may still have them. Same-name dynamic table instances
-- are removable through these table statements in Snowflake.
DROP TABLE IF EXISTS FACT_MONITORING_COST_DAILY;
DROP TABLE IF EXISTS OVERWATCH_COST_SAVINGS_VERIFICATION_RUN;
DROP TABLE IF EXISTS OVERWATCH_EXTERNAL_CONTROL_FEED;
DROP TABLE IF EXISTS OVERWATCH_SOURCE_CONTROL_CHANGE;
DROP TABLE IF EXISTS OVERWATCH_OWNER_APPROVAL;
DROP TABLE IF EXISTS OVERWATCH_OWNER_DIRECTORY;
DROP TABLE IF EXISTS OVERWATCH_PLATFORM_FUTURES_CONTROL_REGISTER;
DROP TABLE IF EXISTS OVERWATCH_PLATFORM_FUTURES_EVIDENCE;
DROP TABLE IF EXISTS OVERWATCH_COMMAND_INTELLIGENCE_CAPABILITY;
DROP TABLE IF EXISTS OVERWATCH_REFRESH_POLICY;
DROP TABLE IF EXISTS OVERWATCH_COMPANY_SCOPE;

DROP TABLE IF EXISTS OVERWATCH_SCHEMA_DIFF_RESULT;
DROP TABLE IF EXISTS OVERWATCH_RECON_RUN;
DROP TABLE IF EXISTS OVERWATCH_RECON_CONFIG;

DROP TABLE IF EXISTS OVERWATCH_EXECUTIVE_PACKET;
DROP TABLE IF EXISTS OVERWATCH_AUTOMATION_RUN;

DROP TABLE IF EXISTS OVERWATCH_ALERT_RULES;
DROP TABLE IF EXISTS OVERWATCH_ALERT_RULE_AUDIT;
DROP TABLE IF EXISTS OVERWATCH_ALERT_DELIVERY_LOG;
DROP TABLE IF EXISTS OVERWATCH_ANNOTATIONS;
DROP TABLE IF EXISTS ALERT_DATA_QUALITY_CHECKS;
DROP TABLE IF EXISTS ALERT_REMEDIATION_DRY_RUN;
DROP TABLE IF EXISTS ALERT_REMEDIATION_POLICY;
DROP TABLE IF EXISTS ALERT_NATIVE_OBJECT_REGISTRY;
DROP TABLE IF EXISTS ALERT_OWNER_ROUTING;
DROP TABLE IF EXISTS ALERT_REMEDIATION_LOG;
DROP TABLE IF EXISTS ALERT_NOTIFICATION_LOG;
DROP TABLE IF EXISTS ALERT_ACKNOWLEDGEMENTS;
DROP TABLE IF EXISTS ALERT_RUN_HISTORY;
DROP TABLE IF EXISTS ALERT_EVENTS;
DROP TABLE IF EXISTS ALERT_THRESHOLDS;
DROP TABLE IF EXISTS ALERT_CONFIG;
DROP TABLE IF EXISTS OVERWATCH_ALERTS;

DROP TABLE IF EXISTS OVERWATCH_SECURITY_ACCESS_REVIEW;
DROP TABLE IF EXISTS OVERWATCH_WAREHOUSE_SETTING_REVIEW;
DROP TABLE IF EXISTS OVERWATCH_CHANGE_CONTROL_EVIDENCE;
DROP TABLE IF EXISTS OVERWATCH_DBA_CHECKLIST_HISTORY;
DROP TABLE IF EXISTS OVERWATCH_WORKLOAD_RECOVERY_AUDIT;
DROP TABLE IF EXISTS OVERWATCH_ACTION_QUEUE;
DROP TABLE IF EXISTS OVERWATCH_USAGE_LOG;
DROP TABLE IF EXISTS OVERWATCH_ADMIN_ACTION_AUDIT;
DROP TABLE IF EXISTS OVERWATCH_LOAD_AUDIT;
DROP TABLE IF EXISTS OVERWATCH_OWNER_TAG_NAMES;
DROP TABLE IF EXISTS OVERWATCH_SCHEMA_MIGRATION;
DROP TABLE IF EXISTS OVERWATCH_SETTINGS;

-- -----------------------------------------------------------------------------
-- 6. Optional runtime/container reset.
-- -----------------------------------------------------------------------------
-- Uncomment only when you want to remove the runtime container objects too.
-- The standard fresh rebuild path is:
--   1. Run this script as-is.
--   2. Run snowflake/OVERWATCH_MART_SETUP.sql.
--
-- DROP SCHEMA IF EXISTS DBA_MAINT_DB.OVERWATCH;
-- DROP DATABASE IF EXISTS DBA_MAINT_DB;
-- Do not drop COMPUTE_WH from this reset script; it is the approved current
-- shared runtime warehouse until a dedicated OVERWATCH warehouse is approved.
-- Review any COMPUTE_WH_RM removal with the Snowflake platform owner first.
-- DROP ROLE IF EXISTS SNOW_SYSADMINS;
-- DROP ROLE IF EXISTS SNOW_ACCOUNTADMINS;
