-- OVERWATCH Release Remediation
-- Purpose:
--   Repair existing OVERWATCH deployments that predate the release objects used
--   by alert suppression windows and dedicated app-runtime cost guardrails.
--
-- Run as a platform-admin role after reviewing the statements below. This file
-- is intentionally narrower than OVERWATCH_MART_SETUP.sql and is safe to rerun.
-- It does not resume suspended tasks automatically; review task history first,
-- then uncomment the task commands at the bottom if appropriate.

CREATE DATABASE IF NOT EXISTS DBA_MAINT_DB;
CREATE SCHEMA IF NOT EXISTS DBA_MAINT_DB.OVERWATCH;

CREATE WAREHOUSE IF NOT EXISTS OVERWATCH_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  STATEMENT_TIMEOUT_IN_SECONDS = 600
  COMMENT = 'Dedicated warehouse for OVERWATCH Streamlit app runtime and isolated cost attribution.';

CREATE RESOURCE MONITOR IF NOT EXISTS OVERWATCH_WH_RM
  WITH CREDIT_QUOTA = 50
       FREQUENCY = MONTHLY
       START_TIMESTAMP = IMMEDIATELY
       TRIGGERS ON 80 PERCENT DO NOTIFY
                ON 100 PERCENT DO SUSPEND;

ALTER RESOURCE MONITOR IF EXISTS OVERWATCH_WH_RM
  SET CREDIT_QUOTA = 50;

ALTER WAREHOUSE IF EXISTS OVERWATCH_WH
  SET RESOURCE_MONITOR = OVERWATCH_WH_RM;

USE DATABASE DBA_MAINT_DB;
USE SCHEMA OVERWATCH;

CREATE TABLE IF NOT EXISTS OVERWATCH_ANNOTATIONS (
  ANNOTATION_ID     NUMBER AUTOINCREMENT PRIMARY KEY,
  CREATED_BY        VARCHAR(200),
  CREATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  ENTITY            VARCHAR(500),
  ENTITY_TYPE       VARCHAR(50),
  WINDOW_START      TIMESTAMP_NTZ NOT NULL,
  WINDOW_END        TIMESTAMP_NTZ NOT NULL,
  ANNOTATION_TYPE   VARCHAR(100),
  DESCRIPTION       VARCHAR(2000),
  SUPPRESS_ALERTS   BOOLEAN DEFAULT TRUE,
  ACTIVE            BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS OVERWATCH_SCHEMA_MIGRATION (
  MIGRATION_VERSION   VARCHAR(100) NOT NULL,
  MIGRATION_NAME      VARCHAR(300) NOT NULL,
  APPLIED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  APPLIED_BY          VARCHAR(200) DEFAULT CURRENT_USER(),
  SOURCE_FILE         VARCHAR(500),
  NOTES               VARCHAR(1000)
);

MERGE INTO OVERWATCH_SCHEMA_MIGRATION tgt
USING (
  SELECT
    '2026.06.04-release-remediation' AS MIGRATION_VERSION,
    'Release remediation for annotations and app warehouse guardrails' AS MIGRATION_NAME,
    'snowflake/OVERWATCH_RELEASE_REMEDIATION.sql' AS SOURCE_FILE,
    'Creates alert annotation windows table and attaches OVERWATCH_WH_RM to OVERWATCH_WH for existing deployments.' AS NOTES
) src
ON tgt.MIGRATION_VERSION = src.MIGRATION_VERSION
WHEN MATCHED THEN UPDATE SET
  MIGRATION_NAME = src.MIGRATION_NAME,
  SOURCE_FILE = src.SOURCE_FILE,
  NOTES = src.NOTES
WHEN NOT MATCHED THEN INSERT (MIGRATION_VERSION, MIGRATION_NAME, SOURCE_FILE, NOTES)
VALUES (src.MIGRATION_VERSION, src.MIGRATION_NAME, src.SOURCE_FILE, src.NOTES);

SHOW RESOURCE MONITORS LIKE 'OVERWATCH_WH_RM';
SHOW WAREHOUSES LIKE 'OVERWATCH_WH';
SHOW TABLES LIKE 'OVERWATCH_ANNOTATIONS' IN SCHEMA DBA_MAINT_DB.OVERWATCH;
SHOW TASKS LIKE 'OVERWATCH_%' IN SCHEMA DBA_MAINT_DB.OVERWATCH;

-- Optional post-remediation task checks. Run these only after reviewing recent
-- TASK_HISTORY and confirming OVERWATCH_ANNOTATIONS exists.
-- EXECUTE TASK DBA_MAINT_DB.OVERWATCH.OVERWATCH_ANOMALY_CHECK;
-- ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.OVERWATCH_ANOMALY_CHECK RESUME;
-- ALTER TASK IF EXISTS DBA_MAINT_DB.OVERWATCH.OVERWATCH_COST_SAVINGS_VERIFY RESUME;
