-- OVERWATCH_NATIVE_ALERT_DEPLOYMENT.sql
-- OVERWATCH native alert deployment review.
-- Run after OVERWATCH_MART_SETUP.sql.
--
-- This script does not enable or execute native alerts automatically. It builds
-- an operator review view and a remediation dry-run staging procedure so alert
-- deployment can be approved one candidate at a time.

USE DATABASE DBA_MAINT_DB;
USE SCHEMA OVERWATCH;

CREATE OR REPLACE VIEW ALERT_NATIVE_DEPLOYMENT_REVIEW_V AS
SELECT
  REGISTRY_KEY,
  ALERT_KEY,
  CATEGORY,
  ALERT_OBJECT_NAME,
  TARGET_ROUTE,
  WAREHOUSE_NAME,
  SCHEDULE_TEXT,
  STATUS,
  ENABLED_BY_DEFAULT,
  CASE
    WHEN COALESCE(ENABLED_BY_DEFAULT, FALSE) THEN 'BLOCKED_ENABLED_BY_DEFAULT'
    WHEN UPPER(COALESCE(STATUS, 'CANDIDATE')) IN ('APPROVED', 'READY', 'READY_TO_DEPLOY') THEN 'READY_FOR_MANUAL_DEPLOY'
    WHEN UPPER(COALESCE(STATUS, 'CANDIDATE')) IN ('DEPLOYED', 'ACTIVE') THEN 'DEPLOYED_MONITOR'
    ELSE 'CANDIDATE_REVIEW_REQUIRED'
  END AS DEPLOYMENT_STATE,
  IFF(GENERATED_CREATE_SQL ILIKE '%CREATE OR REPLACE ALERT%', TRUE, FALSE) AS DEPLOYMENT_SQL_PRESENT,
  IFF(GENERATED_DROP_SQL ILIKE '%DROP ALERT%', TRUE, FALSE) AS ROLLBACK_SQL_PRESENT,
  CASE
    WHEN COALESCE(ENABLED_BY_DEFAULT, FALSE) THEN 'Set ENABLED_BY_DEFAULT to FALSE before review can continue.'
    WHEN UPPER(COALESCE(STATUS, 'CANDIDATE')) IN ('APPROVED', 'READY', 'READY_TO_DEPLOY') THEN 'Run GENERATED_CREATE_SQL manually after owner, threshold, schedule, and warehouse approval.'
    WHEN UPPER(COALESCE(STATUS, 'CANDIDATE')) IN ('DEPLOYED', 'ACTIVE') THEN 'Monitor ALERT_EVENTS and dry-run outcomes; use GENERATED_DROP_SQL only for rollback.'
    ELSE 'Review owner, threshold, route, safety note, and generated SQL before marking approved.'
  END AS DEPLOYMENT_NEXT_STEP,
  'SHOW ALERTS LIKE ''' || ALERT_OBJECT_NAME || ''';' AS VALIDATION_SQL,
  SAFETY_NOTE,
  GENERATED_CREATE_SQL,
  GENERATED_DROP_SQL,
  UPDATED_AT,
  UPDATED_BY
FROM ALERT_NATIVE_OBJECT_REGISTRY;

CREATE OR REPLACE PROCEDURE SP_OVERWATCH_STAGE_ALERT_REMEDIATION_DRY_RUN(
  P_EVENT_ID NUMBER,
  P_ALERT_KEY VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
  INSERT INTO ALERT_REMEDIATION_DRY_RUN
    (POLICY_ID, EVENT_ID, ALERT_KEY, DRY_RUN_STATUS, BEFORE_STATE, PROPOSED_SQL,
     EXPECTED_EFFECT, BLOCKING_REASON, VERIFICATION_SQL)
  SELECT
    p.POLICY_ID,
    e.EVENT_ID,
    e.ALERT_KEY,
    CASE
      WHEN COALESCE(p.AUTO_ELIGIBLE, FALSE) THEN 'REVIEW_REQUIRED_AUTO_DISABLED'
      ELSE 'BLOCKED_REVIEW_REQUIRED'
    END AS DRY_RUN_STATUS,
    p.BEFORE_STATE_SQL AS BEFORE_STATE,
    COALESCE(NULLIF(p.EXECUTION_SQL_TEMPLATE, ''), p.DRY_RUN_SQL) AS PROPOSED_SQL,
    'Dry-run only. Capture before-state, review route owner, and verify expected impact before any manual action.' AS EXPECTED_EFFECT,
    CASE
      WHEN COALESCE(p.AUTO_ELIGIBLE, FALSE) THEN 'AUTO_ELIGIBLE is not sufficient for execution; guarded automation is not enabled in OVERWATCH.'
      ELSE 'AUTO_ELIGIBLE is false. Manual review is required before any action.'
    END AS BLOCKING_REASON,
    p.VERIFICATION_SQL
  FROM ALERT_EVENTS e
  JOIN ALERT_REMEDIATION_POLICY p
    ON UPPER(p.ALERT_KEY) = UPPER(e.ALERT_KEY)
   AND COALESCE(p.ACTIVE, TRUE)
  WHERE (P_EVENT_ID IS NULL OR e.EVENT_ID = P_EVENT_ID)
    AND (P_ALERT_KEY IS NULL OR UPPER(e.ALERT_KEY) = UPPER(P_ALERT_KEY))
    AND NOT EXISTS (
      SELECT 1
      FROM ALERT_REMEDIATION_DRY_RUN d
      WHERE d.EVENT_ID = e.EVENT_ID
        AND d.POLICY_ID = p.POLICY_ID
        AND d.CREATED_AT >= DATEADD('hour', -24, CURRENT_TIMESTAMP())
    );

  RETURN 'Remediation dry-run staging completed. Review ALERT_REMEDIATION_DRY_RUN before any manual action.';
END;
$$;

SELECT *
FROM ALERT_NATIVE_DEPLOYMENT_REVIEW_V
ORDER BY DEPLOYMENT_STATE, TARGET_ROUTE, CATEGORY, ALERT_KEY;

-- Example dry-run staging call for all events matching an alert key:
-- CALL SP_OVERWATCH_STAGE_ALERT_REMEDIATION_DRY_RUN(NULL, 'COST_WAREHOUSE_CREDIT_SPIKE');
