-- OVERWATCH_MART_VALIDATION.sql
-- Read-only deployment validation for the OVERWATCH command-center marts.
-- Run from the database/schema where OVERWATCH_MART_SETUP.sql was deployed.

-- 1) Required command-center objects.
WITH required_objects AS (
    SELECT * FROM VALUES
        ('TABLE', 'MART_EXECUTIVE_OBSERVABILITY'),
        ('TABLE', 'FACT_COST_DAILY'),
        ('TABLE', 'FACT_CORTEX_DAILY'),
        ('TABLE', 'FACT_QUERY_HOURLY'),
        ('TABLE', 'FACT_QUERY_DETAIL_RECENT'),
        ('TABLE', 'FACT_TASK_RUN'),
        ('TABLE', 'FACT_TASK_CRITICAL_PATH'),
        ('TABLE', 'FACT_PROCEDURE_RUN'),
        ('TABLE', 'ALERT_EVENTS'),
        ('TABLE', 'ALERT_ACKNOWLEDGEMENTS'),
        ('TABLE', 'ALERT_REMEDIATION_LOG'),
        ('TABLE', 'ALERT_NOTIFICATION_LOG'),
        ('TABLE', 'ALERT_THRESHOLDS'),
        ('TABLE', 'ALERT_OWNER_ROUTING'),
        ('TABLE', 'OVERWATCH_RECON_CONFIG'),
        ('TABLE', 'OVERWATCH_RECON_RUN'),
        ('TABLE', 'OVERWATCH_SCHEMA_DIFF_RESULT')
    AS t(REQUIRED_TYPE, REQUIRED_OBJECT)
),
existing_objects AS (
    SELECT TABLE_TYPE AS OBJECT_TYPE, TABLE_NAME AS OBJECT_NAME
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = CURRENT_SCHEMA()
    UNION ALL
    SELECT 'VIEW' AS OBJECT_TYPE, TABLE_NAME AS OBJECT_NAME
    FROM INFORMATION_SCHEMA.VIEWS
    WHERE TABLE_SCHEMA = CURRENT_SCHEMA()
)
SELECT
    r.REQUIRED_TYPE,
    r.REQUIRED_OBJECT,
    IFF(e.OBJECT_NAME IS NULL, 'MISSING', 'PRESENT') AS VALIDATION_STATUS
FROM required_objects r
LEFT JOIN existing_objects e
  ON UPPER(e.OBJECT_NAME) = r.REQUIRED_OBJECT
ORDER BY VALIDATION_STATUS DESC, REQUIRED_TYPE, REQUIRED_OBJECT;

-- 2) Deployable object count contract.
WITH expected_counts AS (
    SELECT * FROM VALUES
        ('TABLE', 56),
        ('VIEW', 2),
        ('PROCEDURE', 8),
        ('FUNCTION', 1)
    AS t(OBJECT_TYPE, EXPECTED_COUNT)
),
actual_counts AS (
    SELECT 'TABLE' AS OBJECT_TYPE, COUNT(*) AS ACTUAL_COUNT
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = CURRENT_SCHEMA()
      AND (
          TABLE_NAME ILIKE 'FACT\_%' ESCAPE '\'
          OR TABLE_NAME ILIKE 'DIM\_%' ESCAPE '\'
          OR TABLE_NAME ILIKE 'MART\_%' ESCAPE '\'
          OR TABLE_NAME ILIKE 'OVERWATCH\_%' ESCAPE '\'
          OR TABLE_NAME ILIKE 'ALERT\_%' ESCAPE '\'
      )
    UNION ALL
    SELECT 'VIEW', COUNT(*)
    FROM INFORMATION_SCHEMA.VIEWS
    WHERE TABLE_SCHEMA = CURRENT_SCHEMA()
      AND (
          TABLE_NAME ILIKE 'OVERWATCH\_%' ESCAPE '\'
          OR TABLE_NAME ILIKE 'ALERT\_%' ESCAPE '\'
      )
    UNION ALL
    SELECT 'PROCEDURE', COUNT(DISTINCT PROCEDURE_NAME)
    FROM INFORMATION_SCHEMA.PROCEDURES
    WHERE PROCEDURE_SCHEMA = CURRENT_SCHEMA()
      AND PROCEDURE_NAME ILIKE 'SP\_OVERWATCH\_%' ESCAPE '\'
    UNION ALL
    SELECT 'FUNCTION', COUNT(DISTINCT FUNCTION_NAME)
    FROM INFORMATION_SCHEMA.FUNCTIONS
    WHERE FUNCTION_SCHEMA = CURRENT_SCHEMA()
      AND FUNCTION_NAME ILIKE 'OVERWATCH\_%' ESCAPE '\'
)
SELECT
    e.OBJECT_TYPE,
    e.EXPECTED_COUNT,
    COALESCE(a.ACTUAL_COUNT, 0) AS ACTUAL_COUNT,
    IFF(COALESCE(a.ACTUAL_COUNT, 0) = e.EXPECTED_COUNT, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM expected_counts e
LEFT JOIN actual_counts a
  ON a.OBJECT_TYPE = e.OBJECT_TYPE
ORDER BY VALIDATION_STATUS DESC, e.OBJECT_TYPE;

-- 3) Task graph deployment proof.
SHOW TASKS IN SCHEMA;

WITH expected_tasks AS (
    SELECT * FROM VALUES
        ('OVERWATCH_ANOMALY_CHECK'),
        ('OVERWATCH_LOAD_HOURLY'),
        ('OVERWATCH_LOAD_CORTEX'),
        ('OVERWATCH_REFRESH_CONTROL_ROOM'),
        ('OVERWATCH_COST_MONITORING_REFRESH'),
        ('OVERWATCH_EXECUTIVE_OBSERVABILITY_REFRESH'),
        ('OVERWATCH_LOAD_DAILY')
    AS t(TASK_NAME)
),
actual_tasks AS (
    SELECT
        UPPER("name") AS TASK_NAME,
        UPPER(COALESCE("state", 'UNKNOWN')) AS TASK_STATE
    FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
)
SELECT
    e.TASK_NAME,
    COALESCE(a.TASK_STATE, 'MISSING') AS TASK_STATE,
    CASE
        WHEN a.TASK_NAME IS NULL THEN 'MISSING'
        WHEN a.TASK_STATE = 'SUSPENDED' THEN 'SUSPENDED'
        ELSE 'PRESENT'
    END AS VALIDATION_STATUS
FROM expected_tasks e
LEFT JOIN actual_tasks a
  ON a.TASK_NAME = e.TASK_NAME
ORDER BY VALIDATION_STATUS DESC, e.TASK_NAME;

-- 4) Executive board panel coverage.
WITH required_panels AS (
    SELECT * FROM VALUES
        ('KPI'),
        ('DAILY_COST'),
        ('MONTHLY_COST'),
        ('DAILY_WORKLOAD'),
        ('COST_DRIVER'),
        ('QUERY_TYPE'),
        ('QUERY_DATABASE'),
        ('EXEC_STATUS'),
        ('WAREHOUSE_PRESSURE'),
        ('FRESHNESS'),
        ('SOURCE_STATUS')
    AS t(PANEL)
),
actual_panels AS (
    SELECT PANEL, COUNT(*) AS ROW_COUNT, MAX(SNAPSHOT_TS) AS LATEST_SNAPSHOT
    FROM MART_EXECUTIVE_OBSERVABILITY
    GROUP BY PANEL
)
SELECT
    r.PANEL,
    COALESCE(a.ROW_COUNT, 0) AS ROW_COUNT,
    a.LATEST_SNAPSHOT,
    IFF(a.PANEL IS NULL, 'MISSING', 'PRESENT') AS VALIDATION_STATUS
FROM required_panels r
LEFT JOIN actual_panels a
  ON a.PANEL = r.PANEL
ORDER BY VALIDATION_STATUS DESC, r.PANEL;

-- 5) Executive board freshness by source.
SELECT
    COMPANY,
    ENVIRONMENT,
    WINDOW_DAYS,
    DIMENSION AS SOURCE_NAME,
    MAX(PERIOD_START) AS LATEST_SOURCE_TS,
    DATEDIFF('minute', MAX(PERIOD_START), CURRENT_TIMESTAMP()) AS AGE_MINUTES,
    MAX(SOURCE) AS SOURCE_TABLE
FROM MART_EXECUTIVE_OBSERVABILITY
WHERE PANEL = 'FRESHNESS'
GROUP BY COMPANY, ENVIRONMENT, WINDOW_DAYS, DIMENSION
ORDER BY AGE_MINUTES DESC NULLS FIRST, SOURCE_NAME;

-- 6) Refresh contract for first paint and live fallback.
WITH refresh_contract AS (
    SELECT * FROM VALUES
        ('EXECUTIVE_OBSERVABILITY', 'Executive Landing', 'MART', 60, 'TASK_AFTER_FACT_LOADS', 'MART_EXECUTIVE_OBSERVABILITY', 35, TRUE, FALSE, 'Executive Landing reads one compact mart query on first paint.', 'DBA / Platform'),
        ('DBA_CONTROL_ROOM_FAST', 'DBA Control Room', 'MART', 60, 'TASK_AFTER_HOURLY_FACTS', 'MART_DBA_CONTROL_ROOM', 35, TRUE, FALSE, 'Morning triage renders from a small control-room mart before live ACCOUNT_USAGE detail.', 'DBA On-Call'),
        ('COST_WATCH_FLOOR', 'Cost & Contract', 'MART_AND_BOUNDED_OFFICIAL_COST', 60, 'TASK_PLUS_EXPLICIT_REFRESH', 'FACT_COST_DAILY; FACT_CORTEX_DAILY; WAREHOUSE_METERING_HISTORY', 730, TRUE, FALSE, 'Cost first paint shows lightweight spend, Cortex, and warehouse movement; full attribution proof is explicit.', 'DBA / Cost owner'),
        ('ALERT_COMMAND_VIEW', 'Alert Center', 'APP_TABLES', 15, 'TASK_OR_APP_WRITE', 'ALERT_EVENTS; ALERT_NOTIFICATION_LOG; OVERWATCH_ACTION_QUEUE', 180, TRUE, FALSE, 'Alert Center may auto-load bounded app tables because they are small, routed, and deduplicated.', 'DBA / Alert Owner'),
        ('WORKLOAD_SNAPSHOT', 'Workload Operations', 'MART_AND_TASK_HISTORY', 30, 'TASK_PLUS_EXPLICIT_REFRESH', 'FACT_QUERY_HOURLY; FACT_TASK_RUN', 35, TRUE, FALSE, 'Workload first paint shows task/query pressure from compact facts; live triage is explicit.', 'DBA / Workload Owner'),
        ('LIVE_TRIAGE', 'DBA Control Room / Workload Operations', 'NEAR_REAL_TIME', 5, 'ON_DEMAND_ONLY', 'INFORMATION_SCHEMA table functions; SHOW commands', 1, FALSE, TRUE, 'Near-real-time checks stay explicit to avoid runaway monitoring cost.', 'DBA On-Call'),
        ('DATA_RECONCILIATION', 'Workload Operations', 'ON_DEMAND_PROOF', NULL, 'OPERATOR_RUN', 'OVERWATCH_RECON_CONFIG; OVERWATCH_RECON_RUN', 365, FALSE, TRUE, 'Schema and data comparison proof can be expensive and runs only on operator request.', 'DBA / Data Owner')
    AS t(
        POLICY_NAME, SURFACE, SOURCE_CLASS, TARGET_FRESHNESS_MIN, REFRESH_METHOD,
        BASE_OBJECT, RETENTION_DAYS, RUN_IN_FIRST_PAINT, APPROVED_LIVE_FALLBACK,
        WHY_THIS_POLICY, OWNER
    )
)
SELECT
    POLICY_NAME,
    SURFACE,
    SOURCE_CLASS AS FIRST_PAINT_SOURCE,
    TARGET_FRESHNESS_MIN AS TARGET_FRESHNESS_MINUTES,
    APPROVED_LIVE_FALLBACK AS LIVE_FALLBACK_ALLOWED,
    RUN_IN_FIRST_PAINT,
    REFRESH_METHOD,
    BASE_OBJECT,
    OWNER,
    WHY_THIS_POLICY AS WHY_THIS_DECISION
FROM refresh_contract
ORDER BY RUN_IN_FIRST_PAINT DESC, SURFACE;

-- 7) Refresh freshness enforcement proof.
WITH refresh_contract AS (
    SELECT * FROM VALUES
        ('EXECUTIVE_OBSERVABILITY', 'Executive Landing', 'MART', 60, 'TASK_AFTER_FACT_LOADS', 'MART_EXECUTIVE_OBSERVABILITY', 35, TRUE, FALSE),
        ('DBA_CONTROL_ROOM_FAST', 'DBA Control Room', 'MART', 60, 'TASK_AFTER_HOURLY_FACTS', 'MART_DBA_CONTROL_ROOM', 35, TRUE, FALSE),
        ('COST_WATCH_FLOOR', 'Cost & Contract', 'MART_AND_BOUNDED_OFFICIAL_COST', 60, 'TASK_PLUS_EXPLICIT_REFRESH', 'FACT_COST_DAILY; FACT_CORTEX_DAILY; WAREHOUSE_METERING_HISTORY', 730, TRUE, FALSE),
        ('ALERT_COMMAND_VIEW', 'Alert Center', 'APP_TABLES', 15, 'TASK_OR_APP_WRITE', 'ALERT_EVENTS; ALERT_NOTIFICATION_LOG; OVERWATCH_ACTION_QUEUE', 180, TRUE, FALSE),
        ('WORKLOAD_SNAPSHOT', 'Workload Operations', 'MART_AND_TASK_HISTORY', 30, 'TASK_PLUS_EXPLICIT_REFRESH', 'FACT_QUERY_HOURLY; FACT_TASK_RUN', 35, TRUE, FALSE),
        ('LIVE_TRIAGE', 'DBA Control Room / Workload Operations', 'NEAR_REAL_TIME', 5, 'ON_DEMAND_ONLY', 'INFORMATION_SCHEMA table functions; SHOW commands', 1, FALSE, TRUE),
        ('DATA_RECONCILIATION', 'Workload Operations', 'ON_DEMAND_PROOF', NULL, 'OPERATOR_RUN', 'OVERWATCH_RECON_CONFIG; OVERWATCH_RECON_RUN', 365, FALSE, TRUE)
    AS t(
        POLICY_NAME, SURFACE, SOURCE_CLASS, TARGET_FRESHNESS_MIN, REFRESH_METHOD,
        BASE_OBJECT, RETENTION_DAYS, RUN_IN_FIRST_PAINT, APPROVED_LIVE_FALLBACK
    )
),
freshness AS (
    SELECT
        'Executive Landing' AS SURFACE,
        MAX(SNAPSHOT_TS) AS LATEST_REFRESH_TS
    FROM MART_EXECUTIVE_OBSERVABILITY
    UNION ALL
    SELECT
        'Alert Center' AS SURFACE,
        MAX(ALERT_TS) AS LATEST_REFRESH_TS
    FROM ALERT_EVENTS
),
policy AS (
    SELECT
        SURFACE,
        MIN(TARGET_FRESHNESS_MIN) AS TARGET_FRESHNESS_MINUTES,
        MAX(IFF(RUN_IN_FIRST_PAINT, 1, 0)) AS FIRST_PAINT_REQUIRED,
        MAX(IFF(APPROVED_LIVE_FALLBACK, 1, 0)) AS LIVE_FALLBACK_ALLOWED,
        LISTAGG(POLICY_NAME, ', ') WITHIN GROUP (ORDER BY POLICY_NAME) AS POLICY_NAMES
    FROM refresh_contract
    WHERE RUN_IN_FIRST_PAINT
    GROUP BY SURFACE
)
SELECT
    p.SURFACE,
    p.POLICY_NAMES,
    p.TARGET_FRESHNESS_MINUTES,
    f.LATEST_REFRESH_TS,
    DATEDIFF('minute', f.LATEST_REFRESH_TS, CURRENT_TIMESTAMP()) AS AGE_MINUTES,
    IFF(p.FIRST_PAINT_REQUIRED = 1, 'YES', 'NO') AS FIRST_PAINT_REQUIRED,
    IFF(p.LIVE_FALLBACK_ALLOWED = 1, 'YES', 'NO') AS LIVE_FALLBACK_ALLOWED,
    CASE
        WHEN f.LATEST_REFRESH_TS IS NULL THEN 'NO_ROWS'
        WHEN p.TARGET_FRESHNESS_MINUTES IS NULL THEN 'NO_TARGET'
        WHEN DATEDIFF('minute', f.LATEST_REFRESH_TS, CURRENT_TIMESTAMP()) <= p.TARGET_FRESHNESS_MINUTES THEN 'FRESH'
        ELSE 'STALE'
    END AS REFRESH_STATE
FROM policy p
LEFT JOIN freshness f
  ON f.SURFACE = p.SURFACE
ORDER BY
    CASE REFRESH_STATE WHEN 'STALE' THEN 0 WHEN 'NO_ROWS' THEN 1 WHEN 'NO_TARGET' THEN 2 ELSE 3 END,
    p.SURFACE;

-- 8) Alert lifecycle and remediation audit coverage.
SELECT 'ALERT_EVENTS' AS OBJECT_NAME, COUNT(*) AS ROW_COUNT, MAX(ALERT_TS) AS LATEST_EVENT_TS FROM ALERT_EVENTS
UNION ALL
SELECT 'ALERT_ACKNOWLEDGEMENTS', COUNT(*), MAX(ACKNOWLEDGED_AT) FROM ALERT_ACKNOWLEDGEMENTS
UNION ALL
SELECT 'ALERT_REMEDIATION_LOG', COUNT(*), MAX(REQUESTED_AT) FROM ALERT_REMEDIATION_LOG
UNION ALL
SELECT 'ALERT_NOTIFICATION_LOG', COUNT(*), MAX(NOTIFICATION_TS) FROM ALERT_NOTIFICATION_LOG;

-- 9) Reconciliation configuration and last run proof.
WITH latest_runs AS (
    SELECT
        r.*,
        ROW_NUMBER() OVER (
            PARTITION BY r.CHECK_ID
            ORDER BY r.RUN_TS DESC, r.RUN_ID DESC
        ) AS rn
    FROM OVERWATCH_RECON_RUN r
)
SELECT
    c.CHECK_ID,
    c.CHECK_NAME,
    c.SOURCE_DATABASE,
    c.SOURCE_SCHEMA,
    c.TARGET_DATABASE,
    c.TARGET_SCHEMA,
    c.TABLE_PATTERN,
    c.CHECK_MODE,
    c.SEVERITY,
    c.OWNER,
    c.ENABLED,
    lr.RUN_TS AS LAST_RUN_TS,
    lr.RUN_STATUS AS LAST_RUN_STATUS
FROM OVERWATCH_RECON_CONFIG c
LEFT JOIN latest_runs lr
  ON lr.CHECK_ID = c.CHECK_ID
 AND lr.rn = 1
ORDER BY c.ENABLED DESC, c.SEVERITY, c.CHECK_NAME;

-- 10) Secure-view and dynamic-table compatibility guard.
SHOW DYNAMIC TABLES IN SCHEMA;

WITH dynamic_objects AS (
    SELECT UPPER("name") AS OBJECT_NAME
    FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
),
overwatch_dynamic_collisions AS (
    SELECT OBJECT_NAME
    FROM dynamic_objects
    WHERE OBJECT_NAME ILIKE 'FACT\_%' ESCAPE '\'
       OR OBJECT_NAME ILIKE 'DIM\_%' ESCAPE '\'
       OR OBJECT_NAME ILIKE 'MART\_%' ESCAPE '\'
       OR OBJECT_NAME ILIKE 'OVERWATCH\_%' ESCAPE '\'
       OR OBJECT_NAME ILIKE 'ALERT\_%' ESCAPE '\'
)
SELECT
    'DYNAMIC_TABLE_COLLISIONS' AS CHECK_NAME,
    COUNT(*) AS ISSUE_COUNT,
    IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS VALIDATION_STATUS,
    LISTAGG(OBJECT_NAME, ', ') WITHIN GROUP (ORDER BY OBJECT_NAME) AS DETAILS
FROM overwatch_dynamic_collisions;

SELECT
    'SECURE_VIEW_COLLISIONS' AS CHECK_NAME,
    COUNT(*) AS ISSUE_COUNT,
    IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS VALIDATION_STATUS,
    LISTAGG(TABLE_NAME, ', ') WITHIN GROUP (ORDER BY TABLE_NAME) AS DETAILS
FROM INFORMATION_SCHEMA.VIEWS
WHERE TABLE_SCHEMA = CURRENT_SCHEMA()
  AND UPPER(COALESCE(IS_SECURE, 'NO')) = 'YES'
  AND (
      TABLE_NAME ILIKE 'FACT\_%' ESCAPE '\'
      OR TABLE_NAME ILIKE 'DIM\_%' ESCAPE '\'
      OR TABLE_NAME ILIKE 'MART\_%' ESCAPE '\'
      OR TABLE_NAME ILIKE 'OVERWATCH\_%' ESCAPE '\'
      OR TABLE_NAME ILIKE 'ALERT\_%' ESCAPE '\'
  );

-- 11) Caller context for privilege troubleshooting.
SELECT
    CURRENT_ACCOUNT() AS CURRENT_ACCOUNT_NAME,
    CURRENT_DATABASE() AS CURRENT_DATABASE_NAME,
    CURRENT_SCHEMA() AS CURRENT_SCHEMA_NAME,
    CURRENT_USER() AS CURRENT_USER_NAME,
    CURRENT_ROLE() AS CURRENT_ROLE_NAME,
    CURRENT_WAREHOUSE() AS CURRENT_WAREHOUSE_NAME;
