-- OVERWATCH Snowflake Mart Setup runner
--
-- The deployable setup has been split into numbered files under
-- snowflake/mart_setup/. Run those files in numeric order.
--
-- SnowSQL example:
--   !source snowflake/mart_setup/01_roles.sql
--   !source snowflake/mart_setup/02_databases.sql
--   !source snowflake/mart_setup/03_schemas.sql
--   !source snowflake/mart_setup/04_tables.sql
--   !source snowflake/mart_setup/05_views.sql
--   !source snowflake/mart_setup/06_procedures.sql
--   !source snowflake/mart_setup/07_tasks.sql
--   !source snowflake/mart_setup/08_grants.sql
--   !source snowflake/mart_setup/09_validation.sql
--
-- See snowflake/mart_setup/README.md for deployment order and notes.
