-- OVERWATCH deprecated object retirement draft
-- Date: 2026-06-22
--
-- This file is intentionally review-only.
-- Do not uncomment or execute any DROP statement until:
--   1. The simplified four-area UI has passed Snowflake validation.
--   2. The object is confirmed unused by visible UI, tasks, and procedures.
--   3. A DBA owner explicitly approves the final drop list.
--   4. A rollback/export plan exists.

-- Executive scorecard objects.
-- DROP TABLE IF EXISTS OVERWATCH_EXECUTIVE_SCORECARD_CONFIG;
-- DROP TABLE IF EXISTS OVERWATCH_EXECUTIVE_SCORECARD_HISTORY;
-- DROP TABLE IF EXISTS MART_EXECUTIVE_SCORECARD_SUMMARY;

-- Forecasting objects.
-- DROP TABLE IF EXISTS OVERWATCH_FORECAST_CONFIG;
-- DROP TABLE IF EXISTS OVERWATCH_FORECAST_HISTORY;
-- DROP TABLE IF EXISTS MART_EXECUTIVE_FORECAST_SUMMARY;

-- Data trust / readiness proof objects.
-- DROP TABLE IF EXISTS OVERWATCH_DATA_TRUST_SOURCE;
-- DROP TABLE IF EXISTS OVERWATCH_DATA_TRUST_STATUS;
-- DROP TABLE IF EXISTS MART_DATA_TRUST_SUMMARY;
-- DROP TABLE IF EXISTS OVERWATCH_PRODUCTION_CHECKLIST;
-- DROP TABLE IF EXISTS OVERWATCH_ROLE_READINESS_REQUIREMENT;
-- DROP TABLE IF EXISTS OVERWATCH_PRIVILEGE_READINESS_REQUIREMENT;
-- DROP TABLE IF EXISTS OVERWATCH_PRODUCTION_VALIDATION_STATUS;
-- DROP TABLE IF EXISTS MART_PRODUCTION_READINESS_SUMMARY;

-- Ownership/value proof objects.
-- DROP TABLE IF EXISTS OVERWATCH_OPERATIONAL_OWNER_MAP;
-- DROP TABLE IF EXISTS MART_OPERATIONAL_OWNER_COVERAGE;
-- DROP TABLE IF EXISTS OVERWATCH_VALUE_LEDGER;
-- DROP TABLE IF EXISTS MART_EXECUTIVE_VALUE_LEDGER;

-- Closed-loop workflow proof objects.
-- DROP TABLE IF EXISTS OVERWATCH_ACTION_WORKFLOW;
-- DROP TABLE IF EXISTS OVERWATCH_ACTION_APPROVAL;
-- DROP TABLE IF EXISTS OVERWATCH_ACTION_EXECUTION_PLAN;
-- DROP TABLE IF EXISTS OVERWATCH_ACTION_VERIFICATION;
-- DROP TABLE IF EXISTS OVERWATCH_ACTION_EVIDENCE;
-- DROP TABLE IF EXISTS MART_CLOSED_LOOP_OPERATIONS_SUMMARY;

-- Overmodeled command-center evidence objects.
-- DROP TABLE IF EXISTS OVERWATCH_COMMAND_CENTER_QUESTION;
-- DROP TABLE IF EXISTS OVERWATCH_COMMAND_CENTER_FINDING;
-- DROP TABLE IF EXISTS OVERWATCH_COMMAND_CENTER_EVIDENCE;
-- DROP TABLE IF EXISTS OVERWATCH_COMMAND_CENTER_RECOMMENDATION;
-- DROP TABLE IF EXISTS MART_COMMAND_CENTER_SUMMARY;

-- Change-intelligence hierarchy candidates.
-- Keep FACT_OBJECT_CHANGE unless a replacement exists.
-- DROP TABLE IF EXISTS OVERWATCH_CHANGE_RULE;
-- DROP TABLE IF EXISTS OVERWATCH_CHANGE_EVENT;
-- DROP TABLE IF EXISTS OVERWATCH_CHANGE_CORRELATION;
-- DROP TABLE IF EXISTS MART_CHANGE_INTELLIGENCE_SUMMARY;

-- Alert deployment/remediation internals.
-- DROP TABLE IF EXISTS ALERT_NATIVE_OBJECT_REGISTRY;
-- DROP TABLE IF EXISTS ALERT_REMEDIATION_POLICY;
-- DROP TABLE IF EXISTS ALERT_REMEDIATION_DRY_RUN;
-- DROP TABLE IF EXISTS ALERT_REMEDIATION_LOG;
-- DROP TABLE IF EXISTS OVERWATCH_ALERT_RULE_AUDIT;
-- DROP TABLE IF EXISTS OVERWATCH_ALERT_RULES;
-- DROP TABLE IF EXISTS OVERWATCH_ALERT_DELIVERY_LOG;
-- DROP VIEW IF EXISTS ALERT_NATIVE_DEPLOYMENT_REVIEW_V;

-- Derived operability/proof facts.
-- DROP TABLE IF EXISTS FACT_ACCOUNT_HEALTH_OPERABILITY_DAILY;
-- DROP TABLE IF EXISTS FACT_SECURITY_OPERABILITY_DAILY;
-- DROP TABLE IF EXISTS FACT_WAREHOUSE_OPERABILITY_DAILY;
-- DROP TABLE IF EXISTS FACT_CHANGE_CONTROL_OPERABILITY_DAILY;
-- DROP TABLE IF EXISTS FACT_COST_SOURCE_HEALTH_DAILY;
-- DROP TABLE IF EXISTS FACT_COST_MONITORING_SIGNAL;
-- DROP TABLE IF EXISTS FACT_COST_INCIDENT_TIMELINE;

-- Snapshot dimensions: approve only if schema/data compare no longer needs them.
-- DROP TABLE IF EXISTS DIM_TASK_SNAPSHOT;
-- DROP TABLE IF EXISTS DIM_PROCEDURE_SNAPSHOT;
-- DROP TABLE IF EXISTS DIM_TABLE_SNAPSHOT;

