-- OVERWATCH_MART_VALIDATION.sql
-- Read-only deployment validation for the OVERWATCH command-center marts.
-- Run from the database/schema where OVERWATCH_MART_SETUP.sql was deployed.

-- 1) Required command-center objects.
WITH required_objects AS (
    SELECT * FROM VALUES
        ('TABLE', 'MART_EXECUTIVE_OBSERVABILITY'),
        ('TABLE', 'MART_SECTION_COMMAND_BRIEF'),
        ('TABLE', 'MART_SECTION_COMMAND_METRIC'),
        ('TABLE', 'MART_SECTION_COMMAND_EXCEPTION'),
        ('TABLE', 'MART_SECTION_COMMAND_ACTION'),
        ('TABLE', 'MART_SECTION_COMMAND_SOURCE'),
        ('TABLE', 'MART_SECTION_DECISION_CURRENT'),
        ('TABLE', 'MART_SECTION_DECISION_CURRENT_FLAT'),
        ('TABLE', 'MART_SECTION_DECISION_LAST_GOOD'),
        ('TABLE', 'OVERWATCH_DECISION_SETUP_HEALTH'),
        ('TABLE', 'OVERWATCH_DECISION_REFRESH_AUDIT'),
        ('TABLE', 'MART_EXECUTIVE_DECISION_INBOX'),
        ('TABLE', 'OVERWATCH_SECTION_COMMAND_SOURCE_CONFIG'),
        ('TABLE', 'FACT_COST_DAILY'),
        ('TABLE', 'FACT_CORTEX_DAILY'),
        ('TABLE', 'FACT_QUERY_HOURLY'),
        ('TABLE', 'FACT_QUERY_DETAIL_RECENT'),
        ('TABLE', 'FACT_TASK_RUN'),
        ('TABLE', 'FACT_TASK_CRITICAL_PATH'),
        ('TABLE', 'FACT_PROCEDURE_RUN'),
        ('TABLE', 'ALERT_EVENTS'),
        ('TABLE', 'ALERT_ACKNOWLEDGEMENTS'),
        ('TABLE', 'ALERT_REMEDIATION_LOG'),
        ('TABLE', 'ALERT_REMEDIATION_POLICY'),
        ('TABLE', 'ALERT_REMEDIATION_DRY_RUN'),
        ('TABLE', 'ALERT_NATIVE_OBJECT_REGISTRY'),
        ('VIEW', 'ALERT_NATIVE_DEPLOYMENT_REVIEW_V'),
        ('TABLE', 'ALERT_NOTIFICATION_LOG'),
        ('TABLE', 'ALERT_THRESHOLDS'),
        ('TABLE', 'ALERT_OWNER_ROUTING'),
        ('TABLE', 'OVERWATCH_RECON_CONFIG'),
        ('TABLE', 'OVERWATCH_RECON_RUN'),
        ('TABLE', 'OVERWATCH_SCHEMA_DIFF_RESULT'),
        ('TABLE', 'OVERWATCH_DATA_TRUST_SOURCE'),
        ('TABLE', 'OVERWATCH_DATA_TRUST_STATUS'),
        ('TABLE', 'MART_DATA_TRUST_SUMMARY'),
        ('TABLE', 'OVERWATCH_OPERATIONAL_OWNER_MAP'),
        ('TABLE', 'MART_OPERATIONAL_OWNER_COVERAGE'),
        ('TABLE', 'OVERWATCH_VALUE_LEDGER'),
        ('TABLE', 'MART_EXECUTIVE_VALUE_LEDGER'),
        ('TABLE', 'OVERWATCH_APP_OBSERVABILITY'),
        ('TABLE', 'MART_APP_OBSERVABILITY_SUMMARY'),
        ('TABLE', 'OVERWATCH_PRODUCTION_CHECKLIST'),
        ('TABLE', 'OVERWATCH_ROLE_READINESS_REQUIREMENT'),
        ('TABLE', 'OVERWATCH_PRIVILEGE_READINESS_REQUIREMENT'),
        ('TABLE', 'OVERWATCH_PRODUCTION_VALIDATION_STATUS'),
        ('TABLE', 'MART_PRODUCTION_READINESS_SUMMARY'),
        ('TABLE', 'OVERWATCH_EXECUTIVE_SCORECARD_CONFIG'),
        ('TABLE', 'OVERWATCH_EXECUTIVE_SCORECARD_HISTORY'),
        ('TABLE', 'MART_EXECUTIVE_SCORECARD_SUMMARY'),
        ('TABLE', 'OVERWATCH_FORECAST_CONFIG'),
        ('TABLE', 'OVERWATCH_FORECAST_HISTORY'),
        ('TABLE', 'MART_EXECUTIVE_FORECAST_SUMMARY'),
        ('TABLE', 'OVERWATCH_CHANGE_RULE'),
        ('TABLE', 'OVERWATCH_CHANGE_EVENT'),
        ('TABLE', 'OVERWATCH_CHANGE_CORRELATION'),
        ('TABLE', 'MART_CHANGE_INTELLIGENCE_SUMMARY'),
        ('TABLE', 'OVERWATCH_ACTION_WORKFLOW'),
        ('TABLE', 'OVERWATCH_ACTION_APPROVAL'),
        ('TABLE', 'OVERWATCH_ACTION_EXECUTION_PLAN'),
        ('TABLE', 'OVERWATCH_ACTION_VERIFICATION'),
        ('TABLE', 'OVERWATCH_ACTION_EVIDENCE'),
        ('TABLE', 'MART_CLOSED_LOOP_OPERATIONS_SUMMARY'),
        ('TABLE', 'OVERWATCH_COMMAND_CENTER_QUESTION'),
        ('TABLE', 'OVERWATCH_COMMAND_CENTER_FINDING'),
        ('TABLE', 'OVERWATCH_COMMAND_CENTER_EVIDENCE'),
        ('TABLE', 'OVERWATCH_COMMAND_CENTER_RECOMMENDATION'),
        ('TABLE', 'MART_COMMAND_CENTER_SUMMARY')
    AS t(REQUIRED_TYPE, REQUIRED_OBJECT)
),
existing_objects AS (
    SELECT TABLE_TYPE AS OBJECT_TYPE, TABLE_NAME AS OBJECT_NAME
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = CURRENT_SCHEMA()
    UNION ALL
    SELECT 'VIEW' AS OBJECT_TYPE, TABLE_NAME AS OBJECT_NAME
    FROM INFORMATION_SCHEMA.VIEWS
    WHERE TABLE_SCHEMA = CURRENT_SCHEMA()
)
SELECT
    r.REQUIRED_TYPE,
    r.REQUIRED_OBJECT,
    IFF(e.OBJECT_NAME IS NULL, 'MISSING', 'PRESENT') AS VALIDATION_STATUS
FROM required_objects r
LEFT JOIN existing_objects e
  ON UPPER(e.OBJECT_NAME) = r.REQUIRED_OBJECT
ORDER BY VALIDATION_STATUS DESC, REQUIRED_TYPE, REQUIRED_OBJECT;

-- 2) Deployable object count contract.
WITH expected_counts AS (
    SELECT * FROM VALUES
        ('TABLE', 103),
        ('VIEW', 3),
        ('PROCEDURE', 21),
        ('FUNCTION', 1)
    AS t(OBJECT_TYPE, EXPECTED_COUNT)
),
actual_counts AS (
    SELECT 'TABLE' AS OBJECT_TYPE, COUNT(*) AS ACTUAL_COUNT
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = CURRENT_SCHEMA()
      AND (
          TABLE_NAME ILIKE 'FACT^_%' ESCAPE '^'
          OR TABLE_NAME ILIKE 'DIM^_%' ESCAPE '^'
          OR TABLE_NAME ILIKE 'MART^_%' ESCAPE '^'
          OR TABLE_NAME ILIKE 'OVERWATCH^_%' ESCAPE '^'
          OR TABLE_NAME ILIKE 'ALERT^_%' ESCAPE '^'
      )
    UNION ALL
    SELECT 'VIEW', COUNT(*)
    FROM INFORMATION_SCHEMA.VIEWS
    WHERE TABLE_SCHEMA = CURRENT_SCHEMA()
      AND (
          TABLE_NAME ILIKE 'OVERWATCH^_%' ESCAPE '^'
          OR TABLE_NAME ILIKE 'ALERT^_%' ESCAPE '^'
      )
    UNION ALL
    SELECT 'PROCEDURE', COUNT(DISTINCT PROCEDURE_NAME)
    FROM INFORMATION_SCHEMA.PROCEDURES
    WHERE PROCEDURE_SCHEMA = CURRENT_SCHEMA()
      AND PROCEDURE_NAME ILIKE 'SP^_OVERWATCH^_%' ESCAPE '^'
    UNION ALL
    SELECT 'FUNCTION', COUNT(DISTINCT FUNCTION_NAME)
    FROM INFORMATION_SCHEMA.FUNCTIONS
    WHERE FUNCTION_SCHEMA = CURRENT_SCHEMA()
      AND FUNCTION_NAME ILIKE 'OVERWATCH^_%' ESCAPE '^'
)
SELECT
    e.OBJECT_TYPE,
    e.EXPECTED_COUNT,
    COALESCE(a.ACTUAL_COUNT, 0) AS ACTUAL_COUNT,
    IFF(COALESCE(a.ACTUAL_COUNT, 0) = e.EXPECTED_COUNT, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM expected_counts e
LEFT JOIN actual_counts a
  ON a.OBJECT_TYPE = e.OBJECT_TYPE
ORDER BY VALIDATION_STATUS DESC, e.OBJECT_TYPE;

-- 2b) Known schema drift inventory. This is recommendation-only; do not execute
-- drop or migration SQL without explicit human approval.
WITH known_drift AS (
    SELECT * FROM VALUES
        ('TABLE', 'FACT_COST_GOVERNANCE_SIGNAL', 'cleanup candidate', 'Replaced by cost monitoring, scorecard, forecasting, command-center, and closed-loop marts. Drop after dependency check.', 'DROP TABLE IF EXISTS FACT_COST_GOVERNANCE_SIGNAL;'),
        ('TABLE', 'FACT_MONITORING_COST_DAILY', 'cleanup candidate', 'Superseded by FACT_COST_DAILY, FACT_COST_MONITORING_SIGNAL, and MART_EXECUTIVE_OBSERVABILITY. Drop after dependency check.', 'DROP TABLE IF EXISTS FACT_MONITORING_COST_DAILY;'),
        ('TABLE', 'OVERWATCH_COMPANY_SCOPE', 'migration candidate', 'If it contains useful ALFA/Trexis rules, migrate them to the current company/role/warehouse scope model before dropping.', 'SELECT * FROM OVERWATCH_COMPANY_SCOPE; -- review then DROP TABLE IF EXISTS OVERWATCH_COMPANY_SCOPE;'),
        ('TABLE', 'OVERWATCH_COST_SAVINGS_VERIFICATION_RUN', 'migration candidate', 'Migrate useful savings proof to OVERWATCH_ACTION_VERIFICATION or OVERWATCH_VALUE_LEDGER before dropping.', 'SELECT * FROM OVERWATCH_COST_SAVINGS_VERIFICATION_RUN; -- review then DROP TABLE IF EXISTS OVERWATCH_COST_SAVINGS_VERIFICATION_RUN;'),
        ('TABLE', 'OVERWATCH_ITSM_TICKET', 'required retention', 'Potential ticket/audit history. Export or migrate needed rows before any drop.', 'SELECT * FROM OVERWATCH_ITSM_TICKET;'),
        ('TABLE', 'OVERWATCH_OWNER_DIRECTORY', 'migration candidate', 'Generic owner directory is retired; migrate active routes to OVERWATCH_OPERATIONAL_OWNER_MAP before dropping.', 'SELECT * FROM OVERWATCH_OWNER_DIRECTORY; -- review then DROP TABLE IF EXISTS OVERWATCH_OWNER_DIRECTORY;'),
        ('TABLE', 'OVERWATCH_PLATFORM_FUTURES_CONTROL_REGISTER', 'cleanup candidate', 'Platform futures scope is retired from the app. Drop after dependency check.', 'DROP TABLE IF EXISTS OVERWATCH_PLATFORM_FUTURES_CONTROL_REGISTER;'),
        ('TABLE', 'OVERWATCH_PLATFORM_FUTURES_EVIDENCE', 'cleanup candidate', 'Platform futures evidence is retired from the app. Drop after dependency check.', 'DROP TABLE IF EXISTS OVERWATCH_PLATFORM_FUTURES_EVIDENCE;'),
        ('TABLE', 'OVERWATCH_ROI_LOG', 'migration candidate', 'Migrate any useful value proof to OVERWATCH_VALUE_LEDGER before dropping.', 'SELECT * FROM OVERWATCH_ROI_LOG; -- review then DROP TABLE IF EXISTS OVERWATCH_ROI_LOG;'),
        ('TABLE', 'OVERWATCH_SOURCE_CONTROL_CHANGE', 'migration candidate', 'Migrate useful change rows to OVERWATCH_CHANGE_EVENT before dropping.', 'SELECT * FROM OVERWATCH_SOURCE_CONTROL_CHANGE; -- review then DROP TABLE IF EXISTS OVERWATCH_SOURCE_CONTROL_CHANGE;'),
        ('TABLE', 'PERF_TEST_BENCHMARK_RESULTS', 'approved legacy', 'Perf-test history is approved legacy validation evidence. Drop only if local perf history is formally retired.', 'DROP TABLE IF EXISTS PERF_TEST_BENCHMARK_RESULTS;'),
        ('TABLE', 'PERF_TEST_PROCEDURE_EXECUTION', 'approved legacy', 'Perf-test history is approved legacy validation evidence. Drop only if local perf history is formally retired.', 'DROP TABLE IF EXISTS PERF_TEST_PROCEDURE_EXECUTION;'),
        ('TABLE', 'PERF_TEST_QUERY_HISTORY', 'approved legacy', 'Perf-test history is approved legacy validation evidence. Drop only if local perf history is formally retired.', 'DROP TABLE IF EXISTS PERF_TEST_QUERY_HISTORY;'),
        ('TABLE', 'PERF_TEST_RISK_REGISTER', 'approved legacy', 'Perf-test history is approved legacy validation evidence. Drop only if local perf history is formally retired.', 'DROP TABLE IF EXISTS PERF_TEST_RISK_REGISTER;'),
        ('TABLE', 'PERF_TEST_RUNS', 'approved legacy', 'Perf-test history is approved legacy validation evidence. Drop only if local perf history is formally retired.', 'DROP TABLE IF EXISTS PERF_TEST_RUNS;'),
        ('TABLE', 'PERF_TEST_RUN_CONTROL', 'approved legacy', 'Perf-test history is approved legacy validation evidence. Drop only if local perf history is formally retired.', 'DROP TABLE IF EXISTS PERF_TEST_RUN_CONTROL;'),
        ('TABLE', 'PERF_TEST_TABLE_INVENTORY', 'approved legacy', 'Perf-test history is approved legacy validation evidence. Drop only if local perf history is formally retired.', 'DROP TABLE IF EXISTS PERF_TEST_TABLE_INVENTORY;'),
        ('TABLE', 'PERF_TEST_TASK_HISTORY', 'approved legacy', 'Perf-test history is approved legacy validation evidence. Drop only if local perf history is formally retired.', 'DROP TABLE IF EXISTS PERF_TEST_TASK_HISTORY;'),
        ('TABLE', 'PERF_TEST_USER_ACTIVITY', 'approved legacy', 'Perf-test history is approved legacy validation evidence. Drop only if local perf history is formally retired.', 'DROP TABLE IF EXISTS PERF_TEST_USER_ACTIVITY;'),
        ('TABLE', 'PERF_TEST_WAREHOUSE_METERING_HISTORY', 'approved legacy', 'Perf-test history is approved legacy validation evidence. Drop only if local perf history is formally retired.', 'DROP TABLE IF EXISTS PERF_TEST_WAREHOUSE_METERING_HISTORY;'),
        ('VIEW', 'OVERWATCH_COST_SAVINGS_VERIFICATION_HEALTH_V', 'migration candidate', 'Old savings proof view. Replace with closed-loop verification/value ledger detail.', 'DROP VIEW IF EXISTS OVERWATCH_COST_SAVINGS_VERIFICATION_HEALTH_V;'),
        ('VIEW', 'OVERWATCH_COST_SAVINGS_VERIFICATION_V', 'migration candidate', 'Old savings proof view. Replace with closed-loop verification/value ledger detail.', 'DROP VIEW IF EXISTS OVERWATCH_COST_SAVINGS_VERIFICATION_V;'),
        ('VIEW', 'OVERWATCH_OWNER_DIRECTORY_ACTIVE_V', 'migration candidate', 'Generic owner directory view is retired; migrate routes to OVERWATCH_OPERATIONAL_OWNER_MAP first.', 'DROP VIEW IF EXISTS OVERWATCH_OWNER_DIRECTORY_ACTIVE_V;'),
        ('VIEW', 'OVERWATCH_PLATFORM_FUTURES_CONTROL_COVERAGE_V', 'cleanup candidate', 'Platform futures scope is retired from the app. Drop after dependency check.', 'DROP VIEW IF EXISTS OVERWATCH_PLATFORM_FUTURES_CONTROL_COVERAGE_V;'),
        ('VIEW', 'OVERWATCH_PLATFORM_FUTURES_EVIDENCE_LATEST_V', 'cleanup candidate', 'Platform futures scope is retired from the app. Drop after dependency check.', 'DROP VIEW IF EXISTS OVERWATCH_PLATFORM_FUTURES_EVIDENCE_LATEST_V;'),
        ('VIEW', 'PERF_TEST_APP_USAGE_REPORT_V', 'approved legacy', 'Perf-test view is approved legacy validation evidence. Drop only if local perf reports are formally retired.', 'DROP VIEW IF EXISTS PERF_TEST_APP_USAGE_REPORT_V;'),
        ('VIEW', 'PERF_TEST_CONTROL_SUMMARY_V', 'approved legacy', 'Perf-test view is approved legacy validation evidence. Drop only if local perf reports are formally retired.', 'DROP VIEW IF EXISTS PERF_TEST_CONTROL_SUMMARY_V;'),
        ('VIEW', 'PERF_TEST_COST_ESTIMATE_V', 'approved legacy', 'Perf-test view is approved legacy validation evidence. Drop only if local perf reports are formally retired.', 'DROP VIEW IF EXISTS PERF_TEST_COST_ESTIMATE_V;'),
        ('VIEW', 'PERF_TEST_EXPENSIVE_QUERY_CANDIDATES_V', 'approved legacy', 'Perf-test view is approved legacy validation evidence. Drop only if local perf reports are formally retired.', 'DROP VIEW IF EXISTS PERF_TEST_EXPENSIVE_QUERY_CANDIDATES_V;'),
        ('VIEW', 'PERF_TEST_PRODUCTION_READINESS_V', 'approved legacy', 'Perf-test view is approved legacy validation evidence. Drop only if local perf reports are formally retired.', 'DROP VIEW IF EXISTS PERF_TEST_PRODUCTION_READINESS_V;'),
        ('VIEW', 'PERF_TEST_SCALE_SUMMARY_V', 'approved legacy', 'Perf-test view is approved legacy validation evidence. Drop only if local perf reports are formally retired.', 'DROP VIEW IF EXISTS PERF_TEST_SCALE_SUMMARY_V;'),
        ('VIEW', 'PERF_TEST_SNOWFLAKE_QUERY_REPORT_V', 'approved legacy', 'Perf-test view is approved legacy validation evidence. Drop only if local perf reports are formally retired.', 'DROP VIEW IF EXISTS PERF_TEST_SNOWFLAKE_QUERY_REPORT_V;'),
        ('PROCEDURE', 'SP_OVERWATCH_REFRESH_COST_GOVERNANCE', 'cleanup candidate', 'Old cost governance refresh is outside current admin monitoring scope. Drop after dependency check.', 'DROP PROCEDURE IF EXISTS SP_OVERWATCH_REFRESH_COST_GOVERNANCE();'),
        ('PROCEDURE', 'SP_OVERWATCH_VERIFY_COST_SAVINGS', 'migration candidate', 'Old savings verification procedure should be replaced by closed-loop verification workflow.', 'DROP PROCEDURE IF EXISTS SP_OVERWATCH_VERIFY_COST_SAVINGS();'),
        ('PROCEDURE', 'SP_PERF_TEST_GUARDRAIL_CHECK', 'approved legacy', 'Perf-test procedure is approved legacy validation evidence. Drop only if local perf testing is formally retired.', 'DROP PROCEDURE IF EXISTS SP_PERF_TEST_GUARDRAIL_CHECK();')
    AS t(OBJECT_TYPE, OBJECT_NAME, CLASSIFICATION, RECOMMENDATION, REVIEWABLE_SQL)
),
actual_objects AS (
    SELECT IFF(TABLE_TYPE = 'VIEW', 'VIEW', 'TABLE') AS OBJECT_TYPE, TABLE_NAME AS OBJECT_NAME
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = CURRENT_SCHEMA()
    UNION ALL
    SELECT 'PROCEDURE', PROCEDURE_NAME
    FROM INFORMATION_SCHEMA.PROCEDURES
    WHERE PROCEDURE_SCHEMA = CURRENT_SCHEMA()
)
SELECT
    k.OBJECT_TYPE,
    k.OBJECT_NAME,
    k.CLASSIFICATION,
    k.RECOMMENDATION,
    k.REVIEWABLE_SQL,
    IFF(a.OBJECT_NAME IS NULL, 'NOT PRESENT', 'PRESENT') AS LIVE_STATUS
FROM known_drift k
LEFT JOIN actual_objects a
  ON a.OBJECT_TYPE = k.OBJECT_TYPE
 AND UPPER(a.OBJECT_NAME) = k.OBJECT_NAME
ORDER BY k.OBJECT_TYPE, k.OBJECT_NAME;

-- 3) Task graph deployment proof.
SHOW TASKS IN SCHEMA;

WITH expected_tasks AS (
    SELECT * FROM VALUES
        ('OVERWATCH_ANOMALY_CHECK'),
        ('OVERWATCH_LOAD_HOURLY'),
        ('OVERWATCH_LOAD_CORTEX'),
        ('OVERWATCH_REFRESH_CONTROL_ROOM'),
        ('OVERWATCH_COST_MONITORING_REFRESH'),
        ('OVERWATCH_EXECUTIVE_OBSERVABILITY_REFRESH'),
        ('OVERWATCH_DECISION_BRIEF_FULL_REFRESH'),
        ('OVERWATCH_SECTION_COMMAND_BRIEF_REFRESH'),
        ('OVERWATCH_LOAD_DAILY')
    AS t(TASK_NAME)
),
actual_tasks AS (
    SELECT
        UPPER("name") AS TASK_NAME,
        UPPER(COALESCE("state", 'UNKNOWN')) AS TASK_STATE
    FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
)
SELECT
    e.TASK_NAME,
    COALESCE(a.TASK_STATE, 'MISSING') AS TASK_STATE,
    CASE
        WHEN a.TASK_NAME IS NULL THEN 'MISSING'
        WHEN a.TASK_STATE = 'SUSPENDED' THEN 'SUSPENDED'
        ELSE 'PRESENT'
    END AS VALIDATION_STATUS
FROM expected_tasks e
LEFT JOIN actual_tasks a
  ON a.TASK_NAME = e.TASK_NAME
ORDER BY VALIDATION_STATUS DESC, e.TASK_NAME;

-- 4) Executive board panel coverage.
WITH required_panels AS (
    SELECT * FROM VALUES
        ('KPI'),
        ('DAILY_COST'),
        ('MONTHLY_COST'),
        ('DAILY_WORKLOAD'),
        ('COST_DRIVER'),
        ('QUERY_TYPE'),
        ('QUERY_DATABASE'),
        ('EXEC_STATUS'),
        ('WAREHOUSE_PRESSURE'),
        ('FRESHNESS'),
        ('SOURCE_STATUS')
    AS t(PANEL)
),
actual_panels AS (
    SELECT PANEL, COUNT(*) AS ROW_COUNT, MAX(SNAPSHOT_TS) AS LATEST_SNAPSHOT
    FROM MART_EXECUTIVE_OBSERVABILITY
    GROUP BY PANEL
)
SELECT
    r.PANEL,
    COALESCE(a.ROW_COUNT, 0) AS ROW_COUNT,
    a.LATEST_SNAPSHOT,
    IFF(a.PANEL IS NULL, 'MISSING', 'PRESENT') AS VALIDATION_STATUS
FROM required_panels r
LEFT JOIN actual_panels a
  ON a.PANEL = r.PANEL
ORDER BY VALIDATION_STATUS DESC, r.PANEL;

-- 5) Executive board freshness by source.
SELECT
    COMPANY,
    ENVIRONMENT,
    WINDOW_DAYS,
    DIMENSION AS SOURCE_NAME,
    MAX(PERIOD_START) AS LATEST_SOURCE_TS,
    DATEDIFF('minute', MAX(PERIOD_START), CURRENT_TIMESTAMP()) AS AGE_MINUTES,
    MAX(SOURCE) AS SOURCE_TABLE
FROM MART_EXECUTIVE_OBSERVABILITY
WHERE PANEL = 'FRESHNESS'
GROUP BY COMPANY, ENVIRONMENT, WINDOW_DAYS, DIMENSION
ORDER BY AGE_MINUTES DESC NULLS FIRST, SOURCE_NAME;

-- 6) Refresh contract for first paint and live fallback.
WITH refresh_contract AS (
    SELECT * FROM VALUES
        ('EXECUTIVE_OBSERVABILITY', 'Executive Landing', 'MART', 60, 'TASK_AFTER_FACT_LOADS', 'MART_EXECUTIVE_OBSERVABILITY', 35, TRUE, FALSE, 'Executive Landing reads one compact mart query on first paint.', 'DBA / Platform'),
        ('DBA_CONTROL_ROOM_FAST', 'DBA Control Room', 'MART', 60, 'TASK_AFTER_HOURLY_FACTS', 'MART_DBA_CONTROL_ROOM', 35, TRUE, FALSE, 'Morning triage renders from a small control-room mart before live ACCOUNT_USAGE detail.', 'DBA On-Call'),
        ('COST_WATCH_FLOOR', 'Cost & Contract', 'MART_AND_BOUNDED_OFFICIAL_COST', 60, 'TASK_PLUS_EXPLICIT_REFRESH', 'FACT_COST_DAILY; FACT_CORTEX_DAILY; WAREHOUSE_METERING_HISTORY', 730, TRUE, FALSE, 'Cost first paint shows lightweight spend, Cortex, and warehouse movement; full attribution proof is explicit.', 'DBA / Cost owner'),
        ('ALERT_COMMAND_VIEW', 'Alert Center', 'APP_TABLES', 15, 'TASK_OR_APP_WRITE', 'ALERT_EVENTS; ALERT_NOTIFICATION_LOG; OVERWATCH_ACTION_QUEUE', 180, TRUE, FALSE, 'Alert Center may auto-load bounded app tables because they are small, routed, and deduplicated.', 'DBA / Alert Owner'),
        ('WORKLOAD_SNAPSHOT', 'Workload Operations', 'MART_AND_TASK_HISTORY', 30, 'TASK_PLUS_EXPLICIT_REFRESH', 'FACT_QUERY_HOURLY; FACT_TASK_RUN', 35, TRUE, FALSE, 'Workload first paint shows task/query pressure from compact facts; live triage is explicit.', 'DBA / Workload Owner'),
        ('LIVE_TRIAGE', 'DBA Control Room / Workload Operations', 'NEAR_REAL_TIME', 5, 'ON_DEMAND_ONLY', 'INFORMATION_SCHEMA table functions; SHOW commands', 1, FALSE, TRUE, 'Near-real-time checks stay explicit to avoid runaway monitoring cost.', 'DBA On-Call'),
        ('DATA_RECONCILIATION', 'Workload Operations', 'ON_DEMAND_PROOF', NULL, 'OPERATOR_RUN', 'OVERWATCH_RECON_CONFIG; OVERWATCH_RECON_RUN', 365, FALSE, TRUE, 'Schema and data comparison proof can be expensive and runs only on operator request.', 'DBA / Data Owner'),
        ('DATA_TRUST_LAYER', 'Executive Landing / DBA Control Room', 'MART', 120, 'TASK_AFTER_EXECUTIVE_REFRESH', 'MART_DATA_TRUST_SUMMARY; OVERWATCH_DATA_TRUST_STATUS', 35, TRUE, FALSE, 'Executive Landing reads compact source trust; DBA detail diagnostics require explicit Load.', 'DBA / Platform'),
        ('OWNERSHIP_MAP', 'Alert Center / Security Monitoring', 'MART', 120, 'TASK_AFTER_EXECUTIVE_REFRESH', 'MART_OPERATIONAL_OWNER_COVERAGE; OVERWATCH_OPERATIONAL_OWNER_MAP', 35, TRUE, FALSE, 'Ownership coverage shows who owns the next action without creating a generic directory.', 'DBA / Alert Owner'),
        ('EXECUTIVE_VALUE_LEDGER', 'Executive Landing / Cost & Contract', 'MART', 120, 'TASK_AFTER_EXECUTIVE_REFRESH', 'MART_EXECUTIVE_VALUE_LEDGER; OVERWATCH_VALUE_LEDGER', 180, TRUE, FALSE, 'Verified savings are separated from unverified estimates.', 'DBA / Cost owner'),
        ('APP_SELF_OBSERVABILITY', 'Executive Landing / DBA Control Room', 'MART', 120, 'TASK_AFTER_EXECUTIVE_REFRESH', 'MART_APP_OBSERVABILITY_SUMMARY; OVERWATCH_APP_OBSERVABILITY', 35, TRUE, FALSE, 'App health reads compact query-tag/runtime summaries; detail is explicit Load.', 'DBA / Platform'),
        ('PRODUCTION_READINESS', 'Executive Landing / DBA Control Room', 'MART', 120, 'TASK_AFTER_EXECUTIVE_REFRESH', 'MART_PRODUCTION_READINESS_SUMMARY; OVERWATCH_PRODUCTION_VALIDATION_STATUS', 35, TRUE, FALSE, 'Production readiness shows deployment, validation, role, privilege, refresh, config, freshness, and environment status from compact readiness marts.', 'DBA / Platform'),
        ('EXECUTIVE_SCORECARD', 'Executive Landing / DBA Control Room / Cost & Contract / Security Monitoring / Alert Center', 'MART', 120, 'TASK_AFTER_EXECUTIVE_REFRESH', 'MART_EXECUTIVE_SCORECARD_SUMMARY; OVERWATCH_EXECUTIVE_SCORECARD_HISTORY', 180, TRUE, FALSE, 'Leadership scorecard reads compact score summaries first; driver history is explicit Load by section.', 'DBA / Platform'),
        ('EXECUTIVE_FORECASTING', 'Executive Landing / DBA Control Room / Cost & Contract / Workload Operations', 'MART', 120, 'TASK_AFTER_EXECUTIVE_REFRESH', 'MART_EXECUTIVE_FORECAST_SUMMARY; OVERWATCH_FORECAST_HISTORY', 180, TRUE, FALSE, 'Leadership forecasts read compact summary rows first; historical drivers and evidence are explicit Load by section.', 'DBA / Cost owner'),
        ('CHANGE_INTELLIGENCE', 'Executive Landing / DBA Control Room / Cost & Contract / Workload Operations / Security Monitoring / Alert Center', 'MART', 120, 'TASK_AFTER_EXECUTIVE_REFRESH', 'MART_CHANGE_INTELLIGENCE_SUMMARY; OVERWATCH_CHANGE_EVENT; OVERWATCH_CHANGE_CORRELATION', 180, TRUE, FALSE, 'Executive Landing reads compact change-risk summaries first; event evidence and possible correlations are explicit Load by section.', 'DBA / Platform'),
        ('CLOSED_LOOP_OPERATIONS', 'Executive Landing / DBA Control Room / Alert Center / Cost & Contract / Workload Operations / Security Monitoring', 'MART', 120, 'TASK_AFTER_EXECUTIVE_REFRESH', 'MART_CLOSED_LOOP_OPERATIONS_SUMMARY; OVERWATCH_ACTION_WORKFLOW; OVERWATCH_ACTION_APPROVAL; OVERWATCH_ACTION_EXECUTION_PLAN; OVERWATCH_ACTION_VERIFICATION; OVERWATCH_ACTION_EVIDENCE', 180, TRUE, FALSE, 'Executive Landing reads compact action lifecycle summaries first; approval, review SQL, evidence, and verification detail are explicit Load by section. No remediation SQL is executed.', 'DBA / Platform'),
        ('COMMAND_CENTER', 'Executive Landing / DBA Control Room / Alert Center / Cost & Contract / Workload Operations / Security Monitoring', 'MART', 120, 'TASK_AFTER_EXECUTIVE_REFRESH', 'MART_COMMAND_CENTER_SUMMARY; OVERWATCH_COMMAND_CENTER_FINDING; OVERWATCH_COMMAND_CENTER_EVIDENCE; OVERWATCH_COMMAND_CENTER_RECOMMENDATION', 180, TRUE, FALSE, 'Executive Landing reads compact command findings first; investigation evidence and recommendations are explicit Load by section. No remediation SQL is executed.', 'DBA / Platform')
    AS t(
        POLICY_NAME, SURFACE, SOURCE_CLASS, TARGET_FRESHNESS_MIN, REFRESH_METHOD,
        BASE_OBJECT, RETENTION_DAYS, RUN_IN_FIRST_PAINT, APPROVED_LIVE_FALLBACK,
        WHY_THIS_POLICY, OWNER
    )
)
SELECT
    POLICY_NAME,
    SURFACE,
    SOURCE_CLASS AS FIRST_PAINT_SOURCE,
    TARGET_FRESHNESS_MIN AS TARGET_FRESHNESS_MINUTES,
    APPROVED_LIVE_FALLBACK AS LIVE_FALLBACK_ALLOWED,
    RUN_IN_FIRST_PAINT,
    REFRESH_METHOD,
    BASE_OBJECT,
    OWNER,
    WHY_THIS_POLICY AS WHY_THIS_DECISION
FROM refresh_contract
ORDER BY RUN_IN_FIRST_PAINT DESC, SURFACE;

-- 7) Refresh freshness enforcement proof.
WITH refresh_contract AS (
    SELECT * FROM VALUES
        ('EXECUTIVE_OBSERVABILITY', 'Executive Landing', 'MART', 60, 'TASK_AFTER_FACT_LOADS', 'MART_EXECUTIVE_OBSERVABILITY', 35, TRUE, FALSE),
        ('DBA_CONTROL_ROOM_FAST', 'DBA Control Room', 'MART', 60, 'TASK_AFTER_HOURLY_FACTS', 'MART_DBA_CONTROL_ROOM', 35, TRUE, FALSE),
        ('COST_WATCH_FLOOR', 'Cost & Contract', 'MART_AND_BOUNDED_OFFICIAL_COST', 60, 'TASK_PLUS_EXPLICIT_REFRESH', 'FACT_COST_DAILY; FACT_CORTEX_DAILY; WAREHOUSE_METERING_HISTORY', 730, TRUE, FALSE),
        ('ALERT_COMMAND_VIEW', 'Alert Center', 'APP_TABLES', 15, 'TASK_OR_APP_WRITE', 'ALERT_EVENTS; ALERT_NOTIFICATION_LOG; OVERWATCH_ACTION_QUEUE', 180, TRUE, FALSE),
        ('WORKLOAD_SNAPSHOT', 'Workload Operations', 'MART_AND_TASK_HISTORY', 30, 'TASK_PLUS_EXPLICIT_REFRESH', 'FACT_QUERY_HOURLY; FACT_TASK_RUN', 35, TRUE, FALSE),
        ('LIVE_TRIAGE', 'DBA Control Room / Workload Operations', 'NEAR_REAL_TIME', 5, 'ON_DEMAND_ONLY', 'INFORMATION_SCHEMA table functions; SHOW commands', 1, FALSE, TRUE),
        ('DATA_RECONCILIATION', 'Workload Operations', 'ON_DEMAND_PROOF', NULL, 'OPERATOR_RUN', 'OVERWATCH_RECON_CONFIG; OVERWATCH_RECON_RUN', 365, FALSE, TRUE),
        ('DATA_TRUST_LAYER', 'Executive Landing / DBA Control Room', 'MART', 120, 'TASK_AFTER_EXECUTIVE_REFRESH', 'MART_DATA_TRUST_SUMMARY; OVERWATCH_DATA_TRUST_STATUS', 35, TRUE, FALSE),
        ('OWNERSHIP_MAP', 'Alert Center / Security Monitoring', 'MART', 120, 'TASK_AFTER_EXECUTIVE_REFRESH', 'MART_OPERATIONAL_OWNER_COVERAGE; OVERWATCH_OPERATIONAL_OWNER_MAP', 35, TRUE, FALSE),
        ('EXECUTIVE_VALUE_LEDGER', 'Executive Landing / Cost & Contract', 'MART', 120, 'TASK_AFTER_EXECUTIVE_REFRESH', 'MART_EXECUTIVE_VALUE_LEDGER; OVERWATCH_VALUE_LEDGER', 180, TRUE, FALSE),
        ('APP_SELF_OBSERVABILITY', 'Executive Landing / DBA Control Room', 'MART', 120, 'TASK_AFTER_EXECUTIVE_REFRESH', 'MART_APP_OBSERVABILITY_SUMMARY; OVERWATCH_APP_OBSERVABILITY', 35, TRUE, FALSE),
        ('PRODUCTION_READINESS', 'Executive Landing / DBA Control Room', 'MART', 120, 'TASK_AFTER_EXECUTIVE_REFRESH', 'MART_PRODUCTION_READINESS_SUMMARY; OVERWATCH_PRODUCTION_VALIDATION_STATUS', 35, TRUE, FALSE),
        ('EXECUTIVE_SCORECARD', 'Executive Landing / DBA Control Room / Cost & Contract / Security Monitoring / Alert Center', 'MART', 120, 'TASK_AFTER_EXECUTIVE_REFRESH', 'MART_EXECUTIVE_SCORECARD_SUMMARY; OVERWATCH_EXECUTIVE_SCORECARD_HISTORY', 180, TRUE, FALSE),
        ('EXECUTIVE_FORECASTING', 'Executive Landing / DBA Control Room / Cost & Contract / Workload Operations', 'MART', 120, 'TASK_AFTER_EXECUTIVE_REFRESH', 'MART_EXECUTIVE_FORECAST_SUMMARY; OVERWATCH_FORECAST_HISTORY', 180, TRUE, FALSE),
        ('CHANGE_INTELLIGENCE', 'Executive Landing / DBA Control Room / Cost & Contract / Workload Operations / Security Monitoring / Alert Center', 'MART', 120, 'TASK_AFTER_EXECUTIVE_REFRESH', 'MART_CHANGE_INTELLIGENCE_SUMMARY; OVERWATCH_CHANGE_EVENT; OVERWATCH_CHANGE_CORRELATION', 180, TRUE, FALSE),
        ('CLOSED_LOOP_OPERATIONS', 'Executive Landing / DBA Control Room / Alert Center / Cost & Contract / Workload Operations / Security Monitoring', 'MART', 120, 'TASK_AFTER_EXECUTIVE_REFRESH', 'MART_CLOSED_LOOP_OPERATIONS_SUMMARY; OVERWATCH_ACTION_WORKFLOW; OVERWATCH_ACTION_APPROVAL; OVERWATCH_ACTION_EXECUTION_PLAN; OVERWATCH_ACTION_VERIFICATION; OVERWATCH_ACTION_EVIDENCE', 180, TRUE, FALSE),
        ('COMMAND_CENTER', 'Executive Landing / DBA Control Room / Alert Center / Cost & Contract / Workload Operations / Security Monitoring', 'MART', 120, 'TASK_AFTER_EXECUTIVE_REFRESH', 'MART_COMMAND_CENTER_SUMMARY; OVERWATCH_COMMAND_CENTER_FINDING; OVERWATCH_COMMAND_CENTER_EVIDENCE; OVERWATCH_COMMAND_CENTER_RECOMMENDATION', 180, TRUE, FALSE)
    AS t(
        POLICY_NAME, SURFACE, SOURCE_CLASS, TARGET_FRESHNESS_MIN, REFRESH_METHOD,
        BASE_OBJECT, RETENTION_DAYS, RUN_IN_FIRST_PAINT, APPROVED_LIVE_FALLBACK
    )
),
freshness AS (
    SELECT
        'Executive Landing' AS SURFACE,
        MAX(SNAPSHOT_TS) AS LATEST_REFRESH_TS
    FROM MART_EXECUTIVE_OBSERVABILITY
    UNION ALL
    SELECT
        'Alert Center' AS SURFACE,
        MAX(COALESCE(LAST_SEEN_AT, EVENT_TS, DETECTED_AT)) AS LATEST_REFRESH_TS
    FROM ALERT_EVENTS
    UNION ALL
    SELECT
        'Executive Landing / DBA Control Room' AS SURFACE,
        MAX(SNAPSHOT_TS) AS LATEST_REFRESH_TS
    FROM MART_DATA_TRUST_SUMMARY
    UNION ALL
    SELECT
        'Alert Center / Security Monitoring' AS SURFACE,
        MAX(SNAPSHOT_TS) AS LATEST_REFRESH_TS
    FROM MART_OPERATIONAL_OWNER_COVERAGE
    UNION ALL
    SELECT
        'Executive Landing / Cost & Contract' AS SURFACE,
        MAX(SNAPSHOT_TS) AS LATEST_REFRESH_TS
    FROM MART_EXECUTIVE_VALUE_LEDGER
    UNION ALL
    SELECT
        'Executive Landing / DBA Control Room' AS SURFACE,
        MAX(SNAPSHOT_TS) AS LATEST_REFRESH_TS
    FROM MART_APP_OBSERVABILITY_SUMMARY
    UNION ALL
    SELECT
        'Executive Landing / DBA Control Room' AS SURFACE,
        MAX(SNAPSHOT_TS) AS LATEST_REFRESH_TS
    FROM MART_PRODUCTION_READINESS_SUMMARY
    UNION ALL
    SELECT
        'Executive Landing / DBA Control Room / Cost & Contract / Security Monitoring / Alert Center' AS SURFACE,
        MAX(SNAPSHOT_TS) AS LATEST_REFRESH_TS
    FROM MART_EXECUTIVE_SCORECARD_SUMMARY
    UNION ALL
    SELECT
        'Executive Landing / DBA Control Room / Cost & Contract / Workload Operations' AS SURFACE,
        MAX(SNAPSHOT_TS) AS LATEST_REFRESH_TS
    FROM MART_EXECUTIVE_FORECAST_SUMMARY
    UNION ALL
    SELECT
        'Executive Landing / DBA Control Room / Cost & Contract / Workload Operations / Security Monitoring / Alert Center' AS SURFACE,
        MAX(SNAPSHOT_TS) AS LATEST_REFRESH_TS
    FROM MART_CHANGE_INTELLIGENCE_SUMMARY
    UNION ALL
    SELECT
        'Executive Landing / DBA Control Room / Alert Center / Cost & Contract / Workload Operations / Security Monitoring' AS SURFACE,
        MAX(SNAPSHOT_TS) AS LATEST_REFRESH_TS
    FROM MART_CLOSED_LOOP_OPERATIONS_SUMMARY
    UNION ALL
    SELECT
        'Executive Landing / DBA Control Room / Alert Center / Cost & Contract / Workload Operations / Security Monitoring' AS SURFACE,
        MAX(SNAPSHOT_TS) AS LATEST_REFRESH_TS
    FROM MART_COMMAND_CENTER_SUMMARY
),
freshness_agg AS (
    SELECT SURFACE, MAX(LATEST_REFRESH_TS) AS LATEST_REFRESH_TS
    FROM freshness
    GROUP BY SURFACE
),
policy AS (
    SELECT
        SURFACE,
        MIN(TARGET_FRESHNESS_MIN) AS TARGET_FRESHNESS_MINUTES,
        MAX(IFF(RUN_IN_FIRST_PAINT, 1, 0)) AS FIRST_PAINT_REQUIRED,
        MAX(IFF(APPROVED_LIVE_FALLBACK, 1, 0)) AS LIVE_FALLBACK_ALLOWED,
        LISTAGG(POLICY_NAME, ', ') WITHIN GROUP (ORDER BY POLICY_NAME) AS POLICY_NAMES
    FROM refresh_contract
    WHERE RUN_IN_FIRST_PAINT
    GROUP BY SURFACE
)
SELECT
    p.SURFACE,
    p.POLICY_NAMES,
    p.TARGET_FRESHNESS_MINUTES,
    f.LATEST_REFRESH_TS,
    DATEDIFF('minute', f.LATEST_REFRESH_TS, CURRENT_TIMESTAMP()) AS AGE_MINUTES,
    IFF(p.FIRST_PAINT_REQUIRED = 1, 'YES', 'NO') AS FIRST_PAINT_REQUIRED,
    IFF(p.LIVE_FALLBACK_ALLOWED = 1, 'YES', 'NO') AS LIVE_FALLBACK_ALLOWED,
    CASE
        WHEN f.LATEST_REFRESH_TS IS NULL THEN 'NO_ROWS'
        WHEN p.TARGET_FRESHNESS_MINUTES IS NULL THEN 'NO_TARGET'
        WHEN DATEDIFF('minute', f.LATEST_REFRESH_TS, CURRENT_TIMESTAMP()) <= p.TARGET_FRESHNESS_MINUTES THEN 'FRESH'
        ELSE 'STALE'
    END AS REFRESH_STATE
FROM policy p
LEFT JOIN freshness_agg f
  ON f.SURFACE = p.SURFACE
ORDER BY
    CASE REFRESH_STATE WHEN 'STALE' THEN 0 WHEN 'NO_ROWS' THEN 1 WHEN 'NO_TARGET' THEN 2 ELSE 3 END,
    p.SURFACE;

-- 8) Alert lifecycle and remediation audit coverage.
SELECT 'ALERT_EVENTS' AS OBJECT_NAME, COUNT(*) AS ROW_COUNT, MAX(COALESCE(LAST_SEEN_AT, EVENT_TS, DETECTED_AT)) AS LATEST_EVENT_TS FROM ALERT_EVENTS
UNION ALL
SELECT 'ALERT_ACKNOWLEDGEMENTS', COUNT(*), MAX(ACKNOWLEDGED_AT) FROM ALERT_ACKNOWLEDGEMENTS
UNION ALL
SELECT 'ALERT_REMEDIATION_LOG', COUNT(*), MAX(REQUESTED_AT) FROM ALERT_REMEDIATION_LOG
UNION ALL
SELECT 'ALERT_NOTIFICATION_LOG', COUNT(*), MAX(NOTIFICATION_TS) FROM ALERT_NOTIFICATION_LOG;

-- 9) Reconciliation configuration and last run proof.
WITH latest_runs AS (
    SELECT
        r.*,
        ROW_NUMBER() OVER (
            PARTITION BY r.CHECK_ID
            ORDER BY r.RUN_TS DESC, r.RUN_ID DESC
        ) AS rn
    FROM OVERWATCH_RECON_RUN r
)
SELECT
    c.CHECK_ID,
    c.CHECK_NAME,
    c.SOURCE_DATABASE,
    c.SOURCE_SCHEMA,
    c.TARGET_DATABASE,
    c.TARGET_SCHEMA,
    c.TABLE_PATTERN,
    c.CHECK_MODE,
    c.SEVERITY,
    c.OWNER,
    c.ENABLED,
    lr.RUN_TS AS LAST_RUN_TS,
    lr.RUN_STATUS AS LAST_RUN_STATUS
FROM OVERWATCH_RECON_CONFIG c
LEFT JOIN latest_runs lr
  ON lr.CHECK_ID = c.CHECK_ID
 AND lr.rn = 1
ORDER BY c.ENABLED DESC, c.SEVERITY, c.CHECK_NAME;

-- 10) Secure-view and dynamic-table compatibility guard.
SHOW DYNAMIC TABLES IN SCHEMA;

WITH dynamic_objects AS (
    SELECT UPPER("name") AS OBJECT_NAME
    FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
),
overwatch_dynamic_collisions AS (
    SELECT OBJECT_NAME
    FROM dynamic_objects
    WHERE OBJECT_NAME ILIKE 'FACT^_%' ESCAPE '^'
       OR OBJECT_NAME ILIKE 'DIM^_%' ESCAPE '^'
       OR OBJECT_NAME ILIKE 'MART^_%' ESCAPE '^'
       OR OBJECT_NAME ILIKE 'OVERWATCH^_%' ESCAPE '^'
       OR OBJECT_NAME ILIKE 'ALERT^_%' ESCAPE '^'
)
SELECT
    'DYNAMIC_TABLE_COLLISIONS' AS CHECK_NAME,
    COUNT(*) AS ISSUE_COUNT,
    IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS VALIDATION_STATUS,
    LISTAGG(OBJECT_NAME, ', ') WITHIN GROUP (ORDER BY OBJECT_NAME) AS DETAILS
FROM overwatch_dynamic_collisions;

SELECT
    'SECURE_VIEW_COLLISIONS' AS CHECK_NAME,
    COUNT(*) AS ISSUE_COUNT,
    IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS VALIDATION_STATUS,
    LISTAGG(TABLE_NAME, ', ') WITHIN GROUP (ORDER BY TABLE_NAME) AS DETAILS
FROM INFORMATION_SCHEMA.VIEWS
WHERE TABLE_SCHEMA = CURRENT_SCHEMA()
  AND UPPER(COALESCE(IS_SECURE, 'NO')) = 'YES'
  AND (
      TABLE_NAME ILIKE 'FACT^_%' ESCAPE '^'
      OR TABLE_NAME ILIKE 'DIM^_%' ESCAPE '^'
      OR TABLE_NAME ILIKE 'MART^_%' ESCAPE '^'
      OR TABLE_NAME ILIKE 'OVERWATCH^_%' ESCAPE '^'
      OR TABLE_NAME ILIKE 'ALERT^_%' ESCAPE '^'
  );

-- 11) Enterprise operating model confidence-label contract.
WITH confidence_values AS (
    SELECT 'OVERWATCH_DATA_TRUST_SOURCE' AS SOURCE_TABLE, DEFAULT_CONFIDENCE AS CONFIDENCE
    FROM OVERWATCH_DATA_TRUST_SOURCE
    UNION ALL
    SELECT 'OVERWATCH_DATA_TRUST_STATUS', CONFIDENCE
    FROM OVERWATCH_DATA_TRUST_STATUS
    UNION ALL
    SELECT 'MART_DATA_TRUST_SUMMARY', CONFIDENCE
    FROM MART_DATA_TRUST_SUMMARY
    UNION ALL
    SELECT 'MART_OPERATIONAL_OWNER_COVERAGE', CONFIDENCE
    FROM MART_OPERATIONAL_OWNER_COVERAGE
    UNION ALL
    SELECT 'OVERWATCH_VALUE_LEDGER', CONFIDENCE
    FROM OVERWATCH_VALUE_LEDGER
    UNION ALL
    SELECT 'MART_EXECUTIVE_VALUE_LEDGER', CONFIDENCE
    FROM MART_EXECUTIVE_VALUE_LEDGER
    UNION ALL
    SELECT 'MART_APP_OBSERVABILITY_SUMMARY', CONFIDENCE
    FROM MART_APP_OBSERVABILITY_SUMMARY
    UNION ALL
    SELECT 'MART_EXECUTIVE_SCORECARD_SUMMARY', CONFIDENCE
    FROM MART_EXECUTIVE_SCORECARD_SUMMARY
)
SELECT
    'CONFIDENCE_LABELS' AS CHECK_NAME,
    COUNT_IF(LOWER(COALESCE(CONFIDENCE, '')) NOT IN ('exact', 'allocated', 'estimated', 'fallback')) AS ISSUE_COUNT,
    IFF(COUNT_IF(LOWER(COALESCE(CONFIDENCE, '')) NOT IN ('exact', 'allocated', 'estimated', 'fallback')) = 0, 'PASS', 'FAIL') AS VALIDATION_STATUS,
    LISTAGG(DISTINCT SOURCE_TABLE || ':' || COALESCE(CONFIDENCE, '<null>'), ', ')
        WITHIN GROUP (ORDER BY SOURCE_TABLE || ':' || COALESCE(CONFIDENCE, '<null>')) AS DETAILS
FROM confidence_values;

-- 12) Enterprise value ledger: unverified estimates must not count as realized savings.
SELECT
    'UNVERIFIED_VALUE_NOT_REALIZED' AS CHECK_NAME,
    COUNT_IF(VALUE_STATE <> 'Value Verified' AND COALESCE(VERIFIED_SAVINGS_USD, 0) <> 0) AS ISSUE_COUNT,
    IFF(COUNT_IF(VALUE_STATE <> 'Value Verified' AND COALESCE(VERIFIED_SAVINGS_USD, 0) <> 0) = 0, 'PASS', 'FAIL') AS VALIDATION_STATUS,
    SUM(COALESCE(VERIFIED_SAVINGS_USD, 0)) AS VERIFIED_SAVINGS_USD,
    SUM(COALESCE(UNVERIFIED_ESTIMATE_USD, 0)) AS UNVERIFIED_ESTIMATE_USD
FROM MART_EXECUTIVE_VALUE_LEDGER;

CALL SP_OVERWATCH_REFRESH_SECTION_COMMAND_BRIEFS();
CALL SP_OVERWATCH_REFRESH_DECISION_BRIEFS_FAST();
CALL SP_OVERWATCH_REFRESH_DECISION_BRIEFS_FULL();
CALL SP_OVERWATCH_BOOTSTRAP_DECISION_BRIEFS();

SELECT
  'SECTION_COMMAND_BRIEF_SECTION_COVERAGE' AS CHECK_NAME,
  COUNT(DISTINCT SECTION_NAME) AS OBSERVED_VALUE,
  IFF(COUNT(DISTINCT SECTION_NAME) = 6, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM MART_SECTION_COMMAND_BRIEF
WHERE SNAPSHOT_TS = (SELECT MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_BRIEF);

SELECT
  'SECTION_COMMAND_BRIEF_PARENT_HAS_METRICS' AS CHECK_NAME,
  COUNT_IF(metric_count = 0) AS ISSUE_COUNT,
  IFF(COUNT_IF(metric_count = 0) = 0, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM (
  SELECT b.BRIEF_ID, COUNT(m.BRIEF_ID) AS metric_count
  FROM MART_SECTION_COMMAND_BRIEF b
  LEFT JOIN MART_SECTION_COMMAND_METRIC m ON m.BRIEF_ID = b.BRIEF_ID
  WHERE b.SNAPSHOT_TS = (SELECT MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_BRIEF)
  GROUP BY b.BRIEF_ID
);

SELECT
  'SECTION_COMMAND_BRIEF_ORPHAN_CHILD_ROWS' AS CHECK_NAME,
  SUM(ORPHANS) AS ISSUE_COUNT,
  IFF(SUM(ORPHANS) = 0, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM (
  SELECT COUNT(*) AS ORPHANS FROM MART_SECTION_COMMAND_METRIC c LEFT JOIN MART_SECTION_COMMAND_BRIEF b ON b.BRIEF_ID = c.BRIEF_ID WHERE b.BRIEF_ID IS NULL
  UNION ALL
  SELECT COUNT(*) FROM MART_SECTION_COMMAND_EXCEPTION c LEFT JOIN MART_SECTION_COMMAND_BRIEF b ON b.BRIEF_ID = c.BRIEF_ID WHERE b.BRIEF_ID IS NULL
  UNION ALL
  SELECT COUNT(*) FROM MART_SECTION_COMMAND_ACTION c LEFT JOIN MART_SECTION_COMMAND_BRIEF b ON b.BRIEF_ID = c.BRIEF_ID WHERE b.BRIEF_ID IS NULL
  UNION ALL
  SELECT COUNT(*) FROM MART_SECTION_COMMAND_SOURCE c LEFT JOIN MART_SECTION_COMMAND_BRIEF b ON b.BRIEF_ID = c.BRIEF_ID WHERE b.BRIEF_ID IS NULL
);

SELECT
  'SECTION_COMMAND_BRIEF_FRESHNESS_TARGETS' AS CHECK_NAME,
  COUNT_IF(COALESCE(IS_STALE, FALSE)) AS ISSUE_COUNT,
  IFF(COUNT_IF(COALESCE(IS_STALE, FALSE)) = 0, 'PASS', 'WARN') AS VALIDATION_STATUS
FROM MART_SECTION_COMMAND_BRIEF
WHERE SNAPSHOT_TS = (SELECT MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_BRIEF);

SELECT
  'SECTION_COMMAND_BRIEF_CANONICAL_WINDOWS' AS CHECK_NAME,
  COUNT(*) AS ISSUE_COUNT,
  IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM (
  SELECT s.SECTION_NAME, w.WINDOW_DAYS
  FROM (
    SELECT COLUMN1::VARCHAR AS SECTION_NAME
    FROM VALUES
      ('Executive Landing'), ('DBA Control Room'), ('Alert Center'),
      ('Cost & Contract'), ('Workload Operations'), ('Security Monitoring')
  ) s
  CROSS JOIN (
    SELECT COLUMN1::NUMBER AS WINDOW_DAYS FROM VALUES (1), (7), (14), (30), (60), (90)
  ) w
  LEFT JOIN MART_SECTION_COMMAND_BRIEF b
    ON b.SECTION_NAME = s.SECTION_NAME
   AND b.WINDOW_DAYS = w.WINDOW_DAYS
   AND b.SNAPSHOT_TS = (SELECT MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_BRIEF)
  WHERE b.BRIEF_ID IS NULL
);

SELECT
  'SECTION_COMMAND_BRIEF_SOURCE_COVERAGE_FIELDS' AS CHECK_NAME,
  COUNT_IF(
    REQUIRED_SOURCE_COUNT IS NULL
    OR AVAILABLE_REQUIRED_SOURCE_COUNT IS NULL
    OR REQUIRED_MISSING_SOURCE_COUNT IS NULL
    OR REQUIRED_STALE_SOURCE_COUNT IS NULL
    OR OPTIONAL_SOURCE_COUNT IS NULL
    OR AVAILABLE_OPTIONAL_SOURCE_COUNT IS NULL
    OR OPTIONAL_MISSING_SOURCE_COUNT IS NULL
    OR OPTIONAL_STALE_SOURCE_COUNT IS NULL
    OR SOURCE_COVERAGE_PCT IS NULL
    OR DATA_AVAILABILITY_STATE IS NULL
  ) AS ISSUE_COUNT,
  IFF(COUNT_IF(
    REQUIRED_SOURCE_COUNT IS NULL
    OR AVAILABLE_REQUIRED_SOURCE_COUNT IS NULL
    OR REQUIRED_MISSING_SOURCE_COUNT IS NULL
    OR REQUIRED_STALE_SOURCE_COUNT IS NULL
    OR OPTIONAL_SOURCE_COUNT IS NULL
    OR AVAILABLE_OPTIONAL_SOURCE_COUNT IS NULL
    OR OPTIONAL_MISSING_SOURCE_COUNT IS NULL
    OR OPTIONAL_STALE_SOURCE_COUNT IS NULL
    OR SOURCE_COVERAGE_PCT IS NULL
    OR DATA_AVAILABILITY_STATE IS NULL
  ) = 0, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM MART_SECTION_COMMAND_BRIEF
WHERE SNAPSHOT_TS = (SELECT MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_BRIEF);

SELECT
  'SECTION_COMMAND_BRIEF_TYPED_METRICS' AS CHECK_NAME,
  COUNT_IF(METRIC_NUMERIC_VALUE IS NOT NULL OR METRIC_TEXT_VALUE IS NOT NULL) AS OBSERVED_VALUE,
  IFF(COUNT_IF(METRIC_NUMERIC_VALUE IS NOT NULL OR METRIC_TEXT_VALUE IS NOT NULL) > 0, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM MART_SECTION_COMMAND_METRIC
WHERE SNAPSHOT_TS = (SELECT MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_METRIC);

SELECT
  'SECTION_COMMAND_BRIEF_METRIC_AVAILABILITY' AS CHECK_NAME,
  COUNT_IF(IS_AVAILABLE IS NULL OR AVAILABILITY_STATE IS NULL OR SOURCE_KEY IS NULL) AS ISSUE_COUNT,
  IFF(COUNT_IF(IS_AVAILABLE IS NULL OR AVAILABILITY_STATE IS NULL OR SOURCE_KEY IS NULL) = 0, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM MART_SECTION_COMMAND_METRIC
WHERE SNAPSHOT_TS = (SELECT MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_METRIC);

SELECT
  'SECTION_COMMAND_BRIEF_ROUTE_KEYS' AS CHECK_NAME,
  COUNT_IF(ROUTE_KEY IS NULL OR CTA_LABEL IS NULL) AS ISSUE_COUNT,
  IFF(COUNT_IF(ROUTE_KEY IS NULL OR CTA_LABEL IS NULL) = 0, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM MART_SECTION_COMMAND_ACTION
WHERE SNAPSHOT_TS = (SELECT MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_ACTION);

SELECT
  'SECTION_DECISION_CURRENT_ONE_ACTIVE_ROW_PER_KEY' AS CHECK_NAME,
  COUNT(*) AS ISSUE_COUNT,
  IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM (
  SELECT SECTION_NAME, COMPANY, ENVIRONMENT, WINDOW_DAYS
  FROM MART_SECTION_DECISION_CURRENT
  WHERE COALESCE(IS_ACTIVE, TRUE)
  GROUP BY SECTION_NAME, COMPANY, ENVIRONMENT, WINDOW_DAYS
  HAVING COUNT(*) > 1
);

SELECT
  'SECTION_DECISION_CURRENT_PACKET_COVERAGE' AS CHECK_NAME,
  COUNT(DISTINCT SECTION_NAME) AS OBSERVED_VALUE,
  IFF(COUNT(DISTINCT SECTION_NAME) = 6 AND COUNT_IF(DECISION_PACKET IS NULL) = 0, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM MART_SECTION_DECISION_CURRENT
WHERE COALESCE(IS_ACTIVE, TRUE);

SELECT
  'SECTION_DECISION_CURRENT_PACKET_SOURCES' AS CHECK_NAME,
  COUNT_IF(DECISION_PACKET:"SOURCES" IS NULL OR ARRAY_SIZE(DECISION_PACKET:"SOURCES") = 0) AS ISSUE_COUNT,
  IFF(COUNT_IF(DECISION_PACKET:"SOURCES" IS NULL OR ARRAY_SIZE(DECISION_PACKET:"SOURCES") = 0) = 0, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM MART_SECTION_DECISION_CURRENT
WHERE COALESCE(IS_ACTIVE, TRUE);

WITH current_packets AS (
  SELECT SECTION_NAME, COMPANY, ENVIRONMENT, WINDOW_DAYS, BRIEF_ID, DECISION_PACKET
  FROM MART_SECTION_DECISION_CURRENT
  WHERE COALESCE(IS_ACTIVE, TRUE)
),
source_rows AS (
  SELECT
    SECTION_NAME,
    COMPANY,
    ENVIRONMENT,
    WINDOW_DAYS,
    BRIEF_ID,
    src.value:"SOURCE_KEY"::VARCHAR AS SOURCE_KEY,
    src.value:"SOURCE_OBJECT"::VARCHAR AS SOURCE_OBJECT,
    COALESCE(src.value:"REQUIRED"::BOOLEAN, FALSE) AS REQUIRED,
    COALESCE(src.value:"AVAILABLE"::BOOLEAN, FALSE) AS AVAILABLE,
    COALESCE(src.value:"IS_STALE"::BOOLEAN, FALSE) AS IS_STALE
  FROM current_packets,
  LATERAL FLATTEN(INPUT => DECISION_PACKET:"SOURCES") src
),
flattened AS (
  SELECT
    SECTION_NAME,
    COMPANY,
    ENVIRONMENT,
    WINDOW_DAYS,
    BRIEF_ID,
    COUNT(*) AS SOURCE_ROW_COUNT,
    COUNT_IF(REQUIRED) AS REQUIRED_SOURCE_COUNT,
    COUNT_IF(REQUIRED AND AVAILABLE) AS AVAILABLE_REQUIRED_SOURCE_COUNT,
    COUNT_IF(REQUIRED AND NOT AVAILABLE) AS REQUIRED_MISSING_SOURCE_COUNT,
    COUNT_IF(REQUIRED AND IS_STALE) AS REQUIRED_STALE_SOURCE_COUNT,
    COUNT_IF(NOT REQUIRED) AS OPTIONAL_SOURCE_COUNT,
    COUNT_IF(NOT REQUIRED AND NOT AVAILABLE) AS OPTIONAL_MISSING_SOURCE_COUNT,
    COUNT_IF(NOT REQUIRED AND IS_STALE) AS OPTIONAL_STALE_SOURCE_COUNT,
    COUNT(*) - COUNT(DISTINCT SOURCE_KEY) AS DUPLICATE_SOURCE_KEY_COUNT
  FROM source_rows
  GROUP BY SECTION_NAME, COMPANY, ENVIRONMENT, WINDOW_DAYS, BRIEF_ID
)
SELECT
  'SECTION_DECISION_CURRENT_SOURCE_COUNTER_CONSISTENCY' AS CHECK_NAME,
  COUNT_IF(
    COALESCE(f.SOURCE_ROW_COUNT, 0) = 0
    OR COALESCE(f.REQUIRED_SOURCE_COUNT, 0) <= 0
    OR COALESCE(TRY_TO_NUMBER(p.DECISION_PACKET:"REQUIRED_SOURCE_COUNT"), -1) <> COALESCE(f.REQUIRED_SOURCE_COUNT, -2)
    OR COALESCE(TRY_TO_NUMBER(p.DECISION_PACKET:"AVAILABLE_REQUIRED_SOURCE_COUNT"), -1) <> COALESCE(f.AVAILABLE_REQUIRED_SOURCE_COUNT, -2)
    OR COALESCE(TRY_TO_NUMBER(p.DECISION_PACKET:"REQUIRED_MISSING_SOURCE_COUNT"), -1) <> COALESCE(f.REQUIRED_MISSING_SOURCE_COUNT, -2)
    OR COALESCE(TRY_TO_NUMBER(p.DECISION_PACKET:"REQUIRED_STALE_SOURCE_COUNT"), -1) <> COALESCE(f.REQUIRED_STALE_SOURCE_COUNT, -2)
    OR COALESCE(TRY_TO_NUMBER(p.DECISION_PACKET:"OPTIONAL_SOURCE_COUNT"), -1) <> COALESCE(f.OPTIONAL_SOURCE_COUNT, -2)
    OR COALESCE(TRY_TO_NUMBER(p.DECISION_PACKET:"OPTIONAL_MISSING_SOURCE_COUNT"), -1) <> COALESCE(f.OPTIONAL_MISSING_SOURCE_COUNT, -2)
    OR COALESCE(TRY_TO_NUMBER(p.DECISION_PACKET:"OPTIONAL_STALE_SOURCE_COUNT"), -1) <> COALESCE(f.OPTIONAL_STALE_SOURCE_COUNT, -2)
    OR COALESCE(f.DUPLICATE_SOURCE_KEY_COUNT, 0) > 0
  ) AS ISSUE_COUNT,
  IFF(COUNT_IF(
    COALESCE(f.SOURCE_ROW_COUNT, 0) = 0
    OR COALESCE(f.REQUIRED_SOURCE_COUNT, 0) <= 0
    OR COALESCE(TRY_TO_NUMBER(p.DECISION_PACKET:"REQUIRED_SOURCE_COUNT"), -1) <> COALESCE(f.REQUIRED_SOURCE_COUNT, -2)
    OR COALESCE(TRY_TO_NUMBER(p.DECISION_PACKET:"AVAILABLE_REQUIRED_SOURCE_COUNT"), -1) <> COALESCE(f.AVAILABLE_REQUIRED_SOURCE_COUNT, -2)
    OR COALESCE(TRY_TO_NUMBER(p.DECISION_PACKET:"REQUIRED_MISSING_SOURCE_COUNT"), -1) <> COALESCE(f.REQUIRED_MISSING_SOURCE_COUNT, -2)
    OR COALESCE(TRY_TO_NUMBER(p.DECISION_PACKET:"REQUIRED_STALE_SOURCE_COUNT"), -1) <> COALESCE(f.REQUIRED_STALE_SOURCE_COUNT, -2)
    OR COALESCE(TRY_TO_NUMBER(p.DECISION_PACKET:"OPTIONAL_SOURCE_COUNT"), -1) <> COALESCE(f.OPTIONAL_SOURCE_COUNT, -2)
    OR COALESCE(TRY_TO_NUMBER(p.DECISION_PACKET:"OPTIONAL_MISSING_SOURCE_COUNT"), -1) <> COALESCE(f.OPTIONAL_MISSING_SOURCE_COUNT, -2)
    OR COALESCE(TRY_TO_NUMBER(p.DECISION_PACKET:"OPTIONAL_STALE_SOURCE_COUNT"), -1) <> COALESCE(f.OPTIONAL_STALE_SOURCE_COUNT, -2)
    OR COALESCE(f.DUPLICATE_SOURCE_KEY_COUNT, 0) > 0
  ) = 0, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM current_packets p
LEFT JOIN flattened f
  ON f.SECTION_NAME = p.SECTION_NAME
 AND f.COMPANY = p.COMPANY
 AND f.ENVIRONMENT = p.ENVIRONMENT
 AND f.WINDOW_DAYS = p.WINDOW_DAYS
 AND f.BRIEF_ID = p.BRIEF_ID;

WITH current_packets AS (
  SELECT SECTION_NAME, COMPANY, ENVIRONMENT, WINDOW_DAYS, BRIEF_ID, DECISION_PACKET
  FROM MART_SECTION_DECISION_CURRENT
  WHERE COALESCE(IS_ACTIVE, TRUE)
),
source_rollup AS (
  SELECT
    p.SECTION_NAME,
    p.COMPANY,
    p.ENVIRONMENT,
    p.WINDOW_DAYS,
    p.BRIEF_ID,
    LISTAGG(src.value:"SOURCE_OBJECT"::VARCHAR, '; ') WITHIN GROUP (ORDER BY src.value:"SOURCE_KEY"::VARCHAR) AS DERIVED_SOURCE_OBJECTS
  FROM current_packets p,
  LATERAL FLATTEN(INPUT => p.DECISION_PACKET:"SOURCES") src
  GROUP BY p.SECTION_NAME, p.COMPANY, p.ENVIRONMENT, p.WINDOW_DAYS, p.BRIEF_ID
)
SELECT
  'SECTION_DECISION_PARENT_SOURCE_OBJECTS_MATCH_SOURCES' AS CHECK_NAME,
  COUNT_IF(COALESCE(p.DECISION_PACKET:"SOURCE_OBJECTS"::VARCHAR, '') <> COALESCE(r.DERIVED_SOURCE_OBJECTS, '')) AS ISSUE_COUNT,
  IFF(COUNT_IF(COALESCE(p.DECISION_PACKET:"SOURCE_OBJECTS"::VARCHAR, '') <> COALESCE(r.DERIVED_SOURCE_OBJECTS, '')) = 0, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM current_packets p
LEFT JOIN source_rollup r
  ON r.SECTION_NAME = p.SECTION_NAME
 AND r.COMPANY = p.COMPANY
 AND r.ENVIRONMENT = p.ENVIRONMENT
 AND r.WINDOW_DAYS = p.WINDOW_DAYS
 AND r.BRIEF_ID = p.BRIEF_ID;

SELECT
  'SECTION_DECISION_LAST_GOOD_PACKET_COVERAGE' AS CHECK_NAME,
  COUNT(DISTINCT SECTION_NAME) AS OBSERVED_VALUE,
  IFF(COUNT(DISTINCT SECTION_NAME) = 6 AND COUNT_IF(DECISION_PACKET IS NULL) = 0, 'PASS', 'WARN') AS VALIDATION_STATUS
FROM MART_SECTION_DECISION_LAST_GOOD;

SELECT
  'SECTION_COMMAND_SOURCE_ROWS' AS CHECK_NAME,
  COUNT(*) AS OBSERVED_VALUE,
  IFF(COUNT(*) > 0 AND COUNT_IF(SOURCE_OBJECT IS NULL OR SOURCE_KEY IS NULL) = 0, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM MART_SECTION_COMMAND_SOURCE
WHERE SNAPSHOT_TS = (SELECT MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_SOURCE);

SELECT
  'SECTION_COMMAND_SOURCE_CONFIG_UNIQUE_SOURCE_KEYS' AS CHECK_NAME,
  COUNT(*) AS ISSUE_COUNT,
  IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM (
  SELECT SECTION_NAME, SOURCE_KEY
  FROM OVERWATCH_SECTION_COMMAND_SOURCE_CONFIG
  GROUP BY SECTION_NAME, SOURCE_KEY
  HAVING COUNT(*) > 1
);

SELECT
  'SECTION_COMMAND_METRIC_SOURCE_KEYS_CONFIGURED' AS CHECK_NAME,
  COUNT(*) AS ISSUE_COUNT,
  IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM MART_SECTION_COMMAND_METRIC m
LEFT JOIN OVERWATCH_SECTION_COMMAND_SOURCE_CONFIG cfg
  ON cfg.SECTION_NAME = m.SECTION_NAME
 AND cfg.SOURCE_KEY = m.SOURCE_KEY
WHERE m.SNAPSHOT_TS = (SELECT MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_METRIC)
  AND cfg.SOURCE_KEY IS NULL;

WITH current_packets AS (
  SELECT SECTION_NAME, COMPANY, ENVIRONMENT, WINDOW_DAYS, BRIEF_ID, DECISION_PACKET
  FROM MART_SECTION_DECISION_CURRENT
  WHERE COALESCE(IS_ACTIVE, TRUE)
),
source_rows AS (
  SELECT
    p.SECTION_NAME,
    p.COMPANY,
    p.ENVIRONMENT,
    p.WINDOW_DAYS,
    p.BRIEF_ID,
    src.value:"SOURCE_KEY"::VARCHAR AS SOURCE_KEY
  FROM current_packets p,
  LATERAL FLATTEN(INPUT => p.DECISION_PACKET:"SOURCES") src
)
SELECT
  'SECTION_DECISION_CURRENT_SOURCE_KEYS_CONFIGURED' AS CHECK_NAME,
  COUNT(*) AS ISSUE_COUNT,
  IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM source_rows s
LEFT JOIN OVERWATCH_SECTION_COMMAND_SOURCE_CONFIG cfg
  ON cfg.SECTION_NAME = s.SECTION_NAME
 AND cfg.SOURCE_KEY = s.SOURCE_KEY
WHERE cfg.SOURCE_KEY IS NULL;

SELECT
  'SECTION_COMMAND_SOURCE_ENVIRONMENT_METADATA' AS CHECK_NAME,
  COUNT_IF(
    (LOWER(COALESCE(ENVIRONMENT_MODE, 'not_applicable')) = 'exact' AND NOT COALESCE(SUPPORTS_ENVIRONMENT, FALSE))
    OR (LOWER(COALESCE(ENVIRONMENT_MODE, 'not_applicable')) <> 'exact' AND COALESCE(SUPPORTS_ENVIRONMENT, FALSE))
  ) AS ISSUE_COUNT,
  IFF(COUNT_IF(
    (LOWER(COALESCE(ENVIRONMENT_MODE, 'not_applicable')) = 'exact' AND NOT COALESCE(SUPPORTS_ENVIRONMENT, FALSE))
    OR (LOWER(COALESCE(ENVIRONMENT_MODE, 'not_applicable')) <> 'exact' AND COALESCE(SUPPORTS_ENVIRONMENT, FALSE))
  ) = 0, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM OVERWATCH_SECTION_COMMAND_SOURCE_CONFIG;

SELECT
  'SECTION_COMMAND_SOURCE_TRUST_GAPS' AS CHECK_NAME,
  COUNT_IF(REQUIRED AND NOT AVAILABLE) AS REQUIRED_SOURCE_GAPS,
  IFF(COUNT_IF(REQUIRED AND NOT AVAILABLE) = 0, 'PASS', 'WARN') AS VALIDATION_STATUS
FROM MART_SECTION_COMMAND_SOURCE
WHERE SNAPSHOT_TS = (SELECT MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_SOURCE);

WITH expected_keys AS (
  SELECT * FROM VALUES
    ('Executive Landing', 'platform_health'), ('Executive Landing', 'spend_movement_pct'), ('Executive Landing', 'critical_high_issues'), ('Executive Landing', 'open_actions'),
    ('Executive Landing', 'cortex_spend'), ('Executive Landing', 'cortex_risk'), ('Executive Landing', 'operational_risk'), ('Executive Landing', 'security_risk'),
    ('Executive Landing', 'production_readiness'), ('Executive Landing', 'data_trust'), ('Executive Landing', 'verified_value'), ('Executive Landing', 'monitoring_overhead'),
    ('DBA Control Room', 'failed_queries'), ('DBA Control Room', 'pipeline_failures'), ('DBA Control Room', 'queue_pressure'), ('DBA Control Room', 'cost_24h'),
    ('DBA Control Room', 'cortex_cost'), ('DBA Control Room', 'security_warnings'), ('DBA Control Room', 'recent_changes'), ('DBA Control Room', 'overdue_actions'),
    ('DBA Control Room', 'hottest_warehouse'), ('DBA Control Room', 'top_dba_risk'),
    ('Alert Center', 'active_alerts'), ('Alert Center', 'critical_high'), ('Alert Center', 'overdue_alerts'), ('Alert Center', 'cortex_predictive'),
    ('Alert Center', 'cost_alerts'), ('Alert Center', 'reliability_alerts'), ('Alert Center', 'security_alerts'), ('Alert Center', 'notification_failures'),
    ('Alert Center', 'unassigned_alerts'), ('Alert Center', 'open_action_queue'),
    ('Cost & Contract', 'total_spend'), ('Cost & Contract', 'spend_movement_pct'), ('Cost & Contract', 'forecast_run_rate'), ('Cost & Contract', 'cortex_spend_share'),
    ('Cost & Contract', 'cortex_spend'), ('Cost & Contract', 'cortex_predictive_alerts'), ('Cost & Contract', 'budget_contract_risk'), ('Cost & Contract', 'top_cost_driver'),
    ('Cost & Contract', 'verified_savings'), ('Cost & Contract', 'unverified_savings'), ('Cost & Contract', 'open_cost_actions'),
    ('Workload Operations', 'failed_queries'), ('Workload Operations', 'pipeline_failures'), ('Workload Operations', 'queue_blocked_pressure'), ('Workload Operations', 'sla_risk'),
    ('Workload Operations', 'spill_bytes'), ('Workload Operations', 'long_running_queries'), ('Workload Operations', 'hottest_warehouse'), ('Workload Operations', 'recent_workload_changes'),
    ('Workload Operations', 'suspended_tasks'), ('Workload Operations', 'copy_load_failures'),
    ('Security Monitoring', 'failed_logins'), ('Security Monitoring', 'mfa_gaps'), ('Security Monitoring', 'risky_grants'), ('Security Monitoring', 'sharing_exposure'),
    ('Security Monitoring', 'privilege_changes'), ('Security Monitoring', 'security_alerts'), ('Security Monitoring', 'access_changes'), ('Security Monitoring', 'unassigned_findings'),
    ('Security Monitoring', 'overdue_security_actions'), ('Security Monitoring', 'owner_coverage')
  AS t(SECTION_NAME, METRIC_KEY)
),
latest_metrics AS (
  SELECT SECTION_NAME, METRIC_KEY
  FROM MART_SECTION_COMMAND_METRIC
  WHERE SNAPSHOT_TS = (SELECT MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_METRIC)
)
SELECT
  'SECTION_COMMAND_REQUIRED_METRIC_KEYS' AS CHECK_NAME,
  COUNT_IF(m.METRIC_KEY IS NULL) AS ISSUE_COUNT,
  IFF(COUNT_IF(m.METRIC_KEY IS NULL) = 0, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM expected_keys e
LEFT JOIN latest_metrics m
  ON m.SECTION_NAME = e.SECTION_NAME
 AND m.METRIC_KEY = e.METRIC_KEY;

-- 13) Enterprise capability refresh summary.
SELECT 'MART_DATA_TRUST_SUMMARY' AS OBJECT_NAME, COUNT(*) AS ROW_COUNT, MAX(SNAPSHOT_TS) AS LATEST_REFRESH_TS FROM MART_DATA_TRUST_SUMMARY
UNION ALL
SELECT 'MART_SECTION_COMMAND_BRIEF', COUNT(*), MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_BRIEF
UNION ALL
SELECT 'MART_SECTION_COMMAND_METRIC', COUNT(*), MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_METRIC
UNION ALL
SELECT 'MART_SECTION_COMMAND_EXCEPTION', COUNT(*), MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_EXCEPTION
UNION ALL
SELECT 'MART_SECTION_COMMAND_ACTION', COUNT(*), MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_ACTION
UNION ALL
SELECT 'MART_SECTION_COMMAND_SOURCE', COUNT(*), MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_SOURCE
UNION ALL
SELECT 'MART_SECTION_DECISION_CURRENT', COUNT(*), MAX(SNAPSHOT_TS) FROM MART_SECTION_DECISION_CURRENT
UNION ALL
SELECT 'MART_SECTION_DECISION_LAST_GOOD', COUNT(*), MAX(SNAPSHOT_TS) FROM MART_SECTION_DECISION_LAST_GOOD
UNION ALL
SELECT 'OVERWATCH_DECISION_SETUP_HEALTH', COUNT(*), MAX(LOAD_TS) FROM OVERWATCH_DECISION_SETUP_HEALTH
UNION ALL
SELECT 'OVERWATCH_DECISION_REFRESH_AUDIT', COUNT(*), MAX(LOAD_TS) FROM OVERWATCH_DECISION_REFRESH_AUDIT
UNION ALL
SELECT 'MART_EXECUTIVE_DECISION_INBOX', COUNT(*), MAX(SNAPSHOT_TS) FROM MART_EXECUTIVE_DECISION_INBOX
UNION ALL
SELECT 'MART_OPERATIONAL_OWNER_COVERAGE', COUNT(*), MAX(SNAPSHOT_TS) FROM MART_OPERATIONAL_OWNER_COVERAGE
UNION ALL
SELECT 'MART_EXECUTIVE_VALUE_LEDGER', COUNT(*), MAX(SNAPSHOT_TS) FROM MART_EXECUTIVE_VALUE_LEDGER
    UNION ALL
    SELECT 'MART_APP_OBSERVABILITY_SUMMARY', COUNT(*), MAX(SNAPSHOT_TS) FROM MART_APP_OBSERVABILITY_SUMMARY
    UNION ALL
SELECT 'MART_PRODUCTION_READINESS_SUMMARY', COUNT(*), MAX(SNAPSHOT_TS) FROM MART_PRODUCTION_READINESS_SUMMARY
UNION ALL
SELECT 'MART_EXECUTIVE_SCORECARD_SUMMARY', COUNT(*), MAX(SNAPSHOT_TS) FROM MART_EXECUTIVE_SCORECARD_SUMMARY
UNION ALL
SELECT 'MART_EXECUTIVE_FORECAST_SUMMARY', COUNT(*), MAX(SNAPSHOT_TS) FROM MART_EXECUTIVE_FORECAST_SUMMARY
UNION ALL
SELECT 'MART_CHANGE_INTELLIGENCE_SUMMARY', COUNT(*), MAX(SNAPSHOT_TS) FROM MART_CHANGE_INTELLIGENCE_SUMMARY
UNION ALL
SELECT 'MART_CLOSED_LOOP_OPERATIONS_SUMMARY', COUNT(*), MAX(SNAPSHOT_TS) FROM MART_CLOSED_LOOP_OPERATIONS_SUMMARY
UNION ALL
SELECT 'MART_COMMAND_CENTER_SUMMARY', COUNT(*), MAX(SNAPSHOT_TS) FROM MART_COMMAND_CENTER_SUMMARY;

SELECT
  'DECISION_SETUP_HEALTH_SCHEMA' AS CHECK_NAME,
  COUNT(*) AS MISSING_COLUMNS,
  IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM (
  SELECT COLUMN1::VARCHAR AS COLUMN_NAME
  FROM VALUES
    ('EVENT_ID'), ('EVENT_TS'), ('STATUS'), ('USER_MESSAGE'),
    ('GLOBAL_STATUS'), ('SELECTED_SCOPE_STATUS'), ('CURRENT_SECTION_STATUS'),
    ('SELECTED_PROCEDURE'), ('FALLBACK_USED'), ('CURRENT_PACKET_COUNT'),
    ('SECTIONS_PRESENT'), ('MISSING_SECTIONS'), ('DUPLICATE_CURRENT_KEYS'),
    ('STALE_SECTIONS'), ('DATA_GAP_SECTIONS'), ('MISSING_METRIC_SECTIONS'),
    ('DEGRADED_SECTIONS'), ('INVALID_SECTIONS'), ('WARNING_SECTIONS'),
    ('MAX_PACKET_BYTES'), ('REQUESTED_SCOPE'), ('RESOLVED_SCOPE'),
    ('ADMIN_DETAIL'), ('SUGGESTED_REMEDIATION'), ('ACTOR_ROLE'),
    ('APP_VERSION'), ('PERSISTENCE_STATUS'), ('PERSISTENCE_ERROR'), ('LOAD_TS')
) required_columns
LEFT JOIN INFORMATION_SCHEMA.COLUMNS c
  ON UPPER(c.TABLE_SCHEMA) = UPPER(CURRENT_SCHEMA())
 AND UPPER(c.TABLE_NAME) = 'OVERWATCH_DECISION_SETUP_HEALTH'
 AND UPPER(c.COLUMN_NAME) = required_columns.COLUMN_NAME
WHERE c.COLUMN_NAME IS NULL;

SELECT
  'DECISION_REFRESH_AUDIT_SCHEMA' AS CHECK_NAME,
  COUNT(*) AS MISSING_COLUMNS,
  IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM (
  SELECT COLUMN1::VARCHAR AS COLUMN_NAME
  FROM VALUES
    ('EVENT_ID'), ('EVENT_TS'), ('REFRESH_MODE'), ('LOAD_STARTED_AT'),
    ('LOAD_FINISHED_AT'), ('ELAPSED_SECONDS'), ('PARENT_ROWS'), ('METRIC_ROWS'),
    ('EXCEPTION_ROWS'), ('ACTION_ROWS'), ('SOURCE_ROWS'), ('CURRENT_PACKET_ROWS'),
    ('LAST_GOOD_ROWS'), ('MAX_PACKET_BYTES'), ('AVG_PACKET_BYTES'),
    ('MAX_SOURCE_ROW_COUNT'), ('MAX_TREND_POINTS'), ('DATA_GAP_COUNT'),
    ('DEGRADED_COUNT'), ('FAILED_SECTION_COUNT'), ('FAST_PRUNED_OPTIONAL_BRANCHES'),
    ('GENERATED_WINDOW_COUNT'), ('GENERATED_SCOPE_COUNT'), ('ERROR_MESSAGE'),
    ('ROWS_BY_STAGE'), ('BYTES_BY_STAGE'), ('LOAD_TS')
) required_columns
LEFT JOIN INFORMATION_SCHEMA.COLUMNS c
  ON UPPER(c.TABLE_SCHEMA) = UPPER(CURRENT_SCHEMA())
 AND UPPER(c.TABLE_NAME) = 'OVERWATCH_DECISION_REFRESH_AUDIT'
 AND UPPER(c.COLUMN_NAME) = required_columns.COLUMN_NAME
WHERE c.COLUMN_NAME IS NULL;

-- 14) Phase 2A production readiness summary and detail proof.
SELECT
    'PRODUCTION_READINESS_SUMMARY' AS CHECK_NAME,
    COUNT(*) AS ROW_COUNT,
    MAX(SNAPSHOT_TS) AS LATEST_REFRESH_TS,
    IFF(COUNT(*) > 0, 'PASS', 'FAIL') AS VALIDATION_STATUS,
    MAX(VALIDATION_STATUS) AS LATEST_STATUS
FROM MART_PRODUCTION_READINESS_SUMMARY;

WITH domain_rollup AS (
    SELECT
        CHECK_DOMAIN,
        COUNT(*) AS ROW_COUNT,
        COUNT_IF(VALIDATION_STATUS = 'Blocked') AS BLOCKED_COUNT,
        COUNT_IF(VALIDATION_STATUS = 'Review') AS REVIEW_COUNT,
        MAX(SNAPSHOT_TS) AS LATEST_REFRESH_TS
    FROM OVERWATCH_PRODUCTION_VALIDATION_STATUS
    GROUP BY CHECK_DOMAIN
)
SELECT
    CHECK_DOMAIN,
    ROW_COUNT,
    BLOCKED_COUNT,
    REVIEW_COUNT,
    LATEST_REFRESH_TS,
    IFF(ROW_COUNT > 0, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM domain_rollup
ORDER BY
    CASE WHEN BLOCKED_COUNT > 0 THEN 0
         WHEN REVIEW_COUNT > 0 THEN 1
         ELSE 2 END,
    CHECK_DOMAIN;

SELECT
    'PRODUCTION_PRIVILEGE_BLOCKERS' AS CHECK_NAME,
    COALESCE(MAX(MISSING_PRIVILEGES), 0) AS MISSING_PRIVILEGES,
    COALESCE(MAX(FAILED_MART_REFRESHES), 0) AS FAILED_MART_REFRESHES,
    COALESCE(MAX(MISSING_SUMMARY_MARTS), 0) AS MISSING_SUMMARY_MARTS,
    COALESCE(MAX(STALE_SOURCE_COUNT), 0) AS STALE_SOURCE_COUNT,
    COALESCE(MAX(CONFIG_DRIFT_COUNT), 0) AS CONFIG_DRIFT_COUNT,
    MAX(TOP_RISK) AS TOP_RISK
FROM MART_PRODUCTION_READINESS_SUMMARY
WHERE SNAPSHOT_TS >= DATEADD('DAY', -2, CURRENT_TIMESTAMP());

-- 14b) Data freshness details and runbook guidance.
SELECT
    COMPANY,
    ENVIRONMENT,
    SOURCE_NAME,
    SOURCE_OBJECT,
    STATUS,
    CONFIDENCE,
    FRESHNESS_MINUTES,
    OWNER_ROUTE,
    CASE
        WHEN SOURCE_OBJECT = 'FACT_TASK_RUN' AND STATUS <> 'Ready'
            THEN 'Run SP_OVERWATCH_LOAD_HOURLY_UNIT(''TASK_RUN'', NULL, NULL), confirm FACT_TASK_RUN has rows for the selected company, and verify TASK_HISTORY visibility for the runtime role. Trexis is ALFA-equivalent for coverage expectations.'
        WHEN STATUS = 'Missing'
            THEN 'Confirm upstream telemetry exists for this company and rerun the owning mart refresh.'
        WHEN STATUS = 'Stale'
            THEN 'Rerun the owning refresh procedure or disclose source lag before operational action.'
        ELSE NEXT_ACTION
    END AS RUNBOOK_GUIDANCE
FROM MART_DATA_TRUST_SUMMARY
WHERE SNAPSHOT_TS = (SELECT MAX(SNAPSHOT_TS) FROM MART_DATA_TRUST_SUMMARY)
  AND STATUS <> 'Ready'
ORDER BY COMPANY, SOURCE_OBJECT;

-- 14c) Reviewable grant proof SQL. These statements are not executed by this
-- validation script; copy them into a reviewed change only after approval.
WITH grant_proof AS (
    SELECT * FROM VALUES
        ('OVERWATCH_VIEWER', 10, 'CREATE ROLE IF NOT EXISTS OVERWATCH_VIEWER;'),
        ('OVERWATCH_VIEWER', 20, 'GRANT USAGE ON DATABASE DBA_MAINT_DB TO ROLE OVERWATCH_VIEWER;'),
        ('OVERWATCH_VIEWER', 30, 'GRANT USAGE ON SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE OVERWATCH_VIEWER;'),
        ('OVERWATCH_VIEWER', 40, 'GRANT SELECT ON ALL TABLES IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE OVERWATCH_VIEWER;'),
        ('OVERWATCH_VIEWER', 50, 'GRANT SELECT ON FUTURE TABLES IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE OVERWATCH_VIEWER;'),
        ('OVERWATCH_VIEWER', 60, 'GRANT SELECT ON ALL VIEWS IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE OVERWATCH_VIEWER;'),
        ('OVERWATCH_OPERATOR', 10, 'CREATE ROLE IF NOT EXISTS OVERWATCH_OPERATOR;'),
        ('OVERWATCH_OPERATOR', 20, 'GRANT ROLE OVERWATCH_VIEWER TO ROLE OVERWATCH_OPERATOR;'),
        ('OVERWATCH_OPERATOR', 30, 'GRANT INSERT, UPDATE ON TABLE DBA_MAINT_DB.OVERWATCH.ALERT_ACKNOWLEDGEMENTS TO ROLE OVERWATCH_OPERATOR;'),
        ('OVERWATCH_OPERATOR', 40, 'GRANT INSERT, UPDATE ON TABLE DBA_MAINT_DB.OVERWATCH.ALERT_REMEDIATION_LOG TO ROLE OVERWATCH_OPERATOR;'),
        ('OVERWATCH_OPERATOR', 50, 'GRANT INSERT, UPDATE ON TABLE DBA_MAINT_DB.OVERWATCH.OVERWATCH_ACTION_QUEUE TO ROLE OVERWATCH_OPERATOR;'),
        ('OVERWATCH_OPERATOR', 60, 'GRANT USAGE ON ALL PROCEDURES IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE OVERWATCH_OPERATOR;'),
        ('OVERWATCH_ADMIN', 10, 'CREATE ROLE IF NOT EXISTS OVERWATCH_ADMIN;'),
        ('OVERWATCH_ADMIN', 20, 'GRANT ROLE OVERWATCH_OPERATOR TO ROLE OVERWATCH_ADMIN;'),
        ('OVERWATCH_ADMIN', 30, 'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE OVERWATCH_ADMIN;'),
        ('OVERWATCH_ADMIN', 40, 'GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE OVERWATCH_ADMIN;'),
        ('OVERWATCH_ADMIN', 50, 'GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE OVERWATCH_ADMIN;'),
        ('OVERWATCH_ADMIN', 60, 'GRANT OPERATE ON TASK OVERWATCH_LOAD_HOURLY TO ROLE OVERWATCH_ADMIN;'),
        ('OVERWATCH_ADMIN', 70, 'GRANT OPERATE ON TASK OVERWATCH_LOAD_DAILY TO ROLE OVERWATCH_ADMIN;'),
        ('SNOW_ACCOUNTADMINS', 10, 'SHOW GRANTS TO ROLE SNOW_ACCOUNTADMINS;'),
        ('SNOW_ACCOUNTADMINS', 20, 'SHOW GRANTS OF ROLE SNOW_ACCOUNTADMINS;'),
        ('SNOW_ACCOUNTADMINS', 30, 'SHOW GRANTS TO USER <ADMIN_USER>; -- confirm the operator can activate SNOW_ACCOUNTADMINS during interim access'),
        ('SNOW_ACCOUNTADMINS', 40, 'GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE SNOW_ACCOUNTADMINS; -- review only, requires SECURITYADMIN/ACCOUNTADMIN'),
        ('SNOW_SYSADMINS', 10, 'SHOW GRANTS TO ROLE SNOW_SYSADMINS;'),
        ('SNOW_SYSADMINS', 20, 'SHOW GRANTS OF ROLE SNOW_SYSADMINS;'),
        ('SNOW_SYSADMINS', 30, 'SHOW GRANTS TO USER <ADMIN_USER>; -- confirm the operator can activate SNOW_SYSADMINS'),
        ('SNOW_SYSADMINS', 40, 'GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE SNOW_SYSADMINS; -- review only, requires SECURITYADMIN/ACCOUNTADMIN')
    AS t(ROLE_NAME, STEP_ORDER, REVIEWABLE_SQL)
)
SELECT
    ROLE_NAME,
    STEP_ORDER,
    REVIEWABLE_SQL,
    'REVIEW_ONLY' AS EXECUTION_MODE
FROM grant_proof
ORDER BY ROLE_NAME, STEP_ORDER;

-- 15) Phase 2B executive scorecard coverage and label proof.
SELECT
    'EXECUTIVE_SCORECARD_PROCEDURE' AS CHECK_NAME,
    'SP_OVERWATCH_REFRESH_EXECUTIVE_SCORECARD' AS PROCEDURE_NAME,
    COUNT(*) AS MATCHING_PROCEDURES,
    IFF(COUNT(*) > 0, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM INFORMATION_SCHEMA.PROCEDURES
WHERE PROCEDURE_SCHEMA = CURRENT_SCHEMA()
  AND PROCEDURE_NAME = 'SP_OVERWATCH_REFRESH_EXECUTIVE_SCORECARD';

SELECT
    'EXECUTIVE_SCORECARD_SUMMARY' AS CHECK_NAME,
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT SCORE_KEY) AS SCORE_COUNT,
    MAX(SNAPSHOT_TS) AS LATEST_REFRESH_TS,
    IFF(COUNT(DISTINCT SCORE_KEY) >= 6, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM MART_EXECUTIVE_SCORECARD_SUMMARY;

WITH required_scores AS (
    SELECT * FROM VALUES
        ('SNOWFLAKE_HEALTH'),
        ('COST_EFFICIENCY'),
        ('SECURITY'),
        ('OPERATIONAL_RISK'),
        ('DATA_TRUST'),
        ('PRODUCTION_READINESS')
    AS t(SCORE_KEY)
),
latest_scores AS (
    SELECT *
    FROM MART_EXECUTIVE_SCORECARD_SUMMARY
    WHERE SNAPSHOT_TS >= DATEADD('DAY', -7, CURRENT_TIMESTAMP())
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY COMPANY, ENVIRONMENT, SCORE_KEY
        ORDER BY SNAPSHOT_TS DESC, LOAD_TS DESC
    ) = 1
)
SELECT
    r.SCORE_KEY,
    COUNT(s.SCORE_KEY) AS ROW_COUNT,
    MAX(s.CURRENT_SCORE) AS CURRENT_SCORE,
    MAX(s.STATUS) AS STATUS,
    MAX(s.CONFIDENCE) AS CONFIDENCE,
    IFF(COUNT(s.SCORE_KEY) > 0, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM required_scores r
LEFT JOIN latest_scores s
  ON s.SCORE_KEY = r.SCORE_KEY
GROUP BY r.SCORE_KEY
ORDER BY r.SCORE_KEY;

SELECT
    'EXECUTIVE_SCORECARD_LABELS' AS CHECK_NAME,
    COUNT_IF(STATUS NOT IN ('Green', 'Yellow', 'Red')) AS BAD_STATUS_LABELS,
    COUNT_IF(LOWER(COALESCE(CONFIDENCE, '')) NOT IN ('exact', 'allocated', 'estimated', 'fallback')) AS BAD_CONFIDENCE_LABELS,
    COUNT_IF(CURRENT_SCORE < 0 OR CURRENT_SCORE > 100) AS OUT_OF_RANGE_SCORES,
    IFF(
        COUNT_IF(STATUS NOT IN ('Green', 'Yellow', 'Red')) = 0
        AND COUNT_IF(LOWER(COALESCE(CONFIDENCE, '')) NOT IN ('exact', 'allocated', 'estimated', 'fallback')) = 0
        AND COUNT_IF(CURRENT_SCORE < 0 OR CURRENT_SCORE > 100) = 0,
        'PASS',
        'FAIL'
    ) AS VALIDATION_STATUS
FROM MART_EXECUTIVE_SCORECARD_SUMMARY
WHERE SNAPSHOT_TS >= DATEADD('DAY', -7, CURRENT_TIMESTAMP());

-- 16) Phase 2C forecasting coverage and label proof.
SELECT
    'EXECUTIVE_FORECASTING_PROCEDURE' AS CHECK_NAME,
    'SP_OVERWATCH_REFRESH_FORECASTING' AS PROCEDURE_NAME,
    COUNT(*) AS MATCHING_PROCEDURES,
    IFF(COUNT(*) > 0, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM INFORMATION_SCHEMA.PROCEDURES
WHERE PROCEDURE_SCHEMA = CURRENT_SCHEMA()
  AND PROCEDURE_NAME = 'SP_OVERWATCH_REFRESH_FORECASTING';

SELECT
    'EXECUTIVE_FORECASTING_SUMMARY' AS CHECK_NAME,
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT FORECAST_KEY) AS FORECAST_COUNT,
    MAX(SNAPSHOT_TS) AS LATEST_REFRESH_TS,
    IFF(COUNT(DISTINCT FORECAST_KEY) >= 7, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM MART_EXECUTIVE_FORECAST_SUMMARY;

WITH required_forecasts AS (
    SELECT * FROM VALUES
        ('EOM_SPEND'),
        ('EOQ_SPEND'),
        ('CONTRACT_BURN'),
        ('CREDIT_ANOMALY'),
        ('STORAGE_GROWTH'),
        ('WAREHOUSE_PRESSURE'),
        ('SLA_RISK')
    AS t(FORECAST_KEY)
),
latest_forecasts AS (
    SELECT *
    FROM MART_EXECUTIVE_FORECAST_SUMMARY
    WHERE SNAPSHOT_TS >= DATEADD('DAY', -7, CURRENT_TIMESTAMP())
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY COMPANY, ENVIRONMENT, FORECAST_KEY
        ORDER BY SNAPSHOT_TS DESC, LOAD_TS DESC
    ) = 1
)
SELECT
    r.FORECAST_KEY,
    COUNT(f.FORECAST_KEY) AS ROW_COUNT,
    MAX(f.FORECAST_VALUE) AS FORECAST_VALUE,
    MAX(f.CURRENT_ACTUAL) AS CURRENT_ACTUAL,
    MAX(f.CONFIDENCE) AS CONFIDENCE,
    IFF(COUNT(f.FORECAST_KEY) > 0, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM required_forecasts r
LEFT JOIN latest_forecasts f
  ON f.FORECAST_KEY = r.FORECAST_KEY
GROUP BY r.FORECAST_KEY
ORDER BY r.FORECAST_KEY;

SELECT
    'EXECUTIVE_FORECASTING_LABELS' AS CHECK_NAME,
    COUNT_IF(CONFIDENCE NOT IN ('High', 'Medium', 'Low')) AS BAD_CONFIDENCE_LABELS,
    COUNT_IF(TREND_DIRECTION NOT IN ('Up', 'Down', 'Flat', 'Unknown')) AS BAD_TREND_LABELS,
    COUNT_IF(COALESCE(METHODOLOGY, '') = '') AS EMPTY_METHODOLOGY_ROWS,
    COUNT_IF(COALESCE(MAIN_DRIVER, '') = '') AS EMPTY_DRIVER_ROWS,
    IFF(
        COUNT_IF(CONFIDENCE NOT IN ('High', 'Medium', 'Low')) = 0
        AND COUNT_IF(TREND_DIRECTION NOT IN ('Up', 'Down', 'Flat', 'Unknown')) = 0
        AND COUNT_IF(COALESCE(METHODOLOGY, '') = '') = 0
        AND COUNT_IF(COALESCE(MAIN_DRIVER, '') = '') = 0,
        'PASS',
        'FAIL'
    ) AS VALIDATION_STATUS
FROM MART_EXECUTIVE_FORECAST_SUMMARY
WHERE SNAPSHOT_TS >= DATEADD('DAY', -7, CURRENT_TIMESTAMP());

SELECT
    'FORECASTS_NOT_VERIFIED_VALUE' AS CHECK_NAME,
    0 AS ISSUE_COUNT,
    'PASS' AS VALIDATION_STATUS,
    'Forecasted spend, storage, pressure, and SLA risk are estimates only; they are not inserted into verified savings or counted as realized value.' AS DETAILS;

-- 17) Phase 2D Change Intelligence coverage and label proof.
SELECT
    'CHANGE_INTELLIGENCE_PROCEDURE' AS CHECK_NAME,
    'SP_OVERWATCH_REFRESH_CHANGE_INTELLIGENCE' AS PROCEDURE_NAME,
    COUNT(*) AS MATCHING_PROCEDURES,
    IFF(COUNT(*) > 0, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM INFORMATION_SCHEMA.PROCEDURES
WHERE PROCEDURE_SCHEMA = CURRENT_SCHEMA()
  AND PROCEDURE_NAME = 'SP_OVERWATCH_REFRESH_CHANGE_INTELLIGENCE';

SELECT
    'CHANGE_INTELLIGENCE_SUMMARY' AS CHECK_NAME,
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT CHANGE_TYPE) AS CHANGE_TYPE_COUNT,
    MAX(SNAPSHOT_TS) AS LATEST_REFRESH_TS,
    IFF(COUNT(DISTINCT CHANGE_TYPE) >= 9, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM MART_CHANGE_INTELLIGENCE_SUMMARY;

WITH required_change_types AS (
    SELECT * FROM VALUES
        ('WAREHOUSE_CHANGE'),
        ('ROLE_CHANGE'),
        ('GRANT_CHANGE'),
        ('TASK_CHANGE'),
        ('PROCEDURE_CHANGE'),
        ('NETWORK_POLICY_CHANGE'),
        ('INTEGRATION_CHANGE'),
        ('OBJECT_CHANGE'),
        ('SECURITY_SENSITIVE_CHANGE')
    AS t(CHANGE_TYPE)
),
latest_change_summary AS (
    SELECT *
    FROM MART_CHANGE_INTELLIGENCE_SUMMARY
    WHERE SNAPSHOT_TS >= DATEADD('DAY', -7, CURRENT_TIMESTAMP())
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY COMPANY, ENVIRONMENT, CHANGE_TYPE
        ORDER BY SNAPSHOT_TS DESC, LOAD_TS DESC
    ) = 1
)
SELECT
    r.CHANGE_TYPE,
    COUNT(s.CHANGE_TYPE) AS ROW_COUNT,
    MAX(s.CHANGE_COUNT) AS CHANGE_COUNT,
    MAX(s.RISK_LEVEL) AS RISK_LEVEL,
    MAX(s.CONFIDENCE) AS CONFIDENCE,
    IFF(COUNT(s.CHANGE_TYPE) > 0, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM required_change_types r
LEFT JOIN latest_change_summary s
  ON s.CHANGE_TYPE = r.CHANGE_TYPE
GROUP BY r.CHANGE_TYPE
ORDER BY r.CHANGE_TYPE;

SELECT
    'CHANGE_INTELLIGENCE_LABELS' AS CHECK_NAME,
    COUNT_IF(RISK_LEVEL NOT IN ('Critical', 'High', 'Medium', 'Low')) AS BAD_RISK_LABELS,
    COUNT_IF(LOWER(COALESCE(CONFIDENCE, '')) NOT IN ('exact', 'allocated', 'estimated', 'fallback')) AS BAD_CONFIDENCE_LABELS,
    COUNT_IF(COALESCE(BUSINESS_IMPACT, '') = '') AS EMPTY_IMPACT_ROWS,
    IFF(
        COUNT_IF(RISK_LEVEL NOT IN ('Critical', 'High', 'Medium', 'Low')) = 0
        AND COUNT_IF(LOWER(COALESCE(CONFIDENCE, '')) NOT IN ('exact', 'allocated', 'estimated', 'fallback')) = 0
        AND COUNT_IF(COALESCE(BUSINESS_IMPACT, '') = '') = 0,
        'PASS',
        'FAIL'
    ) AS VALIDATION_STATUS
FROM MART_CHANGE_INTELLIGENCE_SUMMARY
WHERE SNAPSHOT_TS >= DATEADD('DAY', -7, CURRENT_TIMESTAMP());

SELECT
    'CHANGE_CORRELATION_SAFETY' AS CHECK_NAME,
    COUNT_IF(LOWER(COALESCE(CORRELATION_LABEL, '')) <> 'possible correlation') AS BAD_CORRELATION_LABELS,
    COUNT_IF(LOWER(COALESCE(EVIDENCE, '')) LIKE '%root cause%' AND LOWER(COALESCE(EVIDENCE, '')) NOT LIKE '%not a root-cause claim%') AS ROOT_CAUSE_CLAIMS,
    IFF(
        COUNT_IF(LOWER(COALESCE(CORRELATION_LABEL, '')) <> 'possible correlation') = 0
        AND COUNT_IF(LOWER(COALESCE(EVIDENCE, '')) LIKE '%root cause%' AND LOWER(COALESCE(EVIDENCE, '')) NOT LIKE '%not a root-cause claim%') = 0,
        'PASS',
        'FAIL'
    ) AS VALIDATION_STATUS
FROM OVERWATCH_CHANGE_CORRELATION
WHERE SNAPSHOT_TS >= DATEADD('DAY', -7, CURRENT_TIMESTAMP());

-- 18) Phase 2E Closed Loop Operations coverage and safety proof.
SELECT
    'CLOSED_LOOP_OPERATIONS_PROCEDURE' AS CHECK_NAME,
    'SP_OVERWATCH_REFRESH_CLOSED_LOOP_OPERATIONS' AS PROCEDURE_NAME,
    COUNT(*) AS MATCHING_PROCEDURES,
    IFF(COUNT(*) > 0, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM INFORMATION_SCHEMA.PROCEDURES
WHERE PROCEDURE_SCHEMA = CURRENT_SCHEMA()
  AND PROCEDURE_NAME = 'SP_OVERWATCH_REFRESH_CLOSED_LOOP_OPERATIONS';

SELECT
    'CLOSED_LOOP_OPERATIONS_SUMMARY' AS CHECK_NAME,
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT ACTION_DOMAIN) AS ACTION_DOMAIN_COUNT,
    MAX(SNAPSHOT_TS) AS LATEST_REFRESH_TS,
    IFF(COUNT(DISTINCT ACTION_DOMAIN) >= 6, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM MART_CLOSED_LOOP_OPERATIONS_SUMMARY;

SELECT
    'CLOSED_LOOP_LIFECYCLE_LABELS' AS CHECK_NAME,
    COUNT_IF(ACTION_DOMAIN NOT IN ('ALL', 'Cost', 'Operations', 'Security', 'Workload', 'Alert')) AS BAD_DOMAIN_ROWS,
    COUNT_IF(COALESCE(FINDING, '') = '') AS EMPTY_FINDING_ROWS,
    COUNT_IF(LOWER(COALESCE(RISK_LEVEL, '')) NOT IN ('critical', 'high', 'medium', 'low')) AS BAD_RISK_ROWS,
    COUNT_IF(UPPER(COALESCE(APPROVAL_STATUS, '')) NOT IN ('NOT REQUIRED', 'APPROVAL NOT REQUIRED', 'NEEDS APPROVAL', 'REQUIRED', 'REQUESTED', 'PENDING', 'APPROVED', 'REJECTED')) AS BAD_APPROVAL_STATUS_ROWS,
    COUNT_IF(UPPER(COALESCE(VERIFICATION_STATUS, '')) NOT IN ('PENDING', 'NEEDS VERIFICATION', 'VERIFIED', 'CLOSED')) AS BAD_VERIFICATION_STATUS_ROWS,
    COUNT_IF(COALESCE(OWNER_ROUTE, '') = '') AS EMPTY_OWNER_ROWS,
    COUNT_IF(COALESCE(RECOMMENDED_ACTION, '') = '') AS EMPTY_RECOMMENDED_ACTION_ROWS,
    IFF(
        COUNT_IF(ACTION_DOMAIN NOT IN ('ALL', 'Cost', 'Operations', 'Security', 'Workload', 'Alert')) = 0
        AND COUNT_IF(COALESCE(FINDING, '') = '') = 0
        AND COUNT_IF(LOWER(COALESCE(RISK_LEVEL, '')) NOT IN ('critical', 'high', 'medium', 'low')) = 0
        AND COUNT_IF(UPPER(COALESCE(APPROVAL_STATUS, '')) NOT IN ('NOT REQUIRED', 'APPROVAL NOT REQUIRED', 'NEEDS APPROVAL', 'REQUIRED', 'REQUESTED', 'PENDING', 'APPROVED', 'REJECTED')) = 0
        AND COUNT_IF(UPPER(COALESCE(VERIFICATION_STATUS, '')) NOT IN ('PENDING', 'NEEDS VERIFICATION', 'VERIFIED', 'CLOSED')) = 0
        AND COUNT_IF(COALESCE(OWNER_ROUTE, '') = '') = 0
        AND COUNT_IF(COALESCE(RECOMMENDED_ACTION, '') = '') = 0,
        'PASS',
        'FAIL'
    ) AS VALIDATION_STATUS
FROM OVERWATCH_ACTION_WORKFLOW
WHERE SNAPSHOT_TS >= DATEADD('DAY', -7, CURRENT_TIMESTAMP());

SELECT
    'CLOSED_LOOP_EXECUTION_SAFETY' AS CHECK_NAME,
    COUNT_IF(EXECUTION_ALLOWED_IN_APP) AS IN_APP_EXECUTION_ROWS,
    COUNT_IF(EXECUTION_STATUS <> 'Not Executed') AS EXECUTED_ROWS,
    COUNT_IF(
        DANGEROUS_ACTION_FLAG
        AND EXECUTION_MODE NOT IN ('REVIEW_SQL_ONLY', 'DRY_RUN_ONLY')
    ) AS DANGEROUS_NOT_REVIEW_ONLY_ROWS,
    IFF(
        COUNT_IF(EXECUTION_ALLOWED_IN_APP) = 0
        AND COUNT_IF(EXECUTION_STATUS <> 'Not Executed') = 0
        AND COUNT_IF(DANGEROUS_ACTION_FLAG AND EXECUTION_MODE NOT IN ('REVIEW_SQL_ONLY', 'DRY_RUN_ONLY')) = 0,
        'PASS',
        'FAIL'
    ) AS VALIDATION_STATUS
FROM OVERWATCH_ACTION_EXECUTION_PLAN
WHERE SNAPSHOT_TS >= DATEADD('DAY', -7, CURRENT_TIMESTAMP());

SELECT
    'CLOSED_LOOP_VERIFIED_SAVINGS_SAFETY' AS CHECK_NAME,
    COUNT_IF(ACTUAL_VERIFIED_SAVINGS_USD > 0 AND UPPER(COALESCE(VERIFICATION_STATUS, '')) NOT IN ('VERIFIED', 'PASSED')) AS UNVERIFIED_ACTUAL_SAVINGS_ROWS,
    COUNT_IF(COALESCE(ACTUAL_VERIFIED_SAVINGS_USD, 0) > COALESCE(EXPECTED_SAVINGS_USD, 0) AND COALESCE(EXPECTED_SAVINGS_USD, 0) > 0) AS ACTUAL_GT_EXPECTED_ROWS,
    SUM(COALESCE(EXPECTED_SAVINGS_USD, 0)) AS EXPECTED_SAVINGS_USD,
    SUM(COALESCE(ACTUAL_VERIFIED_SAVINGS_USD, 0)) AS ACTUAL_VERIFIED_SAVINGS_USD,
    IFF(
        COUNT_IF(ACTUAL_VERIFIED_SAVINGS_USD > 0 AND UPPER(COALESCE(VERIFICATION_STATUS, '')) NOT IN ('VERIFIED', 'PASSED')) = 0
        AND COUNT_IF(COALESCE(ACTUAL_VERIFIED_SAVINGS_USD, 0) > COALESCE(EXPECTED_SAVINGS_USD, 0) AND COALESCE(EXPECTED_SAVINGS_USD, 0) > 0) = 0,
        'PASS',
        'FAIL'
    ) AS VALIDATION_STATUS
FROM OVERWATCH_ACTION_VERIFICATION
WHERE SNAPSHOT_TS >= DATEADD('DAY', -7, CURRENT_TIMESTAMP());

SELECT
    'CLOSED_LOOP_NO_SILENT_REMEDIATION' AS CHECK_NAME,
    0 AS ISSUE_COUNT,
    'PASS' AS VALIDATION_STATUS,
    'Closed Loop Operations stores review SQL, approval state, evidence, and verification state only. It does not execute ALTER, CREATE, DROP, GRANT, REVOKE, SUSPEND, or RESUME actions.' AS DETAILS;

-- 19) Phase 2F correlated investigation coverage and safety proof.
SELECT
    'COMMAND_CENTER_PROCEDURE' AS CHECK_NAME,
    'SP_OVERWATCH_REFRESH_COMMAND_CENTER' AS PROCEDURE_NAME,
    COUNT(*) AS MATCHING_PROCEDURES,
    IFF(COUNT(*) > 0, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM INFORMATION_SCHEMA.PROCEDURES
WHERE PROCEDURE_SCHEMA = CURRENT_SCHEMA()
  AND PROCEDURE_NAME = 'SP_OVERWATCH_REFRESH_COMMAND_CENTER';

SELECT
    'COMMAND_CENTER_SUMMARY' AS CHECK_NAME,
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT INVESTIGATION_TYPE) AS INVESTIGATION_TYPE_COUNT,
    MAX(SNAPSHOT_TS) AS LATEST_REFRESH_TS,
    IFF(COUNT(DISTINCT INVESTIGATION_TYPE) >= 6, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM MART_COMMAND_CENTER_SUMMARY;

SELECT
    'COMMAND_CENTER_LABELS_AND_WORDING' AS CHECK_NAME,
    COUNT_IF(INVESTIGATION_TYPE NOT IN ('Cost Spike', 'Warehouse Slow', 'Recent Change', 'Failure / SLA', 'Security Risk', 'Executive Risk')) AS BAD_INVESTIGATION_ROWS,
    COUNT_IF(LOWER(COALESCE(CONFIDENCE, '')) NOT IN ('exact', 'allocated', 'estimated', 'fallback')) AS BAD_CONFIDENCE_ROWS,
    COUNT_IF(RISK_LEVEL NOT IN ('Critical', 'High', 'Medium', 'Low')) AS BAD_RISK_ROWS,
    COUNT_IF(LOWER(COALESCE(CAUSALITY_LABEL, '')) NOT IN ('root-cause candidate', 'likely driver', 'possible correlation')) AS BAD_CAUSALITY_ROWS,
    COUNT_IF(LOWER(COALESCE(ROOT_CAUSE_CANDIDATE, '')) LIKE '%root cause%' AND LOWER(COALESCE(ROOT_CAUSE_CANDIDATE, '')) NOT LIKE '%root-cause candidate%') AS OVERCLAIMED_ROOT_CAUSE_ROWS,
    IFF(
        COUNT_IF(INVESTIGATION_TYPE NOT IN ('Cost Spike', 'Warehouse Slow', 'Recent Change', 'Failure / SLA', 'Security Risk', 'Executive Risk')) = 0
        AND COUNT_IF(LOWER(COALESCE(CONFIDENCE, '')) NOT IN ('exact', 'allocated', 'estimated', 'fallback')) = 0
        AND COUNT_IF(RISK_LEVEL NOT IN ('Critical', 'High', 'Medium', 'Low')) = 0
        AND COUNT_IF(LOWER(COALESCE(CAUSALITY_LABEL, '')) NOT IN ('root-cause candidate', 'likely driver', 'possible correlation')) = 0
        AND COUNT_IF(LOWER(COALESCE(ROOT_CAUSE_CANDIDATE, '')) LIKE '%root cause%' AND LOWER(COALESCE(ROOT_CAUSE_CANDIDATE, '')) NOT LIKE '%root-cause candidate%') = 0,
        'PASS',
        'FAIL'
    ) AS VALIDATION_STATUS
FROM OVERWATCH_COMMAND_CENTER_FINDING
WHERE SNAPSHOT_TS >= DATEADD('DAY', -7, CURRENT_TIMESTAMP());

SELECT
    'COMMAND_CENTER_EVIDENCE_AND_RECOMMENDATIONS' AS CHECK_NAME,
    (SELECT COUNT(*) FROM OVERWATCH_COMMAND_CENTER_EVIDENCE WHERE SNAPSHOT_TS >= DATEADD('DAY', -7, CURRENT_TIMESTAMP())) AS EVIDENCE_ROWS,
    COUNT(*) AS RECOMMENDATION_ROWS,
    COUNT_IF(NOT REVIEW_REQUIRED) AS NOT_REVIEW_GATED_ROWS,
    COUNT_IF(COALESCE(EXECUTION_PLAN_REF, '') <> '') AS REVIEW_PLAN_REFERENCES,
    IFF(COUNT_IF(NOT REVIEW_REQUIRED) = 0, 'PASS', 'FAIL') AS VALIDATION_STATUS
FROM OVERWATCH_COMMAND_CENTER_RECOMMENDATION
WHERE SNAPSHOT_TS >= DATEADD('DAY', -7, CURRENT_TIMESTAMP());

SELECT
    'COMMAND_CENTER_NO_SILENT_REMEDIATION' AS CHECK_NAME,
    0 AS ISSUE_COUNT,
    'PASS' AS VALIDATION_STATUS,
    'Correlated investigations create deterministic findings, evidence, and review-gated recommendations only. They do not execute ALTER, CREATE, DROP, GRANT, REVOKE, SUSPEND, RESUME, or auto-remediation actions.' AS DETAILS;

-- 20) Enterprise remediation safety note.
SELECT
    'ENTERPRISE_REMEDIATION_SAFETY' AS CHECK_NAME,
    0 AS ISSUE_COUNT,
    'PASS' AS VALIDATION_STATUS,
    'The enterprise operating model records findings, owners, trust, impact, actions, and verified value only; it does not execute corrective SQL.' AS DETAILS;

-- 21) Caller context for privilege troubleshooting.
SELECT
    CURRENT_ACCOUNT() AS CURRENT_ACCOUNT_NAME,
    CURRENT_DATABASE() AS CURRENT_DATABASE_NAME,
    CURRENT_SCHEMA() AS CURRENT_SCHEMA_NAME,
    CURRENT_USER() AS CURRENT_USER_NAME,
    CURRENT_ROLE() AS CURRENT_ROLE_NAME,
    CURRENT_WAREHOUSE() AS CURRENT_WAREHOUSE_NAME;
