-- OVERWATCH_ROLE_SETUP.sql
-- Production role contract for the Snowflake DBA command center.
-- Run as SECURITYADMIN/ACCOUNTADMIN, then assign users/service principals.

CREATE ROLE IF NOT EXISTS OVERWATCH_MONITOR;
CREATE ROLE IF NOT EXISTS OVERWATCH_OPERATOR;

GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE OVERWATCH_MONITOR;
GRANT USAGE ON WAREHOUSE OVERWATCH_WH TO ROLE OVERWATCH_MONITOR;
GRANT USAGE ON WAREHOUSE OVERWATCH_WH TO ROLE OVERWATCH_OPERATOR;

GRANT USAGE ON DATABASE DBA_MAINT_DB TO ROLE OVERWATCH_MONITOR;
GRANT USAGE ON SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE OVERWATCH_MONITOR;
GRANT SELECT ON ALL TABLES IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE OVERWATCH_MONITOR;
GRANT SELECT ON ALL VIEWS IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE OVERWATCH_MONITOR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE OVERWATCH_MONITOR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE OVERWATCH_MONITOR;

GRANT ROLE OVERWATCH_MONITOR TO ROLE OVERWATCH_OPERATOR;
GRANT INSERT, UPDATE ON ALL TABLES IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE OVERWATCH_OPERATOR;
GRANT INSERT, UPDATE ON FUTURE TABLES IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE OVERWATCH_OPERATOR;

-- Optional, approval-gated remediation privileges. Grant only after runbook signoff.
-- GRANT OPERATE ON WAREHOUSE <WAREHOUSE_NAME> TO ROLE OVERWATCH_OPERATOR;
-- GRANT OPERATE ON TASK <DATABASE>.<SCHEMA>.<TASK_NAME> TO ROLE OVERWATCH_OPERATOR;
-- GRANT MONITOR EXECUTION ON ACCOUNT TO ROLE OVERWATCH_MONITOR;

COMMENT ON ROLE OVERWATCH_MONITOR IS
    'Read-only OVERWATCH telemetry role for Snowflake account usage, marts, and dashboard evidence.';
COMMENT ON ROLE OVERWATCH_OPERATOR IS
    'Approval-gated OVERWATCH operator role for acknowledgements, action queue updates, and logged remediation.';
