-- OVERWATCH_MART_VALIDATION.sql
-- Read-only deployment validation for the OVERWATCH command-center marts.
-- Run from the database/schema where OVERWATCH_MART_SETUP.sql was deployed.

-- 1) Required command-center objects.
WITH required_objects AS (
    SELECT * FROM VALUES
        ('TABLE', 'OVERWATCH_REFRESH_POLICY'),
        ('TABLE', 'MART_EXECUTIVE_OBSERVABILITY'),
        ('TABLE', 'FACT_COST_DAILY'),
        ('TABLE', 'FACT_CORTEX_DAILY'),
        ('TABLE', 'FACT_QUERY_HOURLY'),
        ('TABLE', 'FACT_QUERY_DETAIL_RECENT'),
        ('TABLE', 'FACT_TASK_RUN'),
        ('TABLE', 'FACT_TASK_CRITICAL_PATH'),
        ('TABLE', 'FACT_PROCEDURE_RUN'),
        ('TABLE', 'ALERT_EVENTS'),
        ('TABLE', 'ALERT_ACKNOWLEDGEMENTS'),
        ('TABLE', 'ALERT_REMEDIATION_LOG'),
        ('TABLE', 'ALERT_NOTIFICATION_LOG'),
        ('TABLE', 'ALERT_THRESHOLDS'),
        ('TABLE', 'ALERT_OWNER_ROUTING'),
        ('TABLE', 'OVERWATCH_RECON_CONFIG'),
        ('TABLE', 'OVERWATCH_RECON_RUN'),
        ('TABLE', 'OVERWATCH_SCHEMA_DIFF_RESULT'),
        ('VIEW',  'OVERWATCH_VALUE_CANDIDATE_V')
    AS t(REQUIRED_TYPE, REQUIRED_OBJECT)
),
existing_objects AS (
    SELECT TABLE_TYPE AS OBJECT_TYPE, TABLE_NAME AS OBJECT_NAME
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = CURRENT_SCHEMA()
    UNION ALL
    SELECT 'VIEW' AS OBJECT_TYPE, TABLE_NAME AS OBJECT_NAME
    FROM INFORMATION_SCHEMA.VIEWS
    WHERE TABLE_SCHEMA = CURRENT_SCHEMA()
)
SELECT
    r.REQUIRED_TYPE,
    r.REQUIRED_OBJECT,
    IFF(e.OBJECT_NAME IS NULL, 'MISSING', 'PRESENT') AS VALIDATION_STATUS
FROM required_objects r
LEFT JOIN existing_objects e
  ON UPPER(e.OBJECT_NAME) = r.REQUIRED_OBJECT
ORDER BY VALIDATION_STATUS DESC, REQUIRED_TYPE, REQUIRED_OBJECT;

-- 2) Executive board panel coverage.
WITH required_panels AS (
    SELECT * FROM VALUES
        ('KPI'),
        ('DAILY_COST'),
        ('MONTHLY_COST'),
        ('DAILY_WORKLOAD'),
        ('COST_DRIVER'),
        ('QUERY_TYPE'),
        ('QUERY_DATABASE'),
        ('EXEC_STATUS'),
        ('WAREHOUSE_PRESSURE'),
        ('FRESHNESS'),
        ('SOURCE_STATUS')
    AS t(PANEL)
),
actual_panels AS (
    SELECT PANEL, COUNT(*) AS ROW_COUNT, MAX(SNAPSHOT_TS) AS LATEST_SNAPSHOT
    FROM MART_EXECUTIVE_OBSERVABILITY
    GROUP BY PANEL
)
SELECT
    r.PANEL,
    COALESCE(a.ROW_COUNT, 0) AS ROW_COUNT,
    a.LATEST_SNAPSHOT,
    IFF(a.PANEL IS NULL, 'MISSING', 'PRESENT') AS VALIDATION_STATUS
FROM required_panels r
LEFT JOIN actual_panels a
  ON a.PANEL = r.PANEL
ORDER BY VALIDATION_STATUS DESC, r.PANEL;

-- 3) Executive board freshness by source.
SELECT
    COMPANY,
    ENVIRONMENT,
    WINDOW_DAYS,
    DIMENSION AS SOURCE_NAME,
    MAX(PERIOD_START) AS LATEST_SOURCE_TS,
    DATEDIFF('minute', MAX(PERIOD_START), CURRENT_TIMESTAMP()) AS AGE_MINUTES,
    MAX(SOURCE) AS SOURCE_TABLE
FROM MART_EXECUTIVE_OBSERVABILITY
WHERE PANEL = 'FRESHNESS'
GROUP BY COMPANY, ENVIRONMENT, WINDOW_DAYS, DIMENSION
ORDER BY AGE_MINUTES DESC NULLS FIRST, SOURCE_NAME;

-- 4) Refresh-policy contract for first paint and live fallback.
SELECT
    SURFACE,
    FIRST_PAINT_SOURCE,
    TARGET_FRESHNESS_MINUTES,
    LIVE_FALLBACK_ALLOWED,
    RUN_IN_FIRST_PAINT,
    OWNER,
    WHY_THIS_DECISION
FROM OVERWATCH_REFRESH_POLICY
ORDER BY RUN_IN_FIRST_PAINT DESC, SURFACE;

-- 5) Alert lifecycle and remediation audit coverage.
SELECT 'ALERT_EVENTS' AS OBJECT_NAME, COUNT(*) AS ROW_COUNT, MAX(ALERT_TS) AS LATEST_EVENT_TS FROM ALERT_EVENTS
UNION ALL
SELECT 'ALERT_ACKNOWLEDGEMENTS', COUNT(*), MAX(ACKNOWLEDGED_AT) FROM ALERT_ACKNOWLEDGEMENTS
UNION ALL
SELECT 'ALERT_REMEDIATION_LOG', COUNT(*), MAX(REQUESTED_AT) FROM ALERT_REMEDIATION_LOG
UNION ALL
SELECT 'ALERT_NOTIFICATION_LOG', COUNT(*), MAX(NOTIFICATION_TS) FROM ALERT_NOTIFICATION_LOG;

-- 6) Reconciliation configuration and last run proof.
WITH latest_runs AS (
    SELECT
        r.*,
        ROW_NUMBER() OVER (
            PARTITION BY r.CHECK_ID
            ORDER BY r.RUN_TS DESC, r.RUN_ID DESC
        ) AS rn
    FROM OVERWATCH_RECON_RUN r
)
SELECT
    c.CHECK_ID,
    c.CHECK_NAME,
    c.SOURCE_DATABASE,
    c.SOURCE_SCHEMA,
    c.TARGET_DATABASE,
    c.TARGET_SCHEMA,
    c.TABLE_PATTERN,
    c.CHECK_MODE,
    c.SEVERITY,
    c.OWNER,
    c.ENABLED,
    lr.RUN_TS AS LAST_RUN_TS,
    lr.RUN_STATUS AS LAST_RUN_STATUS
FROM OVERWATCH_RECON_CONFIG c
LEFT JOIN latest_runs lr
  ON lr.CHECK_ID = c.CHECK_ID
 AND lr.rn = 1
ORDER BY c.ENABLED DESC, c.SEVERITY, c.CHECK_NAME;

-- 7) Caller context for privilege troubleshooting.
SELECT
    CURRENT_ACCOUNT() AS CURRENT_ACCOUNT_NAME,
    CURRENT_DATABASE() AS CURRENT_DATABASE_NAME,
    CURRENT_SCHEMA() AS CURRENT_SCHEMA_NAME,
    CURRENT_USER() AS CURRENT_USER_NAME,
    CURRENT_ROLE() AS CURRENT_ROLE_NAME,
    CURRENT_WAREHOUSE() AS CURRENT_WAREHOUSE_NAME;
