-- OVERWATCH Snowflake Mart Setup
-- Purpose:
--   Build the low-cost Snowflake architecture behind the OVERWATCH Streamlit app.
--   Streamlit should read these compact mart tables for history/cost/security
--   pages and reserve live INFORMATION_SCHEMA queries for true operations.
--
-- Run as a role that can:
--   - CREATE DATABASE / SCHEMA / WAREHOUSE / TASK / PROCEDURE
--   - SELECT from SNOWFLAKE.ACCOUNT_USAGE views
--   - MONITOR ACCOUNT for operational metadata
--
-- Cost posture:
--   - XSMALL warehouse, 60-second auto-suspend
--   - transient mart tables for rebuildable data
--   - permanent audit/action tables for evidence
--   - hourly refresh, offset from the top of the hour for ACCOUNT_USAGE latency

-- -----------------------------------------------------------------------------
-- 1. Runtime objects
-- -----------------------------------------------------------------------------

CREATE DATABASE IF NOT EXISTS DBA_MAINT_DB;
CREATE SCHEMA IF NOT EXISTS DBA_MAINT_DB.OVERWATCH;

CREATE WAREHOUSE IF NOT EXISTS OVERWATCH_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  STATEMENT_TIMEOUT_IN_SECONDS = 300
  COMMENT = 'Low-cost warehouse for OVERWATCH metadata mart refreshes.';

USE DATABASE DBA_MAINT_DB;
USE SCHEMA OVERWATCH;

-- -----------------------------------------------------------------------------
-- 2. Configuration and audit tables
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS OVERWATCH_SETTINGS (
  SETTING_NAME        VARCHAR(200) PRIMARY KEY,
  SETTING_VALUE       VARCHAR(4000),
  SETTING_TYPE        VARCHAR(50),
  DESCRIPTION         VARCHAR(1000),
  UPDATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY          VARCHAR(200) DEFAULT CURRENT_USER()
);

MERGE INTO OVERWATCH_SETTINGS tgt
USING (
  SELECT * FROM VALUES
    ('CREDIT_PRICE_USD', '3.68', 'NUMBER', 'Contract credit price used for estimated cost display.'),
    ('AI_CREDIT_PRICE_USD', '2.20', 'NUMBER', 'Cortex AI/token credit price used for estimated AI cost display.'),
    ('MART_QUERY_RETENTION_DAYS', '35', 'NUMBER', 'Rolling window reloaded from ACCOUNT_USAGE query history.'),
    ('DETAIL_RETENTION_DAYS', '30', 'NUMBER', 'Retention for recent query/task/procedure detail marts.'),
    ('AGG_RETENTION_DAYS', '730', 'NUMBER', 'Retention for hourly and daily aggregate marts.'),
    ('SLA_DURATION_MULTIPLIER', '1.5', 'NUMBER', 'Flags task/procedure latest duration over this multiple of historical average.')
) src(SETTING_NAME, SETTING_VALUE, SETTING_TYPE, DESCRIPTION)
ON tgt.SETTING_NAME = src.SETTING_NAME
WHEN MATCHED THEN UPDATE SET
  SETTING_VALUE = tgt.SETTING_VALUE,
  SETTING_TYPE = src.SETTING_TYPE,
  DESCRIPTION = src.DESCRIPTION
WHEN NOT MATCHED THEN INSERT (SETTING_NAME, SETTING_VALUE, SETTING_TYPE, DESCRIPTION)
VALUES (src.SETTING_NAME, src.SETTING_VALUE, src.SETTING_TYPE, src.DESCRIPTION);

CREATE TABLE IF NOT EXISTS OVERWATCH_COMPANY_SCOPE (
  COMPANY              VARCHAR(100) NOT NULL,
  SCOPE_TYPE           VARCHAR(100) NOT NULL,
  SCOPE_PATTERN        VARCHAR(500) NOT NULL,
  MATCH_MODE           VARCHAR(20) DEFAULT 'ILIKE', -- ILIKE, NOT_ILIKE, EQUALS
  ENVIRONMENT          VARCHAR(50),
  IS_ACTIVE            BOOLEAN DEFAULT TRUE,
  NOTES                VARCHAR(1000),
  CREATED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CREATED_BY           VARCHAR(200) DEFAULT CURRENT_USER()
);

MERGE INTO OVERWATCH_COMPANY_SCOPE tgt
USING (
  SELECT * FROM VALUES
    ('ALFA',   'WAREHOUSE', 'WH_TRXS_%',             'NOT_ILIKE', NULL, 'Exclude Trexis warehouses from ALFA.'),
    ('ALFA',   'DATABASE',  'TRXS_%',                'NOT_ILIKE', NULL, 'Exclude Trexis databases from ALFA.'),
    ('ALFA',   'DATABASE',  'ALFA%',                 'ILIKE',     NULL, 'ALFA database naming convention.'),
    ('ALFA',   'DATABASE',  'ADMIN',                 'ILIKE',     NULL, 'Shared admin database used by ALFA DBAs.'),
    ('ALFA',   'DATABASE',  'ALFA_EDW_PROD',         'EQUALS',    'PROD', 'ALFA production EDW database.'),
    ('ALFA',   'DATABASE',  'ALFA_EDW_DEV',          'EQUALS',    'ALFA_EDW_DEV', 'ALFA development EDW database.'),
    ('ALFA',   'DATABASE',  'ALFA_EDW_SAN',          'EQUALS',    'ALFA_EDW_SAN', 'ALFA sandbox EDW database.'),
    ('ALFA',   'DATABASE',  'ALFA_EDW_PHX',          'EQUALS',    'ALFA_EDW_PHX', 'ALFA PHX EDW database.'),
    ('ALFA',   'DATABASE',  'ALFA_EDW_SEA',          'EQUALS',    'ALFA_EDW_SEA', 'ALFA SEA EDW database.'),
    ('ALFA',   'DATABASE',  'ALFA_EDW_SIT',          'EQUALS',    'ALFA_EDW_SIT', 'ALFA SIT EDW database.'),
    ('Trexis', 'WAREHOUSE', 'WH_TRXS_%',             'ILIKE',     NULL, 'Trexis warehouses.'),
    ('Trexis', 'DATABASE',  'TRXS_%',                'ILIKE',     NULL, 'Trexis databases.')
) src(COMPANY, SCOPE_TYPE, SCOPE_PATTERN, MATCH_MODE, ENVIRONMENT, NOTES)
ON tgt.COMPANY = src.COMPANY
AND tgt.SCOPE_TYPE = src.SCOPE_TYPE
AND tgt.SCOPE_PATTERN = src.SCOPE_PATTERN
AND tgt.MATCH_MODE = src.MATCH_MODE
WHEN NOT MATCHED THEN INSERT (COMPANY, SCOPE_TYPE, SCOPE_PATTERN, MATCH_MODE, ENVIRONMENT, NOTES)
VALUES (src.COMPANY, src.SCOPE_TYPE, src.SCOPE_PATTERN, src.MATCH_MODE, src.ENVIRONMENT, src.NOTES);

CREATE OR REPLACE FUNCTION OVERWATCH_DATABASE_ENVIRONMENT(DATABASE_NAME VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
  CASE
    WHEN UPPER(DATABASE_NAME) = 'ALFA_EDW_PROD' THEN 'PROD'
    WHEN UPPER(DATABASE_NAME) = 'ALFA_EDW_DEV' THEN 'ALFA_EDW_DEV'
    WHEN UPPER(DATABASE_NAME) = 'ALFA_EDW_SAN' THEN 'ALFA_EDW_SAN'
    WHEN UPPER(DATABASE_NAME) = 'ALFA_EDW_PHX' THEN 'ALFA_EDW_PHX'
    WHEN UPPER(DATABASE_NAME) = 'ALFA_EDW_SEA' THEN 'ALFA_EDW_SEA'
    WHEN UPPER(DATABASE_NAME) = 'ALFA_EDW_SIT' THEN 'ALFA_EDW_SIT'
    WHEN DATABASE_NAME ILIKE 'ALFA_EDW_%' THEN 'Other ALFA Non-Prod'
    WHEN DATABASE_NAME IS NULL THEN 'No Database Context'
    ELSE 'Other / Shared'
  END
$$;

CREATE TABLE IF NOT EXISTS OVERWATCH_LOAD_AUDIT (
  LOAD_ID              NUMBER AUTOINCREMENT PRIMARY KEY,
  LOAD_NAME            VARCHAR(200),
  LOAD_STARTED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  LOAD_FINISHED_AT     TIMESTAMP_NTZ,
  STATUS               VARCHAR(40),
  ROWS_LOADED          NUMBER,
  MESSAGE              VARCHAR(4000)
);

CREATE TABLE IF NOT EXISTS OVERWATCH_ADMIN_ACTION_AUDIT (
  ACTION_ID            NUMBER AUTOINCREMENT PRIMARY KEY,
  ACTION_TS            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  COMPANY              VARCHAR(100),
  ENVIRONMENT          VARCHAR(50),
  APP_USER             VARCHAR(200),
  SNOWFLAKE_USER       VARCHAR(200),
  SNOWFLAKE_ROLE       VARCHAR(200),
  ACTION_TYPE          VARCHAR(100),
  TARGET_OBJECT        VARCHAR(1000),
  SQL_TEXT             VARCHAR,
  SQL_HASH             VARCHAR(80),
  CONFIRMATION_TEXT    VARCHAR(1000),
  CONTROL_CONTEXT      VARCHAR(4000),
  RESULT_STATUS        VARCHAR(40),
  RESULT_MESSAGE       VARCHAR(4000)
);

CREATE TABLE IF NOT EXISTS OVERWATCH_USAGE_LOG (
  RUN_ID               NUMBER AUTOINCREMENT PRIMARY KEY,
  LOG_TIME             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  SF_USER              VARCHAR(200),
  SF_ROLE              VARCHAR(200),
  COMPANY_VIEW         VARCHAR(100),
  SECTION              VARCHAR(200),
  QUERY_DURATION_MS    NUMBER,
  APP_VERSION          VARCHAR(20) DEFAULT '3.0',
  SESSION_ID           VARCHAR(200),
  EVENT_TYPE           VARCHAR(50) DEFAULT 'SECTION_LOAD',
  QUERY_HASH           VARCHAR(80),
  CACHE_KEY            VARCHAR(300),
  CACHE_TIER           VARCHAR(50),
  ROW_COUNT            NUMBER,
  RESULT_MB            NUMBER(18,4),
  USED_CACHE           BOOLEAN,
  MESSAGE              VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS OVERWATCH_ACTION_QUEUE (
  ACTION_ID                 VARCHAR(64) PRIMARY KEY,
  CREATED_AT                TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT                TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  SOURCE                    VARCHAR(100),
  CATEGORY                  VARCHAR(100),
  SEVERITY                  VARCHAR(20),
  ENTITY_TYPE               VARCHAR(100),
  ENTITY_NAME               VARCHAR(500),
  OWNER                     VARCHAR(200),
  STATUS                    VARCHAR(40) DEFAULT 'New',
  FINDING                   VARCHAR(4000),
  RECOMMENDED_ACTION        VARCHAR(4000),
  EST_MONTHLY_SAVINGS       FLOAT,
  GENERATED_SQL_FIX         VARCHAR(8000),
  PROOF_QUERY               VARCHAR(8000),
  COMPANY                   VARCHAR(100),
  ENVIRONMENT               VARCHAR(100),
  TICKET_ID                 VARCHAR(200),
  APPROVER                  VARCHAR(200),
  DUE_DATE                  DATE,
  VERIFICATION_STATUS       VARCHAR(40) DEFAULT 'Pending',
  VERIFICATION_NOTES        VARCHAR(4000),
  VERIFICATION_QUERY        VARCHAR(8000),
  VERIFICATION_RESULT       VARCHAR(8000),
  BASELINE_VALUE            FLOAT,
  CURRENT_VALUE             FLOAT,
  MEASURED_DELTA            FLOAT,
  VERIFIED_BY               VARCHAR(200),
  VERIFIED_AT               TIMESTAMP_NTZ,
  ACKNOWLEDGED_BY           VARCHAR(200),
  ACKNOWLEDGED_AT           TIMESTAMP_NTZ,
  FIXED_BY                  VARCHAR(200),
  FIXED_AT                  TIMESTAMP_NTZ,
  IGNORED_REASON            VARCHAR(2000),
  LAST_SEEN_AT              TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  SEEN_COUNT                NUMBER DEFAULT 1
);

ALTER TABLE OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS ENVIRONMENT VARCHAR(100);
ALTER TABLE OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS TICKET_ID VARCHAR(200);
ALTER TABLE OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS APPROVER VARCHAR(200);
ALTER TABLE OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS DUE_DATE DATE;
ALTER TABLE OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS VERIFICATION_STATUS VARCHAR(40) DEFAULT 'Pending';
ALTER TABLE OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS VERIFICATION_NOTES VARCHAR(4000);
ALTER TABLE OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS VERIFICATION_QUERY VARCHAR(8000);
ALTER TABLE OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS VERIFICATION_RESULT VARCHAR(8000);
ALTER TABLE OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS BASELINE_VALUE FLOAT;
ALTER TABLE OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS CURRENT_VALUE FLOAT;
ALTER TABLE OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS MEASURED_DELTA FLOAT;
ALTER TABLE OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS VERIFIED_BY VARCHAR(200);
ALTER TABLE OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS VERIFIED_AT TIMESTAMP_NTZ;

CREATE TABLE IF NOT EXISTS OVERWATCH_ALERTS (
  ALERT_ID             NUMBER AUTOINCREMENT PRIMARY KEY,
  ALERT_TS             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  COMPANY              VARCHAR(100),
  CATEGORY             VARCHAR(100),
  SEVERITY             VARCHAR(20),
  ENTITY_NAME          VARCHAR(500),
  MESSAGE              VARCHAR(4000),
  PROOF_QUERY          VARCHAR(8000),
  DELIVERY_TARGET      VARCHAR(500),
  DELIVERY_STATUS      VARCHAR(100),
  ACKNOWLEDGED_BY      VARCHAR(200),
  ACKNOWLEDGED_AT      TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS OVERWATCH_ROI_LOG (
  ROI_ID               NUMBER AUTOINCREMENT PRIMARY KEY,
  LOGGED_DATE          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  LOGGED_BY            VARCHAR(200),
  CATEGORY             VARCHAR(100),
  DESCRIPTION          VARCHAR(1000),
  ENTITY               VARCHAR(500),
  BASELINE_CREDITS     FLOAT,
  CURRENT_CREDITS      FLOAT,
  SAVINGS_CREDITS      FLOAT,
  SAVINGS_MONTHLY      FLOAT,
  VERIFIED             BOOLEAN DEFAULT FALSE,
  COMPANY              VARCHAR(100),
  NOTES                VARCHAR(2000)
);

-- -----------------------------------------------------------------------------
-- 3. Transient mart tables
-- -----------------------------------------------------------------------------

CREATE TRANSIENT TABLE IF NOT EXISTS FACT_WAREHOUSE_HOURLY (
  HOUR_START                   TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  WAREHOUSE_NAME               VARCHAR(300),
  CREDITS_USED                 NUMBER(18,6),
  CREDITS_USED_COMPUTE         NUMBER(18,6),
  CREDITS_USED_CLOUD_SERVICES  NUMBER(18,6),
  EST_COST_USD                 NUMBER(18,2),
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TRANSIENT TABLE IF NOT EXISTS FACT_QUERY_HOURLY (
  HOUR_START                   TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  WAREHOUSE_NAME               VARCHAR(300),
  WAREHOUSE_SIZE               VARCHAR(100),
  USER_NAME                    VARCHAR(300),
  ROLE_NAME                    VARCHAR(300),
  DATABASE_NAME                VARCHAR(300),
  ENVIRONMENT                  VARCHAR(100),
  SCHEMA_NAME                  VARCHAR(300),
  QUERY_TYPE                   VARCHAR(100),
  QUERY_COUNT                  NUMBER,
  FAILED_COUNT                 NUMBER,
  AVG_EXECUTION_MS             NUMBER(18,2),
  P95_EXECUTION_MS             NUMBER(18,2),
  TOTAL_ELAPSED_MS             NUMBER,
  TOTAL_QUEUED_MS              NUMBER,
  TOTAL_SPILL_BYTES            NUMBER,
  TOTAL_BYTES_SCANNED          NUMBER,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TRANSIENT TABLE IF NOT EXISTS FACT_QUERY_DETAIL_RECENT (
  QUERY_ID                     VARCHAR(200),
  START_TIME                   TIMESTAMP_NTZ,
  END_TIME                     TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  WAREHOUSE_NAME               VARCHAR(300),
  USER_NAME                    VARCHAR(300),
  ROLE_NAME                    VARCHAR(300),
  DATABASE_NAME                VARCHAR(300),
  ENVIRONMENT                  VARCHAR(100),
  SCHEMA_NAME                  VARCHAR(300),
  QUERY_TYPE                   VARCHAR(100),
  EXECUTION_STATUS             VARCHAR(100),
  WAREHOUSE_SIZE               VARCHAR(100),
  ERROR_CODE                   VARCHAR(100),
  ERROR_MESSAGE                VARCHAR,
  TOTAL_ELAPSED_TIME           NUMBER,
  COMPILATION_TIME             NUMBER,
  EXECUTION_TIME               NUMBER,
  QUEUED_OVERLOAD_TIME         NUMBER,
  QUEUED_PROVISIONING_TIME     NUMBER,
  QUEUED_REPAIR_TIME           NUMBER,
  TRANSACTION_BLOCKED_TIME     NUMBER,
  BYTES_SCANNED                NUMBER,
  BYTES_SPILLED_TO_LOCAL_STORAGE NUMBER,
  BYTES_SPILLED_TO_REMOTE_STORAGE NUMBER,
  PARTITIONS_SCANNED           NUMBER,
  PARTITIONS_TOTAL             NUMBER,
  ROWS_PRODUCED                NUMBER,
  QUERY_HASH                   VARCHAR(300),
  QUERY_TEXT                   VARCHAR,
  QUERY_TAG                    VARCHAR,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TRANSIENT TABLE IF NOT EXISTS FACT_TASK_RUN (
  SCHEDULED_TIME               TIMESTAMP_NTZ,
  COMPLETED_TIME               TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  DATABASE_NAME                VARCHAR(300),
  ENVIRONMENT                  VARCHAR(100),
  SCHEMA_NAME                  VARCHAR(300),
  ROOT_TASK_NAME               VARCHAR(500),
  TASK_NAME                    VARCHAR(500),
  STATE                        VARCHAR(100),
  QUERY_ID                     VARCHAR(200),
  ERROR_CODE                   VARCHAR(100),
  ERROR_MESSAGE                VARCHAR,
  DURATION_MS                  NUMBER,
  WAREHOUSE_NAME               VARCHAR(300),
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TRANSIENT TABLE IF NOT EXISTS DIM_TASK_SNAPSHOT (
  SNAPSHOT_TS                  TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  DATABASE_NAME                VARCHAR(300),
  ENVIRONMENT                  VARCHAR(100),
  SCHEMA_NAME                  VARCHAR(300),
  TASK_NAME                    VARCHAR(500),
  ROOT_TASK_NAME               VARCHAR(500),
  STATE                        VARCHAR(100),
  SCHEDULE                     VARCHAR,
  WAREHOUSE_NAME               VARCHAR(300),
  PREDECESSORS                 VARIANT,
  DEFINITION                   VARCHAR,
  PROCEDURE_NAME               VARCHAR
);

CREATE TRANSIENT TABLE IF NOT EXISTS DIM_PROCEDURE_SNAPSHOT (
  SNAPSHOT_TS                  TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  DATABASE_NAME                VARCHAR(300),
  ENVIRONMENT                  VARCHAR(100),
  SCHEMA_NAME                  VARCHAR(300),
  PROCEDURE_NAME               VARCHAR(500),
  OWNER_ROLE                   VARCHAR(300),
  PROCEDURE_LANGUAGE           VARCHAR(100),
  ARGUMENT_SIGNATURE           VARCHAR,
  LAST_ALTERED                 TIMESTAMP_NTZ,
  IS_ORPHAN_CANDIDATE          BOOLEAN
);

CREATE TRANSIENT TABLE IF NOT EXISTS FACT_PROCEDURE_RUN (
  START_TIME                   TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  DATABASE_NAME                VARCHAR(300),
  ENVIRONMENT                  VARCHAR(100),
  PROCEDURE_NAME               VARCHAR(500),
  CALL_QUERY_ID                VARCHAR(200),
  ROOT_QUERY_ID                VARCHAR(200),
  CHILD_QUERY_COUNT            NUMBER,
  TOTAL_DURATION_MS            NUMBER,
  EST_CREDITS                  NUMBER(18,6),
  EST_COST_USD                 NUMBER(18,2),
  STATUS                       VARCHAR(100),
  ERROR_MESSAGE                VARCHAR,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TRANSIENT TABLE IF NOT EXISTS FACT_LOGIN_DAILY (
  LOGIN_DATE                   DATE,
  COMPANY                      VARCHAR(100),
  USER_NAME                    VARCHAR(300),
  CLIENT_IP                    VARCHAR(300),
  REPORTED_CLIENT_TYPE         VARCHAR(300),
  REPORTED_CLIENT_VERSION      VARCHAR(300),
  SUCCESS_COUNT                NUMBER,
  FAILURE_COUNT                NUMBER,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TRANSIENT TABLE IF NOT EXISTS FACT_OBJECT_CHANGE (
  START_TIME                   TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  QUERY_ID                     VARCHAR(200),
  USER_NAME                    VARCHAR(300),
  ROLE_NAME                    VARCHAR(300),
  DATABASE_NAME                VARCHAR(300),
  ENVIRONMENT                  VARCHAR(100),
  SCHEMA_NAME                  VARCHAR(300),
  CHANGE_CATEGORY              VARCHAR(100),
  QUERY_TYPE                   VARCHAR(100),
  QUERY_TAG                    VARCHAR,
  QUERY_TEXT                   VARCHAR,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TRANSIENT TABLE IF NOT EXISTS FACT_GRANT_DAILY (
  SNAPSHOT_DATE                DATE,
  COMPANY                      VARCHAR(100),
  ROLE_NAME                    VARCHAR(300),
  GRANTEE_NAME                 VARCHAR(300),
  GRANTED_TO                   VARCHAR(100),
  CREATED_ON                   TIMESTAMP_NTZ,
  DELETED_ON                   TIMESTAMP_NTZ,
  GRANT_COUNT                  NUMBER,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Existing mart deployments are upgraded in place. Snowflake ignores the add
-- when the column is already present.
ALTER TABLE FACT_QUERY_HOURLY ADD COLUMN IF NOT EXISTS WAREHOUSE_SIZE VARCHAR(100);
ALTER TABLE FACT_QUERY_HOURLY ADD COLUMN IF NOT EXISTS ENVIRONMENT VARCHAR(100);
ALTER TABLE FACT_QUERY_DETAIL_RECENT ADD COLUMN IF NOT EXISTS WAREHOUSE_SIZE VARCHAR(100);
ALTER TABLE FACT_QUERY_DETAIL_RECENT ADD COLUMN IF NOT EXISTS ENVIRONMENT VARCHAR(100);
ALTER TABLE FACT_QUERY_DETAIL_RECENT ADD COLUMN IF NOT EXISTS COMPILATION_TIME NUMBER;
ALTER TABLE FACT_QUERY_DETAIL_RECENT ADD COLUMN IF NOT EXISTS EXECUTION_TIME NUMBER;
ALTER TABLE FACT_QUERY_DETAIL_RECENT ADD COLUMN IF NOT EXISTS TRANSACTION_BLOCKED_TIME NUMBER;
ALTER TABLE FACT_QUERY_DETAIL_RECENT ADD COLUMN IF NOT EXISTS BYTES_SPILLED_TO_LOCAL_STORAGE NUMBER;
ALTER TABLE FACT_QUERY_DETAIL_RECENT ADD COLUMN IF NOT EXISTS PARTITIONS_SCANNED NUMBER;
ALTER TABLE FACT_QUERY_DETAIL_RECENT ADD COLUMN IF NOT EXISTS PARTITIONS_TOTAL NUMBER;
ALTER TABLE FACT_QUERY_DETAIL_RECENT ADD COLUMN IF NOT EXISTS ROWS_PRODUCED NUMBER;
ALTER TABLE FACT_QUERY_DETAIL_RECENT ADD COLUMN IF NOT EXISTS QUERY_HASH VARCHAR(300);
ALTER TABLE FACT_TASK_RUN ADD COLUMN IF NOT EXISTS ENVIRONMENT VARCHAR(100);
ALTER TABLE DIM_TASK_SNAPSHOT ADD COLUMN IF NOT EXISTS ENVIRONMENT VARCHAR(100);
ALTER TABLE DIM_PROCEDURE_SNAPSHOT ADD COLUMN IF NOT EXISTS ENVIRONMENT VARCHAR(100);
ALTER TABLE FACT_PROCEDURE_RUN ADD COLUMN IF NOT EXISTS DATABASE_NAME VARCHAR(300);
ALTER TABLE FACT_PROCEDURE_RUN ADD COLUMN IF NOT EXISTS ENVIRONMENT VARCHAR(100);
ALTER TABLE FACT_OBJECT_CHANGE ADD COLUMN IF NOT EXISTS QUERY_TAG VARCHAR;
ALTER TABLE FACT_OBJECT_CHANGE ADD COLUMN IF NOT EXISTS ENVIRONMENT VARCHAR(100);
ALTER TABLE FACT_GRANT_DAILY ADD COLUMN IF NOT EXISTS CREATED_ON TIMESTAMP_NTZ;

CREATE TRANSIENT TABLE IF NOT EXISTS FACT_STORAGE_DAILY (
  SNAPSHOT_DATE                DATE,
  COMPANY                      VARCHAR(100),
  DATABASE_NAME                VARCHAR(300),
  ENVIRONMENT                  VARCHAR(100),
  ACTIVE_BYTES                 NUMBER,
  TIME_TRAVEL_BYTES            NUMBER,
  FAILSAFE_BYTES               NUMBER,
  RETAINED_FOR_CLONE_BYTES     NUMBER,
  EST_STORAGE_TB               NUMBER(18,4),
  EST_COST_USD                 NUMBER(18,2),
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TRANSIENT TABLE IF NOT EXISTS DIM_TABLE_SNAPSHOT (
  SNAPSHOT_TS                  TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  DATABASE_NAME                VARCHAR(300),
  ENVIRONMENT                  VARCHAR(100),
  SCHEMA_NAME                  VARCHAR(300),
  TABLE_NAME                   VARCHAR(500),
  TABLE_TYPE                   VARCHAR(100),
  ROW_COUNT                    NUMBER,
  BYTES                        NUMBER,
  LAST_ALTERED                 TIMESTAMP_LTZ,
  CREATED                      TIMESTAMP_LTZ,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TRANSIENT TABLE IF NOT EXISTS FACT_COPY_LOAD_DAILY (
  LOAD_DATE                    DATE,
  COMPANY                      VARCHAR(100),
  DATABASE_NAME                VARCHAR(300),
  ENVIRONMENT                  VARCHAR(100),
  SCHEMA_NAME                  VARCHAR(300),
  TABLE_NAME                   VARCHAR(500),
  STATUS                       VARCHAR(100),
  FILE_COUNT                   NUMBER,
  ROW_COUNT                    NUMBER,
  ROW_PARSED                   NUMBER,
  ERROR_COUNT                  NUMBER,
  FILE_SIZE_BYTES              NUMBER,
  BYTES_BILLED                 NUMBER,
  LAST_SEEN                    TIMESTAMP_LTZ,
  LATEST_ERROR                 VARCHAR,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

ALTER TABLE FACT_STORAGE_DAILY ADD COLUMN IF NOT EXISTS ENVIRONMENT VARCHAR(100);
ALTER TABLE DIM_TABLE_SNAPSHOT ADD COLUMN IF NOT EXISTS ENVIRONMENT VARCHAR(100);
ALTER TABLE FACT_COPY_LOAD_DAILY ADD COLUMN IF NOT EXISTS ENVIRONMENT VARCHAR(100);

CREATE TRANSIENT TABLE IF NOT EXISTS FACT_CORTEX_DAILY (
  USAGE_DATE                   DATE,
  COMPANY                      VARCHAR(100),
  USER_ID                      VARCHAR(300),
  SOURCE                       VARCHAR(100),
  CREDITS_USED                 NUMBER(18,6),
  EST_COST_USD                 NUMBER(18,2),
  REQUEST_COUNT                NUMBER,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TRANSIENT TABLE IF NOT EXISTS FACT_MONITORING_COST_DAILY (
  USAGE_DATE                   DATE,
  COMPANY                      VARCHAR(100),
  COST_COMPONENT               VARCHAR(100),
  CREDITS_USED                 NUMBER(18,6),
  EST_COST_USD                 NUMBER(18,2),
  SOURCE                       VARCHAR(1000),
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TRANSIENT TABLE IF NOT EXISTS MART_DBA_CONTROL_ROOM (
  SNAPSHOT_TS                  TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  HEALTH_SCORE                 NUMBER(5,2),
  FAILED_QUERIES_24H           NUMBER,
  FAILED_TASKS_24H             NUMBER,
  QUEUED_MS_24H                NUMBER,
  CREDITS_24H                  NUMBER(18,6),
  COST_24H_USD                 NUMBER(18,2),
  CORTEX_COST_7D_USD           NUMBER(18,2),
  SECURITY_EVENTS_24H          NUMBER,
  OBJECT_CHANGES_24H           NUMBER,
  TOP_RISK                     VARCHAR(1000),
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- -----------------------------------------------------------------------------
-- 4. Load procedures
-- -----------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE SP_OVERWATCH_PRUNE()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
  detail_days NUMBER DEFAULT 30;
  agg_days NUMBER DEFAULT 730;
BEGIN
  SELECT TRY_TO_NUMBER(SETTING_VALUE) INTO :detail_days
  FROM OVERWATCH_SETTINGS
  WHERE SETTING_NAME = 'DETAIL_RETENTION_DAYS';

  SELECT TRY_TO_NUMBER(SETTING_VALUE) INTO :agg_days
  FROM OVERWATCH_SETTINGS
  WHERE SETTING_NAME = 'AGG_RETENTION_DAYS';

  detail_days := COALESCE(detail_days, 30);
  agg_days := COALESCE(agg_days, 730);

  DELETE FROM FACT_QUERY_DETAIL_RECENT WHERE START_TIME < DATEADD('DAY', -1 * :detail_days, CURRENT_TIMESTAMP());
  DELETE FROM FACT_TASK_RUN WHERE SCHEDULED_TIME < DATEADD('DAY', -1 * :detail_days, CURRENT_TIMESTAMP());
  DELETE FROM FACT_PROCEDURE_RUN WHERE START_TIME < DATEADD('DAY', -1 * :detail_days, CURRENT_TIMESTAMP());
  DELETE FROM FACT_WAREHOUSE_HOURLY WHERE HOUR_START < DATEADD('DAY', -1 * :agg_days, CURRENT_TIMESTAMP());
  DELETE FROM FACT_QUERY_HOURLY WHERE HOUR_START < DATEADD('DAY', -1 * :agg_days, CURRENT_TIMESTAMP());
  DELETE FROM FACT_LOGIN_DAILY WHERE LOGIN_DATE < DATEADD('DAY', -1 * :agg_days, CURRENT_DATE());
  DELETE FROM FACT_OBJECT_CHANGE WHERE START_TIME < DATEADD('DAY', -1 * :agg_days, CURRENT_TIMESTAMP());
  DELETE FROM FACT_GRANT_DAILY WHERE SNAPSHOT_DATE < DATEADD('DAY', -1 * :agg_days, CURRENT_DATE());
  DELETE FROM FACT_STORAGE_DAILY WHERE SNAPSHOT_DATE < DATEADD('DAY', -1 * :agg_days, CURRENT_DATE());
  DELETE FROM DIM_TABLE_SNAPSHOT WHERE SNAPSHOT_TS < DATEADD('DAY', -1 * :agg_days, CURRENT_TIMESTAMP());
  DELETE FROM FACT_COPY_LOAD_DAILY WHERE LOAD_DATE < DATEADD('DAY', -1 * :agg_days, CURRENT_DATE());
  DELETE FROM FACT_CORTEX_DAILY WHERE USAGE_DATE < DATEADD('DAY', -1 * :agg_days, CURRENT_DATE());
  DELETE FROM FACT_MONITORING_COST_DAILY WHERE USAGE_DATE < DATEADD('DAY', -1 * :agg_days, CURRENT_DATE());

  RETURN 'OVERWATCH prune complete';
END;
$$;

CREATE OR REPLACE PROCEDURE SP_OVERWATCH_LOAD_HOURLY()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
  credit_price NUMBER(18,4) DEFAULT 3.68;
  started_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP();
  rows_loaded NUMBER DEFAULT 0;
BEGIN
  SELECT TRY_TO_NUMBER(SETTING_VALUE) INTO :credit_price
  FROM OVERWATCH_SETTINGS
  WHERE SETTING_NAME = 'CREDIT_PRICE_USD';

  credit_price := COALESCE(credit_price, 3.68);

  INSERT INTO OVERWATCH_LOAD_AUDIT (LOAD_NAME, LOAD_STARTED_AT, STATUS, MESSAGE)
  VALUES ('SP_OVERWATCH_LOAD_HOURLY', :started_at, 'RUNNING', 'Started hourly mart load.');

  DELETE FROM FACT_WAREHOUSE_HOURLY
  WHERE HOUR_START >= DATEADD('DAY', -35, CURRENT_TIMESTAMP());

  INSERT INTO FACT_WAREHOUSE_HOURLY (
    HOUR_START, COMPANY, WAREHOUSE_NAME, CREDITS_USED,
    CREDITS_USED_COMPUTE, CREDITS_USED_CLOUD_SERVICES, EST_COST_USD
  )
  SELECT
    DATE_TRUNC('HOUR', START_TIME) AS HOUR_START,
    CASE WHEN WAREHOUSE_NAME ILIKE 'WH_TRXS_%' THEN 'Trexis' ELSE 'ALFA' END AS COMPANY,
    WAREHOUSE_NAME,
    SUM(CREDITS_USED) AS CREDITS_USED,
    SUM(CREDITS_USED_COMPUTE) AS CREDITS_USED_COMPUTE,
    SUM(CREDITS_USED_CLOUD_SERVICES) AS CREDITS_USED_CLOUD_SERVICES,
    ROUND(SUM(CREDITS_USED) * :credit_price, 2) AS EST_COST_USD
  FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
  WHERE START_TIME >= DATEADD('DAY', -35, CURRENT_TIMESTAMP())
  GROUP BY 1, 2, 3;

  rows_loaded := rows_loaded + SQLROWCOUNT;

  DELETE FROM FACT_QUERY_HOURLY
  WHERE HOUR_START >= DATEADD('DAY', -35, CURRENT_TIMESTAMP());

  INSERT INTO FACT_QUERY_HOURLY (
    HOUR_START, COMPANY, WAREHOUSE_NAME, WAREHOUSE_SIZE, USER_NAME, ROLE_NAME, DATABASE_NAME,
    ENVIRONMENT, SCHEMA_NAME, QUERY_TYPE, QUERY_COUNT, FAILED_COUNT, AVG_EXECUTION_MS,
    P95_EXECUTION_MS, TOTAL_ELAPSED_MS, TOTAL_QUEUED_MS, TOTAL_SPILL_BYTES,
    TOTAL_BYTES_SCANNED
  )
  SELECT
    DATE_TRUNC('HOUR', START_TIME) AS HOUR_START,
    CASE
      WHEN WAREHOUSE_NAME ILIKE 'WH_TRXS_%' OR DATABASE_NAME ILIKE 'TRXS_%' OR USER_NAME ILIKE 'TRXS_%' THEN 'Trexis'
      ELSE 'ALFA'
    END AS COMPANY,
    WAREHOUSE_NAME,
    WAREHOUSE_SIZE,
    USER_NAME,
    ROLE_NAME,
    DATABASE_NAME,
    OVERWATCH_DATABASE_ENVIRONMENT(DATABASE_NAME) AS ENVIRONMENT,
    SCHEMA_NAME,
    QUERY_TYPE,
    COUNT(*) AS QUERY_COUNT,
    SUM(IFF(UPPER(COALESCE(EXECUTION_STATUS, '')) IN ('FAILED_WITH_ERROR', 'FAILED'), 1, 0)) AS FAILED_COUNT,
    AVG(TOTAL_ELAPSED_TIME) AS AVG_EXECUTION_MS,
    APPROX_PERCENTILE(TOTAL_ELAPSED_TIME, 0.95) AS P95_EXECUTION_MS,
    SUM(TOTAL_ELAPSED_TIME) AS TOTAL_ELAPSED_MS,
    SUM(COALESCE(QUEUED_OVERLOAD_TIME, 0) + COALESCE(QUEUED_PROVISIONING_TIME, 0) + COALESCE(QUEUED_REPAIR_TIME, 0)) AS TOTAL_QUEUED_MS,
    SUM(COALESCE(BYTES_SPILLED_TO_REMOTE_STORAGE, 0)) AS TOTAL_SPILL_BYTES,
    SUM(COALESCE(BYTES_SCANNED, 0)) AS TOTAL_BYTES_SCANNED
  FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
  WHERE START_TIME >= DATEADD('DAY', -35, CURRENT_TIMESTAMP())
  GROUP BY 1,2,3,4,5,6,7,8,9,10;

  rows_loaded := rows_loaded + SQLROWCOUNT;

  DELETE FROM DIM_TASK_SNAPSHOT
  WHERE SNAPSHOT_TS >= DATEADD('HOUR', -2, CURRENT_TIMESTAMP());

  INSERT INTO DIM_TASK_SNAPSHOT (
    SNAPSHOT_TS, COMPANY, DATABASE_NAME, ENVIRONMENT, SCHEMA_NAME, TASK_NAME,
    ROOT_TASK_NAME, STATE, SCHEDULE, WAREHOUSE_NAME, PREDECESSORS,
    DEFINITION, PROCEDURE_NAME
  )
  SELECT
    CURRENT_TIMESTAMP() AS SNAPSHOT_TS,
    CASE WHEN TASK_DATABASE ILIKE 'TRXS_%' OR TASK_NAME ILIKE 'TRXS_%' THEN 'Trexis' ELSE 'ALFA' END AS COMPANY,
    TASK_DATABASE AS DATABASE_NAME,
    OVERWATCH_DATABASE_ENVIRONMENT(TASK_DATABASE) AS ENVIRONMENT,
    TASK_SCHEMA AS SCHEMA_NAME,
    TASK_NAME,
    IFF(COALESCE(ARRAY_SIZE(PREDECESSORS), 0) = 0, TASK_NAME, NULL) AS ROOT_TASK_NAME,
    STATE,
    SCHEDULE,
    WAREHOUSE AS WAREHOUSE_NAME,
    PREDECESSORS,
    DEFINITION,
    REGEXP_SUBSTR(DEFINITION, 'CALL[[:space:]]+([^[:space:];(]+)', 1, 1, 'ie', 1) AS PROCEDURE_NAME
  FROM SNOWFLAKE.ACCOUNT_USAGE.TASKS
  WHERE DELETED IS NULL;

  rows_loaded := rows_loaded + SQLROWCOUNT;

  DELETE FROM DIM_PROCEDURE_SNAPSHOT
  WHERE SNAPSHOT_TS >= DATEADD('HOUR', -2, CURRENT_TIMESTAMP());

  INSERT INTO DIM_PROCEDURE_SNAPSHOT (
    SNAPSHOT_TS, COMPANY, DATABASE_NAME, ENVIRONMENT, SCHEMA_NAME, PROCEDURE_NAME,
    OWNER_ROLE, PROCEDURE_LANGUAGE, ARGUMENT_SIGNATURE, LAST_ALTERED, IS_ORPHAN_CANDIDATE
  )
  WITH recent_calls AS (
    SELECT DISTINCT UPPER(COALESCE(PROCEDURE_NAME, '')) AS PROCEDURE_NAME
    FROM FACT_PROCEDURE_RUN
    WHERE START_TIME >= DATEADD('DAY', -35, CURRENT_TIMESTAMP())
  )
  SELECT
    CURRENT_TIMESTAMP() AS SNAPSHOT_TS,
    CASE WHEN p.PROCEDURE_CATALOG ILIKE 'TRXS_%' OR p.PROCEDURE_NAME ILIKE 'TRXS_%' THEN 'Trexis' ELSE 'ALFA' END AS COMPANY,
    p.PROCEDURE_CATALOG AS DATABASE_NAME,
    OVERWATCH_DATABASE_ENVIRONMENT(p.PROCEDURE_CATALOG) AS ENVIRONMENT,
    p.PROCEDURE_SCHEMA AS SCHEMA_NAME,
    p.PROCEDURE_NAME,
    p.PROCEDURE_OWNER AS OWNER_ROLE,
    p.PROCEDURE_LANGUAGE AS PROCEDURE_LANGUAGE,
    p.ARGUMENT_SIGNATURE,
    p.LAST_ALTERED,
    IFF(rc.PROCEDURE_NAME IS NULL, TRUE, FALSE) AS IS_ORPHAN_CANDIDATE
  FROM SNOWFLAKE.ACCOUNT_USAGE.PROCEDURES p
  LEFT JOIN recent_calls rc
    ON rc.PROCEDURE_NAME ILIKE '%' || UPPER(p.PROCEDURE_NAME) || '%'
  WHERE p.DELETED IS NULL;

  rows_loaded := rows_loaded + SQLROWCOUNT;

  DELETE FROM FACT_QUERY_DETAIL_RECENT
  WHERE START_TIME >= DATEADD('DAY', -30, CURRENT_TIMESTAMP());

  INSERT INTO FACT_QUERY_DETAIL_RECENT (
    QUERY_ID, START_TIME, END_TIME, COMPANY, WAREHOUSE_NAME, USER_NAME, ROLE_NAME,
    DATABASE_NAME, ENVIRONMENT, SCHEMA_NAME, QUERY_TYPE, EXECUTION_STATUS, ERROR_CODE,
    ERROR_MESSAGE, TOTAL_ELAPSED_TIME, COMPILATION_TIME, EXECUTION_TIME,
    QUEUED_OVERLOAD_TIME, QUEUED_PROVISIONING_TIME, QUEUED_REPAIR_TIME,
    TRANSACTION_BLOCKED_TIME, BYTES_SCANNED, BYTES_SPILLED_TO_LOCAL_STORAGE,
    BYTES_SPILLED_TO_REMOTE_STORAGE, PARTITIONS_SCANNED, PARTITIONS_TOTAL,
    ROWS_PRODUCED, QUERY_HASH, WAREHOUSE_SIZE, QUERY_TEXT, QUERY_TAG
  )
  SELECT
    QUERY_ID,
    START_TIME,
    END_TIME,
    CASE
      WHEN WAREHOUSE_NAME ILIKE 'WH_TRXS_%' OR DATABASE_NAME ILIKE 'TRXS_%' OR USER_NAME ILIKE 'TRXS_%' THEN 'Trexis'
      ELSE 'ALFA'
    END AS COMPANY,
    WAREHOUSE_NAME,
    USER_NAME,
    ROLE_NAME,
    DATABASE_NAME,
    OVERWATCH_DATABASE_ENVIRONMENT(DATABASE_NAME) AS ENVIRONMENT,
    SCHEMA_NAME,
    QUERY_TYPE,
    EXECUTION_STATUS,
    ERROR_CODE,
    ERROR_MESSAGE,
    TOTAL_ELAPSED_TIME,
    COMPILATION_TIME,
    EXECUTION_TIME,
    QUEUED_OVERLOAD_TIME,
    QUEUED_PROVISIONING_TIME,
    QUEUED_REPAIR_TIME,
    TRANSACTION_BLOCKED_TIME,
    BYTES_SCANNED,
    BYTES_SPILLED_TO_LOCAL_STORAGE,
    BYTES_SPILLED_TO_REMOTE_STORAGE,
    PARTITIONS_SCANNED,
    PARTITIONS_TOTAL,
    ROWS_PRODUCED,
    QUERY_HASH,
    WAREHOUSE_SIZE,
    QUERY_TEXT,
    QUERY_TAG
  FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
  WHERE START_TIME >= DATEADD('DAY', -30, CURRENT_TIMESTAMP())
    AND (
      UPPER(COALESCE(EXECUTION_STATUS, '')) IN ('FAILED_WITH_ERROR', 'FAILED')
      OR COALESCE(TOTAL_ELAPSED_TIME, 0) >= 300000
      OR COALESCE(QUEUED_OVERLOAD_TIME, 0) + COALESCE(QUEUED_PROVISIONING_TIME, 0) + COALESCE(QUEUED_REPAIR_TIME, 0) > 0
      OR COALESCE(BYTES_SPILLED_TO_REMOTE_STORAGE, 0) > 0
      OR QUERY_TAG ILIKE 'OVERWATCH:%'
    );

  rows_loaded := rows_loaded + SQLROWCOUNT;

  DELETE FROM FACT_OBJECT_CHANGE
  WHERE START_TIME >= DATEADD('DAY', -35, CURRENT_TIMESTAMP());

  INSERT INTO FACT_OBJECT_CHANGE (
    START_TIME, COMPANY, QUERY_ID, USER_NAME, ROLE_NAME, DATABASE_NAME,
    ENVIRONMENT, SCHEMA_NAME, CHANGE_CATEGORY, QUERY_TYPE, QUERY_TAG, QUERY_TEXT
  )
  SELECT
    START_TIME,
    CASE
      WHEN DATABASE_NAME ILIKE 'TRXS_%' OR USER_NAME ILIKE 'TRXS_%' THEN 'Trexis'
      ELSE 'ALFA'
    END AS COMPANY,
    QUERY_ID,
    USER_NAME,
    ROLE_NAME,
    DATABASE_NAME,
    OVERWATCH_DATABASE_ENVIRONMENT(DATABASE_NAME) AS ENVIRONMENT,
    SCHEMA_NAME,
    CASE
      WHEN QUERY_TEXT ILIKE 'GRANT%' OR QUERY_TEXT ILIKE 'REVOKE%' THEN 'GRANT'
      WHEN QUERY_TEXT ILIKE '%MASKING POLICY%' OR QUERY_TEXT ILIKE '%ROW ACCESS POLICY%' OR QUERY_TEXT ILIKE '% TAG %' THEN 'POLICY'
      WHEN QUERY_TEXT ILIKE '%OWNERSHIP%' THEN 'OWNER'
      WHEN QUERY_TEXT ILIKE 'DROP%' THEN 'DROP'
      WHEN QUERY_TEXT ILIKE 'ALTER%' THEN 'ALTER'
      WHEN QUERY_TEXT ILIKE 'CREATE%' THEN 'CREATE'
      ELSE 'OTHER'
    END AS CHANGE_CATEGORY,
    QUERY_TYPE,
    QUERY_TAG,
    QUERY_TEXT
  FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
  WHERE START_TIME >= DATEADD('DAY', -35, CURRENT_TIMESTAMP())
    AND (
      QUERY_TEXT ILIKE 'CREATE%'
      OR QUERY_TEXT ILIKE 'ALTER%'
      OR QUERY_TEXT ILIKE 'DROP%'
      OR QUERY_TEXT ILIKE 'GRANT%'
      OR QUERY_TEXT ILIKE 'REVOKE%'
    );

  rows_loaded := rows_loaded + SQLROWCOUNT;

  BEGIN
    DELETE FROM FACT_TASK_RUN
    WHERE SCHEDULED_TIME >= DATEADD('DAY', -30, CURRENT_TIMESTAMP());

    INSERT INTO FACT_TASK_RUN (
      SCHEDULED_TIME, COMPLETED_TIME, COMPANY, DATABASE_NAME, ENVIRONMENT, SCHEMA_NAME,
      ROOT_TASK_NAME, TASK_NAME, STATE, QUERY_ID, ERROR_CODE, ERROR_MESSAGE,
      DURATION_MS, WAREHOUSE_NAME
    )
    SELECT
      SCHEDULED_TIME,
      COMPLETED_TIME,
      CASE WHEN DATABASE_NAME ILIKE 'TRXS_%' THEN 'Trexis' ELSE 'ALFA' END AS COMPANY,
      h.DATABASE_NAME,
      OVERWATCH_DATABASE_ENVIRONMENT(h.DATABASE_NAME) AS ENVIRONMENT,
      h.SCHEMA_NAME,
      COALESCE(root_task.TASK_NAME, h.NAME) AS ROOT_TASK_NAME,
      h.NAME AS TASK_NAME,
      h.STATE,
      h.QUERY_ID,
      h.ERROR_CODE,
      h.ERROR_MESSAGE,
      DATEDIFF('MILLISECOND', h.SCHEDULED_TIME, h.COMPLETED_TIME) AS DURATION_MS,
      NULL::VARCHAR AS WAREHOUSE_NAME
    FROM SNOWFLAKE.ACCOUNT_USAGE.TASK_HISTORY h
    LEFT JOIN SNOWFLAKE.ACCOUNT_USAGE.TASKS root_task
      ON h.ROOT_TASK_ID = root_task.ID
    WHERE h.SCHEDULED_TIME >= DATEADD('DAY', -30, CURRENT_TIMESTAMP());

    rows_loaded := rows_loaded + SQLROWCOUNT;
  EXCEPTION
    WHEN OTHER THEN
      INSERT INTO OVERWATCH_LOAD_AUDIT (LOAD_NAME, LOAD_STARTED_AT, LOAD_FINISHED_AT, STATUS, MESSAGE)
      VALUES ('FACT_TASK_RUN', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'SKIPPED', :SQLERRM);
  END;

  DELETE FROM FACT_PROCEDURE_RUN
  WHERE START_TIME >= DATEADD('DAY', -30, CURRENT_TIMESTAMP());

  INSERT INTO FACT_PROCEDURE_RUN (
    START_TIME, COMPANY, DATABASE_NAME, ENVIRONMENT, PROCEDURE_NAME, CALL_QUERY_ID, ROOT_QUERY_ID,
    CHILD_QUERY_COUNT, TOTAL_DURATION_MS, EST_CREDITS, EST_COST_USD, STATUS, ERROR_MESSAGE
  )
  SELECT
    q.START_TIME,
    CASE
      WHEN q.WAREHOUSE_NAME ILIKE 'WH_TRXS_%' OR q.DATABASE_NAME ILIKE 'TRXS_%' OR q.USER_NAME ILIKE 'TRXS_%' THEN 'Trexis'
      ELSE 'ALFA'
    END AS COMPANY,
    q.DATABASE_NAME,
    OVERWATCH_DATABASE_ENVIRONMENT(q.DATABASE_NAME) AS ENVIRONMENT,
    REGEXP_SUBSTR(q.QUERY_TEXT, 'CALL[[:space:]]+([^[:space:];(]+)', 1, 1, 'ie', 1) AS PROCEDURE_NAME,
    q.QUERY_ID AS CALL_QUERY_ID,
    NULL::VARCHAR AS ROOT_QUERY_ID,
    0 AS CHILD_QUERY_COUNT,
    q.TOTAL_ELAPSED_TIME AS TOTAL_DURATION_MS,
    NULL::NUMBER(18,6) AS EST_CREDITS,
    NULL::NUMBER(18,2) AS EST_COST_USD,
    q.EXECUTION_STATUS AS STATUS,
    q.ERROR_MESSAGE
  FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY q
  WHERE q.START_TIME >= DATEADD('DAY', -30, CURRENT_TIMESTAMP())
    AND UPPER(COALESCE(q.QUERY_TYPE, '')) = 'CALL';

  rows_loaded := rows_loaded + SQLROWCOUNT;

  UPDATE OVERWATCH_LOAD_AUDIT
  SET LOAD_FINISHED_AT = CURRENT_TIMESTAMP(),
      STATUS = 'SUCCEEDED',
      ROWS_LOADED = :rows_loaded,
      MESSAGE = 'Hourly mart load complete.'
  WHERE LOAD_NAME = 'SP_OVERWATCH_LOAD_HOURLY'
    AND LOAD_STARTED_AT = :started_at;

  RETURN 'OVERWATCH hourly mart load complete: ' || rows_loaded || ' rows.';

EXCEPTION
  WHEN OTHER THEN
    UPDATE OVERWATCH_LOAD_AUDIT
    SET LOAD_FINISHED_AT = CURRENT_TIMESTAMP(),
        STATUS = 'FAILED',
        MESSAGE = :SQLERRM
    WHERE LOAD_NAME = 'SP_OVERWATCH_LOAD_HOURLY'
      AND LOAD_STARTED_AT = :started_at;
    RAISE;
END;
$$;

CREATE OR REPLACE PROCEDURE SP_OVERWATCH_LOAD_DAILY()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
  credit_price NUMBER(18,4) DEFAULT 3.68;
  started_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP();
  rows_loaded NUMBER DEFAULT 0;
BEGIN
  SELECT TRY_TO_NUMBER(SETTING_VALUE) INTO :credit_price
  FROM OVERWATCH_SETTINGS
  WHERE SETTING_NAME = 'CREDIT_PRICE_USD';

  credit_price := COALESCE(credit_price, 3.68);

  INSERT INTO OVERWATCH_LOAD_AUDIT (LOAD_NAME, LOAD_STARTED_AT, STATUS, MESSAGE)
  VALUES ('SP_OVERWATCH_LOAD_DAILY', :started_at, 'RUNNING', 'Started daily mart load.');

  DELETE FROM FACT_LOGIN_DAILY
  WHERE LOGIN_DATE >= DATEADD('DAY', -35, CURRENT_DATE());

  INSERT INTO FACT_LOGIN_DAILY (
    LOGIN_DATE, COMPANY, USER_NAME, CLIENT_IP, REPORTED_CLIENT_TYPE,
    REPORTED_CLIENT_VERSION, SUCCESS_COUNT, FAILURE_COUNT
  )
  SELECT
    TO_DATE(EVENT_TIMESTAMP) AS LOGIN_DATE,
    CASE WHEN USER_NAME ILIKE 'TRXS_%' THEN 'Trexis' ELSE 'ALFA' END AS COMPANY,
    USER_NAME,
    CLIENT_IP,
    REPORTED_CLIENT_TYPE,
    REPORTED_CLIENT_VERSION,
    SUM(IFF(IS_SUCCESS = 'YES', 1, 0)) AS SUCCESS_COUNT,
    SUM(IFF(IS_SUCCESS = 'NO', 1, 0)) AS FAILURE_COUNT
  FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
  WHERE EVENT_TIMESTAMP >= DATEADD('DAY', -35, CURRENT_TIMESTAMP())
  GROUP BY 1,2,3,4,5,6;

  rows_loaded := rows_loaded + SQLROWCOUNT;

  DELETE FROM FACT_GRANT_DAILY
  WHERE SNAPSHOT_DATE = CURRENT_DATE();

  INSERT INTO FACT_GRANT_DAILY (
    SNAPSHOT_DATE, COMPANY, ROLE_NAME, GRANTEE_NAME, GRANTED_TO, CREATED_ON, DELETED_ON, GRANT_COUNT
  )
  SELECT
    CURRENT_DATE() AS SNAPSHOT_DATE,
    CASE WHEN "ROLE" ILIKE 'TRXS_%' OR GRANTEE_NAME ILIKE 'TRXS_%' THEN 'Trexis' ELSE 'ALFA' END AS COMPANY,
    "ROLE" AS ROLE_NAME,
    GRANTEE_NAME,
    GRANTED_TO,
    CREATED_ON,
    DELETED_ON,
    COUNT(*) AS GRANT_COUNT
  FROM SNOWFLAKE.ACCOUNT_USAGE.GRANTS_TO_USERS
  GROUP BY 1,2,3,4,5,6,7;

  rows_loaded := rows_loaded + SQLROWCOUNT;

  DELETE FROM FACT_STORAGE_DAILY
  WHERE SNAPSHOT_DATE >= DATEADD('DAY', -35, CURRENT_DATE());

  INSERT INTO FACT_STORAGE_DAILY (
    SNAPSHOT_DATE, COMPANY, DATABASE_NAME, ENVIRONMENT, ACTIVE_BYTES, TIME_TRAVEL_BYTES,
    FAILSAFE_BYTES, RETAINED_FOR_CLONE_BYTES, EST_STORAGE_TB, EST_COST_USD
  )
  SELECT
    USAGE_DATE AS SNAPSHOT_DATE,
    CASE WHEN DATABASE_NAME ILIKE 'TRXS_%' THEN 'Trexis' ELSE 'ALFA' END AS COMPANY,
    DATABASE_NAME,
    OVERWATCH_DATABASE_ENVIRONMENT(DATABASE_NAME) AS ENVIRONMENT,
    SUM(AVERAGE_DATABASE_BYTES) AS ACTIVE_BYTES,
    0 AS TIME_TRAVEL_BYTES,
    SUM(AVERAGE_FAILSAFE_BYTES) AS FAILSAFE_BYTES,
    0 AS RETAINED_FOR_CLONE_BYTES,
    ROUND(SUM(AVERAGE_DATABASE_BYTES + AVERAGE_FAILSAFE_BYTES) / POWER(1024, 4), 4) AS EST_STORAGE_TB,
    ROUND(SUM(AVERAGE_DATABASE_BYTES + AVERAGE_FAILSAFE_BYTES) / POWER(1024, 4) * 23, 2) AS EST_COST_USD
  FROM SNOWFLAKE.ACCOUNT_USAGE.DATABASE_STORAGE_USAGE_HISTORY
  WHERE USAGE_DATE >= DATEADD('DAY', -35, CURRENT_DATE())
  GROUP BY 1,2,3,4;

  rows_loaded := rows_loaded + SQLROWCOUNT;

  DELETE FROM DIM_TABLE_SNAPSHOT
  WHERE SNAPSHOT_TS::DATE = CURRENT_DATE();

  INSERT INTO DIM_TABLE_SNAPSHOT (
    SNAPSHOT_TS, COMPANY, DATABASE_NAME, ENVIRONMENT, SCHEMA_NAME, TABLE_NAME, TABLE_TYPE,
    ROW_COUNT, BYTES, LAST_ALTERED, CREATED
  )
  SELECT
    CURRENT_TIMESTAMP() AS SNAPSHOT_TS,
    CASE WHEN TABLE_CATALOG ILIKE 'TRXS_%' THEN 'Trexis' ELSE 'ALFA' END AS COMPANY,
    TABLE_CATALOG AS DATABASE_NAME,
    OVERWATCH_DATABASE_ENVIRONMENT(TABLE_CATALOG) AS ENVIRONMENT,
    TABLE_SCHEMA AS SCHEMA_NAME,
    TABLE_NAME,
    TABLE_TYPE,
    ROW_COUNT,
    BYTES,
    LAST_ALTERED,
    CREATED
  FROM SNOWFLAKE.ACCOUNT_USAGE.TABLES
  WHERE DELETED IS NULL
    AND TABLE_SCHEMA <> 'INFORMATION_SCHEMA';

  rows_loaded := rows_loaded + SQLROWCOUNT;

  DELETE FROM FACT_COPY_LOAD_DAILY
  WHERE LOAD_DATE >= DATEADD('DAY', -35, CURRENT_DATE());

  INSERT INTO FACT_COPY_LOAD_DAILY (
    LOAD_DATE, COMPANY, DATABASE_NAME, ENVIRONMENT, SCHEMA_NAME, TABLE_NAME, STATUS,
    FILE_COUNT, ROW_COUNT, ROW_PARSED, ERROR_COUNT, FILE_SIZE_BYTES,
    BYTES_BILLED, LAST_SEEN, LATEST_ERROR
  )
  SELECT
    TO_DATE(LAST_LOAD_TIME) AS LOAD_DATE,
    CASE WHEN TABLE_CATALOG_NAME ILIKE 'TRXS_%' THEN 'Trexis' ELSE 'ALFA' END AS COMPANY,
    TABLE_CATALOG_NAME AS DATABASE_NAME,
    OVERWATCH_DATABASE_ENVIRONMENT(TABLE_CATALOG_NAME) AS ENVIRONMENT,
    TABLE_SCHEMA_NAME AS SCHEMA_NAME,
    TABLE_NAME,
    STATUS,
    COUNT(*) AS FILE_COUNT,
    SUM(COALESCE(ROW_COUNT, 0)) AS ROW_COUNT,
    SUM(COALESCE(ROW_PARSED, 0)) AS ROW_PARSED,
    SUM(COALESCE(ERROR_COUNT, 0)) AS ERROR_COUNT,
    SUM(COALESCE(FILE_SIZE, 0)) AS FILE_SIZE_BYTES,
    0 AS BYTES_BILLED,
    MAX(LAST_LOAD_TIME) AS LAST_SEEN,
    MAX(FIRST_ERROR_MESSAGE) AS LATEST_ERROR
  FROM SNOWFLAKE.ACCOUNT_USAGE.COPY_HISTORY
  WHERE LAST_LOAD_TIME >= DATEADD('DAY', -35, CURRENT_TIMESTAMP())
  GROUP BY 1,2,3,4,5,6,7;

  rows_loaded := rows_loaded + SQLROWCOUNT;

  DELETE FROM FACT_MONITORING_COST_DAILY
  WHERE USAGE_DATE >= DATEADD('DAY', -35, CURRENT_DATE());

  INSERT INTO FACT_MONITORING_COST_DAILY (
    USAGE_DATE, COMPANY, COST_COMPONENT, CREDITS_USED, EST_COST_USD, SOURCE
  )
  SELECT
    TO_DATE(START_TIME) AS USAGE_DATE,
    CASE WHEN WAREHOUSE_NAME ILIKE 'WH_TRXS_%' THEN 'Trexis' ELSE 'ALFA' END AS COMPANY,
    CASE
      WHEN WAREHOUSE_NAME = 'OVERWATCH_WH' THEN 'MART_REFRESH'
      WHEN WAREHOUSE_NAME ILIKE '%STREAMLIT%' THEN 'STREAMLIT_APP'
      ELSE 'OVERWATCH_TAGGED'
    END AS COST_COMPONENT,
    SUM(CREDITS_USED) AS CREDITS_USED,
    ROUND(SUM(CREDITS_USED) * :credit_price, 2) AS EST_COST_USD,
    'WAREHOUSE_METERING_HISTORY filtered to OVERWATCH_WH and Streamlit-style warehouses' AS SOURCE
  FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
  WHERE START_TIME >= DATEADD('DAY', -35, CURRENT_TIMESTAMP())
    AND (
      WAREHOUSE_NAME = 'OVERWATCH_WH'
      OR WAREHOUSE_NAME ILIKE '%STREAMLIT%'
    )
  GROUP BY 1,2,3;

  rows_loaded := rows_loaded + SQLROWCOUNT;

  CALL SP_OVERWATCH_PRUNE();

  UPDATE OVERWATCH_LOAD_AUDIT
  SET LOAD_FINISHED_AT = CURRENT_TIMESTAMP(),
      STATUS = 'SUCCEEDED',
      ROWS_LOADED = :rows_loaded,
      MESSAGE = 'Daily mart load complete.'
  WHERE LOAD_NAME = 'SP_OVERWATCH_LOAD_DAILY'
    AND LOAD_STARTED_AT = :started_at;

  RETURN 'OVERWATCH daily mart load complete: ' || rows_loaded || ' rows.';

EXCEPTION
  WHEN OTHER THEN
    UPDATE OVERWATCH_LOAD_AUDIT
    SET LOAD_FINISHED_AT = CURRENT_TIMESTAMP(),
        STATUS = 'FAILED',
        MESSAGE = :SQLERRM
    WHERE LOAD_NAME = 'SP_OVERWATCH_LOAD_DAILY'
      AND LOAD_STARTED_AT = :started_at;
    RAISE;
END;
$$;

CREATE OR REPLACE PROCEDURE SP_OVERWATCH_REFRESH_CONTROL_ROOM()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
  DELETE FROM MART_DBA_CONTROL_ROOM
  WHERE SNAPSHOT_TS >= DATEADD('HOUR', -2, CURRENT_TIMESTAMP());

  INSERT INTO MART_DBA_CONTROL_ROOM (
    SNAPSHOT_TS, COMPANY, HEALTH_SCORE, FAILED_QUERIES_24H, FAILED_TASKS_24H,
    QUEUED_MS_24H, CREDITS_24H, COST_24H_USD, CORTEX_COST_7D_USD,
    SECURITY_EVENTS_24H, OBJECT_CHANGES_24H, TOP_RISK
  )
  WITH companies AS (
    SELECT 'ALFA' AS company UNION ALL SELECT 'Trexis'
  ),
  q AS (
    SELECT
      company,
      SUM(failed_count) AS failed_queries,
      SUM(total_queued_ms) AS queued_ms
    FROM FACT_QUERY_HOURLY
    WHERE hour_start >= DATEADD('HOUR', -24, CURRENT_TIMESTAMP())
    GROUP BY company
  ),
  wh AS (
    SELECT
      company,
      SUM(credits_used) AS credits,
      SUM(est_cost_usd) AS cost_usd
    FROM FACT_WAREHOUSE_HOURLY
    WHERE hour_start >= DATEADD('HOUR', -24, CURRENT_TIMESTAMP())
    GROUP BY company
  ),
  oc AS (
    SELECT company, COUNT(*) AS object_changes
    FROM FACT_OBJECT_CHANGE
    WHERE start_time >= DATEADD('HOUR', -24, CURRENT_TIMESTAMP())
    GROUP BY company
  ),
  task_failures AS (
    SELECT company, COUNT(*) AS failed_tasks
    FROM FACT_TASK_RUN
    WHERE scheduled_time >= DATEADD('HOUR', -24, CURRENT_TIMESTAMP())
      AND UPPER(COALESCE(state, '')) IN ('FAILED', 'FAILED_WITH_ERROR')
    GROUP BY company
  ),
  sec AS (
    SELECT company, SUM(failure_count) AS security_events
    FROM FACT_LOGIN_DAILY
    WHERE login_date >= DATEADD('DAY', -1, CURRENT_DATE())
    GROUP BY company
  ),
  cx AS (
    SELECT company, SUM(est_cost_usd) AS cortex_cost
    FROM FACT_CORTEX_DAILY
    WHERE usage_date >= DATEADD('DAY', -7, CURRENT_DATE())
    GROUP BY company
  )
  SELECT
    CURRENT_TIMESTAMP(),
    c.company,
    GREATEST(
      0,
      100
      - LEAST(COALESCE(q.failed_queries, 0) * 2, 25)
      - LEAST(COALESCE(task_failures.failed_tasks, 0) * 4, 25)
      - LEAST(COALESCE(q.queued_ms, 0) / 60000, 20)
      - LEAST(COALESCE(sec.security_events, 0) * 0.5, 20)
      - LEAST(COALESCE(oc.object_changes, 0) * 0.25, 10)
    ) AS health_score,
    COALESCE(q.failed_queries, 0),
    COALESCE(task_failures.failed_tasks, 0) AS failed_tasks_24h,
    COALESCE(q.queued_ms, 0),
    COALESCE(wh.credits, 0),
    COALESCE(wh.cost_usd, 0),
    COALESCE(cx.cortex_cost, 0),
    COALESCE(sec.security_events, 0),
    COALESCE(oc.object_changes, 0),
    CASE
      WHEN COALESCE(task_failures.failed_tasks, 0) > 0 THEN 'Failed tasks'
      WHEN COALESCE(q.failed_queries, 0) > 0 THEN 'Failed queries'
      WHEN COALESCE(q.queued_ms, 0) > 0 THEN 'Queue pressure'
      WHEN COALESCE(sec.security_events, 0) > 0 THEN 'Login/security events'
      WHEN COALESCE(oc.object_changes, 0) > 0 THEN 'Object changes'
      ELSE 'No immediate exception'
    END AS top_risk
  FROM companies c
  LEFT JOIN q ON c.company = q.company
  LEFT JOIN wh ON c.company = wh.company
  LEFT JOIN oc ON c.company = oc.company
  LEFT JOIN task_failures ON c.company = task_failures.company
  LEFT JOIN sec ON c.company = sec.company
  LEFT JOIN cx ON c.company = cx.company;

  RETURN 'OVERWATCH control room mart refreshed.';
END;
$$;

-- Optional Cortex load. This is isolated because Cortex Code usage views might
-- not exist in every account/edition.
CREATE OR REPLACE PROCEDURE SP_OVERWATCH_LOAD_CORTEX()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
  ai_credit_price NUMBER(18,4) DEFAULT 2.20;
BEGIN
  SELECT TRY_TO_NUMBER(SETTING_VALUE) INTO :ai_credit_price
  FROM OVERWATCH_SETTINGS
  WHERE SETTING_NAME = 'AI_CREDIT_PRICE_USD';

  ai_credit_price := COALESCE(ai_credit_price, 2.20);

  DELETE FROM FACT_CORTEX_DAILY
  WHERE USAGE_DATE >= DATEADD('DAY', -35, CURRENT_DATE());

  BEGIN
    INSERT INTO FACT_CORTEX_DAILY (
      USAGE_DATE, COMPANY, USER_ID, SOURCE, CREDITS_USED, EST_COST_USD, REQUEST_COUNT
    )
    SELECT
      raw.USAGE_DATE,
      CASE WHEN COALESCE(u.NAME, raw.USER_ID::VARCHAR) ILIKE 'TRXS_%' THEN 'Trexis' ELSE 'ALFA' END AS COMPANY,
      raw.USER_ID::VARCHAR AS USER_ID,
      raw.SOURCE,
      SUM(raw.CREDITS_USED) AS CREDITS_USED,
      ROUND(SUM(raw.CREDITS_USED) * :ai_credit_price, 2) AS EST_COST_USD,
      COUNT(*) AS REQUEST_COUNT
    FROM (
      SELECT TO_DATE(USAGE_TIME) AS USAGE_DATE, USER_ID, 'SNOWSIGHT' AS SOURCE, TOKEN_CREDITS AS CREDITS_USED
      FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_CODE_SNOWSIGHT_USAGE_HISTORY
      WHERE USAGE_TIME >= DATEADD('DAY', -35, CURRENT_TIMESTAMP())
      UNION ALL
      SELECT TO_DATE(USAGE_TIME) AS USAGE_DATE, USER_ID, 'CLI' AS SOURCE, TOKEN_CREDITS AS CREDITS_USED
      FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_CODE_CLI_USAGE_HISTORY
      WHERE USAGE_TIME >= DATEADD('DAY', -35, CURRENT_TIMESTAMP())
    ) raw
    LEFT JOIN SNOWFLAKE.ACCOUNT_USAGE.USERS u ON raw.USER_ID = u.USER_ID
    GROUP BY 1,2,3,4;
  EXCEPTION
    WHEN OTHER THEN
      INSERT INTO OVERWATCH_LOAD_AUDIT (LOAD_NAME, LOAD_STARTED_AT, LOAD_FINISHED_AT, STATUS, MESSAGE)
      VALUES ('SP_OVERWATCH_LOAD_CORTEX', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'SKIPPED', :SQLERRM);
  END;

  RETURN 'OVERWATCH Cortex load complete or skipped if usage views are unavailable.';
END;
$$;

-- -----------------------------------------------------------------------------
-- 5. Task graph
-- -----------------------------------------------------------------------------

CREATE OR REPLACE TASK OVERWATCH_LOAD_HOURLY
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 25 * * * * America/Chicago'
AS
  CALL SP_OVERWATCH_LOAD_HOURLY();

CREATE OR REPLACE TASK OVERWATCH_LOAD_CORTEX
  WAREHOUSE = COMPUTE_WH
  AFTER OVERWATCH_LOAD_HOURLY
AS
  CALL SP_OVERWATCH_LOAD_CORTEX();

CREATE OR REPLACE TASK OVERWATCH_REFRESH_CONTROL_ROOM
  WAREHOUSE = COMPUTE_WH
  AFTER OVERWATCH_LOAD_CORTEX
AS
  CALL SP_OVERWATCH_REFRESH_CONTROL_ROOM();

CREATE OR REPLACE TASK OVERWATCH_LOAD_DAILY
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 15 6 * * * America/Chicago'
AS
  CALL SP_OVERWATCH_LOAD_DAILY();

-- Resume child tasks first, then root scheduled tasks.
ALTER TASK OVERWATCH_LOAD_CORTEX RESUME;
ALTER TASK OVERWATCH_REFRESH_CONTROL_ROOM RESUME;
ALTER TASK OVERWATCH_LOAD_HOURLY RESUME;
ALTER TASK OVERWATCH_LOAD_DAILY RESUME;

-- -----------------------------------------------------------------------------
-- 6. Smoke checks
-- -----------------------------------------------------------------------------

SHOW TASKS LIKE 'OVERWATCH_%' IN SCHEMA DBA_MAINT_DB.OVERWATCH;

SELECT 'FACT_WAREHOUSE_HOURLY' AS TABLE_NAME, COUNT(*) AS ROWS_LOADED FROM FACT_WAREHOUSE_HOURLY
UNION ALL
SELECT 'FACT_QUERY_HOURLY', COUNT(*) FROM FACT_QUERY_HOURLY
UNION ALL
SELECT 'FACT_QUERY_DETAIL_RECENT', COUNT(*) FROM FACT_QUERY_DETAIL_RECENT
UNION ALL
SELECT 'DIM_TABLE_SNAPSHOT', COUNT(*) FROM DIM_TABLE_SNAPSHOT
UNION ALL
SELECT 'FACT_COPY_LOAD_DAILY', COUNT(*) FROM FACT_COPY_LOAD_DAILY
UNION ALL
SELECT 'MART_DBA_CONTROL_ROOM', COUNT(*) FROM MART_DBA_CONTROL_ROOM;




CALL SP_OVERWATCH_LOAD_HOURLY();
CALL SP_OVERWATCH_LOAD_CORTEX();
CALL SP_OVERWATCH_REFRESH_CONTROL_ROOM();
CALL SP_OVERWATCH_LOAD_DAILY();
