-- OVERWATCH Snowflake Mart Drop
-- Purpose:
--   Drop every deployable object created by snowflake/OVERWATCH_MART_SETUP.sql
--   so the mart/schema can be rebuilt cleanly after DDL logic, naming, or scope
--   changes.
--
-- Run before rerunning OVERWATCH_MART_SETUP.sql when you intentionally want a
-- destructive rebuild of OVERWATCH app objects.
--
-- This script does not drop the database, schema, warehouse, resource monitor,
-- or access roles by default. Optional full-reset statements are listed at the
-- bottom and should stay commented unless you really want to remove the runtime
-- containers too.

USE DATABASE DBA_MAINT_DB;
USE SCHEMA OVERWATCH;

-- -----------------------------------------------------------------------------
-- 1. Stop scheduled work before dropping dependencies.
-- -----------------------------------------------------------------------------

ALTER TASK IF EXISTS OVERWATCH_EXECUTIVE_OBSERVABILITY_REFRESH SUSPEND;
ALTER TASK IF EXISTS OVERWATCH_AUTOMATION_REFRESH SUSPEND;
ALTER TASK IF EXISTS OVERWATCH_COST_MONITORING_REFRESH SUSPEND;
ALTER TASK IF EXISTS OVERWATCH_REFRESH_CONTROL_ROOM SUSPEND;
ALTER TASK IF EXISTS OVERWATCH_LOAD_CORTEX SUSPEND;
ALTER TASK IF EXISTS OVERWATCH_LOAD_HOURLY SUSPEND;
ALTER TASK IF EXISTS OVERWATCH_LOAD_DAILY SUSPEND;
ALTER TASK IF EXISTS OVERWATCH_ANOMALY_CHECK SUSPEND;

-- -----------------------------------------------------------------------------
-- 2. Drop task graph children before roots.
-- -----------------------------------------------------------------------------

DROP TASK IF EXISTS OVERWATCH_EXECUTIVE_OBSERVABILITY_REFRESH;
DROP TASK IF EXISTS OVERWATCH_AUTOMATION_REFRESH;
DROP TASK IF EXISTS OVERWATCH_COST_MONITORING_REFRESH;
DROP TASK IF EXISTS OVERWATCH_REFRESH_CONTROL_ROOM;
DROP TASK IF EXISTS OVERWATCH_LOAD_CORTEX;
DROP TASK IF EXISTS OVERWATCH_LOAD_HOURLY;
DROP TASK IF EXISTS OVERWATCH_LOAD_DAILY;
DROP TASK IF EXISTS OVERWATCH_ANOMALY_CHECK;

-- -----------------------------------------------------------------------------
-- 3. Drop views before tables.
-- -----------------------------------------------------------------------------

DROP VIEW IF EXISTS OVERWATCH_AUTOMATION_HEALTH_V;
DROP VIEW IF EXISTS OVERWATCH_ALERT_TRIAGE_V;
DROP VIEW IF EXISTS OVERWATCH_WORKLOAD_RECOVERY_AUDIT_LATEST_V;

-- -----------------------------------------------------------------------------
-- 4. Drop procedures and functions before backing tables.
-- -----------------------------------------------------------------------------

DROP PROCEDURE IF EXISTS SP_OVERWATCH_SEND_ALERT_DIGEST(VARCHAR, VARCHAR, VARCHAR, BOOLEAN);
DROP PROCEDURE IF EXISTS SP_OVERWATCH_REFRESH_AUTOMATION(VARCHAR, VARCHAR, BOOLEAN);
DROP PROCEDURE IF EXISTS SP_OVERWATCH_REFRESH_EXECUTIVE_OBSERVABILITY();
DROP PROCEDURE IF EXISTS SP_OVERWATCH_REFRESH_COST_MONITORING();
DROP PROCEDURE IF EXISTS SP_OVERWATCH_REFRESH_CONTROL_ROOM();
DROP PROCEDURE IF EXISTS SP_OVERWATCH_LOAD_CORTEX();
DROP PROCEDURE IF EXISTS SP_OVERWATCH_LOAD_DAILY();
DROP PROCEDURE IF EXISTS SP_OVERWATCH_LOAD_HOURLY();
DROP PROCEDURE IF EXISTS SP_OVERWATCH_PRUNE();

DROP FUNCTION IF EXISTS OVERWATCH_DATABASE_ENVIRONMENT(VARCHAR);

-- -----------------------------------------------------------------------------
-- 5. Drop mart, fact, dimension, audit, alert, recon, and settings tables.
-- -----------------------------------------------------------------------------

DROP TABLE IF EXISTS MART_EXECUTIVE_OBSERVABILITY;
DROP TABLE IF EXISTS MART_DBA_CONTROL_ROOM;

DROP TABLE IF EXISTS FACT_COST_INCIDENT_TIMELINE;
DROP TABLE IF EXISTS FACT_COST_MONITORING_SIGNAL;
DROP TABLE IF EXISTS FACT_COST_SOURCE_HEALTH_DAILY;
DROP TABLE IF EXISTS FACT_COST_DAILY;
DROP TABLE IF EXISTS FACT_CORTEX_DAILY;
DROP TABLE IF EXISTS FACT_COPY_LOAD_DAILY;
DROP TABLE IF EXISTS DIM_TABLE_SNAPSHOT;
DROP TABLE IF EXISTS FACT_STORAGE_DAILY;
DROP TABLE IF EXISTS FACT_GRANT_DAILY;
DROP TABLE IF EXISTS FACT_CHANGE_CONTROL_OPERABILITY_DAILY;
DROP TABLE IF EXISTS FACT_OBJECT_CHANGE;
DROP TABLE IF EXISTS FACT_LOGIN_DAILY;
DROP TABLE IF EXISTS FACT_PROCEDURE_RUN;
DROP TABLE IF EXISTS DIM_PROCEDURE_SNAPSHOT;
DROP TABLE IF EXISTS DIM_TASK_SNAPSHOT;
DROP TABLE IF EXISTS FACT_TASK_CRITICAL_PATH;
DROP TABLE IF EXISTS FACT_TASK_RUN;
DROP TABLE IF EXISTS DIM_COST_OWNER_TAG;
DROP TABLE IF EXISTS FACT_CHARGEBACK_DAILY;
DROP TABLE IF EXISTS FACT_QUERY_DETAIL_RECENT;
DROP TABLE IF EXISTS FACT_QUERY_HOURLY;
DROP TABLE IF EXISTS FACT_ACCOUNT_HEALTH_OPERABILITY_DAILY;
DROP TABLE IF EXISTS FACT_SECURITY_OPERABILITY_DAILY;
DROP TABLE IF EXISTS FACT_WAREHOUSE_OPERABILITY_DAILY;
DROP TABLE IF EXISTS FACT_WAREHOUSE_HOURLY;

DROP TABLE IF EXISTS OVERWATCH_SCHEMA_DIFF_RESULT;
DROP TABLE IF EXISTS OVERWATCH_RECON_RUN;
DROP TABLE IF EXISTS OVERWATCH_RECON_CONFIG;

DROP TABLE IF EXISTS OVERWATCH_EXECUTIVE_PACKET;
DROP TABLE IF EXISTS OVERWATCH_AUTOMATION_RUN;

DROP TABLE IF EXISTS OVERWATCH_ALERT_RULES;
DROP TABLE IF EXISTS OVERWATCH_ALERT_RULE_AUDIT;
DROP TABLE IF EXISTS OVERWATCH_ALERT_DELIVERY_LOG;
DROP TABLE IF EXISTS OVERWATCH_ANNOTATIONS;
DROP TABLE IF EXISTS ALERT_DATA_QUALITY_CHECKS;
DROP TABLE IF EXISTS ALERT_OWNER_ROUTING;
DROP TABLE IF EXISTS ALERT_REMEDIATION_LOG;
DROP TABLE IF EXISTS ALERT_NOTIFICATION_LOG;
DROP TABLE IF EXISTS ALERT_ACKNOWLEDGEMENTS;
DROP TABLE IF EXISTS ALERT_RUN_HISTORY;
DROP TABLE IF EXISTS ALERT_EVENTS;
DROP TABLE IF EXISTS ALERT_THRESHOLDS;
DROP TABLE IF EXISTS ALERT_CONFIG;
DROP TABLE IF EXISTS OVERWATCH_ALERTS;

DROP TABLE IF EXISTS OVERWATCH_SECURITY_ACCESS_REVIEW;
DROP TABLE IF EXISTS OVERWATCH_WAREHOUSE_SETTING_REVIEW;
DROP TABLE IF EXISTS OVERWATCH_CHANGE_CONTROL_EVIDENCE;
DROP TABLE IF EXISTS OVERWATCH_DBA_CHECKLIST_HISTORY;
DROP TABLE IF EXISTS OVERWATCH_WORKLOAD_RECOVERY_AUDIT;
DROP TABLE IF EXISTS OVERWATCH_ACTION_QUEUE;
DROP TABLE IF EXISTS OVERWATCH_USAGE_LOG;
DROP TABLE IF EXISTS OVERWATCH_ADMIN_ACTION_AUDIT;
DROP TABLE IF EXISTS OVERWATCH_LOAD_AUDIT;
DROP TABLE IF EXISTS OVERWATCH_OWNER_TAG_NAMES;
DROP TABLE IF EXISTS OVERWATCH_SCHEMA_MIGRATION;
DROP TABLE IF EXISTS OVERWATCH_SETTINGS;

-- -----------------------------------------------------------------------------
-- 6. Optional runtime/container reset.
-- -----------------------------------------------------------------------------
-- Uncomment only when you want to remove the runtime container objects too.
-- The standard fresh rebuild path is:
--   1. Run this script as-is.
--   2. Run snowflake/OVERWATCH_MART_SETUP.sql.
--
-- DROP SCHEMA IF EXISTS DBA_MAINT_DB.OVERWATCH;
-- DROP DATABASE IF EXISTS DBA_MAINT_DB;
-- DROP WAREHOUSE IF EXISTS OVERWATCH_WH;
-- DROP RESOURCE MONITOR IF EXISTS OVERWATCH_WH_RM;
-- DROP ROLE IF EXISTS SNOW_SYSADMINS;
-- DROP ROLE IF EXISTS SNOW_ACCOUNTADMINS;
