-- OVERWATCH optional precompute layer
-- Review warehouse, refresh lag, ownership, and cost before enabling Dynamic Tables.
-- If Dynamic Tables are not approved, use the fallback views/tasks in this file.

USE DATABASE DBA_MAINT_DB;
USE SCHEMA OVERWATCH;

-- -----------------------------------------------------------------------------
-- Optional Dynamic Table path
-- -----------------------------------------------------------------------------

CREATE DYNAMIC TABLE IF NOT EXISTS DT_OVERWATCH_QUERY_HEALTH_HOURLY
  TARGET_LAG = '60 minutes'
  WAREHOUSE = OVERWATCH_WH
AS
SELECT
    DATE_TRUNC('HOUR', START_TIME) AS HOUR_START,
    WAREHOUSE_NAME,
    USER_NAME,
    ROLE_NAME,
    DATABASE_NAME,
    COUNT(*) AS QUERY_COUNT,
    COUNT_IF(EXECUTION_STATUS = 'FAIL') AS FAILED_COUNT,
    AVG(TOTAL_ELAPSED_TIME) AS AVG_ELAPSED_MS,
    MAX(TOTAL_ELAPSED_TIME) AS MAX_ELAPSED_MS,
    SUM(BYTES_SCANNED) AS BYTES_SCANNED,
    SUM(BYTES_SPILLED_TO_REMOTE_STORAGE) AS BYTES_SPILLED_REMOTE,
    SUM(QUEUED_OVERLOAD_TIME + QUEUED_PROVISIONING_TIME + QUEUED_REPAIR_TIME) AS QUEUED_MS
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('DAY', -14, CURRENT_TIMESTAMP())
GROUP BY 1, 2, 3, 4, 5;

CREATE DYNAMIC TABLE IF NOT EXISTS DT_OVERWATCH_COST_DAILY
  TARGET_LAG = '12 hours'
  WAREHOUSE = OVERWATCH_WH
AS
SELECT
    USAGE_DATE,
    WAREHOUSE_NAME,
    SUM(COALESCE(CREDITS_USED_COMPUTE, CREDITS_USED)) AS COMPUTE_CREDITS,
    SUM(CREDITS_USED_CLOUD_SERVICES) AS CLOUD_SERVICES_CREDITS,
    SUM(CREDITS_USED) AS TOTAL_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE USAGE_DATE >= DATEADD('DAY', -180, CURRENT_DATE())
GROUP BY 1, 2;

CREATE DYNAMIC TABLE IF NOT EXISTS DT_OVERWATCH_TASK_CRITICAL_PATH
  TARGET_LAG = '60 minutes'
  WAREHOUSE = OVERWATCH_WH
AS
SELECT
    COALESCE(ROOT_TASK_NAME, NAME) AS ROOT_TASK_NAME,
    DATABASE_NAME,
    SCHEMA_NAME,
    NAME AS TASK_NAME,
    MAX(SCHEDULED_TIME) AS LAST_SCHEDULED_TIME,
    MAX_BY(STATE, SCHEDULED_TIME) AS LAST_STATE,
    COUNT_IF(STATE IN ('FAILED', 'CANCELLED')) AS FAILURES_7D,
    COUNT_IF(STATE = 'SKIPPED') AS SKIPPED_7D,
    COUNT(*) AS RUNS_7D,
    MAX(DATEDIFF('SECOND', QUERY_START_TIME, COMPLETED_TIME)) AS MAX_DURATION_SEC,
    MAX_BY(ERROR_MESSAGE, SCHEDULED_TIME) AS LATEST_ERROR,
    MAX_BY(QUERY_ID, SCHEDULED_TIME) AS LATEST_QUERY_ID
FROM SNOWFLAKE.ACCOUNT_USAGE.TASK_HISTORY
WHERE SCHEDULED_TIME >= DATEADD('DAY', -7, CURRENT_TIMESTAMP())
GROUP BY 1, 2, 3, 4;

-- -----------------------------------------------------------------------------
-- Fallback view path
-- -----------------------------------------------------------------------------

CREATE OR REPLACE VIEW OVERWATCH_QUERY_HEALTH_HOURLY_V AS
SELECT
    DATE_TRUNC('HOUR', START_TIME) AS HOUR_START,
    WAREHOUSE_NAME,
    USER_NAME,
    ROLE_NAME,
    DATABASE_NAME,
    COUNT(*) AS QUERY_COUNT,
    COUNT_IF(EXECUTION_STATUS = 'FAIL') AS FAILED_COUNT,
    AVG(TOTAL_ELAPSED_TIME) AS AVG_ELAPSED_MS,
    MAX(TOTAL_ELAPSED_TIME) AS MAX_ELAPSED_MS,
    SUM(BYTES_SCANNED) AS BYTES_SCANNED,
    SUM(BYTES_SPILLED_TO_REMOTE_STORAGE) AS BYTES_SPILLED_REMOTE,
    SUM(QUEUED_OVERLOAD_TIME + QUEUED_PROVISIONING_TIME + QUEUED_REPAIR_TIME) AS QUEUED_MS
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('DAY', -14, CURRENT_TIMESTAMP())
GROUP BY 1, 2, 3, 4, 5;

CREATE OR REPLACE VIEW OVERWATCH_COST_DAILY_V AS
SELECT
    USAGE_DATE,
    WAREHOUSE_NAME,
    SUM(COALESCE(CREDITS_USED_COMPUTE, CREDITS_USED)) AS COMPUTE_CREDITS,
    SUM(CREDITS_USED_CLOUD_SERVICES) AS CLOUD_SERVICES_CREDITS,
    SUM(CREDITS_USED) AS TOTAL_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE USAGE_DATE >= DATEADD('DAY', -180, CURRENT_DATE())
GROUP BY 1, 2;

CREATE OR REPLACE VIEW OVERWATCH_TASK_CRITICAL_PATH_V AS
SELECT
    COALESCE(ROOT_TASK_NAME, NAME) AS ROOT_TASK_NAME,
    DATABASE_NAME,
    SCHEMA_NAME,
    NAME AS TASK_NAME,
    MAX(SCHEDULED_TIME) AS LAST_SCHEDULED_TIME,
    MAX_BY(STATE, SCHEDULED_TIME) AS LAST_STATE,
    COUNT_IF(STATE IN ('FAILED', 'CANCELLED')) AS FAILURES_7D,
    COUNT_IF(STATE = 'SKIPPED') AS SKIPPED_7D,
    COUNT(*) AS RUNS_7D,
    MAX(DATEDIFF('SECOND', QUERY_START_TIME, COMPLETED_TIME)) AS MAX_DURATION_SEC,
    MAX_BY(ERROR_MESSAGE, SCHEDULED_TIME) AS LATEST_ERROR,
    MAX_BY(QUERY_ID, SCHEDULED_TIME) AS LATEST_QUERY_ID
FROM SNOWFLAKE.ACCOUNT_USAGE.TASK_HISTORY
WHERE SCHEDULED_TIME >= DATEADD('DAY', -7, CURRENT_TIMESTAMP())
GROUP BY 1, 2, 3, 4;

-- -----------------------------------------------------------------------------
-- Operator decision
-- -----------------------------------------------------------------------------

-- Use Dynamic Tables when:
-- 1. OVERWATCH_WH has approved monitoring budget.
-- 2. Target lag is acceptable for DBA morning triage.
-- 3. The account supports Dynamic Tables and the setup role owns the refresh objects.
--
-- Use fallback views/tasks when:
-- 1. Dynamic Tables are not approved.
-- 2. You need caller-mode transparency over scheduled refresh behavior.
-- 3. You want base setup to remain lower-risk while production hardening continues.
