"""Executive Landing workflow contracts."""
from __future__ import annotations

EXECUTIVE_LANDING_VERSION = "2026-06-14-boardroom-glance-v2"
PLATFORM_SUMMARY_STATE_KEY = "executive_landing_platform_summary"
OBSERVABILITY_STATE_KEY = "executive_landing_observability_board"
OBSERVABILITY_OFFLINE_SOURCE = "Snowflake connection unavailable"

EXECUTIVE_OVERVIEW_WORKFLOW = "Executive Overview"
EXECUTIVE_COST_MOVEMENT_WORKFLOW = "Cost Movement"
EXECUTIVE_OPERATIONAL_RISK_WORKFLOW = "Operational Risk"
EXECUTIVE_SECURITY_RISK_WORKFLOW = "Security Risk"
EXECUTIVE_CHANGE_SUMMARY_WORKFLOW = "Change Summary"
EXECUTIVE_ACTIONS_WORKFLOW = "Executive Actions"
EXECUTIVE_ADMIN_WORKFLOW = "Executive Admin / Advanced"
EXECUTIVE_LANDING_WORKFLOWS = (
    EXECUTIVE_OVERVIEW_WORKFLOW,
    EXECUTIVE_COST_MOVEMENT_WORKFLOW,
    EXECUTIVE_OPERATIONAL_RISK_WORKFLOW,
    EXECUTIVE_SECURITY_RISK_WORKFLOW,
    EXECUTIVE_CHANGE_SUMMARY_WORKFLOW,
    EXECUTIVE_ACTIONS_WORKFLOW,
    EXECUTIVE_ADMIN_WORKFLOW,
)
EXECUTIVE_LANDING_LEGACY_WORKFLOW_ALIASES = {
    "Executive Briefing": EXECUTIVE_OVERVIEW_WORKFLOW,
    "Executive Summary": EXECUTIVE_OVERVIEW_WORKFLOW,
    "Adoption Analytics": EXECUTIVE_ADMIN_WORKFLOW,
    "Executive Scorecard": EXECUTIVE_ADMIN_WORKFLOW,
    "Scorecard Formulas": EXECUTIVE_ADMIN_WORKFLOW,
    "Value Ledger": EXECUTIVE_ADMIN_WORKFLOW,
    "Production Readiness": EXECUTIVE_ADMIN_WORKFLOW,
    "Data Trust": EXECUTIVE_ADMIN_WORKFLOW,
    "Command Center": EXECUTIVE_OVERVIEW_WORKFLOW,
    "Forecasting": EXECUTIVE_COST_MOVEMENT_WORKFLOW,
}

__all__ = ['EXECUTIVE_LANDING_VERSION', 'PLATFORM_SUMMARY_STATE_KEY', 'OBSERVABILITY_STATE_KEY', 'OBSERVABILITY_OFFLINE_SOURCE', 'EXECUTIVE_OVERVIEW_WORKFLOW', 'EXECUTIVE_COST_MOVEMENT_WORKFLOW', 'EXECUTIVE_OPERATIONAL_RISK_WORKFLOW', 'EXECUTIVE_SECURITY_RISK_WORKFLOW', 'EXECUTIVE_CHANGE_SUMMARY_WORKFLOW', 'EXECUTIVE_ACTIONS_WORKFLOW', 'EXECUTIVE_ADMIN_WORKFLOW', 'EXECUTIVE_LANDING_WORKFLOWS', 'EXECUTIVE_LANDING_LEGACY_WORKFLOW_ALIASES']
