"""Executive Landing workflow contracts."""
from __future__ import annotations

from route_registry import WORKFLOW_ALIASES_BY_SECTION

EXECUTIVE_LANDING_VERSION = "2026-06-14-boardroom-glance-v2"
PLATFORM_SUMMARY_STATE_KEY = "executive_landing_platform_summary"
OBSERVABILITY_STATE_KEY = "executive_landing_observability_board"
OBSERVABILITY_OFFLINE_SOURCE = "Snowflake connection unavailable"

EXECUTIVE_OVERVIEW_WORKFLOW = "Executive Overview"
EXECUTIVE_COST_MOVEMENT_WORKFLOW = "Cost Movement"
EXECUTIVE_OPERATIONAL_RISK_WORKFLOW = "Operational Risk"
EXECUTIVE_SECURITY_RISK_WORKFLOW = "Security Risk"
EXECUTIVE_CHANGE_SUMMARY_WORKFLOW = "Change Summary"
EXECUTIVE_ACTIONS_WORKFLOW = "Executive Actions"
EXECUTIVE_ADMIN_WORKFLOW = "Executive Admin / Advanced"
EXECUTIVE_LANDING_WORKFLOWS = (
    EXECUTIVE_OVERVIEW_WORKFLOW,
    EXECUTIVE_COST_MOVEMENT_WORKFLOW,
    EXECUTIVE_OPERATIONAL_RISK_WORKFLOW,
    EXECUTIVE_SECURITY_RISK_WORKFLOW,
    EXECUTIVE_CHANGE_SUMMARY_WORKFLOW,
    EXECUTIVE_ACTIONS_WORKFLOW,
    EXECUTIVE_ADMIN_WORKFLOW,
)
EXECUTIVE_LANDING_WORKFLOW_DETAILS = {
    EXECUTIVE_OVERVIEW_WORKFLOW: "Board-ready status, movement, and next actions.",
    EXECUTIVE_COST_MOVEMENT_WORKFLOW: "Spend movement, cost drivers, and forecast context.",
    EXECUTIVE_OPERATIONAL_RISK_WORKFLOW: "Reliability, workload, and production-risk signals.",
    EXECUTIVE_SECURITY_RISK_WORKFLOW: "Security exposure, access, and governance blockers.",
    EXECUTIVE_CHANGE_SUMMARY_WORKFLOW: "Change drift, release movement, and migration risk.",
    EXECUTIVE_ACTIONS_WORKFLOW: "Owner actions and closure posture for leaders.",
    EXECUTIVE_ADMIN_WORKFLOW: "Advanced scorecards, evidence, and administrative telemetry.",
}
EXECUTIVE_LANDING_LEGACY_WORKFLOW_ALIASES = dict(WORKFLOW_ALIASES_BY_SECTION["Executive Landing"])

__all__ = ['EXECUTIVE_LANDING_VERSION', 'PLATFORM_SUMMARY_STATE_KEY', 'OBSERVABILITY_STATE_KEY', 'OBSERVABILITY_OFFLINE_SOURCE', 'EXECUTIVE_OVERVIEW_WORKFLOW', 'EXECUTIVE_COST_MOVEMENT_WORKFLOW', 'EXECUTIVE_OPERATIONAL_RISK_WORKFLOW', 'EXECUTIVE_SECURITY_RISK_WORKFLOW', 'EXECUTIVE_CHANGE_SUMMARY_WORKFLOW', 'EXECUTIVE_ACTIONS_WORKFLOW', 'EXECUTIVE_ADMIN_WORKFLOW', 'EXECUTIVE_LANDING_WORKFLOWS', 'EXECUTIVE_LANDING_WORKFLOW_DETAILS', 'EXECUTIVE_LANDING_LEGACY_WORKFLOW_ALIASES']
