"""Generated Decision Brief contracts. Do not edit by hand."""

from __future__ import annotations

from typing import Mapping

from sections.section_command_contracts import SectionCommandContract, _contract, _metrics, _sources

# Generated from config/decision_brief_contracts.json by scripts/generate_decision_brief_contracts.py.
SECTION_COMMAND_CONTRACTS: Mapping[str, SectionCommandContract] = {
    'Executive Landing': _contract(
        'Executive Landing',
        source_table='MART_SECTION_COMMAND_BRIEF',
        source_configs=_sources(
            60,
            ('executive_observability', 'MART_EXECUTIVE_OBSERVABILITY', True, 'allocated'),
            ('executive_scorecard', 'MART_EXECUTIVE_SCORECARD_SUMMARY', True, 'allocated'),
            ('executive_forecast', 'MART_EXECUTIVE_FORECAST_SUMMARY', True, 'estimated'),
            ('closed_loop', 'MART_CLOSED_LOOP_OPERATIONS_SUMMARY', True, 'allocated'),
            ('production_readiness', 'MART_PRODUCTION_READINESS_SUMMARY', True, 'allocated'),
            ('data_trust', 'MART_DATA_TRUST_SUMMARY', False, 'allocated'),
            ('app_observability', 'MART_APP_OBSERVABILITY_SUMMARY', False, 'allocated'),
        ),
        target_freshness_minutes=60,
        metric_contracts=_metrics(
            ('platform_health', 'Platform Health', True, 'percentage', 'score', 'lower_is_worse', 'executive_observability', 'required'),
            ('spend_movement_pct', 'Spend Movement', True, 'percentage', 'percent', 'higher_is_worse', 'executive_observability', 'required'),
            ('critical_high_issues', 'Critical / High Issues', True, 'integer', 'issues', 'higher_is_worse', 'executive_observability', 'required'),
            ('open_actions', 'Open Actions', True, 'integer', 'actions', 'higher_is_worse', 'executive_observability', 'required'),
            ('cortex_spend', 'Cortex AI Spend', False, 'currency', 'USD', 'higher_is_worse', 'executive_observability', 'optional'),
            ('cortex_risk', 'Cortex Risk', False, 'integer', 'signals', 'higher_is_worse', 'executive_observability', 'optional'),
            ('operational_risk', 'Operational Risk', False, 'integer', 'signals', 'higher_is_worse', 'executive_observability', 'optional'),
            ('security_risk', 'Security Risk', False, 'integer', 'signals', 'higher_is_worse', 'executive_observability', 'optional'),
            ('production_readiness', 'Production Readiness', False, 'percentage', 'percent', 'lower_is_worse', 'production_readiness', 'optional'),
            ('data_trust', 'Data Trust', False, 'percentage', 'percent', 'lower_is_worse', 'data_trust', 'optional'),
            ('verified_value', 'Verified Value', False, 'currency', 'USD', 'higher_is_better', 'executive_observability', 'optional'),
            ('monitoring_overhead', 'Monitoring Overhead', False, 'currency', 'USD', 'higher_is_worse', 'executive_observability', 'optional'),
        ),
        metric_labels=(
            'Platform Health',
            'Spend Movement',
            'Critical / High Issues',
            'Open Actions',
            'Cortex AI Spend',
            'Cortex Risk',
            'Operational Risk',
            'Security Risk',
        ),
        unavailable_headline='Executive command brief needs the summary mart.',
        unavailable_summary='Enable the executive observability mart to populate leadership status, cost movement, Cortex AI risk, and open actions automatically.',
        top_signal_label='Top executive decision',
        top_signal_detail='Review cost, operational, and security signals before loading the full snapshot.',
        next_actions=(
            ('Review Cortex AI Cost & Predictive Alerts', 'Open the Cortex AI financial-risk lane.', 'Cost & Contract', 'Cortex AI'),
            ('Investigate Active Alerts', 'Open current alert families and route the highest-severity item.', 'Alert Center', 'Active Alerts'),
            ('Open DBA Cockpit', 'Open DBA-owned failures, queue pressure, and action status.', 'DBA Control Room', 'Morning Cockpit'),
        ),
        fallback_route_keys=(
            'cost_contract_cortex_ai',
            'alert_center_active',
            'dba_overview',
        ),
    ),
    'DBA Control Room': _contract(
        'DBA Control Room',
        source_table='MART_SECTION_COMMAND_BRIEF',
        source_configs=_sources(
            30,
            ('query_hourly', 'MART_DBA_CONTROL_ROOM', True, 'allocated'),
            ('query_hourly', 'FACT_QUERY_HOURLY', True, 'allocated'),
            ('task_runs', 'FACT_TASK_RUN', True, 'allocated'),
            ('action_queue', 'OVERWATCH_ACTION_QUEUE', True, 'allocated'),
            ('change_summary', 'MART_CHANGE_INTELLIGENCE_SUMMARY', False, 'allocated'),
            ('security_operability', 'FACT_SECURITY_OPERABILITY_DAILY', False, 'allocated'),
            ('cost_daily', 'FACT_COST_DAILY', False, 'allocated'),
        ),
        target_freshness_minutes=30,
        metric_contracts=_metrics(
            ('failed_queries', 'Failed Queries', True, 'integer', 'queries', 'higher_is_worse', 'query_hourly', 'required'),
            ('pipeline_failures', 'Pipeline Failures', True, 'integer', 'events', 'higher_is_worse', 'task_runs', 'required'),
            ('queue_pressure', 'Queue Pressure', True, 'duration', 'seconds', 'higher_is_worse', 'query_hourly', 'required'),
            ('cost_24h', 'Cost 24h', True, 'currency', 'USD', 'higher_is_worse', 'cost_daily', 'required'),
            ('cortex_cost', 'Cortex Cost', False, 'currency', 'USD', 'higher_is_worse', 'cortex_daily', 'optional'),
            ('security_warnings', 'Security Warnings', False, 'integer', 'warnings', 'higher_is_worse', 'security_operability', 'optional'),
            ('recent_changes', 'Recent Changes', False, 'integer', 'changes', 'higher_is_worse', 'change_summary', 'optional'),
            ('overdue_actions', 'Overdue Actions', False, 'integer', 'actions', 'higher_is_worse', 'action_queue', 'optional'),
            ('hottest_warehouse', 'Hottest Warehouse', False, 'text', 'warehouse', 'neutral', 'dba_control_room', 'optional'),
            ('top_dba_risk', 'Top DBA Risk', False, 'text', 'risk', 'neutral', 'dba_control_room', 'optional'),
        ),
        metric_labels=(
            'Failed Queries',
            'Pipeline Failures',
            'Queue Pressure',
            'Cost 24h',
            'Cortex Cost',
            'Security Warnings',
            'Recent Changes',
            'Overdue Actions',
        ),
        unavailable_headline='DBA command brief needs the control-room mart.',
        unavailable_summary='Enable the latest control-room snapshot to populate failures, cost pressure, queue pressure, security warnings, and recent changes automatically.',
        top_signal_label='Top DBA action',
        top_signal_detail='Start with the highest operational exception, then load investigation detail if proof is needed.',
        next_actions=(
            ('Failure Triage', 'Review failed SQL, task, procedure, copy, and SLA signals.', 'DBA Control Room', 'Failure Triage'),
            ('Performance Watch', 'Review queue, spilling, blocked, and long-running pressure.', 'DBA Control Room', 'Performance Watch'),
            ('Cost Watch', 'Review spend pressure, Cortex cost, and largest drivers.', 'DBA Control Room', 'Cost Watch'),
        ),
        fallback_route_keys=(
            'dba_failures',
            'dba_performance',
            'cost_contract_explorer_warehouse',
        ),
    ),
    'Alert Center': _contract(
        'Alert Center',
        source_table='MART_SECTION_COMMAND_BRIEF',
        source_configs=_sources(
            15,
            ('alert_events', 'ALERT_EVENTS', True, 'exact'),
            ('action_queue', 'OVERWATCH_ACTION_QUEUE', True, 'allocated'),
            ('notification_log', 'ALERT_NOTIFICATION_LOG', True, 'exact'),
            ('acknowledgements', 'ALERT_ACKNOWLEDGEMENTS', False, 'exact'),
        ),
        target_freshness_minutes=15,
        metric_contracts=_metrics(
            ('active_alerts', 'Active Alerts', True, 'integer', 'alerts', 'higher_is_worse', 'alert_events', 'required'),
            ('critical_high', 'Critical / High', True, 'integer', 'alerts', 'higher_is_worse', 'alert_events', 'required'),
            ('overdue_alerts', 'Overdue Alerts', True, 'integer', 'alerts', 'higher_is_worse', 'alert_events', 'required'),
            ('cortex_predictive', 'Cortex Predictive', True, 'integer', 'alerts', 'higher_is_worse', 'alert_events', 'required'),
            ('cost_alerts', 'Cost Alerts', False, 'integer', 'alerts', 'higher_is_worse', 'alert_events', 'optional'),
            ('reliability_alerts', 'Reliability Alerts', False, 'integer', 'alerts', 'higher_is_worse', 'alert_events', 'optional'),
            ('security_alerts', 'Security Alerts', False, 'integer', 'alerts', 'higher_is_worse', 'alert_events', 'optional'),
            ('notification_failures', 'Notification Failures', False, 'integer', 'events', 'higher_is_worse', 'notification_log', 'optional'),
            ('unassigned_alerts', 'Unassigned Alerts', False, 'integer', 'alerts', 'higher_is_worse', 'alert_events', 'optional'),
            ('open_action_queue', 'Open Action Queue', False, 'integer', 'actions', 'higher_is_worse', 'action_queue', 'optional'),
        ),
        metric_labels=(
            'Active Alerts',
            'Critical / High',
            'Overdue Alerts',
            'Cortex Predictive',
            'Cost Alerts',
            'Reliability Alerts',
            'Security Alerts',
            'Notification Failures',
        ),
        unavailable_headline='Alert command brief needs alert summary telemetry.',
        unavailable_summary='Enable alert summary marts to populate active, critical, Cortex predictive, cost, reliability, security, and delivery lanes automatically.',
        top_signal_label='Top alert family',
        top_signal_detail='Work the highest severity family first; load alert rows only when row-level evidence is needed.',
        next_actions=(
            ('Open Cortex Predictive', 'Review forecasted Cortex spend and anomaly alerts.', 'Alert Center', 'Cortex Predictive Alerts'),
            ('Review Security Alerts', 'Open security alert family and access-risk routes.', 'Alert Center', 'Security Alerts'),
            ('Review Critical / High', 'Open the highest-severity active alert family.', 'Alert Center', 'Critical / High'),
        ),
        fallback_route_keys=(
            'alert_cortex_predictive',
            'alert_center_security',
            'alert_center_critical_high',
        ),
    ),
    'Cost & Contract': _contract(
        'Cost & Contract',
        source_table='MART_SECTION_COMMAND_BRIEF',
        source_configs=_sources(
            60,
            ('cost_daily', 'FACT_COST_DAILY', True, 'allocated'),
            ('cortex_daily', 'FACT_CORTEX_DAILY', True, 'estimated'),
            ('cost_signals', 'FACT_COST_MONITORING_SIGNAL', True, 'allocated'),
            ('forecast', 'MART_EXECUTIVE_FORECAST_SUMMARY', False, 'estimated'),
            ('value_ledger', 'MART_EXECUTIVE_VALUE_LEDGER', False, 'allocated'),
            ('settings', 'OVERWATCH_SETTINGS', True, 'exact'),
        ),
        target_freshness_minutes=60,
        metric_contracts=_metrics(
            ('total_spend', 'Total Spend', True, 'currency', 'USD', 'higher_is_worse', 'cost_daily', 'required'),
            ('spend_movement_pct', 'Spend Movement', True, 'percentage', 'percent', 'higher_is_worse', 'cost_daily', 'required'),
            ('forecast_run_rate', 'Forecast / Run-rate', True, 'currency', 'USD', 'higher_is_worse', 'forecast', 'required'),
            ('cortex_spend_share', 'Cortex Spend Share', True, 'percentage', 'percent', 'higher_is_worse', 'cortex_daily', 'required'),
            ('cortex_spend', 'Cortex AI Spend', False, 'currency', 'USD', 'higher_is_worse', 'cortex_daily', 'optional'),
            ('cortex_predictive_alerts', 'Cortex Predictive Alerts', False, 'integer', 'alerts', 'higher_is_worse', 'cortex_daily', 'optional'),
            ('budget_contract_risk', 'Budget / Contract Risk', False, 'integer', 'signals', 'higher_is_worse', 'cost_daily', 'optional'),
            ('top_cost_driver', 'Top Cost Driver', False, 'text', 'driver', 'neutral', 'cost_daily', 'optional'),
            ('verified_savings', 'Verified Savings', False, 'currency', 'USD', 'higher_is_better', 'cost_daily', 'optional'),
            ('unverified_savings', 'Unverified Savings', False, 'currency', 'USD', 'higher_is_worse', 'cost_daily', 'optional'),
            ('open_cost_actions', 'Open Cost Actions', False, 'integer', 'actions', 'higher_is_worse', 'cost_daily', 'optional'),
        ),
        metric_labels=(
            'Total Spend',
            'Spend Movement',
            'Forecast / Run-rate',
            'Cortex Spend Share',
            'Cortex AI Spend',
            'Cortex Predictive Alerts',
            'Budget / Contract Risk',
            'Top Cost Driver',
        ),
        unavailable_headline='Cost command brief needs cost summary telemetry.',
        unavailable_summary='Enable cost summary marts to populate spend, run-rate, Cortex AI cost, predictive alerts, budget risk, top driver, and savings actions automatically.',
        top_signal_label='Top cost signal',
        top_signal_detail='Review the largest movement or Cortex risk before loading detailed cost explorer rows.',
        next_actions=(
            ('Review Cortex AI Costs', 'Open Cortex spend, forecast, top drivers, and predictive alerts.', 'Cost & Contract', 'Cortex AI'),
            ('Open Warehouse Drivers', 'Open Cost Explorer by warehouse without loading detail rows.', 'Cost & Contract', 'Cost Explorer'),
            ('Check Budget Risk', 'Open budget, allocation, and contract posture.', 'Cost & Contract', 'Budget vs Actual'),
        ),
        fallback_route_keys=(
            'cost_contract_cortex_ai',
            'cost_contract_explorer_warehouse',
            'cost_contract_budget',
        ),
    ),
    'Workload Operations': _contract(
        'Workload Operations',
        source_table='MART_SECTION_COMMAND_BRIEF',
        source_configs=_sources(
            30,
            ('query_hourly', 'FACT_QUERY_HOURLY', True, 'allocated'),
            ('query_recent', 'FACT_QUERY_DETAIL_RECENT', False, 'allocated'),
            ('task_runs', 'FACT_TASK_RUN', True, 'allocated'),
            ('procedure_runs', 'FACT_PROCEDURE_RUN', True, 'allocated'),
            ('copy_load', 'FACT_COPY_LOAD_DAILY', True, 'allocated'),
            ('change_summary', 'MART_CHANGE_INTELLIGENCE_SUMMARY', False, 'allocated'),
        ),
        target_freshness_minutes=30,
        metric_contracts=_metrics(
            ('failed_queries', 'Failed Queries', True, 'integer', 'queries', 'higher_is_worse', 'query_hourly', 'required'),
            ('pipeline_failures', 'Pipeline Failures', True, 'integer', 'events', 'higher_is_worse', 'query_hourly', 'required'),
            ('queue_blocked_pressure', 'Queue / Blocked Pressure', True, 'duration', 'seconds', 'higher_is_worse', 'query_hourly', 'required'),
            ('sla_risk', 'SLA Risk', True, 'integer', 'items', 'higher_is_worse', 'query_hourly', 'required'),
            ('spill_bytes', 'Spill Bytes', False, 'bytes', 'bytes', 'higher_is_worse', 'query_hourly', 'optional'),
            ('long_running_queries', 'Long Running Queries', False, 'integer', 'queries', 'higher_is_worse', 'query_hourly', 'optional'),
            ('hottest_warehouse', 'Hottest Warehouse', False, 'text', 'warehouse', 'neutral', 'query_hourly', 'optional'),
            ('recent_workload_changes', 'Recent Workload Changes', False, 'integer', 'changes', 'higher_is_worse', 'query_recent', 'optional'),
            ('suspended_tasks', 'Suspended Tasks', False, 'integer', 'tasks', 'higher_is_worse', 'query_hourly', 'optional'),
            ('copy_load_failures', 'Copy / Load Failures', False, 'integer', 'events', 'higher_is_worse', 'copy_load', 'optional'),
        ),
        metric_labels=(
            'Failed Queries',
            'Pipeline Failures',
            'Queue / Blocked Pressure',
            'SLA Risk',
            'Spill Bytes',
            'Long Running Queries',
            'Hottest Warehouse',
            'Recent Workload Changes',
        ),
        unavailable_headline='Workload command brief needs workload summary telemetry.',
        unavailable_summary='Enable workload/reliability summary marts to populate failed SQL, failed tasks, pipeline risk, queue pressure, and recent changes automatically.',
        top_signal_label='Top workload action',
        top_signal_detail='Open the owning investigation workflow, then load detail only for the selected incident.',
        next_actions=(
            ('Query Investigation', 'Open SQL history, diagnosis, and top SQL routes.', 'Workload Operations', 'Query Investigation'),
            ('Pipeline & Tasks', 'Open failed tasks, procedures, copy/load, and SLA risk.', 'Workload Operations', 'Pipeline & Task Health'),
            ('Performance Pressure', 'Open queue, blocked, spilling, and warehouse pressure lanes.', 'Workload Operations', 'Performance & Contention'),
        ),
        fallback_route_keys=(
            'workload_query_investigation',
            'workload_pipeline_tasks',
            'workload_performance',
        ),
    ),
    'Security Monitoring': _contract(
        'Security Monitoring',
        source_table='MART_SECTION_COMMAND_BRIEF',
        source_configs=_sources(
            60,
            ('security_operability', 'FACT_SECURITY_OPERABILITY_DAILY', True, 'allocated'),
            ('login_daily', 'FACT_LOGIN_DAILY', True, 'allocated'),
            ('grant_daily', 'FACT_GRANT_DAILY', True, 'allocated'),
            ('security_alerts', 'ALERT_EVENTS', True, 'allocated'),
            ('owner_coverage', 'MART_OPERATIONAL_OWNER_COVERAGE', True, 'allocated'),
            ('change_summary', 'MART_CHANGE_INTELLIGENCE_SUMMARY', False, 'allocated'),
        ),
        target_freshness_minutes=60,
        metric_contracts=_metrics(
            ('failed_logins', 'Failed Logins', True, 'integer', 'logins', 'higher_is_worse', 'login_daily', 'required'),
            ('mfa_gaps', 'MFA Gaps', True, 'integer', 'users', 'higher_is_worse', 'security_operability', 'required'),
            ('risky_grants', 'Risky Grants', True, 'integer', 'grants', 'higher_is_worse', 'grant_daily', 'required'),
            ('sharing_exposure', 'Sharing Exposure', True, 'integer', 'databases', 'higher_is_worse', 'security_operability', 'required'),
            ('privilege_changes', 'Privilege Changes', False, 'integer', 'changes', 'higher_is_worse', 'security_operability', 'optional'),
            ('security_alerts', 'Security Alerts', False, 'integer', 'alerts', 'higher_is_worse', 'security_operability', 'optional'),
            ('access_changes', 'Access Changes', False, 'integer', 'changes', 'higher_is_worse', 'security_operability', 'optional'),
            ('unassigned_findings', 'Unassigned Findings', False, 'integer', 'findings', 'higher_is_worse', 'security_operability', 'optional'),
            ('overdue_security_actions', 'Overdue Security Actions', False, 'integer', 'actions', 'higher_is_worse', 'security_operability', 'optional'),
            ('owner_coverage', 'Owner Coverage', False, 'percentage', 'percent', 'lower_is_worse', 'owner_coverage', 'optional'),
        ),
        metric_labels=(
            'Failed Logins',
            'MFA Gaps',
            'Risky Grants',
            'Sharing Exposure',
            'Privilege Changes',
            'Security Alerts',
            'Access Changes',
            'Unassigned Findings',
        ),
        unavailable_headline='Security command brief needs security summary telemetry.',
        unavailable_summary='Enable security summary marts to populate failed logins, risky grants, sharing, access changes, alerts, and the top security action automatically.',
        top_signal_label='Top security action',
        top_signal_detail='Review the most exposed identity, grant, sharing, or access-change signal before loading proof tables.',
        next_actions=(
            ('Review Security Alerts', 'Open active security alert context when evidence is loaded.', 'Security Monitoring', 'Security Alerts'),
            ('Review Risky Grants', 'Open grants, role scope, and ownership exposure.', 'Security Monitoring', 'Risky Grants'),
            ('Review Access Changes', 'Open recent grants, revokes, role changes, and admin changes.', 'Security Monitoring', 'Access Changes'),
        ),
        fallback_route_keys=(
            'security_alerts',
            'security_access_changes',
            'security_failed_logins',
        ),
    ),
}

CANONICAL_COMMAND_BRIEF_SECTIONS = tuple(SECTION_COMMAND_CONTRACTS)
