-- -----------------------------------------------------------------------------
-- 1b. Access roles
-- -----------------------------------------------------------------------------

CREATE ROLE IF NOT EXISTS SNOW_ACCOUNTADMINS;
CREATE ROLE IF NOT EXISTS SNOW_SYSADMINS;

GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE SNOW_ACCOUNTADMINS;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE SNOW_SYSADMINS;

GRANT USAGE ON WAREHOUSE WH_ALFA_OVERWATCH TO ROLE SNOW_ACCOUNTADMINS;
GRANT USAGE ON WAREHOUSE WH_ALFA_OVERWATCH TO ROLE SNOW_SYSADMINS;

GRANT USAGE ON DATABASE DBA_MAINT_DB TO ROLE SNOW_ACCOUNTADMINS;
GRANT USAGE ON DATABASE DBA_MAINT_DB TO ROLE SNOW_SYSADMINS;
GRANT USAGE ON SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE SNOW_ACCOUNTADMINS;
GRANT USAGE ON SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE SNOW_SYSADMINS;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE SNOW_ACCOUNTADMINS;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE SNOW_SYSADMINS;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE SNOW_ACCOUNTADMINS;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE SNOW_SYSADMINS;
GRANT SELECT ON ALL VIEWS IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE SNOW_ACCOUNTADMINS;
GRANT SELECT ON ALL VIEWS IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE SNOW_SYSADMINS;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE SNOW_ACCOUNTADMINS;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE SNOW_SYSADMINS;

COMMENT ON ROLE SNOW_ACCOUNTADMINS IS
    'Temporary OVERWATCH admin access role for account-level DBA monitoring and guarded actions.';
COMMENT ON ROLE SNOW_SYSADMINS IS
    'Temporary OVERWATCH admin access role for system DBA monitoring and guarded actions.';

