-- -----------------------------------------------------------------------------
-- 2. Configuration and audit tables
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS OVERWATCH_SETTINGS (
  SETTING_NAME        VARCHAR(200) PRIMARY KEY,
  SETTING_VALUE       VARCHAR(4000),
  SETTING_TYPE        VARCHAR(50),
  DESCRIPTION         VARCHAR(1000),
  UPDATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY          VARCHAR(200) DEFAULT CURRENT_USER()
);

MERGE INTO OVERWATCH_SETTINGS tgt
USING (
  SELECT * FROM VALUES
    ('CREDIT_PRICE_USD', '3.68', 'NUMBER', 'Contract credit price used for estimated cost display.'),
    ('AI_CREDIT_PRICE_USD', '2.20', 'NUMBER', 'Cortex AI/token credit price used for estimated AI cost display.'),
    ('STORAGE_COST_PER_TB_USD', '23.00', 'NUMBER', 'Standard storage cost per TB-month used for estimated storage cost display.'),
    ('MART_QUERY_RETENTION_DAYS', '35', 'NUMBER', 'Rolling window reloaded from ACCOUNT_USAGE query history.'),
    ('HOURLY_REFRESH_LOOKBACK_DAYS', '3', 'NUMBER', 'Small rolling window used by scheduled hourly loader units to avoid warehouse statement timeout. Use explicit unit/window calls for backfill.'),
    ('HOURLY_REFRESH_COMPAT_WRAPPER_ENABLED', 'FALSE', 'BOOLEAN', 'Safety guard for SP_OVERWATCH_LOAD_HOURLY. Keep false on timeout-sensitive warehouses and use the hourly task graph or explicit unit calls.'),
    ('DETAIL_RETENTION_DAYS', '30', 'NUMBER', 'Retention for recent query/task/procedure detail marts.'),
    ('AGG_RETENTION_DAYS', '730', 'NUMBER', 'Retention for hourly and daily aggregate marts.'),
    ('SLA_DURATION_MULTIPLIER', '1.5', 'NUMBER', 'Flags task/procedure latest duration over this multiple of historical average.'),
    ('DEFAULT_ALERT_EMAIL', 'jdees@alfains.com', 'STRING', 'Approved default email recipient list for OVERWATCH alert messages. Override only through governance-approved Snowflake settings.'),
    ('ALERT_DELIVERY_METHOD', 'EMAIL', 'STRING', 'Alert delivery channel used by the OVERWATCH anomaly task.'),
    ('ALERT_EMAIL_NOTIFICATION_INTEGRATION', 'OVERWATCH_EMAIL_INT', 'STRING', 'Approved Snowflake notification integration name for optional Alert Center email delivery.'),
    ('DEFAULT_ALERT_EMAILS', '["jdees@alfains.com"]', 'JSON', 'Governed default alert recipients. App constants are fallback only when settings are unavailable.'),
    ('ALFA_WAREHOUSES', '["BI_COMPUTE_WH","WH_ALFA_OVERWATCH","CROWDSTRIKE_WH","DOC_AI_WH","POSIT_WORKBENCH","SNOWFLAKE_LEARNING_WH","SYSTEM$STREAMLIT_NOTEBOOK_WH","WH_ALFA_ANALYTICS","WH_ALFA_LOAD","WH_ALFA_LOAD_PRD","WH_ALFA_QA","WH_ALFA_QUERY","WH_ALFA_TRANSFORM","WH_ALFA_TRANSFORM_PRD","WH_ALFA_UNLOAD","WH_ALFA_UNLOAD_PRD"]', 'JSON', 'Governed ALFA warehouse list used by scope controls and summary loaders.'),
    ('TREXIS_WAREHOUSES', '["WH_TRXS_LOAD","WH_TRXS_QUERY","WH_TRXS_TRANSFORM","WH_TRXS_UNLOAD"]', 'JSON', 'Governed Trexis warehouse list used by scope controls and summary loaders.'),
    ('ALL_WAREHOUSES', '["BI_COMPUTE_WH","WH_ALFA_OVERWATCH","CROWDSTRIKE_WH","DOC_AI_WH","POSIT_WORKBENCH","SNOWFLAKE_LEARNING_WH","SYSTEM$STREAMLIT_NOTEBOOK_WH","WH_ALFA_ANALYTICS","WH_ALFA_LOAD","WH_ALFA_LOAD_PRD","WH_ALFA_QA","WH_ALFA_QUERY","WH_ALFA_TRANSFORM","WH_ALFA_TRANSFORM_PRD","WH_ALFA_UNLOAD","WH_ALFA_UNLOAD_PRD","WH_TRXS_LOAD","WH_TRXS_QUERY","WH_TRXS_TRANSFORM","WH_TRXS_UNLOAD"]', 'JSON', 'Governed combined warehouse list. Keep aligned with company-specific warehouse settings.'),
    ('ADMIN_ACCESS_ROLES', '["SNOW_ACCOUNTADMINS","SNOW_SYSADMINS"]', 'JSON', 'Governed admin roles for Setup Health and guarded live actions.'),
    ('COMPANY_DEFINITIONS', '{"ALFA":{"label":"ALFA","color":"#34d399"},"Trexis":{"label":"Trexis","color":"#c084fc"},"ALL":{"label":"ALL","color":"#38bdf8"}}', 'JSON', 'Governed company display definitions.'),
    ('COMPANY_DATABASE_PATTERNS', '{"ALFA":["ADMIN","ALFA%"],"Trexis":["TRXS_ABC_METADATA_%","TRXS_EDW_%","TRXS_GW_DATA_%"],"ALL":[]}', 'JSON', 'Governed company database routing patterns.'),
    ('NOTIFICATION_SETTINGS', '{"default_channel":"EMAIL","slack_enabled":false,"teams_enabled":false,"pagerduty_enabled":false}', 'JSON', 'Governed notification routing settings. Webhook secrets are configured outside source code.'),
    ('REFRESH_WAREHOUSE', 'WH_ALFA_OVERWATCH', 'STRING', 'Warehouse used by summary mart refresh tasks until a dedicated OVERWATCH refresh warehouse is approved.'),
    ('AUTO_BOOTSTRAP_DECISION_BRIEFS', 'TRUE', 'BOOLEAN', 'Allow the setup flow to initialize Decision Brief packets after prerequisite marts are refreshed.'),
    ('DECISION_BRIEF_BOOTSTRAP_ROLE', 'SNOW_SYSADMINS', 'STRING', 'Role allowed to initialize Decision Brief packets during installation or setup health repair.'),
    ('DECISION_BRIEF_BOOTSTRAP_PROCEDURE', 'SP_OVERWATCH_BOOTSTRAP_DECISION_BRIEFS', 'STRING', 'Preferred procedure for Decision Brief setup health initialization.'),
    ('DECISION_BRIEF_WAREHOUSE', 'WH_ALFA_OVERWATCH', 'STRING', 'Warehouse used by scheduled Decision Brief refresh tasks when a dedicated warehouse is not configured.'),
    ('DECISION_BRIEF_ALLOW_LEGACY_ADAPTER', 'TRUE', 'BOOLEAN', 'Allow bounded compact legacy-mart adapters when the normalized Decision packet is not current.'),
    ('OVERWATCH_ENABLE_CLUSTER_KEYS', 'TRUE', 'BOOLEAN', 'Edition-safe optional clustering for compact packet and evidence lookup marts.'),
    ('OVERWATCH_ENABLE_SEARCH_OPTIMIZATION', 'FALSE', 'BOOLEAN', 'Enterprise-only search optimization guard. Disabled by default and applied only by explicit admin choice.')
) src(SETTING_NAME, SETTING_VALUE, SETTING_TYPE, DESCRIPTION)
ON tgt.SETTING_NAME = src.SETTING_NAME
WHEN MATCHED THEN UPDATE SET
  SETTING_VALUE = CASE
    WHEN src.SETTING_NAME = 'DEFAULT_ALERT_EMAIL'
      THEN IFF(NULLIF(TRIM(COALESCE(tgt.SETTING_VALUE, '')), '') IS NULL OR COALESCE(tgt.SETTING_VALUE, '') ILIKE '%yourcompany.com%', src.SETTING_VALUE, tgt.SETTING_VALUE)
    ELSE tgt.SETTING_VALUE
  END,
  SETTING_TYPE = src.SETTING_TYPE,
  DESCRIPTION = src.DESCRIPTION
WHEN NOT MATCHED THEN INSERT (SETTING_NAME, SETTING_VALUE, SETTING_TYPE, DESCRIPTION)
VALUES (src.SETTING_NAME, src.SETTING_VALUE, src.SETTING_TYPE, src.DESCRIPTION);

CREATE TABLE IF NOT EXISTS OVERWATCH_SCHEMA_MIGRATION (
  MIGRATION_VERSION   VARCHAR(100) NOT NULL,
  MIGRATION_NAME      VARCHAR(300) NOT NULL,
  APPLIED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  APPLIED_BY          VARCHAR(200) DEFAULT CURRENT_USER(),
  SOURCE_FILE         VARCHAR(500),
  NOTES               VARCHAR(1000)
);

MERGE INTO OVERWATCH_SCHEMA_MIGRATION tgt
USING (
  SELECT
    '2026.06.13-executive-observability-mart' AS MIGRATION_VERSION,
    'Executive observability mart, cost telemetry, procedure context, alert delivery, and migration ledger' AS MIGRATION_NAME,
    'snowflake/OVERWATCH_MART_SETUP.sql' AS SOURCE_FILE,
    'Baseline setup ledger row for the app release, including the executive first-paint observability mart, cost telemetry marts, procedure database/schema context, alert delivery, and migration tracking.' AS NOTES
) src
ON tgt.MIGRATION_VERSION = src.MIGRATION_VERSION
WHEN MATCHED THEN UPDATE SET
  MIGRATION_NAME = src.MIGRATION_NAME,
  SOURCE_FILE = src.SOURCE_FILE,
  NOTES = src.NOTES
WHEN NOT MATCHED THEN INSERT (MIGRATION_VERSION, MIGRATION_NAME, SOURCE_FILE, NOTES)
VALUES (src.MIGRATION_VERSION, src.MIGRATION_NAME, src.SOURCE_FILE, src.NOTES);

MERGE INTO OVERWATCH_SCHEMA_MIGRATION tgt
USING (
  SELECT
    '2026.06.17-enterprise-operating-model' AS MIGRATION_VERSION,
    'Data trust, operational ownership, value ledger, and app self-observability marts' AS MIGRATION_NAME,
    'snowflake/OVERWATCH_MART_SETUP.sql' AS SOURCE_FILE,
    'Adds the Phase 1 enterprise operating model: Finding -> Owner -> Trust Level -> Business Impact -> Action -> Value Verified. First-paint surfaces read compact marts; detail evidence remains explicit-load only.' AS NOTES
) src
ON tgt.MIGRATION_VERSION = src.MIGRATION_VERSION
WHEN MATCHED THEN UPDATE SET
  MIGRATION_NAME = src.MIGRATION_NAME,
  SOURCE_FILE = src.SOURCE_FILE,
  NOTES = src.NOTES
WHEN NOT MATCHED THEN INSERT (MIGRATION_VERSION, MIGRATION_NAME, SOURCE_FILE, NOTES)
VALUES (src.MIGRATION_VERSION, src.MIGRATION_NAME, src.SOURCE_FILE, src.NOTES);

MERGE INTO OVERWATCH_SCHEMA_MIGRATION tgt
USING (
  SELECT
    '2026.06.18-production-readiness' AS MIGRATION_VERSION,
    'Production readiness dashboard, role/privilege/readiness validation, and refresh health marts' AS MIGRATION_NAME,
    'snowflake/OVERWATCH_MART_SETUP.sql' AS SOURCE_FILE,
    'Adds Phase 2A live production validation. First-paint surfaces read a compact readiness mart; role, privilege, validation, and refresh proof rows remain explicit-load diagnostics.' AS NOTES
) src
ON tgt.MIGRATION_VERSION = src.MIGRATION_VERSION
WHEN MATCHED THEN UPDATE SET
  MIGRATION_NAME = src.MIGRATION_NAME,
  SOURCE_FILE = src.SOURCE_FILE,
  NOTES = src.NOTES
WHEN NOT MATCHED THEN INSERT (MIGRATION_VERSION, MIGRATION_NAME, SOURCE_FILE, NOTES)
VALUES (src.MIGRATION_VERSION, src.MIGRATION_NAME, src.SOURCE_FILE, src.NOTES);

MERGE INTO OVERWATCH_SCHEMA_MIGRATION tgt
USING (
  SELECT
    '2026.06.18-executive-scorecard' AS MIGRATION_VERSION,
    'Executive Scorecard leadership health scoring across health, cost, security, risk, trust, and production readiness' AS MIGRATION_NAME,
    'snowflake/OVERWATCH_MART_SETUP.sql' AS SOURCE_FILE,
    'Adds Phase 2B Executive Scorecard. First-paint surfaces read compact scorecard marts; driver evidence remains explicit-load only.' AS NOTES
) src
ON tgt.MIGRATION_VERSION = src.MIGRATION_VERSION
WHEN MATCHED THEN UPDATE SET
  MIGRATION_NAME = src.MIGRATION_NAME,
  SOURCE_FILE = src.SOURCE_FILE,
  NOTES = src.NOTES
WHEN NOT MATCHED THEN INSERT (MIGRATION_VERSION, MIGRATION_NAME, SOURCE_FILE, NOTES)
VALUES (src.MIGRATION_VERSION, src.MIGRATION_NAME, src.SOURCE_FILE, src.NOTES);

MERGE INTO OVERWATCH_SCHEMA_MIGRATION tgt
USING (
  SELECT
    '2026.06.18-executive-forecasting' AS MIGRATION_VERSION,
    'Executive forecasting for cost, contract burn, storage, queue pressure, and SLA risk' AS MIGRATION_NAME,
    'snowflake/OVERWATCH_MART_SETUP.sql' AS SOURCE_FILE,
    'Adds Phase 2C Forecasting. First-paint surfaces read compact forecast summaries; historical forecast drivers and evidence remain explicit-load only. Forecasts are estimates and are not counted as verified savings.' AS NOTES
) src
ON tgt.MIGRATION_VERSION = src.MIGRATION_VERSION
WHEN MATCHED THEN UPDATE SET
  MIGRATION_NAME = src.MIGRATION_NAME,
  SOURCE_FILE = src.SOURCE_FILE,
  NOTES = src.NOTES
WHEN NOT MATCHED THEN INSERT (MIGRATION_VERSION, MIGRATION_NAME, SOURCE_FILE, NOTES)
VALUES (src.MIGRATION_VERSION, src.MIGRATION_NAME, src.SOURCE_FILE, src.NOTES);

MERGE INTO OVERWATCH_SCHEMA_MIGRATION tgt
USING (
  SELECT
    '2026.06.18-change-intelligence' AS MIGRATION_VERSION,
    'Change Intelligence for warehouse, access, object, task, procedure, policy, and integration changes' AS MIGRATION_NAME,
    'snowflake/OVERWATCH_MART_SETUP.sql' AS SOURCE_FILE,
    'Adds Phase 2D Change Intelligence. First-paint surfaces read compact change-risk summaries; change evidence and possible correlations remain explicit-load only. Correlations are not root-cause claims.' AS NOTES
) src
ON tgt.MIGRATION_VERSION = src.MIGRATION_VERSION
WHEN MATCHED THEN UPDATE SET
  MIGRATION_NAME = src.MIGRATION_NAME,
  SOURCE_FILE = src.SOURCE_FILE,
  NOTES = src.NOTES
WHEN NOT MATCHED THEN INSERT (MIGRATION_VERSION, MIGRATION_NAME, SOURCE_FILE, NOTES)
VALUES (src.MIGRATION_VERSION, src.MIGRATION_NAME, src.SOURCE_FILE, src.NOTES);

MERGE INTO OVERWATCH_SCHEMA_MIGRATION tgt
USING (
  SELECT
    '2026.06.18-closed-loop-operations' AS MIGRATION_VERSION,
    'Closed Loop Operations for action, approval, execution-plan, verification, and value evidence' AS MIGRATION_NAME,
    'snowflake/OVERWATCH_MART_SETUP.sql' AS SOURCE_FILE,
    'Adds Phase 2E Closed Loop Operations. First-paint surfaces read compact action workflow summaries; approval, review SQL, evidence, and verification detail remain explicit-load only. No remediation SQL is executed by the refresh procedure.' AS NOTES
) src
ON tgt.MIGRATION_VERSION = src.MIGRATION_VERSION
WHEN MATCHED THEN UPDATE SET
  MIGRATION_NAME = src.MIGRATION_NAME,
  SOURCE_FILE = src.SOURCE_FILE,
  NOTES = src.NOTES
WHEN NOT MATCHED THEN INSERT (MIGRATION_VERSION, MIGRATION_NAME, SOURCE_FILE, NOTES)
VALUES (src.MIGRATION_VERSION, src.MIGRATION_NAME, src.SOURCE_FILE, src.NOTES);

MERGE INTO OVERWATCH_SCHEMA_MIGRATION tgt
USING (
  SELECT
    '2026.06.18-command-center' AS MIGRATION_VERSION,
    'Correlated investigation support for cost, performance, alert, ownership, trust, security, change, forecast, value, and action evidence' AS MIGRATION_NAME,
    'snowflake/OVERWATCH_MART_SETUP.sql' AS SOURCE_FILE,
    'Adds Phase 2F correlated investigations. First-paint surfaces read compact investigation findings; evidence and recommendations remain explicit-load only. Root-cause language is candidate/correlation based and no remediation is executed.' AS NOTES
) src
ON tgt.MIGRATION_VERSION = src.MIGRATION_VERSION
WHEN MATCHED THEN UPDATE SET
  MIGRATION_NAME = src.MIGRATION_NAME,
  SOURCE_FILE = src.SOURCE_FILE,
  NOTES = src.NOTES
WHEN NOT MATCHED THEN INSERT (MIGRATION_VERSION, MIGRATION_NAME, SOURCE_FILE, NOTES)
VALUES (src.MIGRATION_VERSION, src.MIGRATION_NAME, src.SOURCE_FILE, src.NOTES);

MERGE INTO OVERWATCH_SCHEMA_MIGRATION tgt
USING (
  SELECT
    '2026.06.18-governance-alignment-rc' AS MIGRATION_VERSION,
    'Governance Alignment Release Candidate for approved alert route, target roles, interim access, Trexis coverage, and drift classification' AS MIGRATION_NAME,
    'snowflake/OVERWATCH_MART_SETUP.sql' AS SOURCE_FILE,
    'Aligns production readiness scoring with approved governance assumptions without executing grants or dropping legacy objects. True telemetry freshness gaps remain review items.' AS NOTES
) src
ON tgt.MIGRATION_VERSION = src.MIGRATION_VERSION
WHEN MATCHED THEN UPDATE SET
  MIGRATION_NAME = src.MIGRATION_NAME,
  SOURCE_FILE = src.SOURCE_FILE,
  NOTES = src.NOTES
WHEN NOT MATCHED THEN INSERT (MIGRATION_VERSION, MIGRATION_NAME, SOURCE_FILE, NOTES)
VALUES (src.MIGRATION_VERSION, src.MIGRATION_NAME, src.SOURCE_FILE, src.NOTES);

MERGE INTO OVERWATCH_SCHEMA_MIGRATION tgt
USING (
  SELECT
    '2026.06.22-chunked-hourly-load' AS MIGRATION_VERSION,
    'Chunked hourly load procedures and task graph for timeout-safe Snowflake refresh' AS MIGRATION_NAME,
    'snowflake/mart_setup/05_load_procedures.sql; snowflake/mart_setup/07_tasks.sql' AS SOURCE_FILE,
    'Splits the hourly ACCOUNT_USAGE refresh into reviewable units and a chained task graph so accounts with 1000-second statement limits can refresh without one long stored procedure call.' AS NOTES
) src
ON tgt.MIGRATION_VERSION = src.MIGRATION_VERSION
WHEN MATCHED THEN UPDATE SET
  MIGRATION_NAME = src.MIGRATION_NAME,
  SOURCE_FILE = src.SOURCE_FILE,
  NOTES = src.NOTES
WHEN NOT MATCHED THEN INSERT (MIGRATION_VERSION, MIGRATION_NAME, SOURCE_FILE, NOTES)
VALUES (src.MIGRATION_VERSION, src.MIGRATION_NAME, src.SOURCE_FILE, src.NOTES);

CREATE TABLE IF NOT EXISTS OVERWATCH_OWNER_TAG_NAMES (
  TAG_NAME             VARCHAR(300) PRIMARY KEY,
  OWNER_TYPE           VARCHAR(100),
  PRIORITY             NUMBER,
  IS_ACTIVE            BOOLEAN DEFAULT TRUE,
  NOTES                VARCHAR(1000),
  UPDATED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY           VARCHAR(200) DEFAULT CURRENT_USER()
);

MERGE INTO OVERWATCH_OWNER_TAG_NAMES tgt
USING (
  SELECT * FROM VALUES
    ('COST_OWNER',        'COST',        10, TRUE, 'Preferred chargeback owner tag.'),
    ('DATA_OWNER',        'DATA',        20, TRUE, 'Database/schema/table data owner fallback.'),
    ('APP_OWNER',         'APPLICATION', 30, TRUE, 'Application owner fallback.'),
    ('APPLICATION_OWNER', 'APPLICATION', 35, TRUE, 'Alternate application owner tag.'),
    ('BUSINESS_OWNER',    'BUSINESS',    40, TRUE, 'Business owner fallback.'),
    ('SERVICE_OWNER',     'SERVICE',     50, TRUE, 'Service owner fallback.')
) src(TAG_NAME, OWNER_TYPE, PRIORITY, IS_ACTIVE, NOTES)
ON UPPER(tgt.TAG_NAME) = UPPER(src.TAG_NAME)
WHEN MATCHED THEN UPDATE SET
  OWNER_TYPE = src.OWNER_TYPE,
  PRIORITY = src.PRIORITY,
  IS_ACTIVE = src.IS_ACTIVE,
  NOTES = src.NOTES
WHEN NOT MATCHED THEN INSERT (TAG_NAME, OWNER_TYPE, PRIORITY, IS_ACTIVE, NOTES)
VALUES (src.TAG_NAME, src.OWNER_TYPE, src.PRIORITY, src.IS_ACTIVE, src.NOTES);

CREATE OR REPLACE FUNCTION OVERWATCH_DATABASE_ENVIRONMENT(DATABASE_NAME VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
  CASE
    WHEN UPPER(DATABASE_NAME) = 'ALFA_EDW_PRD' THEN 'ALFA_EDW_PRD'
    WHEN UPPER(DATABASE_NAME) = 'ALFA_EDW_MGM' THEN 'ALFA_EDW_MGM'
    WHEN UPPER(DATABASE_NAME) = 'ALFA_EDW_DEV' THEN 'ALFA_EDW_DEV'
    WHEN UPPER(DATABASE_NAME) = 'ALFA_EDW_SAN' THEN 'ALFA_EDW_SAN'
    WHEN UPPER(DATABASE_NAME) = 'ALFA_EDW_PHX' THEN 'ALFA_EDW_PHX'
    WHEN UPPER(DATABASE_NAME) = 'ALFA_EDW_SEA' THEN 'ALFA_EDW_SEA'
    WHEN UPPER(DATABASE_NAME) = 'ALFA_EDW_SIT' THEN 'ALFA_EDW_SIT'
    WHEN UPPER(DATABASE_NAME) = 'TRXS_ABC_METADATA_PRD' THEN 'TRXS_ABC_METADATA_PRD'
    WHEN UPPER(DATABASE_NAME) = 'TRXS_EDW_PRD' THEN 'TRXS_EDW_PRD'
    WHEN UPPER(DATABASE_NAME) = 'TRXS_GW_DATA_PRD' THEN 'TRXS_GW_DATA_PRD'
    WHEN UPPER(DATABASE_NAME) = 'TRXS_ABC_METADATA_DEV' THEN 'TRXS_ABC_METADATA_DEV'
    WHEN UPPER(DATABASE_NAME) = 'TRXS_ABC_METADATA_SIT' THEN 'TRXS_ABC_METADATA_SIT'
    WHEN UPPER(DATABASE_NAME) = 'TRXS_EDW_DEV' THEN 'TRXS_EDW_DEV'
    WHEN UPPER(DATABASE_NAME) = 'TRXS_EDW_SIT' THEN 'TRXS_EDW_SIT'
    WHEN UPPER(DATABASE_NAME) = 'TRXS_GW_DATA_DEV' THEN 'TRXS_GW_DATA_DEV'
    WHEN UPPER(DATABASE_NAME) = 'TRXS_GW_DATA_SIT' THEN 'TRXS_GW_DATA_SIT'
    WHEN DATABASE_NAME ILIKE 'ALFA_EDW_%' THEN 'Other ALFA Non-Prod'
    WHEN DATABASE_NAME IS NULL THEN 'No Database Context'
    ELSE 'Other / Shared'
  END
$$;

CREATE TABLE IF NOT EXISTS OVERWATCH_LOAD_AUDIT (
  LOAD_ID              NUMBER AUTOINCREMENT PRIMARY KEY,
  LOAD_NAME            VARCHAR(200),
  LOAD_STARTED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  LOAD_FINISHED_AT     TIMESTAMP_NTZ,
  STATUS               VARCHAR(40),
  ROWS_LOADED          NUMBER,
  MESSAGE              VARCHAR(4000)
);

CREATE TABLE IF NOT EXISTS OVERWATCH_ADMIN_ACTION_AUDIT (
  ACTION_ID            NUMBER AUTOINCREMENT PRIMARY KEY,
  ACTION_TS            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  COMPANY              VARCHAR(100),
  ENVIRONMENT          VARCHAR(50),
  APP_USER             VARCHAR(200),
  SNOWFLAKE_USER       VARCHAR(200),
  SNOWFLAKE_ROLE       VARCHAR(200),
  ACTION_TYPE          VARCHAR(100),
  TARGET_OBJECT        VARCHAR(1000),
  SQL_TEXT             VARCHAR,
  SQL_HASH             VARCHAR(80),
  CONFIRMATION_TEXT    VARCHAR(1000),
  CONTROL_CONTEXT      VARCHAR(4000),
  RESULT_STATUS        VARCHAR(40),
  RESULT_MESSAGE       VARCHAR(4000)
);

CREATE TABLE IF NOT EXISTS OVERWATCH_USAGE_LOG (
  RUN_ID               NUMBER AUTOINCREMENT PRIMARY KEY,
  LOG_TIME             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  SF_USER              VARCHAR(200),
  SF_ROLE              VARCHAR(200),
  COMPANY_VIEW         VARCHAR(100),
  SECTION              VARCHAR(200),
  QUERY_DURATION_MS    NUMBER,
  APP_VERSION          VARCHAR(20) DEFAULT '3.0',
  SESSION_ID           VARCHAR(200),
  EVENT_TYPE           VARCHAR(50) DEFAULT 'SECTION_LOAD',
  QUERY_HASH           VARCHAR(80),
  CACHE_KEY            VARCHAR(300),
  CACHE_TIER           VARCHAR(50),
  ROW_COUNT            NUMBER,
  RESULT_MB            NUMBER(18,4),
  USED_CACHE           BOOLEAN,
  MESSAGE              VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS OVERWATCH_ACTION_QUEUE (
  ACTION_ID                 VARCHAR(64) PRIMARY KEY,
  CREATED_AT                TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT                TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  SOURCE                    VARCHAR(100),
  CATEGORY                  VARCHAR(100),
  SEVERITY                  VARCHAR(20),
  ENTITY_TYPE               VARCHAR(100),
  ENTITY_NAME               VARCHAR(500),
  OWNER                     VARCHAR(200),
  STATUS                    VARCHAR(40) DEFAULT 'New',
  FINDING                   VARCHAR(4000),
  RECOMMENDED_ACTION        VARCHAR(4000),
  EST_MONTHLY_SAVINGS       FLOAT,
  GENERATED_SQL_FIX         VARCHAR(8000),
  PROOF_QUERY               VARCHAR(8000),
  COMPANY                   VARCHAR(100),
  ENVIRONMENT               VARCHAR(100),
  TICKET_ID                 VARCHAR(200),
  APPROVER                  VARCHAR(200),
  DUE_DATE                  DATE,
  VERIFICATION_STATUS       VARCHAR(40) DEFAULT 'Pending',
  VERIFICATION_NOTES        VARCHAR(4000),
  VERIFICATION_QUERY        VARCHAR(8000),
  VERIFICATION_RESULT       VARCHAR(8000),
  BASELINE_VALUE            FLOAT,
  CURRENT_VALUE             FLOAT,
  MEASURED_DELTA            FLOAT,
  VERIFIED_BY               VARCHAR(200),
  VERIFIED_AT               TIMESTAMP_NTZ,
  OWNER_APPROVAL_STATUS      VARCHAR(40),
  OWNER_APPROVAL_BY          VARCHAR(200),
  OWNER_APPROVAL_AT          TIMESTAMP_NTZ,
  OWNER_APPROVAL_NOTE        VARCHAR(2000),
  RECOVERY_SLA_STATE         VARCHAR(100),
  RECOVERY_SLA_HOURS         FLOAT,
  RECOVERY_SLA_TARGET_HOURS  FLOAT,
  RECOVERY_EVIDENCE          VARCHAR(8000),
  OWNER_EMAIL                VARCHAR(500),
  ONCALL_PRIMARY             VARCHAR(200),
  ONCALL_SECONDARY           VARCHAR(200),
  APPROVAL_GROUP             VARCHAR(200),
  ESCALATION_TARGET          VARCHAR(200),
  OWNER_SOURCE               VARCHAR(200),
  OWNER_EVIDENCE             VARCHAR(2000),
  RECOVERY_AUDIT_STATE       VARCHAR(100),
  ACKNOWLEDGED_BY           VARCHAR(200),
  ACKNOWLEDGED_AT           TIMESTAMP_NTZ,
  FIXED_BY                  VARCHAR(200),
  FIXED_AT                  TIMESTAMP_NTZ,
  IGNORED_REASON            VARCHAR(2000),
  LAST_SEEN_AT              TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  SEEN_COUNT                NUMBER DEFAULT 1
);

-- Upgrade older action queue installs to the current owner/environment and
-- verification contract without rebuilding existing audit data.
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS ENVIRONMENT VARCHAR(100);
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS TICKET_ID VARCHAR(200);
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS APPROVER VARCHAR(200);
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS DUE_DATE DATE;
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS VERIFICATION_STATUS VARCHAR(40);
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS VERIFICATION_NOTES VARCHAR(4000);
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS VERIFICATION_QUERY VARCHAR(8000);
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS VERIFICATION_RESULT VARCHAR(8000);
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS BASELINE_VALUE FLOAT;
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS CURRENT_VALUE FLOAT;
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS MEASURED_DELTA FLOAT;
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS VERIFIED_BY VARCHAR(200);
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS VERIFIED_AT TIMESTAMP_NTZ;
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS OWNER_APPROVAL_STATUS VARCHAR(40);
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS OWNER_APPROVAL_BY VARCHAR(200);
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS OWNER_APPROVAL_AT TIMESTAMP_NTZ;
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS OWNER_APPROVAL_NOTE VARCHAR(2000);
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS RECOVERY_SLA_STATE VARCHAR(100);
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS RECOVERY_SLA_HOURS FLOAT;
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS RECOVERY_SLA_TARGET_HOURS FLOAT;
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS RECOVERY_EVIDENCE VARCHAR(8000);
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS OWNER_EMAIL VARCHAR(500);
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS ONCALL_PRIMARY VARCHAR(200);
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS ONCALL_SECONDARY VARCHAR(200);
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS APPROVAL_GROUP VARCHAR(200);
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS ESCALATION_TARGET VARCHAR(200);
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS OWNER_SOURCE VARCHAR(200);
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS OWNER_EVIDENCE VARCHAR(2000);
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS RECOVERY_AUDIT_STATE VARCHAR(100);


CREATE TABLE IF NOT EXISTS OVERWATCH_WORKLOAD_RECOVERY_AUDIT (
  RECOVERY_AUDIT_ID         NUMBER AUTOINCREMENT PRIMARY KEY,
  RECOVERY_AUDIT_TS         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  ACTION_ID                 VARCHAR(64),
  COMPANY                   VARCHAR(100),
  ENVIRONMENT               VARCHAR(100),
  ENTITY_TYPE               VARCHAR(100),
  ENTITY_NAME               VARCHAR(500),
  INCIDENT_TYPE             VARCHAR(200),
  INCIDENT_PRIORITY         VARCHAR(100),
  OWNER                     VARCHAR(200),
  OWNER_EMAIL               VARCHAR(500),
  ONCALL_PRIMARY            VARCHAR(200),
  APPROVAL_GROUP            VARCHAR(200),
  APPROVER                  VARCHAR(200),
  OWNER_APPROVAL_STATUS     VARCHAR(40),
  RECOVERY_SLA_STATE        VARCHAR(100),
  RECOVERY_SLA_HOURS        FLOAT,
  RECOVERY_SLA_TARGET_HOURS FLOAT,
  TICKET_ID                 VARCHAR(200),
  ACTION_TAKEN              VARCHAR(4000),
  BEFORE_STATE              VARCHAR(4000),
  AFTER_STATE               VARCHAR(4000),
  VERIFICATION_QUERY        VARCHAR(8000),
  VERIFICATION_RESULT       VARCHAR(8000),
  RECOVERY_EVIDENCE         VARCHAR(8000),
  EXECUTED_BY               VARCHAR(200) DEFAULT CURRENT_USER(),
  SOURCE                    VARCHAR(200),
  SOURCE_QUERY_ID           VARCHAR(200),
  NOTES                     VARCHAR(4000)
);

CREATE OR REPLACE VIEW OVERWATCH_WORKLOAD_RECOVERY_AUDIT_LATEST_V AS
SELECT *
FROM OVERWATCH_WORKLOAD_RECOVERY_AUDIT
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY COALESCE(ACTION_ID, ENTITY_NAME), ENTITY_TYPE
  ORDER BY RECOVERY_AUDIT_TS DESC, RECOVERY_AUDIT_ID DESC
) = 1;


CREATE TABLE IF NOT EXISTS OVERWATCH_DBA_CHECKLIST_HISTORY (
  SNAPSHOT_ID       VARCHAR(64),
  SNAPSHOT_TS       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  COMPANY           VARCHAR(100),
  ENVIRONMENT       VARCHAR(100),
  CHECK_NAME        VARCHAR(200),
  STATUS            VARCHAR(80),
  SEVERITY          VARCHAR(40),
  EVIDENCE          VARCHAR(2000),
  OWNER             VARCHAR(200),
  ESCALATION_TARGET VARCHAR(200),
  OWNER_SOURCE      VARCHAR(200),
  ROUTE             VARCHAR(120),
  NEXT_ACTION       VARCHAR(4000),
  PROOF_REQUIRED    VARCHAR(2000),
  ENVIRONMENT_SCOPE VARCHAR(100),
  DATABASE_CONTEXT  VARCHAR(80),
  SCOPE_CONFIDENCE  VARCHAR(160),
  SCOPE_EVIDENCE    VARCHAR(2000),
  APPROVAL_REQUIRED VARCHAR(20),
  QUEUE_READINESS   VARCHAR(80),
  QUEUE_BLOCKERS    VARCHAR(2000),
  VERIFICATION_QUERY VARCHAR(8000),
  RECOVERY_SLA_TARGET_HOURS FLOAT,
  CONTROL_READINESS VARCHAR(100),
  CONTROL_BLOCKERS  VARCHAR(2000),
  NEXT_CONTROL_ACTION VARCHAR(4000),
  HEALTH_SCORE      FLOAT,
  DETAIL_SOURCE     VARCHAR(500),
  ACTIONABLE        BOOLEAN
);

CREATE TABLE IF NOT EXISTS OVERWATCH_CHANGE_CONTROL_EVIDENCE (
  SNAPSHOT_ID              VARCHAR(64),
  SNAPSHOT_TS              TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  COMPANY                  VARCHAR(100),
  ENVIRONMENT              VARCHAR(100),
  FINDING_TYPE             VARCHAR(120),
  SEVERITY                 VARCHAR(40),
  ENTITY                   VARCHAR(500),
  USER_NAME                VARCHAR(300),
  ROLE_NAME                VARCHAR(300),
  QUERY_ID                 VARCHAR(200),
  QUERY_TAG                VARCHAR(1000),
  LAST_SEEN                VARCHAR(100),
  CHANGE_CONTROL_STATE     VARCHAR(120),
  CONTROL_GAP              VARCHAR(1000),
  CHANGE_TICKET_ID         VARCHAR(200),
  CHANGE_TICKET_STATE      VARCHAR(120),
  IAC_RECONCILIATION_STATE VARCHAR(160),
  EXECUTION_AUDIT_STATE    VARCHAR(160),
  OWNER                    VARCHAR(200),
  ESCALATION_TARGET        VARCHAR(200),
  OWNER_SOURCE             VARCHAR(200),
  APPROVER                 VARCHAR(200),
  OWNER_APPROVAL_STATUS    VARCHAR(40),
  APPROVAL_REQUIRED        VARCHAR(20),
  TICKET_REQUIRED          VARCHAR(20),
  BLAST_RADIUS_REQUIRED    VARCHAR(20),
  APPROVAL_ROUTE_READY     VARCHAR(20),
  CHANGE_EVIDENCE_READINESS VARCHAR(80),
  EVIDENCE_BLOCKERS        VARCHAR(2000),
  REVIEW_SLA_HOURS         NUMBER,
  NEXT_CONTROL_ACTION      VARCHAR(4000),
  PROOF_REQUIRED           VARCHAR(2000),
  VERIFICATION_QUERY       VARCHAR(8000),
  BLAST_RADIUS_QUERY       VARCHAR(8000),
  SOURCE                   VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS OVERWATCH_WAREHOUSE_SETTING_REVIEW (
  SNAPSHOT_ID                   VARCHAR(64),
  SNAPSHOT_TS                   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  COMPANY                       VARCHAR(100),
  ENVIRONMENT                   VARCHAR(100),
  WAREHOUSE_NAME                VARCHAR(300),
  SEVERITY                      VARCHAR(40),
  SIGNAL                        VARCHAR(120),
  OWNER                         VARCHAR(200),
  ESCALATION_TARGET             VARCHAR(200),
  OWNER_SOURCE                  VARCHAR(200),
  APPROVER                      VARCHAR(200),
  APPROVAL_REQUIRED             VARCHAR(20),
  ROLLBACK_REQUIRED             VARCHAR(20),
  SAFE_CHANGE_PATH              VARCHAR(4000),
  SETTING_CHANGE_CANDIDATE      VARCHAR(4000),
  CHANGE_RISK                   VARCHAR(2000),
  POST_CHANGE_VERIFICATION      VARCHAR(2000),
  PRESSURE_EVIDENCE             VARCHAR(2000),
  BASELINE_CAPACITY_SCORE       FLOAT,
  BASELINE_QUEUED_QUERIES       NUMBER,
  BASELINE_SPILL_QUERIES        NUMBER,
  BASELINE_HIGH_LATENCY_QUERIES NUMBER,
  BASELINE_P95_ELAPSED_SEC      FLOAT,
  BASELINE_METERED_CREDITS      FLOAT,
  VERIFICATION_QUERY            VARCHAR(8000),
  GENERATED_REVIEW_SQL          VARCHAR(8000),
  IMPACT_TELEMETRY_REQUIRED VARCHAR(20),
  APPROVAL_STATE                VARCHAR(80),
  CHANGE_TICKET_ID              VARCHAR(200),
  CURRENT_SETTINGS_JSON         VARCHAR(8000),
  PROPOSED_SETTINGS_JSON        VARCHAR(8000),
  ROLLBACK_SQL                  VARCHAR(8000),
  EXECUTED_SQL_HASH             VARCHAR(80),
  EXECUTION_STATUS              VARCHAR(80),
  EXECUTED_BY                   VARCHAR(200),
  EXECUTED_AT                   TIMESTAMP_NTZ,
  POST_CHANGE_VERIFICATION_STATUS VARCHAR(80),
  POST_CHANGE_VERIFICATION_RESULT VARCHAR(4000),
  VERIFIED_MONTHLY_SAVINGS     FLOAT,
  AUDIT_READINESS               VARCHAR(100),
  AUDIT_BLOCKERS                VARCHAR(2000),
  NEXT_CONTROL_ACTION           VARCHAR(4000),
  SOURCE                        VARCHAR(500)
);

ALTER TABLE IF EXISTS OVERWATCH_WAREHOUSE_SETTING_REVIEW ADD COLUMN IF NOT EXISTS IMPACT_TELEMETRY_REQUIRED VARCHAR(20);

CREATE TABLE IF NOT EXISTS OVERWATCH_SECURITY_ACCESS_REVIEW (
  SNAPSHOT_ID             VARCHAR(64),
  SNAPSHOT_TS             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  COMPANY                 VARCHAR(100),
  ENVIRONMENT             VARCHAR(100),
  DATABASE_CONTEXT        BOOLEAN,
  FINDING_TYPE            VARCHAR(120),
  SEVERITY                VARCHAR(40),
  ENTITY_TYPE             VARCHAR(120),
  ENTITY                  VARCHAR(500),
  EVENT_COUNT             NUMBER,
  DISTINCT_SOURCES        NUMBER,
  LAST_SEEN               VARCHAR(100),
  OWNER                   VARCHAR(200),
  ESCALATION_TARGET       VARCHAR(200),
  OWNER_SOURCE            VARCHAR(200),
  APPROVER                VARCHAR(200),
  OWNER_APPROVAL_STATUS   VARCHAR(40),
  ACCESS_REVIEW_STATE     VARCHAR(160),
  ROLE_CAPABILITY_STATE   VARCHAR(200),
  TICKET_REQUIRED         VARCHAR(20),
  REVIEW_BY_REQUIRED      VARCHAR(20),
  PROOF_REQUIRED          VARCHAR(2000),
  VERIFICATION_QUERY      VARCHAR(8000),
  ACCESS_TICKET_ID        VARCHAR(200),
  REVIEW_BY_DATE          VARCHAR(100),
  IAM_APPROVAL_STATE      VARCHAR(120),
  REVIEW_READINESS        VARCHAR(100),
  REVIEW_BLOCKERS         VARCHAR(2000),
  REVIEW_SLA_HOURS        NUMBER,
  VERIFICATION_STATUS     VARCHAR(80),
  VERIFICATION_RESULT     VARCHAR(4000),
  CONTROL_READINESS       VARCHAR(100),
  CONTROL_BLOCKERS        VARCHAR(2000),
  NEXT_CONTROL_ACTION     VARCHAR(4000),
  NEXT_ACTION             VARCHAR(4000),
  PROOF_QUERY             VARCHAR(4000),
  SOURCE                  VARCHAR(500)
);


CREATE TABLE IF NOT EXISTS OVERWATCH_ALERTS (
  ALERT_ID             NUMBER AUTOINCREMENT PRIMARY KEY,
  ALERT_TS             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  COMPANY              VARCHAR(100),
  ENVIRONMENT          VARCHAR(100),
  DATABASE_NAME        VARCHAR(300),
  SCHEMA_NAME          VARCHAR(300),
  WAREHOUSE_NAME       VARCHAR(300),
  CATEGORY             VARCHAR(100),
  ALERT_TYPE           VARCHAR(100),
  SEVERITY             VARCHAR(20),
  ENTITY_NAME          VARCHAR(500),
  ENTITY               VARCHAR(500),
  MESSAGE              VARCHAR(4000),
  DETAIL               VARCHAR(4000),
  SUGGESTED_ACTION     VARCHAR(2000),
  PROOF_QUERY          VARCHAR(8000),
  OWNER                VARCHAR(200),
  STATUS               VARCHAR(40) DEFAULT 'New',
  DELIVERY_METHOD      VARCHAR(40) DEFAULT 'EMAIL',
  DELIVERY_TARGET      VARCHAR(500),
  EMAIL_TARGET         VARCHAR(500),
  EMAIL_SUBJECT        VARCHAR(1000),
  EMAIL_BODY           VARCHAR(16000),
  DELIVERY_STATUS      VARCHAR(100),
  ACKNOWLEDGED_BY      VARCHAR(200),
  ACKNOWLEDGED_AT      TIMESTAMP_NTZ,
  RESOLVED             BOOLEAN DEFAULT FALSE,
  STATUS_REASON        VARCHAR(2000),
  LAST_STATUS_BY       VARCHAR(200),
  LAST_STATUS_AT       TIMESTAMP_NTZ,
  LAST_DELIVERY_AT     TIMESTAMP_NTZ,
  LAST_DELIVERY_BY     VARCHAR(200),
  DELIVERY_LOG_COUNT   NUMBER DEFAULT 0,
  ESCALATED_TO         VARCHAR(200),
  ESCALATED_AT         TIMESTAMP_NTZ,
  ESCALATION_ACK_BY    VARCHAR(200),
  ESCALATION_ACK_AT    TIMESTAMP_NTZ,
  ESCALATION_ACK_NOTE  VARCHAR(2000),
  ROUTED_TO_ACTION_QUEUE_AT TIMESTAMP_NTZ,
  ROUTED_ACTION_COUNT  NUMBER DEFAULT 0
);

-- Upgrade older Alert Center installs to the current routing/status contract.
ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS ENVIRONMENT VARCHAR(100);
ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS DATABASE_NAME VARCHAR(300);
ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS SCHEMA_NAME VARCHAR(300);
ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS WAREHOUSE_NAME VARCHAR(300);
ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS ALERT_TYPE VARCHAR(100);
ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS ENTITY VARCHAR(500);
ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS DETAIL VARCHAR(4000);
ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS SUGGESTED_ACTION VARCHAR(2000);
ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS OWNER VARCHAR(200);
ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS STATUS VARCHAR(40);
ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS DELIVERY_METHOD VARCHAR(40);
ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS EMAIL_TARGET VARCHAR(500);
ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS EMAIL_SUBJECT VARCHAR(1000);
ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS EMAIL_BODY VARCHAR(16000);
ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS RESOLVED BOOLEAN;
ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS STATUS_REASON VARCHAR(2000);
ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS LAST_STATUS_BY VARCHAR(200);
ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS LAST_STATUS_AT TIMESTAMP_NTZ;
ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS LAST_DELIVERY_AT TIMESTAMP_NTZ;
ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS LAST_DELIVERY_BY VARCHAR(200);
ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS DELIVERY_LOG_COUNT NUMBER;
ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS ESCALATED_TO VARCHAR(200);
ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS ESCALATED_AT TIMESTAMP_NTZ;
ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS ESCALATION_ACK_BY VARCHAR(200);
ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS ESCALATION_ACK_AT TIMESTAMP_NTZ;
ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS ESCALATION_ACK_NOTE VARCHAR(2000);
ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS ROUTED_TO_ACTION_QUEUE_AT TIMESTAMP_NTZ;
ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS ROUTED_ACTION_COUNT NUMBER;

-- Alert Center configuration, event, acknowledgement, notification, and remediation contract.
-- ACCOUNT_USAGE sources can lag; ALERT_CONFIG.TELEMETRY_LATENCY labels delayed vs near-real-time checks.
CREATE TABLE IF NOT EXISTS ALERT_CONFIG (
  ALERT_KEY                  VARCHAR(200) PRIMARY KEY,
  CATEGORY                   VARCHAR(100) NOT NULL,
  SIGNAL_NAME                VARCHAR(200) NOT NULL,
  DESCRIPTION                VARCHAR(4000),
  DEFAULT_SEVERITY           VARCHAR(20) DEFAULT 'Medium',
  ENABLED                    BOOLEAN DEFAULT TRUE,
  OWNER                      VARCHAR(200),
  ROUTE                      VARCHAR(200),
  BUSINESS_IMPACT_WEIGHT     NUMBER DEFAULT 50,
  DETECTION_SQL              VARCHAR(16000),
  TELEMETRY_SOURCE           VARCHAR(500),
  TELEMETRY_LATENCY          VARCHAR(200),
  NOTIFICATION_CHANNEL       VARCHAR(200),
  REMEDIATION_MODE           VARCHAR(40) DEFAULT 'RECOMMEND',
  DEDUPE_WINDOW_MINUTES      NUMBER DEFAULT 60,
  SUPPRESSION_WINDOW_MINUTES NUMBER DEFAULT 0,
  QUIET_HOURS_START          VARCHAR(20),
  QUIET_HOURS_END            VARCHAR(20),
  AUTO_RESOLVE_AFTER_HOURS   NUMBER DEFAULT 24,
  CREATED_AT                 TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CREATED_BY                 VARCHAR(200) DEFAULT CURRENT_USER(),
  UPDATED_AT                 TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY                 VARCHAR(200) DEFAULT CURRENT_USER()
);

CREATE TABLE IF NOT EXISTS ALERT_THRESHOLDS (
  THRESHOLD_KEY          VARCHAR(200) PRIMARY KEY,
  CATEGORY               VARCHAR(100) NOT NULL,
  SIGNAL_NAME            VARCHAR(200) NOT NULL,
  SEVERITY               VARCHAR(20) DEFAULT 'Medium',
  THRESHOLD_VALUE        FLOAT,
  BASELINE_WINDOW_DAYS   NUMBER DEFAULT 14,
  CURRENT_WINDOW_MINUTES NUMBER DEFAULT 60,
  OWNER                  VARCHAR(200),
  NOTIFICATION_CHANNEL   VARCHAR(200),
  ENABLED                BOOLEAN DEFAULT TRUE,
  UPDATED_AT             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY             VARCHAR(200) DEFAULT CURRENT_USER()
);

CREATE TABLE IF NOT EXISTS ALERT_EVENTS (
  EVENT_ID             NUMBER AUTOINCREMENT PRIMARY KEY,
  COMPANY              VARCHAR(100),
  ENVIRONMENT          VARCHAR(100),
  ALERT_KEY            VARCHAR(200),
  EVENT_TS             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  FIRST_SEEN_AT        TIMESTAMP_NTZ,
  LAST_SEEN_AT         TIMESTAMP_NTZ,
  DETECTED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  RESOLVED_AT          TIMESTAMP_NTZ,
  CATEGORY             VARCHAR(100),
  SEVERITY             VARCHAR(20),
  STATUS               VARCHAR(40) DEFAULT 'New',
  BUSINESS_IMPACT      VARCHAR(4000),
  IMPACT_ESTIMATE      VARCHAR(1000),
  OWNER                VARCHAR(200),
  RECOMMENDED_ACTION   VARCHAR(4000),
  ENTITY_TYPE          VARCHAR(100),
  ENTITY_NAME          VARCHAR(500),
  USER_NAME            VARCHAR(300),
  ROLE_NAME            VARCHAR(300),
  WAREHOUSE_NAME       VARCHAR(300),
  DATABASE_NAME        VARCHAR(300),
  SCHEMA_NAME          VARCHAR(300),
  OBJECT_NAME          VARCHAR(500),
  QUERY_ID             VARCHAR(200),
  SOURCE_IP            VARCHAR(200),
  BASELINE_VALUE       FLOAT,
  CURRENT_VALUE        FLOAT,
  THRESHOLD_VALUE      FLOAT,
  EVIDENCE             VARCHAR(8000),
  PROOF_QUERY          VARCHAR(16000),
  REMEDIATION_MODE     VARCHAR(40) DEFAULT 'RECOMMEND',
  REMEDIATION_SQL      VARCHAR(16000),
  NOTIFICATION_STATUS  VARCHAR(100),
  DEDUPE_KEY           VARCHAR(500),
  RAW_EVENT            VARIANT
);

ALTER TABLE IF EXISTS ALERT_EVENTS ADD COLUMN IF NOT EXISTS COMPANY VARCHAR(100);
ALTER TABLE IF EXISTS ALERT_EVENTS ADD COLUMN IF NOT EXISTS ENVIRONMENT VARCHAR(100);

CREATE TABLE IF NOT EXISTS ALERT_RUN_HISTORY (
  RUN_ID                 VARCHAR(200) PRIMARY KEY,
  STARTED_AT             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  COMPLETED_AT           TIMESTAMP_NTZ,
  STATUS                 VARCHAR(40),
  ALERTS_EVALUATED       NUMBER DEFAULT 0,
  ALERTS_CREATED         NUMBER DEFAULT 0,
  ALERTS_RESOLVED        NUMBER DEFAULT 0,
  ERROR_MESSAGE          VARCHAR(4000),
  DATA_WINDOW_START      TIMESTAMP_NTZ,
  DATA_WINDOW_END        TIMESTAMP_NTZ,
  TELEMETRY_LATENCY_NOTE VARCHAR(2000),
  RUN_BY                 VARCHAR(200) DEFAULT CURRENT_USER()
);

CREATE TABLE IF NOT EXISTS ALERT_ACKNOWLEDGEMENTS (
  ACK_ID              NUMBER AUTOINCREMENT PRIMARY KEY,
  EVENT_ID            NUMBER,
  ALERT_KEY           VARCHAR(200),
  ACKNOWLEDGED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  ACKNOWLEDGED_BY     VARCHAR(200) DEFAULT CURRENT_USER(),
  ACK_NOTE            VARCHAR(4000),
  STATUS_AFTER_ACK    VARCHAR(40) DEFAULT 'Acknowledged',
  OWNER_ASSIGNED      VARCHAR(200),
  NEXT_CHECKPOINT_AT  TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS ALERT_NOTIFICATION_LOG (
  NOTIFICATION_ID  NUMBER AUTOINCREMENT PRIMARY KEY,
  EVENT_ID         NUMBER,
  ALERT_KEY        VARCHAR(200),
  NOTIFICATION_TS  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CHANNEL          VARCHAR(200),
  DESTINATION      VARCHAR(500),
  SEVERITY         VARCHAR(20),
  STATUS           VARCHAR(100),
  DEDUPE_KEY       VARCHAR(500),
  ESCALATION_LEVEL NUMBER DEFAULT 0,
  ERROR_MESSAGE    VARCHAR(4000),
  PAYLOAD          VARIANT,
  SENT_BY          VARCHAR(200) DEFAULT CURRENT_USER()
);

CREATE TABLE IF NOT EXISTS ALERT_REMEDIATION_LOG (
  REMEDIATION_ID     NUMBER AUTOINCREMENT PRIMARY KEY,
  EVENT_ID           NUMBER,
  ALERT_KEY          VARCHAR(200),
  REQUESTED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  REQUESTED_BY       VARCHAR(200) DEFAULT CURRENT_USER(),
  APPROVED_AT        TIMESTAMP_NTZ,
  APPROVED_BY        VARCHAR(200),
  REMEDIATION_MODE   VARCHAR(40),
  ACTION_TYPE        VARCHAR(100),
  ACTION_SQL         VARCHAR(16000),
  BEFORE_STATE       VARCHAR(8000),
  AFTER_STATE        VARCHAR(8000),
  EXECUTION_STATUS   VARCHAR(100),
  ERROR_MESSAGE      VARCHAR(4000),
  ROLLBACK_GUIDANCE  VARCHAR(4000),
  AFFECTED_USER      VARCHAR(300),
  AFFECTED_OBJECT    VARCHAR(500),
  AFFECTED_WAREHOUSE VARCHAR(300),
  AFFECTED_TASK      VARCHAR(500),
  VERIFICATION_SQL   VARCHAR(16000),
  VERIFICATION_RESULT VARCHAR(8000)
);

CREATE TABLE IF NOT EXISTS ALERT_OWNER_ROUTING (
  ROUTE_KEY            VARCHAR(200) PRIMARY KEY,
  CATEGORY             VARCHAR(100),
  ENTITY_TYPE          VARCHAR(100),
  ENTITY_PATTERN       VARCHAR(500),
  OWNER_NAME           VARCHAR(200),
  OWNER_EMAIL          VARCHAR(500),
  ONCALL_PRIMARY       VARCHAR(200),
  ONCALL_SECONDARY     VARCHAR(200),
  APPROVAL_GROUP       VARCHAR(200),
  ESCALATION_TARGET    VARCHAR(200),
  NOTIFICATION_CHANNEL VARCHAR(200),
  SEVERITY_MIN         VARCHAR(20) DEFAULT 'Medium',
  SERVICE_TIER         VARCHAR(40) DEFAULT 'Tier 2',
  ACTIVE               BOOLEAN DEFAULT TRUE,
  UPDATED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY           VARCHAR(200) DEFAULT CURRENT_USER()
);

CREATE TABLE IF NOT EXISTS ALERT_DATA_QUALITY_CHECKS (
  CHECK_KEY            VARCHAR(200) PRIMARY KEY,
  DATABASE_NAME        VARCHAR(300) NOT NULL,
  SCHEMA_NAME          VARCHAR(300) NOT NULL,
  TABLE_NAME           VARCHAR(300) NOT NULL,
  COLUMN_NAME          VARCHAR(300) DEFAULT '*',
  CHECK_TYPE           VARCHAR(100) NOT NULL,
  THRESHOLD_VALUE      FLOAT,
  COMPARISON_OPERATOR  VARCHAR(20) DEFAULT '>',
  SEVERITY             VARCHAR(20) DEFAULT 'Medium',
  OWNER                VARCHAR(200),
  NOTIFICATION_CHANNEL VARCHAR(200),
  ENABLED              BOOLEAN DEFAULT FALSE,
  FRESHNESS_COLUMN     VARCHAR(300),
  KEY_COLUMNS          VARCHAR(1000),
  FILTER_SQL           VARCHAR(4000),
  BUSINESS_IMPACT      VARCHAR(4000),
  UPDATED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY           VARCHAR(200) DEFAULT CURRENT_USER()
);

MERGE INTO ALERT_DATA_QUALITY_CHECKS tgt
USING (
  SELECT * FROM VALUES
    ('DQ_ORDER_FRESHNESS', 'ALFA_EDW_PRD', 'CURATED', 'FACT_ORDER', 'LOAD_TS', 'FRESHNESS_SLA_HOURS', 24, '>', 'High', 'Data Owner', 'DATA_QUALITY', FALSE),
    ('DQ_POLICY_NULL_RATE', 'ALFA_EDW_PRD', 'CURATED', 'DIM_POLICY', 'POLICY_ID', 'NULL_RATE_PCT', 0, '>', 'Critical', 'Data Owner', 'DATA_QUALITY', FALSE),
    ('DQ_CLAIM_VOLUME_DROP', 'ALFA_EDW_PRD', 'CURATED', 'FACT_CLAIM', '*', 'ROW_COUNT_DROP_PCT', 35, '>', 'High', 'Data Owner', 'DATA_QUALITY', FALSE)
) src(CHECK_KEY, DATABASE_NAME, SCHEMA_NAME, TABLE_NAME, COLUMN_NAME, CHECK_TYPE, THRESHOLD_VALUE, COMPARISON_OPERATOR, SEVERITY, OWNER, NOTIFICATION_CHANNEL, ENABLED)
ON tgt.CHECK_KEY = src.CHECK_KEY
WHEN MATCHED THEN UPDATE SET
  DATABASE_NAME = src.DATABASE_NAME,
  SCHEMA_NAME = src.SCHEMA_NAME,
  TABLE_NAME = src.TABLE_NAME,
  COLUMN_NAME = src.COLUMN_NAME,
  CHECK_TYPE = src.CHECK_TYPE,
  THRESHOLD_VALUE = src.THRESHOLD_VALUE,
  COMPARISON_OPERATOR = src.COMPARISON_OPERATOR,
  SEVERITY = src.SEVERITY,
  OWNER = src.OWNER,
  NOTIFICATION_CHANNEL = src.NOTIFICATION_CHANNEL,
  UPDATED_AT = CURRENT_TIMESTAMP(),
  UPDATED_BY = CURRENT_USER()
WHEN NOT MATCHED THEN INSERT
  (CHECK_KEY, DATABASE_NAME, SCHEMA_NAME, TABLE_NAME, COLUMN_NAME, CHECK_TYPE, THRESHOLD_VALUE, COMPARISON_OPERATOR, SEVERITY, OWNER, NOTIFICATION_CHANNEL, ENABLED)
VALUES
  (src.CHECK_KEY, src.DATABASE_NAME, src.SCHEMA_NAME, src.TABLE_NAME, src.COLUMN_NAME, src.CHECK_TYPE, src.THRESHOLD_VALUE, src.COMPARISON_OPERATOR, src.SEVERITY, src.OWNER, src.NOTIFICATION_CHANNEL, src.ENABLED);

CREATE TABLE IF NOT EXISTS ALERT_NATIVE_OBJECT_REGISTRY (
  REGISTRY_KEY          VARCHAR(200) PRIMARY KEY,
  ALERT_KEY             VARCHAR(200),
  CATEGORY              VARCHAR(100),
  ALERT_OBJECT_NAME     VARCHAR(300),
  TARGET_ROUTE          VARCHAR(200),
  WAREHOUSE_NAME        VARCHAR(300),
  SCHEDULE_TEXT         VARCHAR(100),
  STATUS                VARCHAR(40) DEFAULT 'CANDIDATE',
  CONDITION_SOURCE      VARCHAR(1000),
  ACTION_SOURCE         VARCHAR(1000),
  GENERATED_CREATE_SQL  VARCHAR(16000),
  GENERATED_DROP_SQL    VARCHAR(4000),
  ENABLED_BY_DEFAULT    BOOLEAN DEFAULT FALSE,
  SAFETY_NOTE           VARCHAR(4000),
  UPDATED_AT            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY            VARCHAR(200) DEFAULT CURRENT_USER()
);

MERGE INTO ALERT_NATIVE_OBJECT_REGISTRY tgt
USING (
  SELECT * FROM VALUES
    ('NATIVE_COST_CORTEX_SPEND_SPIKE', 'COST_CORTEX_SPEND_SPIKE', 'Cost', 'OVERWATCH_ALERT_CORTEX_SPEND_SPIKE', 'Cost & Contract', 'WH_ALFA_OVERWATCH', '60 MINUTE', 'CANDIDATE', 'FACT_CORTEX_DAILY company-labeled 7-day spend vs shared threshold', 'Insert recommend-only event into ALERT_EVENTS', 'CREATE OR REPLACE ALERT OVERWATCH_ALERT_CORTEX_SPEND_SPIKE WAREHOUSE = WH_ALFA_OVERWATCH SCHEDULE = ''60 MINUTE'' IF (EXISTS (SELECT 1 FROM FACT_CORTEX_DAILY WHERE USAGE_DATE >= DATEADD(''day'', -7, CURRENT_DATE()) GROUP BY COMPANY HAVING SUM(EST_COST_USD) > 25)) THEN INSERT INTO ALERT_EVENTS (COMPANY, ENVIRONMENT, ALERT_KEY, CATEGORY, SEVERITY, STATUS, OWNER, RECOMMENDED_ACTION, ENTITY_TYPE, ENTITY_NAME, REMEDIATION_MODE) SELECT COALESCE(COMPANY, ''Account-Wide''), ''ALL'', ''COST_CORTEX_SPEND_SPIKE'', ''Cost'', ''High'', ''New'', ''DBA / AI cost route'', ''Review Cortex user/source spend, quota settings, grants, and company scope before changing access.'', ''CORTEX'', ''CORTEX'', ''RECOMMEND'' FROM FACT_CORTEX_DAILY WHERE USAGE_DATE >= DATEADD(''day'', -7, CURRENT_DATE()) GROUP BY COMPANY HAVING SUM(EST_COST_USD) > 25;', 'DROP ALERT IF EXISTS OVERWATCH_ALERT_CORTEX_SPEND_SPIKE;', FALSE, 'Recommend-only. Do not alter Cortex access automatically.'),
    ('NATIVE_COST_WAREHOUSE_CREDIT_SPIKE', 'COST_WAREHOUSE_CREDIT_SPIKE', 'Cost', 'OVERWATCH_ALERT_WAREHOUSE_CREDIT_SPIKE', 'Cost & Contract', 'WH_ALFA_OVERWATCH', '60 MINUTE', 'CANDIDATE', 'FACT_WAREHOUSE_HOURLY company-labeled current-day CREDITS_USED by warehouse', 'Insert recommend-only cost movement event into ALERT_EVENTS', 'CREATE OR REPLACE ALERT OVERWATCH_ALERT_WAREHOUSE_CREDIT_SPIKE WAREHOUSE = WH_ALFA_OVERWATCH SCHEDULE = ''60 MINUTE'' IF (EXISTS (SELECT 1 FROM FACT_WAREHOUSE_HOURLY WHERE HOUR_START >= DATEADD(''hour'', -24, CURRENT_TIMESTAMP()) GROUP BY COMPANY, WAREHOUSE_NAME HAVING SUM(CREDITS_USED) > 10)) THEN INSERT INTO ALERT_EVENTS (COMPANY, ENVIRONMENT, ALERT_KEY, CATEGORY, SEVERITY, STATUS, OWNER, RECOMMENDED_ACTION, ENTITY_TYPE, ENTITY_NAME, WAREHOUSE_NAME, CURRENT_VALUE, REMEDIATION_MODE, EVIDENCE, DEDUPE_KEY) SELECT COALESCE(COMPANY, ''Shared/Unclassified''), ''ALL'', ''COST_WAREHOUSE_CREDIT_SPIKE'', ''Cost'', ''High'', ''New'', ''DBA / Cost owner'', ''Explain warehouse credit spike before changing capacity.'', ''WAREHOUSE'', WAREHOUSE_NAME, WAREHOUSE_NAME, SUM(CREDITS_USED), ''RECOMMEND'', ''Native candidate detected warehouse credits above threshold.'', SHA2(''COST_WAREHOUSE_CREDIT_SPIKE|'' || COALESCE(COMPANY, ''Shared/Unclassified'') || ''|'' || WAREHOUSE_NAME || ''|'' || TO_VARCHAR(CURRENT_DATE()), 256) FROM FACT_WAREHOUSE_HOURLY WHERE HOUR_START >= DATEADD(''hour'', -24, CURRENT_TIMESTAMP()) GROUP BY COMPANY, WAREHOUSE_NAME HAVING SUM(CREDITS_USED) > 10;', 'DROP ALERT IF EXISTS OVERWATCH_ALERT_WAREHOUSE_CREDIT_SPIKE;', FALSE, 'Recommend-only. Do not resize, suspend, or alter warehouses automatically.'),
    ('NATIVE_SECURITY_PRIVILEGE_ESCALATION', 'SECURITY_PRIVILEGE_ESCALATION', 'Security', 'OVERWATCH_ALERT_PRIVILEGE_ESCALATION', 'Security Monitoring', 'WH_ALFA_OVERWATCH', '60 MINUTE', 'CANDIDATE', 'FACT_GRANT_DAILY company-labeled privileged role grants', 'Insert status-review event into ALERT_EVENTS', 'CREATE OR REPLACE ALERT OVERWATCH_ALERT_PRIVILEGE_ESCALATION WAREHOUSE = WH_ALFA_OVERWATCH SCHEDULE = ''60 MINUTE'' IF (EXISTS (SELECT 1 FROM FACT_GRANT_DAILY WHERE SNAPSHOT_DATE >= DATEADD(''day'', -2, CURRENT_DATE()) AND CREATED_ON >= DATEADD(''hour'', -24, CURRENT_TIMESTAMP()) AND DELETED_ON IS NULL AND UPPER(ROLE_NAME) IN (''ACCOUNTADMIN'', ''SECURITYADMIN'', ''SYSADMIN'', ''ORGADMIN''))) THEN INSERT INTO ALERT_EVENTS (COMPANY, ENVIRONMENT, ALERT_KEY, CATEGORY, SEVERITY, STATUS, OWNER, RECOMMENDED_ACTION, ENTITY_TYPE, REMEDIATION_MODE) SELECT COALESCE(COMPANY, ''Shared/Unclassified''), ''No Database Context'', ''SECURITY_PRIVILEGE_ESCALATION'', ''Security'', ''Critical'', ''New'', ''Security Reviewer'', ''Validate ticket, reviewer, MFA posture, and access purpose before accepting the privileged grant.'', ''USER'', ''STATUS_REVIEW'' FROM FACT_GRANT_DAILY WHERE SNAPSHOT_DATE >= DATEADD(''day'', -2, CURRENT_DATE()) AND CREATED_ON >= DATEADD(''hour'', -24, CURRENT_TIMESTAMP()) AND DELETED_ON IS NULL AND UPPER(ROLE_NAME) IN (''ACCOUNTADMIN'', ''SECURITYADMIN'', ''SYSADMIN'', ''ORGADMIN'');', 'DROP ALERT IF EXISTS OVERWATCH_ALERT_PRIVILEGE_ESCALATION;', FALSE, 'Status-review only. Never auto-revoke from this alert.'),
    ('NATIVE_PIPELINE_TASK_FAILURE', 'PIPELINE_TASK_FAILURE', 'Task / Pipeline', 'OVERWATCH_ALERT_TASK_FAILURE', 'Workload Operations', 'WH_ALFA_OVERWATCH', '30 MINUTE', 'CANDIDATE', 'FACT_TASK_RUN company/environment-labeled failed/skipped task graph rows', 'Insert status-review event into ALERT_EVENTS', 'CREATE OR REPLACE ALERT OVERWATCH_ALERT_TASK_FAILURE WAREHOUSE = WH_ALFA_OVERWATCH SCHEDULE = ''30 MINUTE'' IF (EXISTS (SELECT 1 FROM FACT_TASK_RUN WHERE SCHEDULED_TIME >= DATEADD(''hour'', -2, CURRENT_TIMESTAMP()) AND UPPER(COALESCE(STATE, '''')) IN (''FAILED'', ''FAILED_WITH_ERROR'', ''SKIPPED'', ''CANCELLED''))) THEN INSERT INTO ALERT_EVENTS (COMPANY, ENVIRONMENT, ALERT_KEY, CATEGORY, SEVERITY, STATUS, OWNER, RECOMMENDED_ACTION, ENTITY_TYPE, REMEDIATION_MODE) SELECT COALESCE(COMPANY, ''Shared/Unclassified''), COALESCE(ENVIRONMENT, ''No Database Context''), ''PIPELINE_TASK_FAILURE'', ''Task / Pipeline'', ''Critical'', ''New'', ''DBA / Pipeline Owner'', ''Identify root task, failed child, last success, downstream SLA, and safe rerun conditions.'', ''TASK'', ''STATUS_REVIEW'' FROM FACT_TASK_RUN WHERE SCHEDULED_TIME >= DATEADD(''hour'', -2, CURRENT_TIMESTAMP()) AND UPPER(COALESCE(STATE, '''')) IN (''FAILED'', ''FAILED_WITH_ERROR'', ''SKIPPED'', ''CANCELLED'');', 'DROP ALERT IF EXISTS OVERWATCH_ALERT_TASK_FAILURE;', FALSE, 'Status-review only. Reruns require task graph safety checks.'),
    ('NATIVE_BEHAVIOR_USER_QUERY_ANOMALY', 'BEHAVIOR_USER_QUERY_ANOMALY', 'Behavior', 'OVERWATCH_ALERT_USER_QUERY_BEHAVIOR', 'Workload Operations', 'WH_ALFA_OVERWATCH', '60 MINUTE', 'CANDIDATE', 'FACT_QUERY_DETAIL_RECENT company/environment-labeled user failure, runtime, spill, and warehouse pressure patterns', 'Insert status-review behavior event into ALERT_EVENTS', 'CREATE OR REPLACE ALERT OVERWATCH_ALERT_USER_QUERY_BEHAVIOR WAREHOUSE = WH_ALFA_OVERWATCH SCHEDULE = ''60 MINUTE'' IF (EXISTS (SELECT 1 FROM FACT_QUERY_DETAIL_RECENT WHERE START_TIME >= DATEADD(''hour'', -2, CURRENT_TIMESTAMP()) GROUP BY COMPANY, ENVIRONMENT, USER_NAME, ROLE_NAME, WAREHOUSE_NAME HAVING COUNT(*) >= 10)) THEN INSERT INTO ALERT_EVENTS (COMPANY, ENVIRONMENT, ALERT_KEY, CATEGORY, SEVERITY, STATUS, OWNER, RECOMMENDED_ACTION, ENTITY_TYPE, REMEDIATION_MODE) SELECT COALESCE(COMPANY, ''Shared/Unclassified''), COALESCE(ENVIRONMENT, ''No Database Context''), ''BEHAVIOR_USER_QUERY_ANOMALY'', ''Behavior'', ''High'', ''New'', ''DBA / Workload reviewer'', ''Review repeated user query behavior before controls.'', ''USER'', ''STATUS_REVIEW'' FROM FACT_QUERY_DETAIL_RECENT WHERE START_TIME >= DATEADD(''hour'', -2, CURRENT_TIMESTAMP()) GROUP BY COMPANY, ENVIRONMENT, USER_NAME, ROLE_NAME, WAREHOUSE_NAME HAVING COUNT(*) >= 10;', 'DROP ALERT IF EXISTS OVERWATCH_ALERT_USER_QUERY_BEHAVIOR;', FALSE, 'Status-review only. Do not cancel queries, disable users, or change grants automatically.')
) src(REGISTRY_KEY, ALERT_KEY, CATEGORY, ALERT_OBJECT_NAME, TARGET_ROUTE, WAREHOUSE_NAME, SCHEDULE_TEXT, STATUS, CONDITION_SOURCE, ACTION_SOURCE, GENERATED_CREATE_SQL, GENERATED_DROP_SQL, ENABLED_BY_DEFAULT, SAFETY_NOTE)
ON tgt.REGISTRY_KEY = src.REGISTRY_KEY
WHEN MATCHED THEN UPDATE SET
  ALERT_KEY = src.ALERT_KEY,
  CATEGORY = src.CATEGORY,
  ALERT_OBJECT_NAME = src.ALERT_OBJECT_NAME,
  TARGET_ROUTE = src.TARGET_ROUTE,
  WAREHOUSE_NAME = src.WAREHOUSE_NAME,
  SCHEDULE_TEXT = src.SCHEDULE_TEXT,
  STATUS = src.STATUS,
  CONDITION_SOURCE = src.CONDITION_SOURCE,
  ACTION_SOURCE = src.ACTION_SOURCE,
  GENERATED_CREATE_SQL = src.GENERATED_CREATE_SQL,
  GENERATED_DROP_SQL = src.GENERATED_DROP_SQL,
  ENABLED_BY_DEFAULT = src.ENABLED_BY_DEFAULT,
  SAFETY_NOTE = src.SAFETY_NOTE,
  UPDATED_AT = CURRENT_TIMESTAMP(),
  UPDATED_BY = CURRENT_USER()
WHEN NOT MATCHED THEN INSERT
  (REGISTRY_KEY, ALERT_KEY, CATEGORY, ALERT_OBJECT_NAME, TARGET_ROUTE, WAREHOUSE_NAME, SCHEDULE_TEXT, STATUS, CONDITION_SOURCE, ACTION_SOURCE, GENERATED_CREATE_SQL, GENERATED_DROP_SQL, ENABLED_BY_DEFAULT, SAFETY_NOTE)
VALUES
  (src.REGISTRY_KEY, src.ALERT_KEY, src.CATEGORY, src.ALERT_OBJECT_NAME, src.TARGET_ROUTE, src.WAREHOUSE_NAME, src.SCHEDULE_TEXT, src.STATUS, src.CONDITION_SOURCE, src.ACTION_SOURCE, src.GENERATED_CREATE_SQL, src.GENERATED_DROP_SQL, src.ENABLED_BY_DEFAULT, src.SAFETY_NOTE);

CREATE TABLE IF NOT EXISTS ALERT_REMEDIATION_POLICY (
  POLICY_ID              VARCHAR(200) PRIMARY KEY,
  ALERT_KEY              VARCHAR(200),
  CATEGORY               VARCHAR(100),
  ACTION_TYPE            VARCHAR(200),
  REMEDIATION_MODE       VARCHAR(40) DEFAULT 'RECOMMEND',
  AUTO_ELIGIBLE          BOOLEAN DEFAULT FALSE,
  REQUIRED_REVIEW        VARCHAR(500),
  BEFORE_STATE_SQL       VARCHAR(8000),
  DRY_RUN_SQL            VARCHAR(8000),
  EXECUTION_SQL_TEMPLATE VARCHAR(8000),
  ROLLBACK_GUIDANCE      VARCHAR(4000),
  VERIFICATION_SQL       VARCHAR(8000),
  ACTIVE                 BOOLEAN DEFAULT TRUE,
  UPDATED_AT             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY             VARCHAR(200) DEFAULT CURRENT_USER()
);

CREATE TABLE IF NOT EXISTS ALERT_REMEDIATION_DRY_RUN (
  DRY_RUN_ID          NUMBER AUTOINCREMENT PRIMARY KEY,
  POLICY_ID           VARCHAR(200),
  EVENT_ID            NUMBER,
  ALERT_KEY           VARCHAR(200),
  CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CREATED_BY          VARCHAR(200) DEFAULT CURRENT_USER(),
  DRY_RUN_STATUS      VARCHAR(100),
  BEFORE_STATE        VARCHAR(8000),
  PROPOSED_SQL        VARCHAR(16000),
  EXPECTED_EFFECT     VARCHAR(4000),
  BLOCKING_REASON     VARCHAR(4000),
  VERIFICATION_SQL    VARCHAR(8000)
);

MERGE INTO ALERT_REMEDIATION_POLICY tgt
USING (
  SELECT * FROM VALUES
    ('POLICY_CORTEX_QUOTA_REVIEW', 'COST_CORTEX_SPEND_SPIKE', 'Cost', 'Cortex quota or access review', 'RECOMMEND', FALSE, 'DBA / AI cost route plus Security when grants change', 'SHOW PARAMETERS LIKE ''CORTEX%'' IN ACCOUNT;', '-- Review top FACT_CORTEX_DAILY users/sources and candidate quota setting; do not execute from Alert Center.', '-- No automatic Cortex access change. Use approved DBA workflow after review.', 'Restore prior Cortex parameter, role grant, or quota setting captured in before-state notes.', 'SELECT * FROM FACT_CORTEX_DAILY WHERE USAGE_DATE >= DATEADD(''day'', -7, CURRENT_DATE()) ORDER BY EST_COST_USD DESC LIMIT 100;'),
    ('POLICY_IDLE_WAREHOUSE_TIMEOUT_REVIEW', 'OPT_UNUSED_WAREHOUSE', 'Cost Recommendations', 'Warehouse auto-suspend timeout review', 'STATUS_REVIEW', FALSE, 'DBA / Cost owner', 'SHOW WAREHOUSES;', '-- Generate ALTER WAREHOUSE <name> SET AUTO_SUSPEND = <seconds> after route review.', 'ALTER WAREHOUSE IDENTIFIER(''<warehouse_name>'') SET AUTO_SUSPEND = <seconds>;', 'Reset AUTO_SUSPEND to the captured before-state value.', 'SHOW WAREHOUSES LIKE ''<warehouse_name>'';'),
    ('POLICY_WAREHOUSE_SPIKE_COST_REVIEW', 'COST_WAREHOUSE_CREDIT_SPIKE', 'Cost', 'Warehouse cost spike review', 'RECOMMEND', FALSE, 'DBA / Cost owner plus workload owner', 'SELECT * FROM FACT_WAREHOUSE_HOURLY WHERE WAREHOUSE_NAME = ''<warehouse_name>'' ORDER BY HOUR_START DESC LIMIT 168;', '-- Compare current/prior run-rate, top query hashes, warehouse settings, and company scope; no ALTER WAREHOUSE from Alert Center.', '-- No automatic warehouse change. Use guarded Admin workflow if a setting change is approved.', 'Restore prior warehouse settings only through guarded Admin review with before-state evidence.', 'SELECT * FROM FACT_WAREHOUSE_HOURLY WHERE WAREHOUSE_NAME = ''<warehouse_name>'' ORDER BY HOUR_START DESC LIMIT 168;'),
    ('POLICY_USER_QUERY_BEHAVIOR_REVIEW', 'BEHAVIOR_USER_QUERY_ANOMALY', 'Behavior', 'User/query behavior review', 'STATUS_REVIEW', FALSE, 'DBA / Workload reviewer', 'SELECT USER_NAME, ROLE_NAME, WAREHOUSE_NAME, QUERY_ID, EXECUTION_STATUS, TOTAL_ELAPSED_TIME, QUERY_TEXT FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY WHERE USER_NAME = ''<user_name>'' ORDER BY START_TIME DESC LIMIT 100;', '-- Compare repeated query hash, failures, role, warehouse, and recent coaching/change source before any control action.', '-- No automatic cancel, disable, revoke, or warehouse change from behavior alerts.', 'If a manual control was applied, restore access/settings only after verified query behavior and owner approval.', 'SELECT USER_NAME, ROLE_NAME, WAREHOUSE_NAME, COUNT(*) AS QUERY_COUNT FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY WHERE START_TIME >= DATEADD(''day'', -1, CURRENT_TIMESTAMP()) GROUP BY 1,2,3 ORDER BY QUERY_COUNT DESC;'),
    ('POLICY_TASK_RERUN_STATUS_REVIEW', 'PIPELINE_TASK_FAILURE', 'Task / Pipeline', 'Task rerun review', 'STATUS_REVIEW', FALSE, 'DBA / Pipeline Owner', 'SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY()) ORDER BY SCHEDULED_TIME DESC LIMIT 100;', '-- Confirm root cause, dependency state, and downstream idempotency before EXECUTE TASK.', 'EXECUTE TASK IDENTIFIER(''<database.schema.task_name>'');', 'Record downstream cleanup plan or rerun blocker before manual execution.', 'SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY()) ORDER BY SCHEDULED_TIME DESC LIMIT 100;'),
    ('POLICY_SECURITY_ACCESS_STATUS_REVIEW', 'SECURITY_PRIVILEGE_ESCALATION', 'Security', 'Access rollback review', 'STATUS_REVIEW', FALSE, 'Security Reviewer', 'SHOW GRANTS TO USER <user_name>;', '-- Compare grant, ticket, reviewer, and MFA posture before any revoke.', '-- Revoke SQL is intentionally not generated for AUTO mode.', 'Re-grant only after reviewer approval and ticket evidence.', 'SHOW GRANTS TO USER <user_name>;')
) src(POLICY_ID, ALERT_KEY, CATEGORY, ACTION_TYPE, REMEDIATION_MODE, AUTO_ELIGIBLE, REQUIRED_REVIEW, BEFORE_STATE_SQL, DRY_RUN_SQL, EXECUTION_SQL_TEMPLATE, ROLLBACK_GUIDANCE, VERIFICATION_SQL)
ON tgt.POLICY_ID = src.POLICY_ID
WHEN MATCHED THEN UPDATE SET
  ALERT_KEY = src.ALERT_KEY,
  CATEGORY = src.CATEGORY,
  ACTION_TYPE = src.ACTION_TYPE,
  REMEDIATION_MODE = src.REMEDIATION_MODE,
  AUTO_ELIGIBLE = src.AUTO_ELIGIBLE,
  REQUIRED_REVIEW = src.REQUIRED_REVIEW,
  BEFORE_STATE_SQL = src.BEFORE_STATE_SQL,
  DRY_RUN_SQL = src.DRY_RUN_SQL,
  EXECUTION_SQL_TEMPLATE = src.EXECUTION_SQL_TEMPLATE,
  ROLLBACK_GUIDANCE = src.ROLLBACK_GUIDANCE,
  VERIFICATION_SQL = src.VERIFICATION_SQL,
  UPDATED_AT = CURRENT_TIMESTAMP(),
  UPDATED_BY = CURRENT_USER()
WHEN NOT MATCHED THEN INSERT
  (POLICY_ID, ALERT_KEY, CATEGORY, ACTION_TYPE, REMEDIATION_MODE, AUTO_ELIGIBLE, REQUIRED_REVIEW, BEFORE_STATE_SQL, DRY_RUN_SQL, EXECUTION_SQL_TEMPLATE, ROLLBACK_GUIDANCE, VERIFICATION_SQL)
VALUES
  (src.POLICY_ID, src.ALERT_KEY, src.CATEGORY, src.ACTION_TYPE, src.REMEDIATION_MODE, src.AUTO_ELIGIBLE, src.REQUIRED_REVIEW, src.BEFORE_STATE_SQL, src.DRY_RUN_SQL, src.EXECUTION_SQL_TEMPLATE, src.ROLLBACK_GUIDANCE, src.VERIFICATION_SQL);

CREATE OR REPLACE VIEW ALERT_NATIVE_DEPLOYMENT_REVIEW_V AS
SELECT
  REGISTRY_KEY,
  ALERT_KEY,
  CATEGORY,
  ALERT_OBJECT_NAME,
  TARGET_ROUTE,
  WAREHOUSE_NAME,
  SCHEDULE_TEXT,
  STATUS,
  ENABLED_BY_DEFAULT,
  CASE
    WHEN COALESCE(ENABLED_BY_DEFAULT, FALSE) THEN 'BLOCKED_ENABLED_BY_DEFAULT'
    WHEN UPPER(COALESCE(STATUS, 'CANDIDATE')) IN ('APPROVED', 'READY', 'READY_TO_DEPLOY') THEN 'READY_FOR_MANUAL_DEPLOY'
    WHEN UPPER(COALESCE(STATUS, 'CANDIDATE')) IN ('DEPLOYED', 'ACTIVE') THEN 'DEPLOYED_MONITOR'
    ELSE 'CANDIDATE_REVIEW_REQUIRED'
  END AS DEPLOYMENT_STATE,
  IFF(GENERATED_CREATE_SQL ILIKE '%CREATE OR REPLACE ALERT%', TRUE, FALSE) AS DEPLOYMENT_SQL_PRESENT,
  IFF(GENERATED_DROP_SQL ILIKE '%DROP ALERT%', TRUE, FALSE) AS ROLLBACK_SQL_PRESENT,
  CASE
    WHEN COALESCE(ENABLED_BY_DEFAULT, FALSE) THEN 'Set ENABLED_BY_DEFAULT to FALSE before review can continue.'
    WHEN UPPER(COALESCE(STATUS, 'CANDIDATE')) IN ('APPROVED', 'READY', 'READY_TO_DEPLOY') THEN 'Run GENERATED_CREATE_SQL manually after owner, threshold, schedule, and warehouse approval.'
    WHEN UPPER(COALESCE(STATUS, 'CANDIDATE')) IN ('DEPLOYED', 'ACTIVE') THEN 'Monitor ALERT_EVENTS and dry-run outcomes; use GENERATED_DROP_SQL only for rollback.'
    ELSE 'Review owner, threshold, route, safety note, and generated SQL before marking approved.'
  END AS DEPLOYMENT_NEXT_STEP,
  'SHOW ALERTS LIKE ''' || ALERT_OBJECT_NAME || ''';' AS VALIDATION_SQL,
  SAFETY_NOTE,
  GENERATED_CREATE_SQL,
  GENERATED_DROP_SQL,
  UPDATED_AT,
  UPDATED_BY
FROM ALERT_NATIVE_OBJECT_REGISTRY;

CREATE OR REPLACE PROCEDURE SP_OVERWATCH_STAGE_ALERT_REMEDIATION_DRY_RUN(
  P_EVENT_ID NUMBER,
  P_ALERT_KEY VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
  INSERT INTO ALERT_REMEDIATION_DRY_RUN
    (POLICY_ID, EVENT_ID, ALERT_KEY, DRY_RUN_STATUS, BEFORE_STATE, PROPOSED_SQL,
     EXPECTED_EFFECT, BLOCKING_REASON, VERIFICATION_SQL)
  SELECT
    p.POLICY_ID,
    e.EVENT_ID,
    e.ALERT_KEY,
    CASE
      WHEN COALESCE(p.AUTO_ELIGIBLE, FALSE) THEN 'REVIEW_REQUIRED_AUTO_DISABLED'
      ELSE 'BLOCKED_REVIEW_REQUIRED'
    END AS DRY_RUN_STATUS,
    p.BEFORE_STATE_SQL AS BEFORE_STATE,
    COALESCE(NULLIF(p.EXECUTION_SQL_TEMPLATE, ''), p.DRY_RUN_SQL) AS PROPOSED_SQL,
    'Dry-run only. Capture before-state, review route owner, and verify expected impact before any manual action.' AS EXPECTED_EFFECT,
    CASE
      WHEN COALESCE(p.AUTO_ELIGIBLE, FALSE) THEN 'AUTO_ELIGIBLE is not sufficient for execution; guarded automation is not enabled in OVERWATCH.'
      ELSE 'AUTO_ELIGIBLE is false. Manual review is required before any action.'
    END AS BLOCKING_REASON,
    p.VERIFICATION_SQL
  FROM ALERT_EVENTS e
  JOIN ALERT_REMEDIATION_POLICY p
    ON UPPER(p.ALERT_KEY) = UPPER(e.ALERT_KEY)
   AND COALESCE(p.ACTIVE, TRUE)
  WHERE (P_EVENT_ID IS NULL OR e.EVENT_ID = P_EVENT_ID)
    AND (P_ALERT_KEY IS NULL OR UPPER(e.ALERT_KEY) = UPPER(P_ALERT_KEY))
    AND NOT EXISTS (
      SELECT 1
      FROM ALERT_REMEDIATION_DRY_RUN d
      WHERE d.EVENT_ID = e.EVENT_ID
        AND d.POLICY_ID = p.POLICY_ID
        AND d.CREATED_AT >= DATEADD('hour', -24, CURRENT_TIMESTAMP())
    );

  RETURN 'Remediation dry-run staging completed. Review ALERT_REMEDIATION_DRY_RUN before any manual action.';
END;
$$;

MERGE INTO ALERT_THRESHOLDS tgt
USING (
  SELECT * FROM VALUES
    ('SECURITY_FAILED_LOGIN_SPIKE', 'Security', 'Failed login spike', 'High', 10, 14, 60, 'DBA / Security', 'DBA_SECURITY'),
    ('SECURITY_PRIVILEGE_ESCALATION', 'Security', 'Privileged role grant', 'Critical', 1, 7, 1440, 'Security Approver', 'DBA_SECURITY'),
    ('COST_WAREHOUSE_CREDIT_SPIKE', 'Cost', 'Warehouse credit spike', 'High', 1.5, 30, 1440, 'DBA / Cost owner', 'COST'),
    ('COST_CORTEX_SPEND_SPIKE', 'Cost', 'Cortex spend spike', 'High', 25, 30, 10080, 'DBA / AI cost route', 'COST'),
    ('BEHAVIOR_USER_QUERY_ANOMALY', 'Behavior', 'User query behavior anomaly', 'High', 10, 14, 120, 'DBA / Workload reviewer', 'DBA_ONCALL'),
    ('PERF_QUEUE_PRESSURE', 'Performance', 'Warehouse queue pressure', 'High', 300, 14, 60, 'DBA / Platform', 'DBA_ONCALL'),
    ('PIPELINE_TASK_FAILURE', 'Task / Pipeline', 'Production task failure', 'Critical', 1, 7, 1440, 'DBA / Pipeline Owner', 'PIPELINE_ONCALL'),
    ('DQ_FRESHNESS_SLA', 'Data Quality', 'Freshness SLA missed', 'High', 1, 7, 1440, 'Data Owner', 'DATA_QUALITY'),
    ('OPT_UNUSED_WAREHOUSE', 'Cost Recommendations', 'Unused or oversized warehouse', 'Medium', 14, 30, 1440, 'DBA / Cost owner', 'COST')
) src(THRESHOLD_KEY, CATEGORY, SIGNAL_NAME, SEVERITY, THRESHOLD_VALUE, BASELINE_WINDOW_DAYS, CURRENT_WINDOW_MINUTES, OWNER, NOTIFICATION_CHANNEL)
ON tgt.THRESHOLD_KEY = src.THRESHOLD_KEY
WHEN MATCHED THEN UPDATE SET
  CATEGORY = src.CATEGORY,
  SIGNAL_NAME = src.SIGNAL_NAME,
  SEVERITY = src.SEVERITY,
  THRESHOLD_VALUE = src.THRESHOLD_VALUE,
  BASELINE_WINDOW_DAYS = src.BASELINE_WINDOW_DAYS,
  CURRENT_WINDOW_MINUTES = src.CURRENT_WINDOW_MINUTES,
  OWNER = src.OWNER,
  NOTIFICATION_CHANNEL = src.NOTIFICATION_CHANNEL,
  UPDATED_AT = CURRENT_TIMESTAMP(),
  UPDATED_BY = CURRENT_USER()
WHEN NOT MATCHED THEN INSERT
  (THRESHOLD_KEY, CATEGORY, SIGNAL_NAME, SEVERITY, THRESHOLD_VALUE, BASELINE_WINDOW_DAYS, CURRENT_WINDOW_MINUTES, OWNER, NOTIFICATION_CHANNEL)
VALUES
  (src.THRESHOLD_KEY, src.CATEGORY, src.SIGNAL_NAME, src.SEVERITY, src.THRESHOLD_VALUE, src.BASELINE_WINDOW_DAYS, src.CURRENT_WINDOW_MINUTES, src.OWNER, src.NOTIFICATION_CHANNEL);

MERGE INTO ALERT_CONFIG tgt
USING (
  SELECT * FROM VALUES
    ('SECURITY_FAILED_LOGIN_SPIKE', 'Security', 'Failed login spike', 'High', 'DBA / Security', 'Security Monitoring', 'DBA_SECURITY'),
    ('SECURITY_PRIVILEGE_ESCALATION', 'Security', 'Privileged role grant', 'Critical', 'Security Reviewer', 'Security Monitoring', 'DBA_SECURITY'),
    ('COST_WAREHOUSE_CREDIT_SPIKE', 'Cost', 'Warehouse credit spike', 'High', 'DBA / Cost owner', 'Cost & Contract', 'COST'),
    ('COST_CORTEX_SPEND_SPIKE', 'Cost', 'Cortex spend spike', 'High', 'DBA / AI cost route', 'Cost & Contract', 'COST'),
    ('BEHAVIOR_USER_QUERY_ANOMALY', 'Behavior', 'User query behavior anomaly', 'High', 'DBA / Workload reviewer', 'Workload Operations', 'DBA_ONCALL'),
    ('PERF_QUEUE_PRESSURE', 'Performance', 'Warehouse queue pressure', 'High', 'DBA / Platform', 'Workload Operations', 'DBA_ONCALL'),
    ('PIPELINE_TASK_FAILURE', 'Task / Pipeline', 'Production task failure', 'Critical', 'DBA / Pipeline Owner', 'Workload Operations', 'PIPELINE_ONCALL'),
    ('DQ_FRESHNESS_SLA', 'Data Quality', 'Freshness SLA missed', 'High', 'Data Owner', 'Workload Operations', 'DATA_QUALITY'),
    ('OPT_UNUSED_WAREHOUSE', 'Cost Recommendations', 'Unused or oversized warehouse', 'Medium', 'DBA / Cost owner', 'Cost & Contract', 'COST')
) src(ALERT_KEY, CATEGORY, SIGNAL_NAME, DEFAULT_SEVERITY, OWNER, ROUTE, NOTIFICATION_CHANNEL)
ON tgt.ALERT_KEY = src.ALERT_KEY
WHEN MATCHED THEN UPDATE SET
  CATEGORY = src.CATEGORY,
  SIGNAL_NAME = src.SIGNAL_NAME,
  DEFAULT_SEVERITY = src.DEFAULT_SEVERITY,
  OWNER = src.OWNER,
  ROUTE = src.ROUTE,
  NOTIFICATION_CHANNEL = src.NOTIFICATION_CHANNEL,
  UPDATED_AT = CURRENT_TIMESTAMP(),
  UPDATED_BY = CURRENT_USER()
WHEN NOT MATCHED THEN INSERT
  (ALERT_KEY, CATEGORY, SIGNAL_NAME, DEFAULT_SEVERITY, OWNER, ROUTE, NOTIFICATION_CHANNEL, TELEMETRY_LATENCY)
VALUES
  (src.ALERT_KEY, src.CATEGORY, src.SIGNAL_NAME, src.DEFAULT_SEVERITY, src.OWNER, src.ROUTE, src.NOTIFICATION_CHANNEL, 'ACCOUNT_USAGE delayed unless otherwise documented');


CREATE TABLE IF NOT EXISTS OVERWATCH_ANNOTATIONS (
  ANNOTATION_ID     NUMBER AUTOINCREMENT PRIMARY KEY,
  CREATED_BY        VARCHAR(200),
  CREATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  ENTITY            VARCHAR(500),
  ENTITY_TYPE       VARCHAR(50),
  WINDOW_START      TIMESTAMP_NTZ NOT NULL,
  WINDOW_END        TIMESTAMP_NTZ NOT NULL,
  ANNOTATION_TYPE   VARCHAR(100),
  DESCRIPTION       VARCHAR(2000),
  SUPPRESS_ALERTS   BOOLEAN DEFAULT TRUE,
  ACTIVE            BOOLEAN DEFAULT TRUE
);


CREATE TABLE IF NOT EXISTS OVERWATCH_ALERT_DELIVERY_LOG (
  DELIVERY_ID      NUMBER AUTOINCREMENT PRIMARY KEY,
  DELIVERY_TS      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  COMPANY          VARCHAR(100),
  ENVIRONMENT      VARCHAR(100),
  ALERT_IDS        VARIANT,
  ALERT_COUNT      NUMBER,
  DELIVERY_METHOD  VARCHAR(40) DEFAULT 'EMAIL',
  DELIVERY_TARGET  VARCHAR(500),
  EMAIL_SUBJECT    VARCHAR(1000),
  EMAIL_BODY       VARCHAR(16000),
  DELIVERY_STATUS  VARCHAR(100),
  DELIVERY_BY      VARCHAR(200),
  DELIVERY_NOTES   VARCHAR(4000)
);

CREATE OR REPLACE PROCEDURE SP_OVERWATCH_SEND_ALERT_DIGEST(
  P_COMPANY VARCHAR DEFAULT 'ALFA',
  P_ENVIRONMENT VARCHAR DEFAULT 'ALL',
  P_RECIPIENT VARCHAR DEFAULT NULL,
  P_DRY_RUN BOOLEAN DEFAULT TRUE
)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  alert_count NUMBER DEFAULT 0;
  alert_ids VARIANT DEFAULT PARSE_JSON('[]');
  subject VARCHAR DEFAULT '';
  body VARCHAR DEFAULT '';
  recipient VARCHAR DEFAULT NULL;
  delivery_status VARCHAR DEFAULT 'EMAIL_DRY_RUN';
BEGIN
  CREATE OR REPLACE TEMPORARY TABLE TMP_OVERWATCH_ALERT_DIGEST AS
  SELECT
    ALERT_ID,
    COMPANY,
    ENVIRONMENT,
    SEVERITY,
    CATEGORY,
    ALERT_TYPE,
    ENTITY_NAME,
    OWNER,
    COALESCE(EMAIL_SUBJECT, 'OVERWATCH ' || COALESCE(SEVERITY, 'Medium') || ' alert digest') AS EMAIL_SUBJECT,
    COALESCE(
      EMAIL_BODY,
      COALESCE(SEVERITY, 'Medium') || ' | ' || COALESCE(CATEGORY, 'Alert') || ' | ' ||
      COALESCE(ALERT_TYPE, CATEGORY, 'Alert') || ' | ' || COALESCE(ENTITY_NAME, ENTITY, 'Snowflake account') ||
      '\nAction: ' || COALESCE(SUGGESTED_ACTION, 'Review in Alert Center.')
    ) AS EMAIL_BODY
  FROM OVERWATCH_ALERTS
  WHERE UPPER(REPLACE(COALESCE(STATUS, 'New'), ' ', '_')) IN ('NEW', 'OPEN', 'ACTIVE', 'EMAIL_READY', 'EMAIL_QUEUED', 'PENDING', 'ACKNOWLEDGED', 'IN_PROGRESS')
    AND (:P_COMPANY = 'ALL' OR COMPANY = :P_COMPANY)
    AND (
      :P_ENVIRONMENT = 'ALL'
      OR COALESCE(ENVIRONMENT, 'No Database Context') = :P_ENVIRONMENT
      OR (:P_ENVIRONMENT = 'DEV_ALL' AND COALESCE(ENVIRONMENT, '') IN ('DEV_ALL', 'ALFA_EDW_DEV', 'ALFA_EDW_SAN', 'ALFA_EDW_PHX', 'ALFA_EDW_SEA', 'ALFA_EDW_SIT', 'OTHER ALFA NON-PROD'))
    )
  ORDER BY
    CASE UPPER(COALESCE(SEVERITY, 'Medium'))
      WHEN 'CRITICAL' THEN 0
      WHEN 'HIGH' THEN 1
      WHEN 'MEDIUM' THEN 2
      WHEN 'LOW' THEN 3
      ELSE 4
    END,
    ALERT_TS DESC
  LIMIT 25;

  SELECT
    COUNT(*),
    TO_VARIANT(ARRAY_AGG(ALERT_ID)),
    'OVERWATCH alert digest - ' || :P_COMPANY || ' / ' || :P_ENVIRONMENT || ' - ' || COUNT(*) || ' open issue(s)',
    LISTAGG(
      '[' || COALESCE(SEVERITY, 'Medium') || '] ' || COALESCE(ALERT_TYPE, CATEGORY, 'Alert') ||
      ' | ' || COALESCE(ENTITY_NAME, 'Snowflake account') ||
      ' | Owner: ' || COALESCE(OWNER, 'DBA') ||
      '\n' || EMAIL_BODY,
      '\n\n---\n\n'
    ) WITHIN GROUP (ORDER BY ALERT_ID)
  INTO :alert_count, :alert_ids, :subject, :body
  FROM TMP_OVERWATCH_ALERT_DIGEST;

  IF (alert_count = 0) THEN
    RETURN 'No open OVERWATCH alerts matched the requested scope.';
  END IF;

  SELECT COALESCE(NULLIF(:P_RECIPIENT, ''), MAX(NULLIF(SETTING_VALUE, '')))
    INTO :recipient
  FROM OVERWATCH_SETTINGS
  WHERE SETTING_NAME = 'DEFAULT_ALERT_EMAIL';

  IF (P_DRY_RUN) THEN
    delivery_status := IFF(recipient IS NULL, 'EMAIL_DRY_RUN_CONFIG_REQUIRED', 'EMAIL_DRY_RUN');
  ELSEIF (recipient IS NULL) THEN
    delivery_status := 'CONFIG_REQUIRED';
  ELSE
    CALL SYSTEM$SEND_EMAIL('OVERWATCH_EMAIL_INT', :recipient, :subject, :body);
    delivery_status := 'EMAIL_SENT';
  END IF;

  INSERT INTO OVERWATCH_ALERT_DELIVERY_LOG
    (COMPANY, ENVIRONMENT, ALERT_IDS, ALERT_COUNT, DELIVERY_METHOD, DELIVERY_TARGET,
     EMAIL_SUBJECT, EMAIL_BODY, DELIVERY_STATUS, DELIVERY_BY, DELIVERY_NOTES)
  VALUES
    (:P_COMPANY, :P_ENVIRONMENT, :alert_ids, :alert_count, 'EMAIL', :recipient,
     :subject, :body, :delivery_status, CURRENT_USER(),
     CASE
       WHEN :recipient IS NULL THEN 'Alert email is not configured; SYSTEM$SEND_EMAIL was not called.'
       WHEN :P_DRY_RUN THEN 'Dry-run replay package prepared; SYSTEM$SEND_EMAIL was not called.'
       ELSE 'Delivered through approved Snowflake email notification integration OVERWATCH_EMAIL_INT.'
     END);

  UPDATE OVERWATCH_ALERTS
  SET
    DELIVERY_STATUS = delivery_status,
    DELIVERY_TARGET = :recipient,
    EMAIL_TARGET = COALESCE(NULLIF(EMAIL_TARGET, ''), :recipient),
    LAST_DELIVERY_AT = CURRENT_TIMESTAMP(),
    LAST_DELIVERY_BY = CURRENT_USER(),
    DELIVERY_LOG_COUNT = COALESCE(DELIVERY_LOG_COUNT, 0) + 1,
    LAST_STATUS_BY = CURRENT_USER(),
    LAST_STATUS_AT = CURRENT_TIMESTAMP()
  WHERE ARRAY_CONTAINS(ALERT_ID::VARIANT, :alert_ids);

  RETURN 'OVERWATCH alert digest ' || delivery_status || ': ' || alert_count || ' alert(s)'
    || IFF(recipient IS NULL, '; alert email not configured.', ' for ' || recipient);
END;
$$;

CREATE TABLE IF NOT EXISTS OVERWATCH_ALERT_RULE_AUDIT (
  AUDIT_ID                NUMBER AUTOINCREMENT PRIMARY KEY,
  AUDIT_TS                TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  RULE_ID                 VARCHAR(200),
  ACTION                  VARCHAR(40),
  PRIOR_DEFAULT_SEVERITY  VARCHAR(20),
  NEW_DEFAULT_SEVERITY    VARCHAR(20),
  PRIOR_SLA_HOURS         NUMBER,
  NEW_SLA_HOURS           NUMBER,
  PRIOR_OWNER             VARCHAR(200),
  NEW_OWNER               VARCHAR(200),
  PRIOR_ROUTE             VARCHAR(200),
  NEW_ROUTE               VARCHAR(200),
  PRIOR_RUNBOOK           VARCHAR(2000),
  NEW_RUNBOOK             VARCHAR(2000),
  PRIOR_IS_ACTIVE         BOOLEAN,
  NEW_IS_ACTIVE           BOOLEAN,
  CHANGED_BY              VARCHAR(200),
  CHANGE_REASON           VARCHAR(2000)
);

CREATE TABLE IF NOT EXISTS OVERWATCH_ALERT_RULES (
  RULE_ID              VARCHAR(200) PRIMARY KEY,
  CATEGORY             VARCHAR(100),
  ALERT_TYPE           VARCHAR(100),
  DEFAULT_SEVERITY     VARCHAR(20),
  SLA_HOURS            NUMBER,
  OWNER                VARCHAR(200),
  ROUTE                VARCHAR(200),
  RUNBOOK              VARCHAR(2000),
  IS_ACTIVE            BOOLEAN DEFAULT TRUE,
  UPDATED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY           VARCHAR(200) DEFAULT CURRENT_USER()
);

MERGE INTO OVERWATCH_ALERT_RULES tgt
USING (
  SELECT * FROM VALUES
    ('COST_CREDIT_SPIKE', 'Cost Control', 'Credit Spike', 'Medium', 24, 'DBA / Cost owner', 'Cost & Contract', 'Explain the bill movement, identify owner-backed drivers, and route cost-control actions.'),
    ('QUERY_HIGH_ERROR_RATE', 'Reliability', 'High Query Error Rate', 'High', 8, 'DBA / Workload Owner', 'Workload Operations', 'Group failures by error code/query text and assign the owning team.'),
    ('TASK_FAILURE', 'Reliability', 'Task Failure', 'High', 8, 'DBA / Pipeline Owner', 'Workload Operations', 'Review task graph impact, retry only after root cause, and verify the next run.'),
    ('PROCEDURE_FAILURE_OR_SPIKE', 'Reliability', 'Stored Procedure Failure / Runtime Spike', 'High', 8, 'DBA / Procedure Owner', 'Workload Operations', 'Compare release windows, inspect child queries, and verify runtime/cost return to baseline.'),
    ('WAREHOUSE_PRESSURE', 'Capacity', 'Warehouse Pressure', 'Medium', 24, 'DBA / Platform', 'Cost & Contract', 'Inspect queue/spill telemetry and route changed-only warehouse setting recommendations.'),
    ('GRANT_REVOKE_ACTIVITY', 'Change Tracking', 'Grant/Revoke Activity', 'Medium', 24, 'DBA / Security', 'Security Monitoring', 'Review least-privilege telemetry, actor, object, and review date.'),
    ('WAREHOUSE_SETTING_CHANGE', 'Change Tracking', 'Warehouse Setting Change', 'Medium', 24, 'DBA / Platform', 'Cost & Contract', 'Review changed-only SQL, rollback SQL, and post-change telemetry.'),
    ('SECURITY_PRIVILEGE_ESCALATION', 'Security', 'Privileged Role Grant', 'Critical', 4, 'Security Reviewer', 'Security Monitoring', 'Validate ticket, reviewer, MFA posture, service-account purpose, and review date before accepting privileged role expansion.'),
    ('SECURITY_SENSITIVE_EXPORT', 'Security', 'Sensitive Access Or Export', 'High', 8, 'DBA / Security', 'Security Monitoring', 'Inspect source IP, role, query_id, destination stage, object access, and masking policy coverage.'),
    ('PERF_QUERY_PRESSURE', 'Performance', 'Query Pressure', 'High', 8, 'DBA / Platform', 'Workload Operations', 'Open Query Investigation or Performance & Contention with query_id, queue/spill/lock telemetry, owner, and specific optimization path.'),
    ('PIPELINE_COPY_FAILURE', 'Task / Pipeline', 'Copy Load Failure', 'High', 8, 'DBA / Data Engineering', 'Workload Operations', 'Group by table/stage/error, fix load cause, confirm downstream task graph freshness, and document SLA recovery.'),
    ('DQ_FRESHNESS_SLA', 'Data Quality', 'Freshness SLA Missed', 'High', 8, 'Data Owner', 'Workload Operations', 'Use configured database/schema/table/column/check threshold, prove latest update/load volume, and route to data owner.'),
    ('OPT_UNUSED_OR_OVERSIZED_WAREHOUSE', 'Cost Recommendations', 'Unused Or Oversized Warehouse', 'Medium', 24, 'DBA / Cost owner', 'Cost & Contract', 'Attach metering/query telemetry, owner route, rollback SQL, and expected savings before changing warehouse settings.'),
    ('WAREHOUSE_COST_MOVEMENT', 'Cost Control', 'WAREHOUSE_COST_MOVEMENT', 'High', 8, 'DBA / Cost owner', 'Cost & Contract', 'Explain the 7d warehouse cost movement, assign the owner, and route action after telemetry review.'),
    ('CORTEX_SPEND_AND_QUOTA', 'Cost Control', 'CORTEX_SPEND_AND_QUOTA', 'Medium', 24, 'DBA / AI cost route', 'Cost & Contract', 'Review shared AI spend threshold, per-user quota, first/last usage, and access expansion before enforcing controls.'),
    ('CHANGE_COST_CORRELATION', 'Cost Control', 'CHANGE_COST_CORRELATION', 'High', 8, 'DBA / Cost owner', 'Cost & Contract', 'Compare warehouse change query_id, actor, rollback telemetry, and cost movement before tuning.')
) src(RULE_ID, CATEGORY, ALERT_TYPE, DEFAULT_SEVERITY, SLA_HOURS, OWNER, ROUTE, RUNBOOK)
ON tgt.RULE_ID = src.RULE_ID
WHEN MATCHED THEN UPDATE SET
  CATEGORY = src.CATEGORY,
  ALERT_TYPE = src.ALERT_TYPE,
  DEFAULT_SEVERITY = src.DEFAULT_SEVERITY,
  SLA_HOURS = src.SLA_HOURS,
  OWNER = src.OWNER,
  ROUTE = src.ROUTE,
  RUNBOOK = src.RUNBOOK,
  IS_ACTIVE = TRUE
WHEN NOT MATCHED THEN INSERT
  (RULE_ID, CATEGORY, ALERT_TYPE, DEFAULT_SEVERITY, SLA_HOURS, OWNER, ROUTE, RUNBOOK)
VALUES
  (src.RULE_ID, src.CATEGORY, src.ALERT_TYPE, src.DEFAULT_SEVERITY, src.SLA_HOURS, src.OWNER, src.ROUTE, src.RUNBOOK);

CREATE OR REPLACE VIEW OVERWATCH_ALERT_TRIAGE_V AS
WITH base AS (
  SELECT
    a.*,
    COALESCE(r.OWNER, a.OWNER, 'DBA') AS ROUTED_OWNER,
    NULL AS OWNER_EMAIL,
    COALESCE(r.OWNER, a.OWNER, 'DBA On-Call') AS ONCALL_PRIMARY,
    NULL AS ONCALL_SECONDARY,
    COALESCE(r.OWNER, a.OWNER, 'DBA Lead') AS APPROVAL_GROUP,
    COALESCE(r.OWNER, a.OWNER, 'DBA Lead') AS OWNER_ESCALATION_TARGET,
    'ALERT_RULE' AS OWNER_SOURCE,
    'Matched alert rule or alert row owner' AS OWNER_EVIDENCE,
    COALESCE(
      r.SLA_HOURS,
      CASE UPPER(COALESCE(a.SEVERITY, 'Medium'))
        WHEN 'CRITICAL' THEN 4
        WHEN 'HIGH' THEN 8
        WHEN 'LOW' THEN 72
        ELSE 24
      END
    ) AS SLA_TARGET_HOURS,
    GREATEST(0, COALESCE(DATEDIFF('hour', a.ALERT_TS, CURRENT_TIMESTAMP()), 0)) AS ALERT_AGE_HOURS,
    COALESCE(r.ROUTE, 'Alert Center') AS ALERT_ROUTE,
    COALESCE(r.RUNBOOK, a.SUGGESTED_ACTION, 'Review the Alert Center issue and route it through the DBA action queue.') AS ALERT_RUNBOOK
  FROM OVERWATCH_ALERTS a
  LEFT JOIN OVERWATCH_ALERT_RULES r
    ON UPPER(COALESCE(a.ALERT_TYPE, a.CATEGORY, '')) = UPPER(COALESCE(r.ALERT_TYPE, r.CATEGORY, ''))
   AND COALESCE(r.IS_ACTIVE, TRUE)
),
sla AS (
  SELECT
    base.*,
    CASE
      WHEN UPPER(REPLACE(COALESCE(STATUS, 'New'), ' ', '_')) IN ('FIXED', 'IGNORED', 'RESOLVED') THEN 'Closed'
      WHEN ALERT_AGE_HOURS > SLA_TARGET_HOURS THEN 'Overdue'
      WHEN ALERT_AGE_HOURS >= (SLA_TARGET_HOURS * 0.75) THEN 'Due Soon'
      ELSE 'Within SLA'
    END AS SLA_STATE
  FROM base
)
SELECT
  sla.*,
  CASE
    WHEN SLA_STATE = 'Overdue' AND UPPER(COALESCE(SEVERITY, 'Medium')) IN ('CRITICAL', 'HIGH') THEN COALESCE(OWNER_ESCALATION_TARGET, ESCALATED_TO, 'DBA Lead')
    ELSE COALESCE(OWNER_ESCALATION_TARGET, ROUTED_OWNER, OWNER, 'DBA')
  END AS ESCALATION_TARGET,
  (
    CASE UPPER(COALESCE(SEVERITY, 'Medium'))
      WHEN 'CRITICAL' THEN 0
      WHEN 'HIGH' THEN 1
      WHEN 'MEDIUM' THEN 2
      WHEN 'LOW' THEN 3
      ELSE 4
    END * 100
    + CASE SLA_STATE
      WHEN 'Overdue' THEN 0
      WHEN 'Due Soon' THEN 1
      WHEN 'Within SLA' THEN 2
      WHEN 'Closed' THEN 9
      ELSE 5
    END * 10
    + CASE UPPER(REPLACE(COALESCE(STATUS, 'New'), ' ', '_'))
      WHEN 'NEW' THEN 0
      WHEN 'EMAIL_READY' THEN 0
      WHEN 'EMAIL_QUEUED' THEN 0
      WHEN 'OPEN' THEN 0
      WHEN 'ACTIVE' THEN 0
      WHEN 'PENDING' THEN 0
      WHEN 'ACKNOWLEDGED' THEN 1
      WHEN 'IN_PROGRESS' THEN 1
      WHEN 'FIXED' THEN 3
      WHEN 'RESOLVED' THEN 3
      WHEN 'IGNORED' THEN 4
      ELSE 2
    END
  ) AS TRIAGE_PRIORITY
FROM sla;

CREATE TABLE IF NOT EXISTS OVERWATCH_RECON_CONFIG (
  CHECK_ID             NUMBER AUTOINCREMENT PRIMARY KEY,
  CHECK_NAME           VARCHAR(300),
  SOURCE_DATABASE      VARCHAR(300),
  SOURCE_SCHEMA        VARCHAR(300),
  TARGET_DATABASE      VARCHAR(300),
  TARGET_SCHEMA        VARCHAR(300),
  TABLE_PATTERN        VARCHAR(300) DEFAULT '%',
  KEY_COLUMNS          VARCHAR(2000),
  EXCLUDE_COLUMNS      VARCHAR(2000),
  WHERE_CLAUSE         VARCHAR(4000),
  HASH_BUCKET_COUNT    NUMBER DEFAULT 64,
  CHECK_MODE           VARCHAR(50) DEFAULT 'COUNT_AND_HASH',
  SEVERITY             VARCHAR(40) DEFAULT 'MEDIUM',
  OWNER                VARCHAR(300),
  ENABLED              BOOLEAN DEFAULT TRUE,
  CREATED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS OVERWATCH_RECON_RUN (
  RUN_ID               NUMBER AUTOINCREMENT PRIMARY KEY,
  CHECK_ID             NUMBER,
  RUN_TS               TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  RUN_STATUS           VARCHAR(40),
  SOURCE_ROW_COUNT     NUMBER,
  TARGET_ROW_COUNT     NUMBER,
  SOURCE_HASH          VARCHAR(200),
  TARGET_HASH          VARCHAR(200),
  MISMATCH_COUNT       NUMBER,
  SAMPLE_DIFF_SQL      VARCHAR(16000),
  RECOMMENDED_ACTION   VARCHAR(2000)
);

CREATE TABLE IF NOT EXISTS OVERWATCH_SCHEMA_DIFF_RESULT (
  RUN_TS               TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  SOURCE_DATABASE      VARCHAR(300),
  SOURCE_SCHEMA        VARCHAR(300),
  TARGET_DATABASE      VARCHAR(300),
  TARGET_SCHEMA        VARCHAR(300),
  OBJECT_TYPE          VARCHAR(100),
  OBJECT_NAME          VARCHAR(1000),
  DIFF_TYPE            VARCHAR(100),
  GENERATED_DDL        VARCHAR(16000),
  OWNER                VARCHAR(300),
  SEVERITY             VARCHAR(40)
);

