-- OVERWATCH mart setup split: 04_tables.sql

-- Create and evolve configuration, audit, and mart tables, including seed rows.

-- Source bundle: snowflake/OVERWATCH_MART_SETUP.sql



USE DATABASE DBA_MAINT_DB;
USE SCHEMA OVERWATCH;




-- -----------------------------------------------------------------------------
-- 2. Configuration and audit tables
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS OVERWATCH_SETTINGS (
  SETTING_NAME        VARCHAR(200) PRIMARY KEY,
  SETTING_VALUE       VARCHAR(4000),
  SETTING_TYPE        VARCHAR(50),
  DESCRIPTION         VARCHAR(1000),
  UPDATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY          VARCHAR(200) DEFAULT CURRENT_USER()
);


CREATE TABLE IF NOT EXISTS OVERWATCH_SCHEMA_MIGRATION (
  MIGRATION_VERSION   VARCHAR(100) NOT NULL,
  MIGRATION_NAME      VARCHAR(300) NOT NULL,
  APPLIED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  APPLIED_BY          VARCHAR(200) DEFAULT CURRENT_USER(),
  SOURCE_FILE         VARCHAR(500),
  NOTES               VARCHAR(1000)
);


CREATE TABLE IF NOT EXISTS OVERWATCH_OWNER_TAG_NAMES (
  TAG_NAME             VARCHAR(300) PRIMARY KEY,
  OWNER_TYPE           VARCHAR(100),
  PRIORITY             NUMBER,
  IS_ACTIVE            BOOLEAN DEFAULT TRUE,
  NOTES                VARCHAR(1000),
  UPDATED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY           VARCHAR(200) DEFAULT CURRENT_USER()
);


CREATE TABLE IF NOT EXISTS OVERWATCH_LOAD_AUDIT (
  LOAD_ID              NUMBER AUTOINCREMENT PRIMARY KEY,
  LOAD_NAME            VARCHAR(200),
  LOAD_STARTED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  LOAD_FINISHED_AT     TIMESTAMP_NTZ,
  STATUS               VARCHAR(40),
  ROWS_LOADED          NUMBER,
  MESSAGE              VARCHAR(4000)
);


CREATE TABLE IF NOT EXISTS OVERWATCH_ADMIN_ACTION_AUDIT (
  ACTION_ID            NUMBER AUTOINCREMENT PRIMARY KEY,
  ACTION_TS            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  COMPANY              VARCHAR(100),
  ENVIRONMENT          VARCHAR(50),
  APP_USER             VARCHAR(200),
  SNOWFLAKE_USER       VARCHAR(200),
  SNOWFLAKE_ROLE       VARCHAR(200),
  ACTION_TYPE          VARCHAR(100),
  TARGET_OBJECT        VARCHAR(1000),
  SQL_TEXT             VARCHAR,
  SQL_HASH             VARCHAR(80),
  CONFIRMATION_TEXT    VARCHAR(1000),
  CONTROL_CONTEXT      VARCHAR(4000),
  RESULT_STATUS        VARCHAR(40),
  RESULT_MESSAGE       VARCHAR(4000)
);


CREATE TABLE IF NOT EXISTS OVERWATCH_USAGE_LOG (
  RUN_ID               NUMBER AUTOINCREMENT PRIMARY KEY,
  LOG_TIME             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  SF_USER              VARCHAR(200),
  SF_ROLE              VARCHAR(200),
  COMPANY_VIEW         VARCHAR(100),
  SECTION              VARCHAR(200),
  QUERY_DURATION_MS    NUMBER,
  APP_VERSION          VARCHAR(20) DEFAULT '3.0',
  SESSION_ID           VARCHAR(200),
  EVENT_TYPE           VARCHAR(50) DEFAULT 'SECTION_LOAD',
  QUERY_HASH           VARCHAR(80),
  CACHE_KEY            VARCHAR(300),
  CACHE_TIER           VARCHAR(50),
  ROW_COUNT            NUMBER,
  RESULT_MB            NUMBER(18,4),
  USED_CACHE           BOOLEAN,
  MESSAGE              VARCHAR(1000)
);


CREATE TABLE IF NOT EXISTS OVERWATCH_ACTION_QUEUE (
  ACTION_ID                 VARCHAR(64) PRIMARY KEY,
  CREATED_AT                TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT                TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  SOURCE                    VARCHAR(100),
  CATEGORY                  VARCHAR(100),
  SEVERITY                  VARCHAR(20),
  ENTITY_TYPE               VARCHAR(100),
  ENTITY_NAME               VARCHAR(500),
  OWNER                     VARCHAR(200),
  STATUS                    VARCHAR(40) DEFAULT 'New',
  FINDING                   VARCHAR(4000),
  RECOMMENDED_ACTION        VARCHAR(4000),
  EST_MONTHLY_SAVINGS       FLOAT,
  GENERATED_SQL_FIX         VARCHAR(8000),
  PROOF_QUERY               VARCHAR(8000),
  COMPANY                   VARCHAR(100),
  ENVIRONMENT               VARCHAR(100),
  TICKET_ID                 VARCHAR(200),
  APPROVER                  VARCHAR(200),
  DUE_DATE                  DATE,
  VERIFICATION_STATUS       VARCHAR(40) DEFAULT 'Pending',
  VERIFICATION_NOTES        VARCHAR(4000),
  VERIFICATION_QUERY        VARCHAR(8000),
  VERIFICATION_RESULT       VARCHAR(8000),
  BASELINE_VALUE            FLOAT,
  CURRENT_VALUE             FLOAT,
  MEASURED_DELTA            FLOAT,
  VERIFIED_BY               VARCHAR(200),
  VERIFIED_AT               TIMESTAMP_NTZ,
  OWNER_APPROVAL_STATUS      VARCHAR(40),
  OWNER_APPROVAL_BY          VARCHAR(200),
  OWNER_APPROVAL_AT          TIMESTAMP_NTZ,
  OWNER_APPROVAL_NOTE        VARCHAR(2000),
  RECOVERY_SLA_STATE         VARCHAR(100),
  RECOVERY_SLA_HOURS         FLOAT,
  RECOVERY_SLA_TARGET_HOURS  FLOAT,
  RECOVERY_EVIDENCE          VARCHAR(8000),
  OWNER_EMAIL                VARCHAR(500),
  ONCALL_PRIMARY             VARCHAR(200),
  ONCALL_SECONDARY           VARCHAR(200),
  APPROVAL_GROUP             VARCHAR(200),
  ESCALATION_TARGET          VARCHAR(200),
  OWNER_SOURCE               VARCHAR(200),
  OWNER_EVIDENCE             VARCHAR(2000),
  RECOVERY_AUDIT_STATE       VARCHAR(100),
  ACKNOWLEDGED_BY           VARCHAR(200),
  ACKNOWLEDGED_AT           TIMESTAMP_NTZ,
  FIXED_BY                  VARCHAR(200),
  FIXED_AT                  TIMESTAMP_NTZ,
  IGNORED_REASON            VARCHAR(2000),
  LAST_SEEN_AT              TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  SEEN_COUNT                NUMBER DEFAULT 1
);


-- Upgrade older action queue installs to the current owner/environment and
-- verification contract without rebuilding existing audit data.
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS ENVIRONMENT VARCHAR(100);

ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS TICKET_ID VARCHAR(200);

ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS APPROVER VARCHAR(200);

ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS DUE_DATE DATE;

ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS VERIFICATION_STATUS VARCHAR(40);

ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS VERIFICATION_NOTES VARCHAR(4000);

ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS VERIFICATION_QUERY VARCHAR(8000);

ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS VERIFICATION_RESULT VARCHAR(8000);

ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS BASELINE_VALUE FLOAT;

ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS CURRENT_VALUE FLOAT;

ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS MEASURED_DELTA FLOAT;

ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS VERIFIED_BY VARCHAR(200);

ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS VERIFIED_AT TIMESTAMP_NTZ;

ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS OWNER_APPROVAL_STATUS VARCHAR(40);

ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS OWNER_APPROVAL_BY VARCHAR(200);

ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS OWNER_APPROVAL_AT TIMESTAMP_NTZ;

ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS OWNER_APPROVAL_NOTE VARCHAR(2000);

ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS RECOVERY_SLA_STATE VARCHAR(100);

ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS RECOVERY_SLA_HOURS FLOAT;

ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS RECOVERY_SLA_TARGET_HOURS FLOAT;

ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS RECOVERY_EVIDENCE VARCHAR(8000);

ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS OWNER_EMAIL VARCHAR(500);

ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS ONCALL_PRIMARY VARCHAR(200);

ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS ONCALL_SECONDARY VARCHAR(200);

ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS APPROVAL_GROUP VARCHAR(200);

ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS ESCALATION_TARGET VARCHAR(200);

ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS OWNER_SOURCE VARCHAR(200);

ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS OWNER_EVIDENCE VARCHAR(2000);

ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE ADD COLUMN IF NOT EXISTS RECOVERY_AUDIT_STATE VARCHAR(100);



CREATE TABLE IF NOT EXISTS OVERWATCH_WORKLOAD_RECOVERY_AUDIT (
  RECOVERY_AUDIT_ID         NUMBER AUTOINCREMENT PRIMARY KEY,
  RECOVERY_AUDIT_TS         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  ACTION_ID                 VARCHAR(64),
  COMPANY                   VARCHAR(100),
  ENVIRONMENT               VARCHAR(100),
  ENTITY_TYPE               VARCHAR(100),
  ENTITY_NAME               VARCHAR(500),
  INCIDENT_TYPE             VARCHAR(200),
  INCIDENT_PRIORITY         VARCHAR(100),
  OWNER                     VARCHAR(200),
  OWNER_EMAIL               VARCHAR(500),
  ONCALL_PRIMARY            VARCHAR(200),
  APPROVAL_GROUP            VARCHAR(200),
  APPROVER                  VARCHAR(200),
  OWNER_APPROVAL_STATUS     VARCHAR(40),
  RECOVERY_SLA_STATE        VARCHAR(100),
  RECOVERY_SLA_HOURS        FLOAT,
  RECOVERY_SLA_TARGET_HOURS FLOAT,
  TICKET_ID                 VARCHAR(200),
  ACTION_TAKEN              VARCHAR(4000),
  BEFORE_STATE              VARCHAR(4000),
  AFTER_STATE               VARCHAR(4000),
  VERIFICATION_QUERY        VARCHAR(8000),
  VERIFICATION_RESULT       VARCHAR(8000),
  RECOVERY_EVIDENCE         VARCHAR(8000),
  EXECUTED_BY               VARCHAR(200) DEFAULT CURRENT_USER(),
  SOURCE                    VARCHAR(200),
  SOURCE_QUERY_ID           VARCHAR(200),
  NOTES                     VARCHAR(4000)
);



CREATE TABLE IF NOT EXISTS OVERWATCH_DBA_CHECKLIST_HISTORY (
  SNAPSHOT_ID       VARCHAR(64),
  SNAPSHOT_TS       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  COMPANY           VARCHAR(100),
  ENVIRONMENT       VARCHAR(100),
  CHECK_NAME        VARCHAR(200),
  STATUS            VARCHAR(80),
  SEVERITY          VARCHAR(40),
  EVIDENCE          VARCHAR(2000),
  OWNER             VARCHAR(200),
  ESCALATION_TARGET VARCHAR(200),
  OWNER_SOURCE      VARCHAR(200),
  ROUTE             VARCHAR(120),
  NEXT_ACTION       VARCHAR(4000),
  PROOF_REQUIRED    VARCHAR(2000),
  ENVIRONMENT_SCOPE VARCHAR(100),
  DATABASE_CONTEXT  VARCHAR(80),
  SCOPE_CONFIDENCE  VARCHAR(160),
  SCOPE_EVIDENCE    VARCHAR(2000),
  APPROVAL_REQUIRED VARCHAR(20),
  QUEUE_READINESS   VARCHAR(80),
  QUEUE_BLOCKERS    VARCHAR(2000),
  VERIFICATION_QUERY VARCHAR(8000),
  RECOVERY_SLA_TARGET_HOURS FLOAT,
  CONTROL_READINESS VARCHAR(100),
  CONTROL_BLOCKERS  VARCHAR(2000),
  NEXT_CONTROL_ACTION VARCHAR(4000),
  HEALTH_SCORE      FLOAT,
  DETAIL_SOURCE     VARCHAR(500),
  ACTIONABLE        BOOLEAN
);


CREATE TABLE IF NOT EXISTS OVERWATCH_CHANGE_CONTROL_EVIDENCE (
  SNAPSHOT_ID              VARCHAR(64),
  SNAPSHOT_TS              TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  COMPANY                  VARCHAR(100),
  ENVIRONMENT              VARCHAR(100),
  FINDING_TYPE             VARCHAR(120),
  SEVERITY                 VARCHAR(40),
  ENTITY                   VARCHAR(500),
  USER_NAME                VARCHAR(300),
  ROLE_NAME                VARCHAR(300),
  QUERY_ID                 VARCHAR(200),
  QUERY_TAG                VARCHAR(1000),
  LAST_SEEN                VARCHAR(100),
  CHANGE_CONTROL_STATE     VARCHAR(120),
  CONTROL_GAP              VARCHAR(1000),
  CHANGE_TICKET_ID         VARCHAR(200),
  CHANGE_TICKET_STATE      VARCHAR(120),
  IAC_RECONCILIATION_STATE VARCHAR(160),
  EXECUTION_AUDIT_STATE    VARCHAR(160),
  OWNER                    VARCHAR(200),
  ESCALATION_TARGET        VARCHAR(200),
  OWNER_SOURCE             VARCHAR(200),
  APPROVER                 VARCHAR(200),
  OWNER_APPROVAL_STATUS    VARCHAR(40),
  APPROVAL_REQUIRED        VARCHAR(20),
  TICKET_REQUIRED          VARCHAR(20),
  BLAST_RADIUS_REQUIRED    VARCHAR(20),
  APPROVAL_ROUTE_READY     VARCHAR(20),
  CHANGE_EVIDENCE_READINESS VARCHAR(80),
  EVIDENCE_BLOCKERS        VARCHAR(2000),
  REVIEW_SLA_HOURS         NUMBER,
  NEXT_CONTROL_ACTION      VARCHAR(4000),
  PROOF_REQUIRED           VARCHAR(2000),
  VERIFICATION_QUERY       VARCHAR(8000),
  BLAST_RADIUS_QUERY       VARCHAR(8000),
  SOURCE                   VARCHAR(500)
);


CREATE TABLE IF NOT EXISTS OVERWATCH_WAREHOUSE_SETTING_REVIEW (
  SNAPSHOT_ID                   VARCHAR(64),
  SNAPSHOT_TS                   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  COMPANY                       VARCHAR(100),
  ENVIRONMENT                   VARCHAR(100),
  WAREHOUSE_NAME                VARCHAR(300),
  SEVERITY                      VARCHAR(40),
  SIGNAL                        VARCHAR(120),
  OWNER                         VARCHAR(200),
  ESCALATION_TARGET             VARCHAR(200),
  OWNER_SOURCE                  VARCHAR(200),
  APPROVER                      VARCHAR(200),
  APPROVAL_REQUIRED             VARCHAR(20),
  ROLLBACK_REQUIRED             VARCHAR(20),
  SAFE_CHANGE_PATH              VARCHAR(4000),
  SETTING_CHANGE_CANDIDATE      VARCHAR(4000),
  CHANGE_RISK                   VARCHAR(2000),
  POST_CHANGE_VERIFICATION      VARCHAR(2000),
  PRESSURE_EVIDENCE             VARCHAR(2000),
  BASELINE_CAPACITY_SCORE       FLOAT,
  BASELINE_QUEUED_QUERIES       NUMBER,
  BASELINE_SPILL_QUERIES        NUMBER,
  BASELINE_HIGH_LATENCY_QUERIES NUMBER,
  BASELINE_P95_ELAPSED_SEC      FLOAT,
  BASELINE_METERED_CREDITS      FLOAT,
  VERIFICATION_QUERY            VARCHAR(8000),
  GENERATED_REVIEW_SQL          VARCHAR(8000),
  IMPACT_TELEMETRY_REQUIRED VARCHAR(20),
  APPROVAL_STATE                VARCHAR(80),
  CHANGE_TICKET_ID              VARCHAR(200),
  CURRENT_SETTINGS_JSON         VARCHAR(8000),
  PROPOSED_SETTINGS_JSON        VARCHAR(8000),
  ROLLBACK_SQL                  VARCHAR(8000),
  EXECUTED_SQL_HASH             VARCHAR(80),
  EXECUTION_STATUS              VARCHAR(80),
  EXECUTED_BY                   VARCHAR(200),
  EXECUTED_AT                   TIMESTAMP_NTZ,
  POST_CHANGE_VERIFICATION_STATUS VARCHAR(80),
  POST_CHANGE_VERIFICATION_RESULT VARCHAR(4000),
  VERIFIED_MONTHLY_SAVINGS     FLOAT,
  AUDIT_READINESS               VARCHAR(100),
  AUDIT_BLOCKERS                VARCHAR(2000),
  NEXT_CONTROL_ACTION           VARCHAR(4000),
  SOURCE                        VARCHAR(500)
);


ALTER TABLE IF EXISTS OVERWATCH_WAREHOUSE_SETTING_REVIEW ADD COLUMN IF NOT EXISTS IMPACT_TELEMETRY_REQUIRED VARCHAR(20);


CREATE TABLE IF NOT EXISTS OVERWATCH_SECURITY_ACCESS_REVIEW (
  SNAPSHOT_ID             VARCHAR(64),
  SNAPSHOT_TS             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  COMPANY                 VARCHAR(100),
  ENVIRONMENT             VARCHAR(100),
  DATABASE_CONTEXT        BOOLEAN,
  FINDING_TYPE            VARCHAR(120),
  SEVERITY                VARCHAR(40),
  ENTITY_TYPE             VARCHAR(120),
  ENTITY                  VARCHAR(500),
  EVENT_COUNT             NUMBER,
  DISTINCT_SOURCES        NUMBER,
  LAST_SEEN               VARCHAR(100),
  OWNER                   VARCHAR(200),
  ESCALATION_TARGET       VARCHAR(200),
  OWNER_SOURCE            VARCHAR(200),
  APPROVER                VARCHAR(200),
  OWNER_APPROVAL_STATUS   VARCHAR(40),
  ACCESS_REVIEW_STATE     VARCHAR(160),
  ROLE_CAPABILITY_STATE   VARCHAR(200),
  TICKET_REQUIRED         VARCHAR(20),
  REVIEW_BY_REQUIRED      VARCHAR(20),
  PROOF_REQUIRED          VARCHAR(2000),
  VERIFICATION_QUERY      VARCHAR(8000),
  ACCESS_TICKET_ID        VARCHAR(200),
  REVIEW_BY_DATE          VARCHAR(100),
  IAM_APPROVAL_STATE      VARCHAR(120),
  REVIEW_READINESS        VARCHAR(100),
  REVIEW_BLOCKERS         VARCHAR(2000),
  REVIEW_SLA_HOURS        NUMBER,
  VERIFICATION_STATUS     VARCHAR(80),
  VERIFICATION_RESULT     VARCHAR(4000),
  CONTROL_READINESS       VARCHAR(100),
  CONTROL_BLOCKERS        VARCHAR(2000),
  NEXT_CONTROL_ACTION     VARCHAR(4000),
  NEXT_ACTION             VARCHAR(4000),
  PROOF_QUERY             VARCHAR(4000),
  SOURCE                  VARCHAR(500)
);



CREATE TABLE IF NOT EXISTS OVERWATCH_ALERTS (
  ALERT_ID             NUMBER AUTOINCREMENT PRIMARY KEY,
  ALERT_TS             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  COMPANY              VARCHAR(100),
  ENVIRONMENT          VARCHAR(100),
  DATABASE_NAME        VARCHAR(300),
  SCHEMA_NAME          VARCHAR(300),
  WAREHOUSE_NAME       VARCHAR(300),
  CATEGORY             VARCHAR(100),
  ALERT_TYPE           VARCHAR(100),
  SEVERITY             VARCHAR(20),
  ENTITY_NAME          VARCHAR(500),
  ENTITY               VARCHAR(500),
  MESSAGE              VARCHAR(4000),
  DETAIL               VARCHAR(4000),
  SUGGESTED_ACTION     VARCHAR(2000),
  PROOF_QUERY          VARCHAR(8000),
  OWNER                VARCHAR(200),
  STATUS               VARCHAR(40) DEFAULT 'New',
  DELIVERY_METHOD      VARCHAR(40) DEFAULT 'EMAIL',
  DELIVERY_TARGET      VARCHAR(500),
  EMAIL_TARGET         VARCHAR(500),
  EMAIL_SUBJECT        VARCHAR(1000),
  EMAIL_BODY           VARCHAR(16000),
  DELIVERY_STATUS      VARCHAR(100),
  ACKNOWLEDGED_BY      VARCHAR(200),
  ACKNOWLEDGED_AT      TIMESTAMP_NTZ,
  RESOLVED             BOOLEAN DEFAULT FALSE,
  STATUS_REASON        VARCHAR(2000),
  LAST_STATUS_BY       VARCHAR(200),
  LAST_STATUS_AT       TIMESTAMP_NTZ,
  LAST_DELIVERY_AT     TIMESTAMP_NTZ,
  LAST_DELIVERY_BY     VARCHAR(200),
  DELIVERY_LOG_COUNT   NUMBER DEFAULT 0,
  ESCALATED_TO         VARCHAR(200),
  ESCALATED_AT         TIMESTAMP_NTZ,
  ESCALATION_ACK_BY    VARCHAR(200),
  ESCALATION_ACK_AT    TIMESTAMP_NTZ,
  ESCALATION_ACK_NOTE  VARCHAR(2000),
  ROUTED_TO_ACTION_QUEUE_AT TIMESTAMP_NTZ,
  ROUTED_ACTION_COUNT  NUMBER DEFAULT 0
);


-- Upgrade older Alert Center installs to the current routing/status contract.
ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS ENVIRONMENT VARCHAR(100);

ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS DATABASE_NAME VARCHAR(300);

ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS SCHEMA_NAME VARCHAR(300);

ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS WAREHOUSE_NAME VARCHAR(300);

ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS ALERT_TYPE VARCHAR(100);

ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS ENTITY VARCHAR(500);

ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS DETAIL VARCHAR(4000);

ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS SUGGESTED_ACTION VARCHAR(2000);

ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS OWNER VARCHAR(200);

ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS STATUS VARCHAR(40);

ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS DELIVERY_METHOD VARCHAR(40);

ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS EMAIL_TARGET VARCHAR(500);

ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS EMAIL_SUBJECT VARCHAR(1000);

ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS EMAIL_BODY VARCHAR(16000);

ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS RESOLVED BOOLEAN;

ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS STATUS_REASON VARCHAR(2000);

ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS LAST_STATUS_BY VARCHAR(200);

ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS LAST_STATUS_AT TIMESTAMP_NTZ;

ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS LAST_DELIVERY_AT TIMESTAMP_NTZ;

ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS LAST_DELIVERY_BY VARCHAR(200);

ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS DELIVERY_LOG_COUNT NUMBER;

ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS ESCALATED_TO VARCHAR(200);

ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS ESCALATED_AT TIMESTAMP_NTZ;

ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS ESCALATION_ACK_BY VARCHAR(200);

ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS ESCALATION_ACK_AT TIMESTAMP_NTZ;

ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS ESCALATION_ACK_NOTE VARCHAR(2000);

ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS ROUTED_TO_ACTION_QUEUE_AT TIMESTAMP_NTZ;

ALTER TABLE IF EXISTS OVERWATCH_ALERTS ADD COLUMN IF NOT EXISTS ROUTED_ACTION_COUNT NUMBER;


-- Alert Command Center configuration, event, acknowledgement, notification, and remediation contract.
-- ACCOUNT_USAGE sources can lag; ALERT_CONFIG.TELEMETRY_LATENCY labels delayed vs near-real-time checks.
CREATE TABLE IF NOT EXISTS ALERT_CONFIG (
  ALERT_KEY                  VARCHAR(200) PRIMARY KEY,
  CATEGORY                   VARCHAR(100) NOT NULL,
  SIGNAL_NAME                VARCHAR(200) NOT NULL,
  DESCRIPTION                VARCHAR(4000),
  DEFAULT_SEVERITY           VARCHAR(20) DEFAULT 'Medium',
  ENABLED                    BOOLEAN DEFAULT TRUE,
  OWNER                      VARCHAR(200),
  ROUTE                      VARCHAR(200),
  BUSINESS_IMPACT_WEIGHT     NUMBER DEFAULT 50,
  DETECTION_SQL              VARCHAR(16000),
  TELEMETRY_SOURCE           VARCHAR(500),
  TELEMETRY_LATENCY          VARCHAR(200),
  NOTIFICATION_CHANNEL       VARCHAR(200),
  REMEDIATION_MODE           VARCHAR(40) DEFAULT 'RECOMMEND',
  DEDUPE_WINDOW_MINUTES      NUMBER DEFAULT 60,
  SUPPRESSION_WINDOW_MINUTES NUMBER DEFAULT 0,
  QUIET_HOURS_START          VARCHAR(20),
  QUIET_HOURS_END            VARCHAR(20),
  AUTO_RESOLVE_AFTER_HOURS   NUMBER DEFAULT 24,
  CREATED_AT                 TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CREATED_BY                 VARCHAR(200) DEFAULT CURRENT_USER(),
  UPDATED_AT                 TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY                 VARCHAR(200) DEFAULT CURRENT_USER()
);


CREATE TABLE IF NOT EXISTS ALERT_THRESHOLDS (
  THRESHOLD_KEY          VARCHAR(200) PRIMARY KEY,
  CATEGORY               VARCHAR(100) NOT NULL,
  SIGNAL_NAME            VARCHAR(200) NOT NULL,
  SEVERITY               VARCHAR(20) DEFAULT 'Medium',
  THRESHOLD_VALUE        FLOAT,
  BASELINE_WINDOW_DAYS   NUMBER DEFAULT 14,
  CURRENT_WINDOW_MINUTES NUMBER DEFAULT 60,
  OWNER                  VARCHAR(200),
  NOTIFICATION_CHANNEL   VARCHAR(200),
  ENABLED                BOOLEAN DEFAULT TRUE,
  UPDATED_AT             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY             VARCHAR(200) DEFAULT CURRENT_USER()
);


CREATE TABLE IF NOT EXISTS ALERT_EVENTS (
  EVENT_ID             NUMBER AUTOINCREMENT PRIMARY KEY,
  COMPANY              VARCHAR(100),
  ENVIRONMENT          VARCHAR(100),
  ALERT_KEY            VARCHAR(200),
  EVENT_TS             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  FIRST_SEEN_AT        TIMESTAMP_NTZ,
  LAST_SEEN_AT         TIMESTAMP_NTZ,
  DETECTED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  RESOLVED_AT          TIMESTAMP_NTZ,
  CATEGORY             VARCHAR(100),
  SEVERITY             VARCHAR(20),
  STATUS               VARCHAR(40) DEFAULT 'New',
  BUSINESS_IMPACT      VARCHAR(4000),
  IMPACT_ESTIMATE      VARCHAR(1000),
  OWNER                VARCHAR(200),
  RECOMMENDED_ACTION   VARCHAR(4000),
  ENTITY_TYPE          VARCHAR(100),
  ENTITY_NAME          VARCHAR(500),
  USER_NAME            VARCHAR(300),
  ROLE_NAME            VARCHAR(300),
  WAREHOUSE_NAME       VARCHAR(300),
  DATABASE_NAME        VARCHAR(300),
  SCHEMA_NAME          VARCHAR(300),
  OBJECT_NAME          VARCHAR(500),
  QUERY_ID             VARCHAR(200),
  SOURCE_IP            VARCHAR(200),
  BASELINE_VALUE       FLOAT,
  CURRENT_VALUE        FLOAT,
  THRESHOLD_VALUE      FLOAT,
  EVIDENCE             VARCHAR(8000),
  PROOF_QUERY          VARCHAR(16000),
  REMEDIATION_MODE     VARCHAR(40) DEFAULT 'RECOMMEND',
  REMEDIATION_SQL      VARCHAR(16000),
  NOTIFICATION_STATUS  VARCHAR(100),
  DEDUPE_KEY           VARCHAR(500),
  RAW_EVENT            VARIANT
);


ALTER TABLE IF EXISTS ALERT_EVENTS ADD COLUMN IF NOT EXISTS COMPANY VARCHAR(100);

ALTER TABLE IF EXISTS ALERT_EVENTS ADD COLUMN IF NOT EXISTS ENVIRONMENT VARCHAR(100);


CREATE TABLE IF NOT EXISTS ALERT_RUN_HISTORY (
  RUN_ID                 VARCHAR(200) PRIMARY KEY,
  STARTED_AT             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  COMPLETED_AT           TIMESTAMP_NTZ,
  STATUS                 VARCHAR(40),
  ALERTS_EVALUATED       NUMBER DEFAULT 0,
  ALERTS_CREATED         NUMBER DEFAULT 0,
  ALERTS_RESOLVED        NUMBER DEFAULT 0,
  ERROR_MESSAGE          VARCHAR(4000),
  DATA_WINDOW_START      TIMESTAMP_NTZ,
  DATA_WINDOW_END        TIMESTAMP_NTZ,
  TELEMETRY_LATENCY_NOTE VARCHAR(2000),
  RUN_BY                 VARCHAR(200) DEFAULT CURRENT_USER()
);


CREATE TABLE IF NOT EXISTS ALERT_ACKNOWLEDGEMENTS (
  ACK_ID              NUMBER AUTOINCREMENT PRIMARY KEY,
  EVENT_ID            NUMBER,
  ALERT_KEY           VARCHAR(200),
  ACKNOWLEDGED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  ACKNOWLEDGED_BY     VARCHAR(200) DEFAULT CURRENT_USER(),
  ACK_NOTE            VARCHAR(4000),
  STATUS_AFTER_ACK    VARCHAR(40) DEFAULT 'Acknowledged',
  OWNER_ASSIGNED      VARCHAR(200),
  NEXT_CHECKPOINT_AT  TIMESTAMP_NTZ
);


CREATE TABLE IF NOT EXISTS ALERT_NOTIFICATION_LOG (
  NOTIFICATION_ID  NUMBER AUTOINCREMENT PRIMARY KEY,
  EVENT_ID         NUMBER,
  ALERT_KEY        VARCHAR(200),
  NOTIFICATION_TS  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CHANNEL          VARCHAR(200),
  DESTINATION      VARCHAR(500),
  SEVERITY         VARCHAR(20),
  STATUS           VARCHAR(100),
  DEDUPE_KEY       VARCHAR(500),
  ESCALATION_LEVEL NUMBER DEFAULT 0,
  ERROR_MESSAGE    VARCHAR(4000),
  PAYLOAD          VARIANT,
  SENT_BY          VARCHAR(200) DEFAULT CURRENT_USER()
);


CREATE TABLE IF NOT EXISTS ALERT_REMEDIATION_LOG (
  REMEDIATION_ID     NUMBER AUTOINCREMENT PRIMARY KEY,
  EVENT_ID           NUMBER,
  ALERT_KEY          VARCHAR(200),
  REQUESTED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  REQUESTED_BY       VARCHAR(200) DEFAULT CURRENT_USER(),
  APPROVED_AT        TIMESTAMP_NTZ,
  APPROVED_BY        VARCHAR(200),
  REMEDIATION_MODE   VARCHAR(40),
  ACTION_TYPE        VARCHAR(100),
  ACTION_SQL         VARCHAR(16000),
  BEFORE_STATE       VARCHAR(8000),
  AFTER_STATE        VARCHAR(8000),
  EXECUTION_STATUS   VARCHAR(100),
  ERROR_MESSAGE      VARCHAR(4000),
  ROLLBACK_GUIDANCE  VARCHAR(4000),
  AFFECTED_USER      VARCHAR(300),
  AFFECTED_OBJECT    VARCHAR(500),
  AFFECTED_WAREHOUSE VARCHAR(300),
  AFFECTED_TASK      VARCHAR(500),
  VERIFICATION_SQL   VARCHAR(16000),
  VERIFICATION_RESULT VARCHAR(8000)
);


CREATE TABLE IF NOT EXISTS ALERT_OWNER_ROUTING (
  ROUTE_KEY            VARCHAR(200) PRIMARY KEY,
  CATEGORY             VARCHAR(100),
  ENTITY_TYPE          VARCHAR(100),
  ENTITY_PATTERN       VARCHAR(500),
  OWNER_NAME           VARCHAR(200),
  OWNER_EMAIL          VARCHAR(500),
  ONCALL_PRIMARY       VARCHAR(200),
  ONCALL_SECONDARY     VARCHAR(200),
  APPROVAL_GROUP       VARCHAR(200),
  ESCALATION_TARGET    VARCHAR(200),
  NOTIFICATION_CHANNEL VARCHAR(200),
  SEVERITY_MIN         VARCHAR(20) DEFAULT 'Medium',
  SERVICE_TIER         VARCHAR(40) DEFAULT 'Tier 2',
  ACTIVE               BOOLEAN DEFAULT TRUE,
  UPDATED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY           VARCHAR(200) DEFAULT CURRENT_USER()
);


CREATE TABLE IF NOT EXISTS ALERT_DATA_QUALITY_CHECKS (
  CHECK_KEY            VARCHAR(200) PRIMARY KEY,
  DATABASE_NAME        VARCHAR(300) NOT NULL,
  SCHEMA_NAME          VARCHAR(300) NOT NULL,
  TABLE_NAME           VARCHAR(300) NOT NULL,
  COLUMN_NAME          VARCHAR(300) DEFAULT '*',
  CHECK_TYPE           VARCHAR(100) NOT NULL,
  THRESHOLD_VALUE      FLOAT,
  COMPARISON_OPERATOR  VARCHAR(20) DEFAULT '>',
  SEVERITY             VARCHAR(20) DEFAULT 'Medium',
  OWNER                VARCHAR(200),
  NOTIFICATION_CHANNEL VARCHAR(200),
  ENABLED              BOOLEAN DEFAULT FALSE,
  FRESHNESS_COLUMN     VARCHAR(300),
  KEY_COLUMNS          VARCHAR(1000),
  FILTER_SQL           VARCHAR(4000),
  BUSINESS_IMPACT      VARCHAR(4000),
  UPDATED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY           VARCHAR(200) DEFAULT CURRENT_USER()
);


CREATE TABLE IF NOT EXISTS ALERT_NATIVE_OBJECT_REGISTRY (
  REGISTRY_KEY          VARCHAR(200) PRIMARY KEY,
  ALERT_KEY             VARCHAR(200),
  CATEGORY              VARCHAR(100),
  ALERT_OBJECT_NAME     VARCHAR(300),
  TARGET_ROUTE          VARCHAR(200),
  WAREHOUSE_NAME        VARCHAR(300),
  SCHEDULE_TEXT         VARCHAR(100),
  STATUS                VARCHAR(40) DEFAULT 'CANDIDATE',
  CONDITION_SOURCE      VARCHAR(1000),
  ACTION_SOURCE         VARCHAR(1000),
  GENERATED_CREATE_SQL  VARCHAR(16000),
  GENERATED_DROP_SQL    VARCHAR(4000),
  ENABLED_BY_DEFAULT    BOOLEAN DEFAULT FALSE,
  SAFETY_NOTE           VARCHAR(4000),
  UPDATED_AT            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY            VARCHAR(200) DEFAULT CURRENT_USER()
);


CREATE TABLE IF NOT EXISTS ALERT_REMEDIATION_POLICY (
  POLICY_ID              VARCHAR(200) PRIMARY KEY,
  ALERT_KEY              VARCHAR(200),
  CATEGORY               VARCHAR(100),
  ACTION_TYPE            VARCHAR(200),
  REMEDIATION_MODE       VARCHAR(40) DEFAULT 'RECOMMEND',
  AUTO_ELIGIBLE          BOOLEAN DEFAULT FALSE,
  REQUIRED_REVIEW        VARCHAR(500),
  BEFORE_STATE_SQL       VARCHAR(8000),
  DRY_RUN_SQL            VARCHAR(8000),
  EXECUTION_SQL_TEMPLATE VARCHAR(8000),
  ROLLBACK_GUIDANCE      VARCHAR(4000),
  VERIFICATION_SQL       VARCHAR(8000),
  ACTIVE                 BOOLEAN DEFAULT TRUE,
  UPDATED_AT             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY             VARCHAR(200) DEFAULT CURRENT_USER()
);


CREATE TABLE IF NOT EXISTS ALERT_REMEDIATION_DRY_RUN (
  DRY_RUN_ID          NUMBER AUTOINCREMENT PRIMARY KEY,
  POLICY_ID           VARCHAR(200),
  EVENT_ID            NUMBER,
  ALERT_KEY           VARCHAR(200),
  CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CREATED_BY          VARCHAR(200) DEFAULT CURRENT_USER(),
  DRY_RUN_STATUS      VARCHAR(100),
  BEFORE_STATE        VARCHAR(8000),
  PROPOSED_SQL        VARCHAR(16000),
  EXPECTED_EFFECT     VARCHAR(4000),
  BLOCKING_REASON     VARCHAR(4000),
  VERIFICATION_SQL    VARCHAR(8000)
);



CREATE TABLE IF NOT EXISTS OVERWATCH_ANNOTATIONS (
  ANNOTATION_ID     NUMBER AUTOINCREMENT PRIMARY KEY,
  CREATED_BY        VARCHAR(200),
  CREATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  ENTITY            VARCHAR(500),
  ENTITY_TYPE       VARCHAR(50),
  WINDOW_START      TIMESTAMP_NTZ NOT NULL,
  WINDOW_END        TIMESTAMP_NTZ NOT NULL,
  ANNOTATION_TYPE   VARCHAR(100),
  DESCRIPTION       VARCHAR(2000),
  SUPPRESS_ALERTS   BOOLEAN DEFAULT TRUE,
  ACTIVE            BOOLEAN DEFAULT TRUE
);



CREATE TABLE IF NOT EXISTS OVERWATCH_ALERT_DELIVERY_LOG (
  DELIVERY_ID      NUMBER AUTOINCREMENT PRIMARY KEY,
  DELIVERY_TS      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  COMPANY          VARCHAR(100),
  ENVIRONMENT      VARCHAR(100),
  ALERT_IDS        VARIANT,
  ALERT_COUNT      NUMBER,
  DELIVERY_METHOD  VARCHAR(40) DEFAULT 'EMAIL',
  DELIVERY_TARGET  VARCHAR(500),
  EMAIL_SUBJECT    VARCHAR(1000),
  EMAIL_BODY       VARCHAR(16000),
  DELIVERY_STATUS  VARCHAR(100),
  DELIVERY_BY      VARCHAR(200),
  DELIVERY_NOTES   VARCHAR(4000)
);


CREATE TABLE IF NOT EXISTS OVERWATCH_ALERT_RULE_AUDIT (
  AUDIT_ID                NUMBER AUTOINCREMENT PRIMARY KEY,
  AUDIT_TS                TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  RULE_ID                 VARCHAR(200),
  ACTION                  VARCHAR(40),
  PRIOR_DEFAULT_SEVERITY  VARCHAR(20),
  NEW_DEFAULT_SEVERITY    VARCHAR(20),
  PRIOR_SLA_HOURS         NUMBER,
  NEW_SLA_HOURS           NUMBER,
  PRIOR_OWNER             VARCHAR(200),
  NEW_OWNER               VARCHAR(200),
  PRIOR_ROUTE             VARCHAR(200),
  NEW_ROUTE               VARCHAR(200),
  PRIOR_RUNBOOK           VARCHAR(2000),
  NEW_RUNBOOK             VARCHAR(2000),
  PRIOR_IS_ACTIVE         BOOLEAN,
  NEW_IS_ACTIVE           BOOLEAN,
  CHANGED_BY              VARCHAR(200),
  CHANGE_REASON           VARCHAR(2000)
);


CREATE TABLE IF NOT EXISTS OVERWATCH_ALERT_RULES (
  RULE_ID              VARCHAR(200) PRIMARY KEY,
  CATEGORY             VARCHAR(100),
  ALERT_TYPE           VARCHAR(100),
  DEFAULT_SEVERITY     VARCHAR(20),
  SLA_HOURS            NUMBER,
  OWNER                VARCHAR(200),
  ROUTE                VARCHAR(200),
  RUNBOOK              VARCHAR(2000),
  IS_ACTIVE            BOOLEAN DEFAULT TRUE,
  UPDATED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY           VARCHAR(200) DEFAULT CURRENT_USER()
);


CREATE TABLE IF NOT EXISTS OVERWATCH_RECON_CONFIG (
  CHECK_ID             NUMBER AUTOINCREMENT PRIMARY KEY,
  CHECK_NAME           VARCHAR(300),
  SOURCE_DATABASE      VARCHAR(300),
  SOURCE_SCHEMA        VARCHAR(300),
  TARGET_DATABASE      VARCHAR(300),
  TARGET_SCHEMA        VARCHAR(300),
  TABLE_PATTERN        VARCHAR(300) DEFAULT '%',
  KEY_COLUMNS          VARCHAR(2000),
  EXCLUDE_COLUMNS      VARCHAR(2000),
  WHERE_CLAUSE         VARCHAR(4000),
  HASH_BUCKET_COUNT    NUMBER DEFAULT 64,
  CHECK_MODE           VARCHAR(50) DEFAULT 'COUNT_AND_HASH',
  SEVERITY             VARCHAR(40) DEFAULT 'MEDIUM',
  OWNER                VARCHAR(300),
  ENABLED              BOOLEAN DEFAULT TRUE,
  CREATED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TABLE IF NOT EXISTS OVERWATCH_RECON_RUN (
  RUN_ID               NUMBER AUTOINCREMENT PRIMARY KEY,
  CHECK_ID             NUMBER,
  RUN_TS               TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  RUN_STATUS           VARCHAR(40),
  SOURCE_ROW_COUNT     NUMBER,
  TARGET_ROW_COUNT     NUMBER,
  SOURCE_HASH          VARCHAR(200),
  TARGET_HASH          VARCHAR(200),
  MISMATCH_COUNT       NUMBER,
  SAMPLE_DIFF_SQL      VARCHAR(16000),
  RECOMMENDED_ACTION   VARCHAR(2000)
);


CREATE TABLE IF NOT EXISTS OVERWATCH_SCHEMA_DIFF_RESULT (
  RUN_TS               TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  SOURCE_DATABASE      VARCHAR(300),
  SOURCE_SCHEMA        VARCHAR(300),
  TARGET_DATABASE      VARCHAR(300),
  TARGET_SCHEMA        VARCHAR(300),
  OBJECT_TYPE          VARCHAR(100),
  OBJECT_NAME          VARCHAR(1000),
  DIFF_TYPE            VARCHAR(100),
  GENERATED_DDL        VARCHAR(16000),
  OWNER                VARCHAR(300),
  SEVERITY             VARCHAR(40)
);


-- -----------------------------------------------------------------------------
-- 3. Transient mart tables
-- -----------------------------------------------------------------------------

CREATE TRANSIENT TABLE IF NOT EXISTS FACT_WAREHOUSE_HOURLY (
  HOUR_START                   TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  WAREHOUSE_NAME               VARCHAR(300),
  CREDITS_USED                 NUMBER(18,6),
  CREDITS_USED_COMPUTE         NUMBER(18,6),
  CREDITS_USED_CLOUD_SERVICES  NUMBER(18,6),
  EST_COST_USD                 NUMBER(18,2),
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS FACT_WAREHOUSE_OPERABILITY_DAILY (
  SNAPSHOT_DATE                DATE,
  COMPANY                      VARCHAR(100),
  ENVIRONMENT                  VARCHAR(100),
  WAREHOUSE_NAME               VARCHAR(300),
  CONTROL_SOURCE               VARCHAR(80),
  SEVERITY                     VARCHAR(40),
  SIGNAL                       VARCHAR(120),
  CONTROL_STATE                VARCHAR(120),
  CONTROL_RANK                 NUMBER,
  CAPACITY_SCORE               FLOAT,
  QUERY_ROWS                   NUMBER,
  QUEUE_PRESSURE_ROWS          NUMBER,
  SPILL_PRESSURE_ROWS          NUMBER,
  HIGH_LATENCY_ROWS            NUMBER,
  METERED_CREDITS              FLOAT,
  CREDIT_ALLOCATION_METHOD     VARCHAR(160),
  REVIEW_ROWS                  NUMBER,
  APPROVAL_REQUIRED_ROWS       NUMBER,
  ROLLBACK_REQUIRED_ROWS       NUMBER,
  IMPACT_TELEMETRY_ROWS    NUMBER,
  OPEN_ACTIONS                 NUMBER,
  OVERDUE_OPEN                 NUMBER,
  FIXED_WITHOUT_VERIFICATION   NUMBER,
  VERIFIED_CLOSURES            NUMBER,
  OWNER_APPROVAL_GAP_ROWS      NUMBER,
  NEXT_CONTROL_ACTION          VARCHAR(4000),
  LAST_ACTIVITY_TS             TIMESTAMP_NTZ,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


ALTER TABLE IF EXISTS FACT_WAREHOUSE_OPERABILITY_DAILY ADD COLUMN IF NOT EXISTS IMPACT_TELEMETRY_ROWS NUMBER;


CREATE TRANSIENT TABLE IF NOT EXISTS FACT_SECURITY_OPERABILITY_DAILY (
  SNAPSHOT_DATE                DATE,
  COMPANY                      VARCHAR(100),
  ENVIRONMENT                  VARCHAR(100),
  CONTROL_SOURCE               VARCHAR(80),
  FINDING_TYPE                 VARCHAR(120),
  ENTITY                       VARCHAR(500),
  ENTITY_TYPE                  VARCHAR(120),
  SEVERITY                     VARCHAR(40),
  CONTROL_STATE                VARCHAR(120),
  CONTROL_RANK                 NUMBER,
  EVENT_ROWS                   NUMBER,
  REVIEW_ROWS                  NUMBER,
  REVIEW_BLOCKER_ROWS          NUMBER,
  TICKET_REQUIRED_ROWS         NUMBER,
  REVIEW_BY_REQUIRED_ROWS      NUMBER,
  CAPABILITY_PROOF_ROWS        NUMBER,
  NO_DATABASE_CONTEXT_ROWS     NUMBER,
  OPEN_ACTIONS                 NUMBER,
  OVERDUE_OPEN                 NUMBER,
  FIXED_WITHOUT_VERIFICATION   NUMBER,
  VERIFIED_CLOSURES            NUMBER,
  OWNER_APPROVAL_GAP_ROWS      NUMBER,
  NEXT_CONTROL_ACTION          VARCHAR(4000),
  LAST_ACTIVITY_TS             TIMESTAMP_NTZ,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS FACT_ACCOUNT_HEALTH_OPERABILITY_DAILY (
  SNAPSHOT_DATE                DATE,
  COMPANY                      VARCHAR(100),
  ENVIRONMENT                  VARCHAR(100),
  CONTROL_SOURCE               VARCHAR(80),
  CHECK_NAME                   VARCHAR(200),
  ROUTE                        VARCHAR(120),
  SEVERITY                     VARCHAR(40),
  CONTROL_STATE                VARCHAR(120),
  CONTROL_RANK                 NUMBER,
  HEALTH_SCORE                 FLOAT,
  ISSUE_ROWS                   NUMBER,
  ROUTE_BLOCKER_ROWS           NUMBER,
  QUEUE_REQUIRED_ROWS          NUMBER,
  ACCESS_HYGIENE_ROWS          NUMBER,
  FAILED_LOGIN_ROWS            NUMBER,
  PRIVILEGED_GRANT_ROWS        NUMBER,
  OPEN_ACTIONS                 NUMBER,
  OVERDUE_OPEN                 NUMBER,
  FIXED_WITHOUT_VERIFICATION   NUMBER,
  VERIFIED_CLOSURES            NUMBER,
  OWNER_APPROVAL_GAP_ROWS      NUMBER,
  RECOVERY_RISK_ROWS           NUMBER,
  NEXT_CONTROL_ACTION          VARCHAR(4000),
  LAST_ACTIVITY_TS             TIMESTAMP_NTZ,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS FACT_QUERY_HOURLY (
  HOUR_START                   TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  WAREHOUSE_NAME               VARCHAR(300),
  WAREHOUSE_SIZE               VARCHAR(100),
  USER_NAME                    VARCHAR(300),
  ROLE_NAME                    VARCHAR(300),
  DATABASE_NAME                VARCHAR(300),
  ENVIRONMENT                  VARCHAR(100),
  SCHEMA_NAME                  VARCHAR(300),
  QUERY_TYPE                   VARCHAR(100),
  QUERY_COUNT                  NUMBER,
  FAILED_COUNT                 NUMBER,
  AVG_EXECUTION_MS             NUMBER(18,2),
  P95_EXECUTION_MS             NUMBER(18,2),
  TOTAL_ELAPSED_MS             NUMBER,
  TOTAL_QUEUED_MS              NUMBER,
  TOTAL_SPILL_BYTES            NUMBER,
  TOTAL_BYTES_SCANNED          NUMBER,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS FACT_QUERY_DETAIL_RECENT (
  QUERY_ID                     VARCHAR(200),
  START_TIME                   TIMESTAMP_NTZ,
  END_TIME                     TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  WAREHOUSE_NAME               VARCHAR(300),
  USER_NAME                    VARCHAR(300),
  ROLE_NAME                    VARCHAR(300),
  DATABASE_NAME                VARCHAR(300),
  ENVIRONMENT                  VARCHAR(100),
  SCHEMA_NAME                  VARCHAR(300),
  QUERY_TYPE                   VARCHAR(100),
  EXECUTION_STATUS             VARCHAR(100),
  WAREHOUSE_SIZE               VARCHAR(100),
  ERROR_CODE                   VARCHAR(100),
  ERROR_MESSAGE                VARCHAR,
  TOTAL_ELAPSED_TIME           NUMBER,
  COMPILATION_TIME             NUMBER,
  EXECUTION_TIME               NUMBER,
  QUEUED_OVERLOAD_TIME         NUMBER,
  QUEUED_PROVISIONING_TIME     NUMBER,
  QUEUED_REPAIR_TIME           NUMBER,
  TRANSACTION_BLOCKED_TIME     NUMBER,
  BYTES_SCANNED                NUMBER,
  BYTES_SPILLED_TO_LOCAL_STORAGE NUMBER,
  BYTES_SPILLED_TO_REMOTE_STORAGE NUMBER,
  PARTITIONS_SCANNED           NUMBER,
  PARTITIONS_TOTAL             NUMBER,
  ROWS_PRODUCED                NUMBER,
  QUERY_HASH                   VARCHAR(300),
  QUERY_TEXT                   VARCHAR,
  QUERY_TAG                    VARCHAR,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS FACT_CHARGEBACK_DAILY (
  USAGE_DATE                   DATE,
  COMPANY                      VARCHAR(100),
  ENVIRONMENT                  VARCHAR(100),
  ENVIRONMENT_ROLLUP           VARCHAR(100),
  DATABASE_NAME                VARCHAR(300),
  USER_NAME                    VARCHAR(300),
  ROLE_NAME                    VARCHAR(300),
  WAREHOUSE_NAME               VARCHAR(300),
  WAREHOUSE_SIZE               VARCHAR(100),
  QUERY_COUNT                  NUMBER,
  ALLOCATED_CREDITS            NUMBER(18,6),
  EST_COST_USD                 NUMBER(18,2),
  ALLOCATION_CONFIDENCE        VARCHAR(100),
  ALLOCATION_BASIS             VARCHAR(1000),
  CHARGEBACK_READY             VARCHAR(100),
  SCOPE_REVIEW                 VARCHAR(1000),
  COST_OWNER                   VARCHAR(300),
  OWNER_SOURCE                 VARCHAR(100),
  OWNER_EVIDENCE               VARCHAR(1000),
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS DIM_COST_OWNER_TAG (
  SNAPSHOT_DATE                DATE,
  OWNER_SCOPE                  VARCHAR(100),
  OBJECT_DATABASE              VARCHAR(300),
  OBJECT_SCHEMA                VARCHAR(300),
  OBJECT_NAME                  VARCHAR(500),
  TAG_NAME                     VARCHAR(300),
  TAG_VALUE                    VARCHAR(1000),
  OWNER_TYPE                   VARCHAR(100),
  PRIORITY                     NUMBER,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS FACT_TASK_RUN (
  SCHEDULED_TIME               TIMESTAMP_NTZ,
  COMPLETED_TIME               TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  DATABASE_NAME                VARCHAR(300),
  ENVIRONMENT                  VARCHAR(100),
  SCHEMA_NAME                  VARCHAR(300),
  ROOT_TASK_NAME               VARCHAR(500),
  TASK_NAME                    VARCHAR(500),
  STATE                        VARCHAR(100),
  QUERY_ID                     VARCHAR(200),
  ERROR_CODE                   VARCHAR(100),
  ERROR_MESSAGE                VARCHAR,
  DURATION_MS                  NUMBER,
  WAREHOUSE_NAME               VARCHAR(300),
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS FACT_TASK_CRITICAL_PATH (
  SNAPSHOT_TS                  TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  DATABASE_NAME                VARCHAR(300),
  ENVIRONMENT                  VARCHAR(100),
  ROOT_TASK_NAME               VARCHAR(500),
  CRITICAL_PATH_STATE          VARCHAR(100),
  CRITICAL_PATH_SCORE          NUMBER(18,1),
  TASK_COUNT                   NUMBER,
  DOWNSTREAM_TASK_COUNT        NUMBER,
  SUSPENDED_TASKS              NUMBER,
  RUNS_7D                      NUMBER,
  FAILURES_7D                  NUMBER,
  SUCCESSES_7D                 NUMBER,
  MAX_DURATION_SEC             NUMBER(18,2),
  LAST_RUN_AT                  TIMESTAMP_NTZ,
  BLAST_RADIUS                 VARCHAR(100),
  WAREHOUSES                   VARCHAR,
  PROCEDURES                   VARCHAR,
  OWNER_ROLE                   VARCHAR(300),
  APPROVAL_PATH                VARCHAR(1000),
  SOURCE_FRESHNESS             VARCHAR(1000),
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS DIM_TASK_SNAPSHOT (
  SNAPSHOT_TS                  TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  DATABASE_NAME                VARCHAR(300),
  ENVIRONMENT                  VARCHAR(100),
  SCHEMA_NAME                  VARCHAR(300),
  TASK_NAME                    VARCHAR(500),
  ROOT_TASK_NAME               VARCHAR(500),
  STATE                        VARCHAR(100),
  SCHEDULE                     VARCHAR,
  WAREHOUSE_NAME               VARCHAR(300),
  PREDECESSORS                 VARIANT,
  DEFINITION                   VARCHAR,
  PROCEDURE_NAME               VARCHAR
);


CREATE TRANSIENT TABLE IF NOT EXISTS DIM_PROCEDURE_SNAPSHOT (
  SNAPSHOT_TS                  TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  DATABASE_NAME                VARCHAR(300),
  ENVIRONMENT                  VARCHAR(100),
  SCHEMA_NAME                  VARCHAR(300),
  PROCEDURE_NAME               VARCHAR(500),
  OWNER_ROLE                   VARCHAR(300),
  PROCEDURE_LANGUAGE           VARCHAR(100),
  ARGUMENT_SIGNATURE           VARCHAR,
  LAST_ALTERED                 TIMESTAMP_NTZ,
  IS_ORPHAN_CANDIDATE          BOOLEAN
);


CREATE TRANSIENT TABLE IF NOT EXISTS FACT_PROCEDURE_RUN (
  START_TIME                   TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  DATABASE_NAME                VARCHAR(300),
  ENVIRONMENT                  VARCHAR(100),
  SCHEMA_NAME                  VARCHAR(300),
  PROCEDURE_NAME               VARCHAR(500),
  CALL_QUERY_ID                VARCHAR(200),
  ROOT_QUERY_ID                VARCHAR(200),
  CHILD_QUERY_COUNT            NUMBER,
  TOTAL_DURATION_MS            NUMBER,
  EST_CREDITS                  NUMBER(18,6),
  EST_COST_USD                 NUMBER(18,2),
  STATUS                       VARCHAR(100),
  ERROR_MESSAGE                VARCHAR,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS FACT_LOGIN_DAILY (
  LOGIN_DATE                   DATE,
  COMPANY                      VARCHAR(100),
  USER_NAME                    VARCHAR(300),
  CLIENT_IP                    VARCHAR(300),
  REPORTED_CLIENT_TYPE         VARCHAR(300),
  REPORTED_CLIENT_VERSION      VARCHAR(300),
  SUCCESS_COUNT                NUMBER,
  FAILURE_COUNT                NUMBER,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS FACT_OBJECT_CHANGE (
  START_TIME                   TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  QUERY_ID                     VARCHAR(200),
  USER_NAME                    VARCHAR(300),
  ROLE_NAME                    VARCHAR(300),
  DATABASE_NAME                VARCHAR(300),
  ENVIRONMENT                  VARCHAR(100),
  SCHEMA_NAME                  VARCHAR(300),
  CHANGE_CATEGORY              VARCHAR(100),
  QUERY_TYPE                   VARCHAR(100),
  QUERY_TAG                    VARCHAR,
  QUERY_TEXT                   VARCHAR,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS FACT_CHANGE_CONTROL_OPERABILITY_DAILY (
  SNAPSHOT_DATE                DATE,
  COMPANY                      VARCHAR(100),
  ENVIRONMENT                  VARCHAR(100),
  CONTROL_SOURCE               VARCHAR(80),
  CONTROL_KEY                  VARCHAR(500),
  FINDING_TYPE                 VARCHAR(120),
  ENTITY                       VARCHAR(500),
  OWNER                        VARCHAR(200),
  ESCALATION_TARGET            VARCHAR(200),
  SEVERITY                     VARCHAR(40),
  EVIDENCE_ROWS                NUMBER,
  HIGH_RISK_CHANGES            NUMBER,
  ROUTE_BLOCKED                NUMBER,
  CLOSURE_BLOCKED              NUMBER,
  REVIEW_READY                 NUMBER,
  MISSING_TICKET_ROWS          NUMBER,
  IAC_GAP_ROWS                 NUMBER,
  MISSING_QUERY_ID_ROWS        NUMBER,
  OPEN_ACTIONS                 NUMBER,
  OVERDUE_OPEN                 NUMBER,
  FIXED_WITHOUT_VERIFICATION   NUMBER,
  VERIFIED_CLOSURES            NUMBER,
  OWNER_APPROVAL_GAP_ROWS      NUMBER,
  CONTROL_STATE                VARCHAR(120),
  CONTROL_RANK                 NUMBER,
  NEXT_CONTROL_ACTION          VARCHAR(4000),
  LAST_ACTIVITY_TS             TIMESTAMP_NTZ,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS FACT_GRANT_DAILY (
  SNAPSHOT_DATE                DATE,
  COMPANY                      VARCHAR(100),
  ROLE_NAME                    VARCHAR(300),
  GRANTEE_NAME                 VARCHAR(300),
  GRANTED_TO                   VARCHAR(100),
  CREATED_ON                   TIMESTAMP_NTZ,
  DELETED_ON                   TIMESTAMP_NTZ,
  GRANT_COUNT                  NUMBER,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


ALTER TABLE IF EXISTS FACT_GRANT_DAILY ADD COLUMN IF NOT EXISTS CREATED_ON TIMESTAMP_NTZ;



CREATE TRANSIENT TABLE IF NOT EXISTS FACT_STORAGE_DAILY (
  SNAPSHOT_DATE                DATE,
  COMPANY                      VARCHAR(100),
  DATABASE_NAME                VARCHAR(300),
  ENVIRONMENT                  VARCHAR(100),
  ACTIVE_BYTES                 NUMBER,
  TIME_TRAVEL_BYTES            NUMBER,
  FAILSAFE_BYTES               NUMBER,
  RETAINED_FOR_CLONE_BYTES     NUMBER,
  STAGE_BYTES                  NUMBER DEFAULT 0,
  HYBRID_TABLE_STORAGE_BYTES   NUMBER DEFAULT 0,
  ARCHIVE_STORAGE_COOL_BYTES   NUMBER DEFAULT 0,
  ARCHIVE_STORAGE_COLD_BYTES   NUMBER DEFAULT 0,
  EST_STORAGE_TB               NUMBER(18,4),
  EST_COST_USD                 NUMBER(18,2),
  STANDARD_STORAGE_COST_USD    NUMBER(18,2) DEFAULT 0,
  HYBRID_STORAGE_COST_USD      NUMBER(18,2) DEFAULT 0,
  ARCHIVE_COOL_COST_USD        NUMBER(18,2) DEFAULT 0,
  ARCHIVE_COLD_COST_USD        NUMBER(18,2) DEFAULT 0,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS DIM_TABLE_SNAPSHOT (
  SNAPSHOT_TS                  TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  DATABASE_NAME                VARCHAR(300),
  ENVIRONMENT                  VARCHAR(100),
  SCHEMA_NAME                  VARCHAR(300),
  TABLE_NAME                   VARCHAR(500),
  TABLE_TYPE                   VARCHAR(100),
  ROW_COUNT                    NUMBER,
  BYTES                        NUMBER,
  LAST_ALTERED                 TIMESTAMP_LTZ,
  CREATED                      TIMESTAMP_LTZ,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS FACT_COPY_LOAD_DAILY (
  LOAD_DATE                    DATE,
  COMPANY                      VARCHAR(100),
  DATABASE_NAME                VARCHAR(300),
  ENVIRONMENT                  VARCHAR(100),
  SCHEMA_NAME                  VARCHAR(300),
  TABLE_NAME                   VARCHAR(500),
  STATUS                       VARCHAR(100),
  FILE_COUNT                   NUMBER,
  ROW_COUNT                    NUMBER,
  ROW_PARSED                   NUMBER,
  ERROR_COUNT                  NUMBER,
  FILE_SIZE_BYTES              NUMBER,
  BYTES_BILLED                 NUMBER,
  LAST_SEEN                    TIMESTAMP_LTZ,
  LATEST_ERROR                 VARCHAR,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);



CREATE TRANSIENT TABLE IF NOT EXISTS FACT_CORTEX_DAILY (
  USAGE_DATE                   DATE,
  COMPANY                      VARCHAR(100),
  USER_ID                      VARCHAR(300),
  SOURCE                       VARCHAR(100),
  CREDITS_USED                 NUMBER(18,6),
  EST_COST_USD                 NUMBER(18,2),
  REQUEST_COUNT                NUMBER,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS FACT_COST_DAILY (
  USAGE_DATE                         DATE,
  COMPANY                            VARCHAR(100),
  SERVICE_CATEGORY                   VARCHAR(120),
  SERVICE_TYPE                       VARCHAR(200),
  CREDITS_USED_COMPUTE               NUMBER(18,6),
  CREDITS_USED_CLOUD_SERVICES        NUMBER(18,6),
  CREDITS_ADJUSTMENT_CLOUD_SERVICES  NUMBER(18,6),
  CREDITS_BILLED                     NUMBER(18,6),
  RATE_USD                           NUMBER(18,4),
  EST_COST_USD                       NUMBER(18,2),
  SOURCE_VIEW                        VARCHAR(300),
  LOAD_TS                            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


ALTER TABLE IF EXISTS FACT_COST_DAILY ADD COLUMN IF NOT EXISTS RATE_USD NUMBER(18,4);


CREATE TRANSIENT TABLE IF NOT EXISTS FACT_COST_SOURCE_HEALTH_DAILY (
  SNAPSHOT_DATE                 DATE,
  SOURCE_NAME                   VARCHAR(200),
  SOURCE_SCOPE                  VARCHAR(200),
  STATUS                        VARCHAR(80),
  EXPECTED_LATENCY_HOURS        NUMBER,
  OBSERVED_ROWS                 NUMBER,
  LAST_DATA_DATE                DATE,
  ERROR_MESSAGE                 VARCHAR(4000),
  LOAD_TS                       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS FACT_COST_MONITORING_SIGNAL (
  SNAPSHOT_TS                  TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  ENVIRONMENT                  VARCHAR(100),
  SIGNAL_TYPE                  VARCHAR(120),
  SEVERITY                     VARCHAR(40),
  ENTITY_TYPE                  VARCHAR(120),
  ENTITY_NAME                  VARCHAR(500),
  CONTROL_SURFACE              VARCHAR(200),
  CONTROL_SCOPE                VARCHAR(200),
  EVIDENCE                     VARCHAR(4000),
  NEXT_ACTION                  VARCHAR(4000),
  PROOF_QUERY                  VARCHAR(8000),
  VALUE_AT_RISK_USD            NUMBER(18,2),
  SOURCE                       VARCHAR(200),
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS FACT_COST_INCIDENT_TIMELINE (
  INCIDENT_ID                  VARCHAR(200),
  EVENT_TS                     TIMESTAMP_NTZ,
  EVENT_ORDER                  NUMBER,
  COMPANY                      VARCHAR(100),
  ENVIRONMENT                  VARCHAR(100),
  ENTITY_NAME                  VARCHAR(500),
  EVENT_TYPE                   VARCHAR(160),
  SEVERITY                     VARCHAR(40),
  EVIDENCE                     VARCHAR(4000),
  NEXT_ACTION                  VARCHAR(4000),
  PROOF_QUERY                  VARCHAR(8000),
  SOURCE                       VARCHAR(200),
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS MART_DBA_CONTROL_ROOM (
  SNAPSHOT_TS                  TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  HEALTH_SCORE                 NUMBER(5,2),
  FAILED_QUERIES_24H           NUMBER,
  FAILED_TASKS_24H             NUMBER,
  QUEUED_MS_24H                NUMBER,
  CREDITS_24H                  NUMBER(18,6),
  COST_24H_USD                 NUMBER(18,2),
  CORTEX_COST_7D_USD           NUMBER(18,2),
  SECURITY_EVENTS_24H          NUMBER,
  OBJECT_CHANGES_24H           NUMBER,
  TOP_RISK                     VARCHAR(1000),
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS MART_EXECUTIVE_OBSERVABILITY (
  SNAPSHOT_TS                  TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  ENVIRONMENT                  VARCHAR(100),
  WINDOW_DAYS                  NUMBER,
  PANEL                        VARCHAR(100),
  METRIC                       VARCHAR(200),
  DIMENSION                    VARCHAR(500),
  PERIOD_START                 TIMESTAMP_NTZ,
  VALUE                        FLOAT,
  VALUE_USD                    FLOAT,
  UNIT                         VARCHAR(100),
  SORT_ORDER                   NUMBER,
  SOURCE                       VARCHAR(500),
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


-- -----------------------------------------------------------------------------
-- Enterprise operating model: Finding -> Owner -> Trust -> Impact -> Action -> Value
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS OVERWATCH_DATA_TRUST_SOURCE (
  SOURCE_KEY                   VARCHAR(200) PRIMARY KEY,
  SOURCE_NAME                  VARCHAR(300),
  SOURCE_OBJECT                VARCHAR(500),
  SOURCE_CLASS                 VARCHAR(100),
  SURFACE                      VARCHAR(200),
  TARGET_FRESHNESS_MIN         NUMBER,
  DEFAULT_CONFIDENCE           VARCHAR(40),
  BUSINESS_IMPACT              VARCHAR(1000),
  OWNER_ROUTE                  VARCHAR(200),
  ENABLED                      BOOLEAN DEFAULT TRUE,
  CREATED_AT                   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT                   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS OVERWATCH_DATA_TRUST_STATUS (
  SNAPSHOT_TS                  TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  ENVIRONMENT                  VARCHAR(100),
  SOURCE_KEY                   VARCHAR(200),
  SOURCE_NAME                  VARCHAR(300),
  SOURCE_OBJECT                VARCHAR(500),
  SOURCE_CLASS                 VARCHAR(100),
  SURFACE                      VARCHAR(200),
  LATEST_SOURCE_TS             TIMESTAMP_NTZ,
  AGE_MINUTES                  NUMBER,
  TARGET_FRESHNESS_MIN         NUMBER,
  STATUS                       VARCHAR(40),
  CONFIDENCE                   VARCHAR(40),
  BUSINESS_IMPACT              VARCHAR(1000),
  OWNER_ROUTE                  VARCHAR(200),
  NEXT_ACTION                  VARCHAR(1000),
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS MART_DATA_TRUST_SUMMARY (
  SNAPSHOT_TS                  TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  ENVIRONMENT                  VARCHAR(100),
  TRUST_DOMAIN                 VARCHAR(100),
  METRIC                       VARCHAR(200),
  SOURCE_NAME                  VARCHAR(300),
  STATUS                       VARCHAR(40),
  CONFIDENCE                   VARCHAR(40),
  VALUE                        FLOAT,
  VALUE_USD                    FLOAT,
  FRESHNESS_MINUTES            NUMBER,
  SOURCE_OBJECT                VARCHAR(500),
  OWNER_ROUTE                  VARCHAR(200),
  BUSINESS_IMPACT              VARCHAR(1000),
  NEXT_ACTION                  VARCHAR(1000),
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TABLE IF NOT EXISTS OVERWATCH_OPERATIONAL_OWNER_MAP (
  ENTITY_TYPE                  VARCHAR(100),
  ENTITY_PATTERN               VARCHAR(500),
  COMPANY                      VARCHAR(100) DEFAULT 'ALL',
  ENVIRONMENT                  VARCHAR(100) DEFAULT 'ALL',
  OWNER_ROUTE                  VARCHAR(200),
  OWNER_EMAIL                  VARCHAR(500),
  ONCALL_PRIMARY               VARCHAR(200),
  ESCALATION_TARGET            VARCHAR(200),
  SOURCE                       VARCHAR(200),
  ACTIVE                       BOOLEAN DEFAULT TRUE,
  CREATED_AT                   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT                   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS MART_OPERATIONAL_OWNER_COVERAGE (
  SNAPSHOT_TS                  TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  ENVIRONMENT                  VARCHAR(100),
  SURFACE                      VARCHAR(200),
  ENTITY_TYPE                  VARCHAR(100),
  TOTAL_ITEMS                  NUMBER,
  ROUTED_ITEMS                 NUMBER,
  GAP_ITEMS                    NUMBER,
  COVERAGE_PCT                 NUMBER(8,2),
  TRUST_LEVEL                  VARCHAR(100),
  CONFIDENCE                   VARCHAR(40),
  TOP_GAP_ENTITY               VARCHAR(500),
  OWNER_ROUTE                  VARCHAR(200),
  NEXT_ACTION                  VARCHAR(1000),
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TABLE IF NOT EXISTS OVERWATCH_VALUE_LEDGER (
  LEDGER_ID                    VARCHAR(64) PRIMARY KEY,
  COMPANY                      VARCHAR(100),
  ENVIRONMENT                  VARCHAR(100),
  FINDING                      VARCHAR(4000),
  ENTITY_TYPE                  VARCHAR(100),
  ENTITY_NAME                  VARCHAR(500),
  OWNER_ROUTE                  VARCHAR(200),
  STATUS                       VARCHAR(100) DEFAULT 'Proposed',
  EXPECTED_SAVINGS_USD         NUMBER(18,2) DEFAULT 0,
  ACTUAL_VERIFIED_SAVINGS_USD  NUMBER(18,2) DEFAULT 0,
  CONFIDENCE                   VARCHAR(40) DEFAULT 'estimated',
  TRUST_LEVEL                  VARCHAR(100) DEFAULT 'Verification Pending',
  BUSINESS_IMPACT              VARCHAR(4000),
  ACTION_TAKEN                 VARCHAR(4000),
  EVIDENCE                     VARCHAR(8000),
  VERIFICATION_WINDOW_START    TIMESTAMP_NTZ,
  VERIFICATION_WINDOW_END      TIMESTAMP_NTZ,
  VERIFIED_BY                  VARCHAR(200),
  VERIFIED_AT                  TIMESTAMP_NTZ,
  ROLLBACK_NOTES               VARCHAR(4000),
  CREATED_AT                   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT                   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS MART_EXECUTIVE_VALUE_LEDGER (
  SNAPSHOT_TS                  TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  ENVIRONMENT                  VARCHAR(100),
  WINDOW_DAYS                  NUMBER,
  METRIC                       VARCHAR(200),
  STATUS                       VARCHAR(100),
  OWNER_ROUTE                  VARCHAR(200),
  EXPECTED_SAVINGS_USD         NUMBER(18,2),
  VERIFIED_SAVINGS_USD         NUMBER(18,2),
  UNVERIFIED_ESTIMATE_USD      NUMBER(18,2),
  CONFIDENCE                   VARCHAR(40),
  VALUE_STATE                  VARCHAR(100),
  OPEN_ITEMS                   NUMBER,
  VERIFIED_ITEMS               NUMBER,
  EVIDENCE                     VARCHAR(4000),
  NEXT_ACTION                  VARCHAR(1000),
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS OVERWATCH_APP_OBSERVABILITY (
  EVENT_TS                     TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  ENVIRONMENT                  VARCHAR(100),
  APP_VERSION                  VARCHAR(40),
  SECTION_NAME                 VARCHAR(200),
  EVENT_TYPE                   VARCHAR(100),
  RENDER_MS                    NUMBER,
  QUERY_COUNT                  NUMBER,
  QUERY_FAILURE_COUNT          NUMBER,
  OVERWATCH_COST_USD           NUMBER(18,4),
  VALIDATION_STATUS            VARCHAR(100),
  DEPLOYMENT_VERSION           VARCHAR(100),
  LAST_DEPLOYMENT_TS           TIMESTAMP_NTZ,
  DETAIL                       VARCHAR(2000),
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS MART_APP_OBSERVABILITY_SUMMARY (
  SNAPSHOT_TS                  TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  ENVIRONMENT                  VARCHAR(100),
  APP_VERSION                  VARCHAR(40),
  HEALTH_STATE                 VARCHAR(100),
  SECTION_NAME                 VARCHAR(200),
  P95_RENDER_MS                NUMBER,
  SLOW_SECTION_COUNT           NUMBER,
  QUERY_FAILURE_COUNT          NUMBER,
  OVERWATCH_COST_USD           NUMBER(18,4),
  VALIDATION_STATUS            VARCHAR(100),
  LAST_DEPLOYMENT_TS           TIMESTAMP_NTZ,
  CONFIDENCE                   VARCHAR(40),
  SOURCE                       VARCHAR(500),
  NEXT_ACTION                  VARCHAR(1000),
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


-- -----------------------------------------------------------------------------
-- Phase 2A: live production validation and readiness contracts
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS OVERWATCH_PRODUCTION_CHECKLIST (
  CHECK_KEY                    VARCHAR(200) PRIMARY KEY,
  CHECK_DOMAIN                 VARCHAR(100),
  CHECK_NAME                   VARCHAR(300),
  SURFACE                      VARCHAR(200),
  SEVERITY                     VARCHAR(40),
  REQUIRED_OBJECT              VARCHAR(500),
  FIRST_PAINT_SAFE             BOOLEAN DEFAULT TRUE,
  EXPLICIT_LOAD_REQUIRED       BOOLEAN DEFAULT FALSE,
  EXPECTED_STATE               VARCHAR(100),
  OWNER_ROUTE                  VARCHAR(200),
  RUNBOOK_STEP                 VARCHAR(2000),
  ENABLED                      BOOLEAN DEFAULT TRUE,
  CREATED_AT                   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT                   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TABLE IF NOT EXISTS OVERWATCH_ROLE_READINESS_REQUIREMENT (
  ROLE_NAME                    VARCHAR(200) PRIMARY KEY,
  ROLE_CLASS                   VARCHAR(100),
  REQUIRED_FOR                 VARCHAR(500),
  REQUIRED                     BOOLEAN DEFAULT TRUE,
  LEGACY_COMPAT                BOOLEAN DEFAULT FALSE,
  CHECK_METHOD                 VARCHAR(1000),
  OWNER_ROUTE                  VARCHAR(200),
  ENABLED                      BOOLEAN DEFAULT TRUE,
  CREATED_AT                   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT                   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TABLE IF NOT EXISTS OVERWATCH_PRIVILEGE_READINESS_REQUIREMENT (
  PRIVILEGE_KEY                VARCHAR(200) PRIMARY KEY,
  OBJECT_NAME                  VARCHAR(500),
  OBJECT_TYPE                  VARCHAR(100),
  REQUIRED_PRIVILEGE           VARCHAR(200),
  REQUIRED_FOR                 VARCHAR(1000),
  REQUIRED                     BOOLEAN DEFAULT TRUE,
  CHECK_METHOD                 VARCHAR(1000),
  OWNER_ROUTE                  VARCHAR(200),
  REMEDIATION_HINT             VARCHAR(2000),
  ENABLED                      BOOLEAN DEFAULT TRUE,
  CREATED_AT                   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT                   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS OVERWATCH_PRODUCTION_VALIDATION_STATUS (
  SNAPSHOT_TS                  TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  ENVIRONMENT                  VARCHAR(100),
  CHECK_DOMAIN                 VARCHAR(100),
  CHECK_KEY                    VARCHAR(200),
  CHECK_NAME                   VARCHAR(300),
  VALIDATION_STATUS            VARCHAR(40),
  RISK_LEVEL                   VARCHAR(40),
  VALUE                        FLOAT,
  VALUE_DETAIL                 VARCHAR(4000),
  SOURCE_OBJECT                VARCHAR(500),
  FRESHNESS_MINUTES            NUMBER,
  OWNER_ROUTE                  VARCHAR(200),
  RUNBOOK_STEP                 VARCHAR(2000),
  CONFIDENCE                   VARCHAR(40),
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS MART_PRODUCTION_READINESS_SUMMARY (
  SNAPSHOT_TS                  TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  ENVIRONMENT                  VARCHAR(100),
  DEPLOYMENT_VERSION           VARCHAR(100),
  LAST_DEPLOYMENT_TS           TIMESTAMP_NTZ,
  LAST_VALIDATION_TS           TIMESTAMP_NTZ,
  VALIDATION_STATUS            VARCHAR(40),
  MISSING_PRIVILEGES           NUMBER,
  FAILED_MART_REFRESHES        NUMBER,
  MISSING_SUMMARY_MARTS        NUMBER,
  STALE_SOURCE_COUNT           NUMBER,
  CONFIG_DRIFT_COUNT           NUMBER,
  ENVIRONMENT_READINESS        VARCHAR(100),
  READINESS_SCORE              NUMBER,
  TOP_RISK                     VARCHAR(1000),
  CONFIDENCE                   VARCHAR(40),
  NEXT_ACTION                  VARCHAR(1000),
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


-- -----------------------------------------------------------------------------
-- Phase 2B: leadership Executive Scorecard
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS OVERWATCH_EXECUTIVE_SCORECARD_CONFIG (
  SCORE_KEY                    VARCHAR(100) PRIMARY KEY,
  SCORE_NAME                   VARCHAR(200),
  DISPLAY_ORDER                NUMBER,
  SCORE_DOMAIN                 VARCHAR(100),
  RED_BELOW                    NUMBER DEFAULT 70,
  YELLOW_BELOW                 NUMBER DEFAULT 85,
  OWNER_ROUTE                  VARCHAR(200),
  DRIVER_SOURCE                VARCHAR(1000),
  RECOMMENDED_ACTION           VARCHAR(1000),
  ENABLED                      BOOLEAN DEFAULT TRUE,
  CREATED_AT                   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT                   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS OVERWATCH_EXECUTIVE_SCORECARD_HISTORY (
  SNAPSHOT_TS                  TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  ENVIRONMENT                  VARCHAR(100),
  SCORE_KEY                    VARCHAR(100),
  SCORE_NAME                   VARCHAR(200),
  CURRENT_SCORE                NUMBER(6,2),
  STATUS                       VARCHAR(40),
  TREND                        VARCHAR(40),
  TREND_DELTA                  NUMBER(8,2),
  RISK_LEVEL                   VARCHAR(40),
  TOP_DRIVER                   VARCHAR(2000),
  RECOMMENDED_ACTION           VARCHAR(2000),
  OWNER_ROUTE                  VARCHAR(200),
  OWNER_GAP                    BOOLEAN DEFAULT FALSE,
  VALUE_AT_RISK_USD            NUMBER(18,2) DEFAULT 0,
  CONFIDENCE                   VARCHAR(40),
  SOURCE_OBJECTS               VARCHAR(1000),
  LAST_REFRESHED_TS            TIMESTAMP_NTZ,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS MART_EXECUTIVE_SCORECARD_SUMMARY (
  SNAPSHOT_TS                  TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  ENVIRONMENT                  VARCHAR(100),
  SCORE_KEY                    VARCHAR(100),
  SCORE_NAME                   VARCHAR(200),
  DISPLAY_ORDER                NUMBER,
  CURRENT_SCORE                NUMBER(6,2),
  STATUS                       VARCHAR(40),
  TREND                        VARCHAR(40),
  TREND_DELTA                  NUMBER(8,2),
  RISK_LEVEL                   VARCHAR(40),
  TOP_DRIVER                   VARCHAR(2000),
  RECOMMENDED_ACTION           VARCHAR(2000),
  OWNER_ROUTE                  VARCHAR(200),
  OWNER_GAP                    BOOLEAN DEFAULT FALSE,
  VALUE_AT_RISK_USD            NUMBER(18,2) DEFAULT 0,
  CONFIDENCE                   VARCHAR(40),
  SOURCE_OBJECTS               VARCHAR(1000),
  LAST_REFRESHED_TS            TIMESTAMP_NTZ,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


-- -----------------------------------------------------------------------------
-- Phase 2C: leadership forecasting
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS OVERWATCH_FORECAST_CONFIG (
  FORECAST_KEY                 VARCHAR(100) PRIMARY KEY,
  FORECAST_NAME                VARCHAR(200),
  DISPLAY_ORDER                NUMBER,
  FORECAST_DOMAIN              VARCHAR(100),
  VALUE_UNIT                   VARCHAR(40),
  OWNER_ROUTE                  VARCHAR(200),
  SOURCE_OBJECTS               VARCHAR(1000),
  METHODOLOGY                  VARCHAR(4000),
  RECOMMENDED_ACTION           VARCHAR(2000),
  CONFIDENCE_RULE              VARCHAR(1000),
  ENABLED                      BOOLEAN DEFAULT TRUE,
  CREATED_AT                   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT                   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS OVERWATCH_FORECAST_HISTORY (
  SNAPSHOT_TS                  TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  ENVIRONMENT                  VARCHAR(100),
  FORECAST_KEY                 VARCHAR(100),
  FORECAST_NAME                VARCHAR(200),
  FORECAST_DOMAIN              VARCHAR(100),
  FORECAST_VALUE               NUMBER(18,4),
  CURRENT_ACTUAL               NUMBER(18,4),
  PRIOR_PERIOD_VALUE           NUMBER(18,4),
  TREND_DIRECTION              VARCHAR(40),
  CONFIDENCE                   VARCHAR(40),
  METHODOLOGY                  VARCHAR(4000),
  MAIN_DRIVER                  VARCHAR(2000),
  RECOMMENDED_ACTION           VARCHAR(2000),
  OWNER_ROUTE                  VARCHAR(200),
  OWNER_GAP                    BOOLEAN DEFAULT FALSE,
  VALUE_UNIT                   VARCHAR(40),
  VALUE_AT_RISK_USD            NUMBER(18,2) DEFAULT 0,
  SOURCE_OBJECTS               VARCHAR(1000),
  LAST_REFRESHED_TS            TIMESTAMP_NTZ,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS MART_EXECUTIVE_FORECAST_SUMMARY (
  SNAPSHOT_TS                  TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  ENVIRONMENT                  VARCHAR(100),
  FORECAST_KEY                 VARCHAR(100),
  FORECAST_NAME                VARCHAR(200),
  DISPLAY_ORDER                NUMBER,
  FORECAST_DOMAIN              VARCHAR(100),
  FORECAST_VALUE               NUMBER(18,4),
  CURRENT_ACTUAL               NUMBER(18,4),
  PRIOR_PERIOD_VALUE           NUMBER(18,4),
  TREND_DIRECTION              VARCHAR(40),
  CONFIDENCE                   VARCHAR(40),
  METHODOLOGY                  VARCHAR(4000),
  MAIN_DRIVER                  VARCHAR(2000),
  RECOMMENDED_ACTION           VARCHAR(2000),
  OWNER_ROUTE                  VARCHAR(200),
  OWNER_GAP                    BOOLEAN DEFAULT FALSE,
  VALUE_UNIT                   VARCHAR(40),
  VALUE_AT_RISK_USD            NUMBER(18,2) DEFAULT 0,
  SOURCE_OBJECTS               VARCHAR(1000),
  LAST_REFRESHED_TS            TIMESTAMP_NTZ,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


-- -----------------------------------------------------------------------------
-- Phase 2D: Change Intelligence
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS OVERWATCH_CHANGE_RULE (
  CHANGE_TYPE                  VARCHAR(100) PRIMARY KEY,
  CHANGE_CATEGORY              VARCHAR(100),
  OBJECT_TYPE                  VARCHAR(100),
  RISK_LEVEL                   VARCHAR(40),
  BUSINESS_IMPACT              VARCHAR(2000),
  OWNER_ROUTE                  VARCHAR(200),
  CONFIDENCE                   VARCHAR(40),
  SOURCE_OBJECTS               VARCHAR(1000),
  MATCH_HINT                   VARCHAR(1000),
  ENABLED                      BOOLEAN DEFAULT TRUE,
  CREATED_AT                   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT                   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS OVERWATCH_CHANGE_EVENT (
  SNAPSHOT_TS                  TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  ENVIRONMENT                  VARCHAR(100),
  CHANGE_ID                    VARCHAR(200),
  CHANGE_TYPE                  VARCHAR(100),
  CHANGE_CATEGORY              VARCHAR(100),
  OBJECT_TYPE                  VARCHAR(100),
  OBJECT_NAME                  VARCHAR(500),
  CHANGED_BY                   VARCHAR(300),
  CHANGE_TS                    TIMESTAMP_NTZ,
  BEFORE_VALUE                 VARCHAR(4000),
  AFTER_VALUE                  VARCHAR(4000),
  RISK_LEVEL                   VARCHAR(40),
  BUSINESS_IMPACT              VARCHAR(2000),
  OWNER_ROUTE                  VARCHAR(200),
  OWNER_GAP                    BOOLEAN DEFAULT FALSE,
  RELATED_ALERT_COUNT          NUMBER DEFAULT 0,
  RELATED_INCIDENTS            VARCHAR(4000),
  CONFIDENCE                   VARCHAR(40),
  SOURCE_OBJECTS               VARCHAR(1000),
  LAST_REFRESHED_TS            TIMESTAMP_NTZ,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS OVERWATCH_CHANGE_CORRELATION (
  SNAPSHOT_TS                  TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  ENVIRONMENT                  VARCHAR(100),
  CHANGE_ID                    VARCHAR(200),
  CHANGE_TYPE                  VARCHAR(100),
  OBJECT_TYPE                  VARCHAR(100),
  OBJECT_NAME                  VARCHAR(500),
  CHANGE_TS                    TIMESTAMP_NTZ,
  CHANGED_BY                   VARCHAR(300),
  CORRELATION_TYPE             VARCHAR(100),
  RELATED_SIGNAL               VARCHAR(500),
  RELATED_ENTITY               VARCHAR(500),
  RELATED_TS                   TIMESTAMP_NTZ,
  RELATED_ALERT_COUNT          NUMBER DEFAULT 0,
  CORRELATION_WINDOW_HOURS     NUMBER,
  CORRELATION_STRENGTH         VARCHAR(40),
  CORRELATION_LABEL            VARCHAR(100),
  RISK_LEVEL                   VARCHAR(40),
  BUSINESS_IMPACT              VARCHAR(2000),
  OWNER_ROUTE                  VARCHAR(200),
  CONFIDENCE                   VARCHAR(40),
  EVIDENCE                     VARCHAR(4000),
  LAST_REFRESHED_TS            TIMESTAMP_NTZ,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS MART_CHANGE_INTELLIGENCE_SUMMARY (
  SNAPSHOT_TS                  TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  ENVIRONMENT                  VARCHAR(100),
  CHANGE_TYPE                  VARCHAR(100),
  CHANGE_CATEGORY              VARCHAR(100),
  OBJECT_TYPE                  VARCHAR(100),
  CHANGE_COUNT                 NUMBER DEFAULT 0,
  HIGH_RISK_COUNT              NUMBER DEFAULT 0,
  OWNER_GAP_COUNT              NUMBER DEFAULT 0,
  RELATED_ALERT_COUNT          NUMBER DEFAULT 0,
  CORRELATION_CANDIDATE_COUNT  NUMBER DEFAULT 0,
  LATEST_CHANGE_TS             TIMESTAMP_NTZ,
  TOP_OBJECT_NAME              VARCHAR(500),
  TOP_CHANGED_BY               VARCHAR(300),
  RISK_LEVEL                   VARCHAR(40),
  BUSINESS_IMPACT              VARCHAR(2000),
  OWNER_ROUTE                  VARCHAR(200),
  CONFIDENCE                   VARCHAR(40),
  LAST_REFRESHED_TS            TIMESTAMP_NTZ,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


-- -----------------------------------------------------------------------------
-- Phase 2E: Closed Loop Operations
-- -----------------------------------------------------------------------------

CREATE TRANSIENT TABLE IF NOT EXISTS OVERWATCH_ACTION_WORKFLOW (
  SNAPSHOT_TS                  TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  ENVIRONMENT                  VARCHAR(100),
  WORKFLOW_ID                  VARCHAR(200),
  ACTION_SOURCE                VARCHAR(100),
  SOURCE_ID                    VARCHAR(200),
  ACTION_DOMAIN                VARCHAR(100),
  FINDING                      VARCHAR(4000),
  SOURCE_TELEMETRY             VARCHAR(8000),
  ENTITY_TYPE                  VARCHAR(100),
  ENTITY_NAME                  VARCHAR(500),
  OWNER_ROUTE                  VARCHAR(200),
  OWNER_GAP                    BOOLEAN DEFAULT FALSE,
  BUSINESS_IMPACT              VARCHAR(4000),
  RISK_LEVEL                   VARCHAR(40),
  RECOMMENDED_ACTION           VARCHAR(4000),
  ACTION_STATUS                VARCHAR(100),
  APPROVAL_STATUS              VARCHAR(100),
  APPROVED_BY                  VARCHAR(200),
  APPROVAL_TS                  TIMESTAMP_NTZ,
  EXECUTION_MODE               VARCHAR(100),
  REVIEW_SQL_TEXT              VARCHAR(16000),
  REVIEW_ACTION_TEXT           VARCHAR(8000),
  ROLLBACK_GUIDANCE            VARCHAR(4000),
  VERIFICATION_STEPS           VARCHAR(8000),
  VERIFICATION_STATUS          VARCHAR(100),
  EXPECTED_SAVINGS_USD         NUMBER(18,2) DEFAULT 0,
  ACTUAL_VERIFIED_SAVINGS_USD  NUMBER(18,2) DEFAULT 0,
  EVIDENCE                     VARCHAR(8000),
  CLOSED_TS                    TIMESTAMP_NTZ,
  LAST_REFRESHED_TS            TIMESTAMP_NTZ,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS OVERWATCH_ACTION_APPROVAL (
  SNAPSHOT_TS                  TIMESTAMP_NTZ,
  WORKFLOW_ID                  VARCHAR(200),
  COMPANY                      VARCHAR(100),
  ENVIRONMENT                  VARCHAR(100),
  ACTION_DOMAIN                VARCHAR(100),
  APPROVAL_STATUS              VARCHAR(100),
  APPROVED_BY                  VARCHAR(200),
  APPROVAL_TS                  TIMESTAMP_NTZ,
  APPROVAL_ROUTE               VARCHAR(200),
  APPROVAL_REQUIRED            BOOLEAN DEFAULT TRUE,
  APPROVAL_EVIDENCE            VARCHAR(4000),
  RISK_LEVEL                   VARCHAR(40),
  OWNER_ROUTE                  VARCHAR(200),
  LAST_REFRESHED_TS            TIMESTAMP_NTZ,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS OVERWATCH_ACTION_EXECUTION_PLAN (
  SNAPSHOT_TS                  TIMESTAMP_NTZ,
  WORKFLOW_ID                  VARCHAR(200),
  COMPANY                      VARCHAR(100),
  ENVIRONMENT                  VARCHAR(100),
  ACTION_DOMAIN                VARCHAR(100),
  EXECUTION_MODE               VARCHAR(100),
  EXECUTION_STATUS             VARCHAR(100),
  REVIEW_SQL_TEXT              VARCHAR(16000),
  REVIEW_ACTION_TEXT           VARCHAR(8000),
  DANGEROUS_ACTION_FLAG        BOOLEAN DEFAULT FALSE,
  EXECUTION_ALLOWED_IN_APP     BOOLEAN DEFAULT FALSE,
  ROLLBACK_GUIDANCE            VARCHAR(4000),
  VERIFICATION_STEPS           VARCHAR(8000),
  LAST_REFRESHED_TS            TIMESTAMP_NTZ,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS OVERWATCH_ACTION_VERIFICATION (
  SNAPSHOT_TS                  TIMESTAMP_NTZ,
  WORKFLOW_ID                  VARCHAR(200),
  COMPANY                      VARCHAR(100),
  ENVIRONMENT                  VARCHAR(100),
  ACTION_DOMAIN                VARCHAR(100),
  VERIFICATION_STATUS          VARCHAR(100),
  VERIFICATION_STEPS           VARCHAR(8000),
  EXPECTED_SAVINGS_USD         NUMBER(18,2) DEFAULT 0,
  ACTUAL_VERIFIED_SAVINGS_USD  NUMBER(18,2) DEFAULT 0,
  VERIFICATION_WINDOW_START    TIMESTAMP_NTZ,
  VERIFICATION_WINDOW_END      TIMESTAMP_NTZ,
  VERIFIED_BY                  VARCHAR(200),
  VERIFIED_AT                  TIMESTAMP_NTZ,
  EVIDENCE                     VARCHAR(8000),
  LAST_REFRESHED_TS            TIMESTAMP_NTZ,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS OVERWATCH_ACTION_EVIDENCE (
  SNAPSHOT_TS                  TIMESTAMP_NTZ,
  WORKFLOW_ID                  VARCHAR(200),
  COMPANY                      VARCHAR(100),
  ENVIRONMENT                  VARCHAR(100),
  ACTION_DOMAIN                VARCHAR(100),
  EVIDENCE_TYPE                VARCHAR(100),
  SOURCE_OBJECT                VARCHAR(500),
  SOURCE_TELEMETRY             VARCHAR(8000),
  EVIDENCE                     VARCHAR(8000),
  CONFIDENCE                   VARCHAR(40),
  LAST_REFRESHED_TS            TIMESTAMP_NTZ,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS MART_CLOSED_LOOP_OPERATIONS_SUMMARY (
  SNAPSHOT_TS                  TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  ENVIRONMENT                  VARCHAR(100),
  ACTION_DOMAIN                VARCHAR(100),
  OPEN_ACTION_COUNT            NUMBER DEFAULT 0,
  APPROVAL_REQUIRED_COUNT      NUMBER DEFAULT 0,
  APPROVED_COUNT               NUMBER DEFAULT 0,
  EXECUTION_PLAN_COUNT         NUMBER DEFAULT 0,
  VERIFICATION_PENDING_COUNT   NUMBER DEFAULT 0,
  VERIFIED_COUNT               NUMBER DEFAULT 0,
  CLOSED_COUNT                 NUMBER DEFAULT 0,
  HIGH_RISK_COUNT              NUMBER DEFAULT 0,
  OWNER_GAP_COUNT              NUMBER DEFAULT 0,
  EVIDENCE_COUNT               NUMBER DEFAULT 0,
  EXPECTED_SAVINGS_USD         NUMBER(18,2) DEFAULT 0,
  ACTUAL_VERIFIED_SAVINGS_USD  NUMBER(18,2) DEFAULT 0,
  UNVERIFIED_EXPECTED_USD      NUMBER(18,2) DEFAULT 0,
  TOP_FINDING                  VARCHAR(4000),
  NEXT_ACTION                  VARCHAR(1000),
  CONFIDENCE                   VARCHAR(40),
  LAST_REFRESHED_TS            TIMESTAMP_NTZ,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


-- -----------------------------------------------------------------------------
-- Phase 2F: Command Center
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS OVERWATCH_COMMAND_CENTER_QUESTION (
  QUESTION_KEY                 VARCHAR(100) PRIMARY KEY,
  INVESTIGATION_TYPE           VARCHAR(100),
  QUESTION_TEXT                VARCHAR(500),
  DISPLAY_ORDER                NUMBER,
  SOURCE_OBJECTS               VARCHAR(1000),
  DEFAULT_OWNER_ROUTE          VARCHAR(200),
  DEFAULT_RISK_LEVEL           VARCHAR(40),
  DEFAULT_CONFIDENCE           VARCHAR(40),
  DEFAULT_ACTION               VARCHAR(2000),
  ENABLED                      BOOLEAN DEFAULT TRUE,
  CREATED_AT                   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT                   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS OVERWATCH_COMMAND_CENTER_FINDING (
  SNAPSHOT_TS                         TIMESTAMP_NTZ,
  COMPANY                             VARCHAR(100),
  ENVIRONMENT                         VARCHAR(100),
  FINDING_ID                          VARCHAR(200),
  QUESTION_KEY                        VARCHAR(100),
  INVESTIGATION_TYPE                  VARCHAR(100),
  QUESTION_TEXT                       VARCHAR(500),
  ROOT_CAUSE_CANDIDATE                VARCHAR(4000),
  EVIDENCE_SUMMARY                    VARCHAR(8000),
  CONFIDENCE                          VARCHAR(40),
  BUSINESS_IMPACT                     VARCHAR(4000),
  TECHNICAL_IMPACT                    VARCHAR(4000),
  OWNER_ROUTE                         VARCHAR(200),
  OWNER_GAP                           BOOLEAN DEFAULT FALSE,
  RELATED_CHANGES                     VARCHAR(4000),
  RELATED_ALERTS                      VARCHAR(4000),
  RELATED_SCORECARD_DRIVERS           VARCHAR(4000),
  RELATED_FORECASTS                   VARCHAR(4000),
  RECOMMENDED_ACTION                  VARCHAR(4000),
  RISK_LEVEL                          VARCHAR(40),
  EXECUTION_PLAN_REF                  VARCHAR(200),
  EXPECTED_SAVINGS_OR_RISK_AVOIDED_USD NUMBER(18,2) DEFAULT 0,
  VERIFICATION_PATH                   VARCHAR(4000),
  CAUSALITY_LABEL                     VARCHAR(100),
  LAST_REFRESHED_TS                   TIMESTAMP_NTZ,
  LOAD_TS                             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS OVERWATCH_COMMAND_CENTER_EVIDENCE (
  SNAPSHOT_TS                  TIMESTAMP_NTZ,
  COMPANY                      VARCHAR(100),
  ENVIRONMENT                  VARCHAR(100),
  FINDING_ID                   VARCHAR(200),
  EVIDENCE_ID                  VARCHAR(200),
  EVIDENCE_TYPE                VARCHAR(100),
  SOURCE_OBJECT                VARCHAR(500),
  RELATED_OBJECT               VARCHAR(500),
  EVIDENCE_SUMMARY             VARCHAR(8000),
  CONFIDENCE                   VARCHAR(40),
  CAUSALITY_LABEL              VARCHAR(100),
  LAST_REFRESHED_TS            TIMESTAMP_NTZ,
  LOAD_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS OVERWATCH_COMMAND_CENTER_RECOMMENDATION (
  SNAPSHOT_TS                         TIMESTAMP_NTZ,
  COMPANY                             VARCHAR(100),
  ENVIRONMENT                         VARCHAR(100),
  FINDING_ID                          VARCHAR(200),
  RECOMMENDATION_ID                   VARCHAR(200),
  RECOMMENDED_ACTION                  VARCHAR(4000),
  RISK_LEVEL                          VARCHAR(40),
  OWNER_ROUTE                         VARCHAR(200),
  EXECUTION_PLAN_REF                  VARCHAR(200),
  REVIEW_REQUIRED                     BOOLEAN DEFAULT TRUE,
  EXPECTED_SAVINGS_OR_RISK_AVOIDED_USD NUMBER(18,2) DEFAULT 0,
  VERIFICATION_PATH                   VARCHAR(4000),
  SAFETY_NOTE                         VARCHAR(2000),
  LAST_REFRESHED_TS                   TIMESTAMP_NTZ,
  LOAD_TS                             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TRANSIENT TABLE IF NOT EXISTS MART_COMMAND_CENTER_SUMMARY (
  SNAPSHOT_TS                         TIMESTAMP_NTZ,
  COMPANY                             VARCHAR(100),
  ENVIRONMENT                         VARCHAR(100),
  INVESTIGATION_TYPE                  VARCHAR(100),
  QUESTION_TEXT                       VARCHAR(500),
  FINDING_COUNT                       NUMBER DEFAULT 0,
  HIGH_RISK_COUNT                     NUMBER DEFAULT 0,
  OWNER_GAP_COUNT                     NUMBER DEFAULT 0,
  RELATED_CHANGE_COUNT                NUMBER DEFAULT 0,
  RELATED_ALERT_COUNT                 NUMBER DEFAULT 0,
  RELATED_SCORECARD_COUNT             NUMBER DEFAULT 0,
  RELATED_FORECAST_COUNT              NUMBER DEFAULT 0,
  REVIEW_PLAN_COUNT                   NUMBER DEFAULT 0,
  EXPECTED_VALUE_USD                  NUMBER(18,2) DEFAULT 0,
  TOP_ROOT_CAUSE_CANDIDATE            VARCHAR(4000),
  TOP_EVIDENCE_SUMMARY                VARCHAR(8000),
  TOP_RECOMMENDED_ACTION              VARCHAR(4000),
  CONFIDENCE                          VARCHAR(40),
  RISK_LEVEL                          VARCHAR(40),
  LAST_REFRESHED_TS                   TIMESTAMP_NTZ,
  LOAD_TS                             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


-- Existing installs may have been created before environment dimensions and
-- detailed query telemetry were added. CREATE TABLE IF NOT EXISTS will not
-- evolve those tables, so keep this upgrade block idempotent.
ALTER TABLE IF EXISTS FACT_QUERY_HOURLY ADD COLUMN IF NOT EXISTS WAREHOUSE_SIZE VARCHAR(100);

ALTER TABLE IF EXISTS FACT_QUERY_HOURLY ADD COLUMN IF NOT EXISTS ENVIRONMENT VARCHAR(100);


ALTER TABLE IF EXISTS FACT_QUERY_DETAIL_RECENT ADD COLUMN IF NOT EXISTS ENVIRONMENT VARCHAR(100);

ALTER TABLE IF EXISTS FACT_QUERY_DETAIL_RECENT ADD COLUMN IF NOT EXISTS WAREHOUSE_SIZE VARCHAR(100);

ALTER TABLE IF EXISTS FACT_QUERY_DETAIL_RECENT ADD COLUMN IF NOT EXISTS COMPILATION_TIME NUMBER;

ALTER TABLE IF EXISTS FACT_QUERY_DETAIL_RECENT ADD COLUMN IF NOT EXISTS EXECUTION_TIME NUMBER;

ALTER TABLE IF EXISTS FACT_QUERY_DETAIL_RECENT ADD COLUMN IF NOT EXISTS TRANSACTION_BLOCKED_TIME NUMBER;

ALTER TABLE IF EXISTS FACT_QUERY_DETAIL_RECENT ADD COLUMN IF NOT EXISTS BYTES_SPILLED_TO_LOCAL_STORAGE NUMBER;

ALTER TABLE IF EXISTS FACT_QUERY_DETAIL_RECENT ADD COLUMN IF NOT EXISTS PARTITIONS_SCANNED NUMBER;

ALTER TABLE IF EXISTS FACT_QUERY_DETAIL_RECENT ADD COLUMN IF NOT EXISTS PARTITIONS_TOTAL NUMBER;

ALTER TABLE IF EXISTS FACT_QUERY_DETAIL_RECENT ADD COLUMN IF NOT EXISTS ROWS_PRODUCED NUMBER;

ALTER TABLE IF EXISTS FACT_QUERY_DETAIL_RECENT ADD COLUMN IF NOT EXISTS QUERY_HASH VARCHAR(300);


ALTER TABLE IF EXISTS FACT_TASK_RUN ADD COLUMN IF NOT EXISTS ENVIRONMENT VARCHAR(100);

ALTER TABLE IF EXISTS DIM_TASK_SNAPSHOT ADD COLUMN IF NOT EXISTS ENVIRONMENT VARCHAR(100);

ALTER TABLE IF EXISTS DIM_PROCEDURE_SNAPSHOT ADD COLUMN IF NOT EXISTS ENVIRONMENT VARCHAR(100);

ALTER TABLE IF EXISTS FACT_PROCEDURE_RUN ADD COLUMN IF NOT EXISTS DATABASE_NAME VARCHAR(300);

ALTER TABLE IF EXISTS FACT_PROCEDURE_RUN ADD COLUMN IF NOT EXISTS ENVIRONMENT VARCHAR(100);

ALTER TABLE IF EXISTS FACT_PROCEDURE_RUN ADD COLUMN IF NOT EXISTS SCHEMA_NAME VARCHAR(300);

ALTER TABLE IF EXISTS FACT_OBJECT_CHANGE ADD COLUMN IF NOT EXISTS ENVIRONMENT VARCHAR(100);

ALTER TABLE IF EXISTS FACT_OBJECT_CHANGE ADD COLUMN IF NOT EXISTS QUERY_TAG VARCHAR;

ALTER TABLE IF EXISTS FACT_STORAGE_DAILY ADD COLUMN IF NOT EXISTS ENVIRONMENT VARCHAR(100);

ALTER TABLE IF EXISTS FACT_STORAGE_DAILY ADD COLUMN IF NOT EXISTS STAGE_BYTES NUMBER;

ALTER TABLE IF EXISTS FACT_STORAGE_DAILY ADD COLUMN IF NOT EXISTS HYBRID_TABLE_STORAGE_BYTES NUMBER;

ALTER TABLE IF EXISTS FACT_STORAGE_DAILY ADD COLUMN IF NOT EXISTS ARCHIVE_STORAGE_COOL_BYTES NUMBER;

ALTER TABLE IF EXISTS FACT_STORAGE_DAILY ADD COLUMN IF NOT EXISTS ARCHIVE_STORAGE_COLD_BYTES NUMBER;

ALTER TABLE IF EXISTS FACT_STORAGE_DAILY ADD COLUMN IF NOT EXISTS STANDARD_STORAGE_COST_USD NUMBER(18,2);

ALTER TABLE IF EXISTS FACT_STORAGE_DAILY ADD COLUMN IF NOT EXISTS HYBRID_STORAGE_COST_USD NUMBER(18,2);

ALTER TABLE IF EXISTS FACT_STORAGE_DAILY ADD COLUMN IF NOT EXISTS ARCHIVE_COOL_COST_USD NUMBER(18,2);

ALTER TABLE IF EXISTS FACT_STORAGE_DAILY ADD COLUMN IF NOT EXISTS ARCHIVE_COLD_COST_USD NUMBER(18,2);

ALTER TABLE IF EXISTS DIM_TABLE_SNAPSHOT ADD COLUMN IF NOT EXISTS ENVIRONMENT VARCHAR(100);

ALTER TABLE IF EXISTS FACT_COPY_LOAD_DAILY ADD COLUMN IF NOT EXISTS ENVIRONMENT VARCHAR(100);

ALTER TABLE IF EXISTS FACT_CHARGEBACK_DAILY ADD COLUMN IF NOT EXISTS ENVIRONMENT VARCHAR(100);

ALTER TABLE IF EXISTS FACT_CHARGEBACK_DAILY ADD COLUMN IF NOT EXISTS ENVIRONMENT_ROLLUP VARCHAR(100);

ALTER TABLE IF EXISTS MART_EXECUTIVE_OBSERVABILITY ADD COLUMN IF NOT EXISTS SOURCE VARCHAR(500);
