-- OVERWATCH mart setup split: 05_views.sql

-- Create derived review and triage views after base tables exist.

-- Source bundle: snowflake/OVERWATCH_MART_SETUP.sql



USE DATABASE DBA_MAINT_DB;
USE SCHEMA OVERWATCH;




CREATE OR REPLACE VIEW OVERWATCH_WORKLOAD_RECOVERY_AUDIT_LATEST_V AS
SELECT *
FROM OVERWATCH_WORKLOAD_RECOVERY_AUDIT
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY COALESCE(ACTION_ID, ENTITY_NAME), ENTITY_TYPE
  ORDER BY RECOVERY_AUDIT_TS DESC, RECOVERY_AUDIT_ID DESC
) = 1;


CREATE OR REPLACE VIEW ALERT_NATIVE_DEPLOYMENT_REVIEW_V AS
SELECT
  REGISTRY_KEY,
  ALERT_KEY,
  CATEGORY,
  ALERT_OBJECT_NAME,
  TARGET_ROUTE,
  WAREHOUSE_NAME,
  SCHEDULE_TEXT,
  STATUS,
  ENABLED_BY_DEFAULT,
  CASE
    WHEN COALESCE(ENABLED_BY_DEFAULT, FALSE) THEN 'BLOCKED_ENABLED_BY_DEFAULT'
    WHEN UPPER(COALESCE(STATUS, 'CANDIDATE')) IN ('APPROVED', 'READY', 'READY_TO_DEPLOY') THEN 'READY_FOR_MANUAL_DEPLOY'
    WHEN UPPER(COALESCE(STATUS, 'CANDIDATE')) IN ('DEPLOYED', 'ACTIVE') THEN 'DEPLOYED_MONITOR'
    ELSE 'CANDIDATE_REVIEW_REQUIRED'
  END AS DEPLOYMENT_STATE,
  IFF(GENERATED_CREATE_SQL ILIKE '%CREATE OR REPLACE ALERT%', TRUE, FALSE) AS DEPLOYMENT_SQL_PRESENT,
  IFF(GENERATED_DROP_SQL ILIKE '%DROP ALERT%', TRUE, FALSE) AS ROLLBACK_SQL_PRESENT,
  CASE
    WHEN COALESCE(ENABLED_BY_DEFAULT, FALSE) THEN 'Set ENABLED_BY_DEFAULT to FALSE before review can continue.'
    WHEN UPPER(COALESCE(STATUS, 'CANDIDATE')) IN ('APPROVED', 'READY', 'READY_TO_DEPLOY') THEN 'Run GENERATED_CREATE_SQL manually after owner, threshold, schedule, and warehouse approval.'
    WHEN UPPER(COALESCE(STATUS, 'CANDIDATE')) IN ('DEPLOYED', 'ACTIVE') THEN 'Monitor ALERT_EVENTS and dry-run outcomes; use GENERATED_DROP_SQL only for rollback.'
    ELSE 'Review owner, threshold, route, safety note, and generated SQL before marking approved.'
  END AS DEPLOYMENT_NEXT_STEP,
  'SHOW ALERTS LIKE ''' || ALERT_OBJECT_NAME || ''';' AS VALIDATION_SQL,
  SAFETY_NOTE,
  GENERATED_CREATE_SQL,
  GENERATED_DROP_SQL,
  UPDATED_AT,
  UPDATED_BY
FROM ALERT_NATIVE_OBJECT_REGISTRY;


CREATE OR REPLACE VIEW OVERWATCH_ALERT_TRIAGE_V AS
WITH base AS (
  SELECT
    a.*,
    COALESCE(r.OWNER, a.OWNER, 'DBA') AS ROUTED_OWNER,
    NULL AS OWNER_EMAIL,
    COALESCE(r.OWNER, a.OWNER, 'DBA On-Call') AS ONCALL_PRIMARY,
    NULL AS ONCALL_SECONDARY,
    COALESCE(r.OWNER, a.OWNER, 'DBA Lead') AS APPROVAL_GROUP,
    COALESCE(r.OWNER, a.OWNER, 'DBA Lead') AS OWNER_ESCALATION_TARGET,
    'ALERT_RULE' AS OWNER_SOURCE,
    'Matched alert rule or alert row owner' AS OWNER_EVIDENCE,
    COALESCE(
      r.SLA_HOURS,
      CASE UPPER(COALESCE(a.SEVERITY, 'Medium'))
        WHEN 'CRITICAL' THEN 4
        WHEN 'HIGH' THEN 8
        WHEN 'LOW' THEN 72
        ELSE 24
      END
    ) AS SLA_TARGET_HOURS,
    GREATEST(0, COALESCE(DATEDIFF('hour', a.ALERT_TS, CURRENT_TIMESTAMP()), 0)) AS ALERT_AGE_HOURS,
    COALESCE(r.ROUTE, 'Alert Center') AS ALERT_ROUTE,
    COALESCE(r.RUNBOOK, a.SUGGESTED_ACTION, 'Review the Alert Center issue and route it through the DBA action queue.') AS ALERT_RUNBOOK
  FROM OVERWATCH_ALERTS a
  LEFT JOIN OVERWATCH_ALERT_RULES r
    ON UPPER(COALESCE(a.ALERT_TYPE, a.CATEGORY, '')) = UPPER(COALESCE(r.ALERT_TYPE, r.CATEGORY, ''))
   AND COALESCE(r.IS_ACTIVE, TRUE)
),
sla AS (
  SELECT
    base.*,
    CASE
      WHEN UPPER(REPLACE(COALESCE(STATUS, 'New'), ' ', '_')) IN ('FIXED', 'IGNORED', 'RESOLVED') THEN 'Closed'
      WHEN ALERT_AGE_HOURS > SLA_TARGET_HOURS THEN 'Overdue'
      WHEN ALERT_AGE_HOURS >= (SLA_TARGET_HOURS * 0.75) THEN 'Due Soon'
      ELSE 'Within SLA'
    END AS SLA_STATE
  FROM base
)
SELECT
  sla.*,
  CASE
    WHEN SLA_STATE = 'Overdue' AND UPPER(COALESCE(SEVERITY, 'Medium')) IN ('CRITICAL', 'HIGH') THEN COALESCE(OWNER_ESCALATION_TARGET, ESCALATED_TO, 'DBA Lead')
    ELSE COALESCE(OWNER_ESCALATION_TARGET, ROUTED_OWNER, OWNER, 'DBA')
  END AS ESCALATION_TARGET,
  (
    CASE UPPER(COALESCE(SEVERITY, 'Medium'))
      WHEN 'CRITICAL' THEN 0
      WHEN 'HIGH' THEN 1
      WHEN 'MEDIUM' THEN 2
      WHEN 'LOW' THEN 3
      ELSE 4
    END * 100
    + CASE SLA_STATE
      WHEN 'Overdue' THEN 0
      WHEN 'Due Soon' THEN 1
      WHEN 'Within SLA' THEN 2
      WHEN 'Closed' THEN 9
      ELSE 5
    END * 10
    + CASE UPPER(REPLACE(COALESCE(STATUS, 'New'), ' ', '_'))
      WHEN 'NEW' THEN 0
      WHEN 'EMAIL_READY' THEN 0
      WHEN 'EMAIL_QUEUED' THEN 0
      WHEN 'OPEN' THEN 0
      WHEN 'ACTIVE' THEN 0
      WHEN 'PENDING' THEN 0
      WHEN 'ACKNOWLEDGED' THEN 1
      WHEN 'IN_PROGRESS' THEN 1
      WHEN 'FIXED' THEN 3
      WHEN 'RESOLVED' THEN 3
      WHEN 'IGNORED' THEN 4
      ELSE 2
    END
  ) AS TRIAGE_PRIORITY
FROM sla;
