-- -----------------------------------------------------------------------------
-- 6. Task graph
-- -----------------------------------------------------------------------------

CREATE OR REPLACE TASK OVERWATCH_LOAD_HOURLY
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 25 * * * * America/Chicago'
AS
  CALL SP_OVERWATCH_LOAD_HOURLY_UNIT('WAREHOUSE_HOURLY', NULL, NULL);

CREATE OR REPLACE TASK OVERWATCH_LOAD_QUERY_HOURLY
  WAREHOUSE = COMPUTE_WH
  AFTER OVERWATCH_LOAD_HOURLY
AS
  CALL SP_OVERWATCH_LOAD_HOURLY_UNIT('QUERY_HOURLY', NULL, NULL);

CREATE OR REPLACE TASK OVERWATCH_LOAD_QUERY_DETAIL
  WAREHOUSE = COMPUTE_WH
  AFTER OVERWATCH_LOAD_QUERY_HOURLY
AS
  CALL SP_OVERWATCH_LOAD_HOURLY_UNIT('QUERY_DETAIL', NULL, NULL);

CREATE OR REPLACE TASK OVERWATCH_LOAD_OBJECT_CHANGE
  WAREHOUSE = COMPUTE_WH
  AFTER OVERWATCH_LOAD_QUERY_DETAIL
AS
  CALL SP_OVERWATCH_LOAD_HOURLY_UNIT('OBJECT_CHANGE', NULL, NULL);

CREATE OR REPLACE TASK OVERWATCH_LOAD_TASK_RUN
  WAREHOUSE = COMPUTE_WH
  AFTER OVERWATCH_LOAD_OBJECT_CHANGE
AS
  CALL SP_OVERWATCH_LOAD_HOURLY_UNIT('TASK_RUN', NULL, NULL);

CREATE OR REPLACE TASK OVERWATCH_LOAD_PROCEDURE_RUN
  WAREHOUSE = COMPUTE_WH
  AFTER OVERWATCH_LOAD_TASK_RUN
AS
  CALL SP_OVERWATCH_LOAD_HOURLY_UNIT('PROCEDURE_RUN', NULL, NULL);

CREATE OR REPLACE TASK OVERWATCH_LOAD_SNAPSHOTS
  WAREHOUSE = COMPUTE_WH
  AFTER OVERWATCH_LOAD_PROCEDURE_RUN
AS
  CALL SP_OVERWATCH_LOAD_HOURLY_UNIT('SNAPSHOTS', NULL, NULL);

CREATE OR REPLACE TASK OVERWATCH_LOAD_TASK_CRITICAL_PATH
  WAREHOUSE = COMPUTE_WH
  AFTER OVERWATCH_LOAD_SNAPSHOTS
AS
  CALL SP_OVERWATCH_LOAD_HOURLY_UNIT('TASK_CRITICAL_PATH', NULL, NULL);

CREATE OR REPLACE TASK OVERWATCH_LOAD_CORTEX
  WAREHOUSE = COMPUTE_WH
  AFTER OVERWATCH_LOAD_TASK_CRITICAL_PATH
AS
  CALL SP_OVERWATCH_LOAD_CORTEX();

CREATE OR REPLACE TASK OVERWATCH_REFRESH_CONTROL_ROOM
  WAREHOUSE = COMPUTE_WH
  AFTER OVERWATCH_LOAD_CORTEX
AS
  CALL SP_OVERWATCH_REFRESH_CONTROL_ROOM();

CREATE OR REPLACE TASK OVERWATCH_COST_MONITORING_REFRESH
  WAREHOUSE = COMPUTE_WH
  AFTER OVERWATCH_REFRESH_CONTROL_ROOM
AS
  CALL SP_OVERWATCH_REFRESH_COST_MONITORING();

CREATE OR REPLACE TASK OVERWATCH_EXECUTIVE_OBSERVABILITY_REFRESH
  WAREHOUSE = COMPUTE_WH
  AFTER OVERWATCH_COST_MONITORING_REFRESH
AS
  CALL SP_OVERWATCH_REFRESH_EXECUTIVE_OBSERVABILITY();

CREATE OR REPLACE TASK OVERWATCH_SECTION_COMMAND_BRIEF_REFRESH
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = '15 MINUTE'
  ALLOW_OVERLAPPING_EXECUTION = FALSE
AS
  CALL SP_OVERWATCH_REFRESH_SECTION_COMMAND_BRIEFS();

CREATE OR REPLACE TASK OVERWATCH_LOAD_DAILY
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 15 6 * * * America/Chicago'
AS
  CALL SP_OVERWATCH_LOAD_DAILY();

-- Resume child tasks first, then root scheduled tasks.
ALTER TASK OVERWATCH_SECTION_COMMAND_BRIEF_REFRESH RESUME;
ALTER TASK OVERWATCH_EXECUTIVE_OBSERVABILITY_REFRESH RESUME;
ALTER TASK OVERWATCH_COST_MONITORING_REFRESH RESUME;
ALTER TASK OVERWATCH_REFRESH_CONTROL_ROOM RESUME;
ALTER TASK OVERWATCH_LOAD_CORTEX RESUME;
ALTER TASK OVERWATCH_LOAD_TASK_CRITICAL_PATH RESUME;
ALTER TASK OVERWATCH_LOAD_SNAPSHOTS RESUME;
ALTER TASK OVERWATCH_LOAD_PROCEDURE_RUN RESUME;
ALTER TASK OVERWATCH_LOAD_TASK_RUN RESUME;
ALTER TASK OVERWATCH_LOAD_OBJECT_CHANGE RESUME;
ALTER TASK OVERWATCH_LOAD_QUERY_DETAIL RESUME;
ALTER TASK OVERWATCH_LOAD_QUERY_HOURLY RESUME;
ALTER TASK OVERWATCH_ANOMALY_CHECK RESUME;
ALTER TASK OVERWATCH_LOAD_HOURLY RESUME;
ALTER TASK OVERWATCH_LOAD_DAILY RESUME;

