-- -----------------------------------------------------------------------------
-- 6. Task graph
-- -----------------------------------------------------------------------------

CREATE OR REPLACE TASK OVERWATCH_LOAD_HOURLY
  WAREHOUSE = OVERWATCH_WH
  SCHEDULE = 'USING CRON 25 * * * * America/Chicago'
AS
  CALL SP_OVERWATCH_LOAD_HOURLY();

CREATE OR REPLACE TASK OVERWATCH_LOAD_CORTEX
  WAREHOUSE = OVERWATCH_WH
  AFTER OVERWATCH_LOAD_HOURLY
AS
  CALL SP_OVERWATCH_LOAD_CORTEX();

CREATE OR REPLACE TASK OVERWATCH_REFRESH_CONTROL_ROOM
  WAREHOUSE = OVERWATCH_WH
  AFTER OVERWATCH_LOAD_CORTEX
AS
  CALL SP_OVERWATCH_REFRESH_CONTROL_ROOM();

CREATE OR REPLACE TASK OVERWATCH_COST_MONITORING_REFRESH
  WAREHOUSE = OVERWATCH_WH
  AFTER OVERWATCH_REFRESH_CONTROL_ROOM
AS
  CALL SP_OVERWATCH_REFRESH_COST_MONITORING();

CREATE OR REPLACE TASK OVERWATCH_EXECUTIVE_OBSERVABILITY_REFRESH
  WAREHOUSE = OVERWATCH_WH
  AFTER OVERWATCH_COST_MONITORING_REFRESH
AS
  CALL SP_OVERWATCH_REFRESH_EXECUTIVE_OBSERVABILITY();

CREATE OR REPLACE TASK OVERWATCH_LOAD_DAILY
  WAREHOUSE = OVERWATCH_WH
  SCHEDULE = 'USING CRON 15 6 * * * America/Chicago'
AS
  CALL SP_OVERWATCH_LOAD_DAILY();

-- Resume child tasks first, then root scheduled tasks.
ALTER TASK OVERWATCH_EXECUTIVE_OBSERVABILITY_REFRESH RESUME;
ALTER TASK OVERWATCH_LOAD_CORTEX RESUME;
ALTER TASK OVERWATCH_REFRESH_CONTROL_ROOM RESUME;
ALTER TASK OVERWATCH_COST_MONITORING_REFRESH RESUME;
ALTER TASK OVERWATCH_ANOMALY_CHECK RESUME;
ALTER TASK OVERWATCH_LOAD_HOURLY RESUME;
ALTER TASK OVERWATCH_LOAD_DAILY RESUME;

