-- OVERWATCH mart setup: 08_grants.sql

-- Apply role grants after deployable objects exist.

-- Run files in numeric order from snowflake/mart_setup/.



USE DATABASE DBA_MAINT_DB;

USE SCHEMA OVERWATCH;



GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE SNOW_ACCOUNTADMINS;

GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE SNOW_SYSADMINS;

GRANT USAGE ON WAREHOUSE OVERWATCH_WH TO ROLE SNOW_ACCOUNTADMINS;

GRANT USAGE ON WAREHOUSE OVERWATCH_WH TO ROLE SNOW_SYSADMINS;

GRANT USAGE ON DATABASE DBA_MAINT_DB TO ROLE SNOW_ACCOUNTADMINS;

GRANT USAGE ON DATABASE DBA_MAINT_DB TO ROLE SNOW_SYSADMINS;

GRANT USAGE ON SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE SNOW_ACCOUNTADMINS;

GRANT USAGE ON SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE SNOW_SYSADMINS;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE SNOW_ACCOUNTADMINS;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE SNOW_SYSADMINS;

GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE SNOW_ACCOUNTADMINS;

GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE SNOW_SYSADMINS;

GRANT SELECT ON ALL VIEWS IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE SNOW_ACCOUNTADMINS;

GRANT SELECT ON ALL VIEWS IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE SNOW_SYSADMINS;

GRANT SELECT ON FUTURE VIEWS IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE SNOW_ACCOUNTADMINS;

GRANT SELECT ON FUTURE VIEWS IN SCHEMA DBA_MAINT_DB.OVERWATCH TO ROLE SNOW_SYSADMINS;

