-- -----------------------------------------------------------------------------
-- 7. Smoke checks
-- -----------------------------------------------------------------------------

SHOW TASKS LIKE 'OVERWATCH_%' IN SCHEMA DBA_MAINT_DB.OVERWATCH;

SELECT 'FACT_WAREHOUSE_HOURLY' AS TABLE_NAME, COUNT(*) AS ROWS_LOADED FROM FACT_WAREHOUSE_HOURLY
UNION ALL
SELECT 'FACT_QUERY_HOURLY', COUNT(*) FROM FACT_QUERY_HOURLY
UNION ALL
SELECT 'FACT_QUERY_DETAIL_RECENT', COUNT(*) FROM FACT_QUERY_DETAIL_RECENT
UNION ALL
SELECT 'DIM_TABLE_SNAPSHOT', COUNT(*) FROM DIM_TABLE_SNAPSHOT
UNION ALL
SELECT 'FACT_COPY_LOAD_DAILY', COUNT(*) FROM FACT_COPY_LOAD_DAILY
UNION ALL
SELECT 'FACT_COST_DAILY', COUNT(*) FROM FACT_COST_DAILY
UNION ALL
SELECT 'FACT_COST_SOURCE_HEALTH_DAILY', COUNT(*) FROM FACT_COST_SOURCE_HEALTH_DAILY
UNION ALL
SELECT 'FACT_COST_MONITORING_SIGNAL', COUNT(*) FROM FACT_COST_MONITORING_SIGNAL
UNION ALL
SELECT 'FACT_COST_INCIDENT_TIMELINE', COUNT(*) FROM FACT_COST_INCIDENT_TIMELINE
UNION ALL
SELECT 'MART_EXECUTIVE_OBSERVABILITY', COUNT(*) FROM MART_EXECUTIVE_OBSERVABILITY
UNION ALL
SELECT 'MART_DBA_CONTROL_ROOM', COUNT(*) FROM MART_DBA_CONTROL_ROOM
UNION ALL
SELECT 'MART_SECTION_COMMAND_BRIEF', COUNT(*) FROM MART_SECTION_COMMAND_BRIEF
UNION ALL
SELECT 'MART_SECTION_COMMAND_METRIC', COUNT(*) FROM MART_SECTION_COMMAND_METRIC
UNION ALL
SELECT 'MART_SECTION_COMMAND_EXCEPTION', COUNT(*) FROM MART_SECTION_COMMAND_EXCEPTION
UNION ALL
SELECT 'MART_SECTION_COMMAND_ACTION', COUNT(*) FROM MART_SECTION_COMMAND_ACTION
UNION ALL
SELECT 'MART_SECTION_COMMAND_SOURCE', COUNT(*) FROM MART_SECTION_COMMAND_SOURCE
UNION ALL
SELECT 'MART_SECTION_DECISION_CURRENT', COUNT(*) FROM MART_SECTION_DECISION_CURRENT
UNION ALL
SELECT 'MART_SECTION_DECISION_CURRENT_FLAT', COUNT(*) FROM MART_SECTION_DECISION_CURRENT_FLAT
UNION ALL
SELECT 'MART_SECTION_DECISION_LAST_GOOD', COUNT(*) FROM MART_SECTION_DECISION_LAST_GOOD
UNION ALL
SELECT 'OVERWATCH_DECISION_SETUP_HEALTH', COUNT(*) FROM OVERWATCH_DECISION_SETUP_HEALTH
UNION ALL
SELECT 'OVERWATCH_DECISION_REFRESH_AUDIT', COUNT(*) FROM OVERWATCH_DECISION_REFRESH_AUDIT
UNION ALL
SELECT 'MART_EXECUTIVE_DECISION_INBOX', COUNT(*) FROM MART_EXECUTIVE_DECISION_INBOX
UNION ALL
SELECT 'MART_DATA_TRUST_SUMMARY', COUNT(*) FROM MART_DATA_TRUST_SUMMARY
UNION ALL
SELECT 'MART_OPERATIONAL_OWNER_COVERAGE', COUNT(*) FROM MART_OPERATIONAL_OWNER_COVERAGE
UNION ALL
SELECT 'MART_EXECUTIVE_VALUE_LEDGER', COUNT(*) FROM MART_EXECUTIVE_VALUE_LEDGER
UNION ALL
SELECT 'MART_APP_OBSERVABILITY_SUMMARY', COUNT(*) FROM MART_APP_OBSERVABILITY_SUMMARY
UNION ALL
SELECT 'MART_PRODUCTION_READINESS_SUMMARY', COUNT(*) FROM MART_PRODUCTION_READINESS_SUMMARY
UNION ALL
SELECT 'MART_EXECUTIVE_SCORECARD_SUMMARY', COUNT(*) FROM MART_EXECUTIVE_SCORECARD_SUMMARY
UNION ALL
SELECT 'MART_EXECUTIVE_FORECAST_SUMMARY', COUNT(*) FROM MART_EXECUTIVE_FORECAST_SUMMARY
UNION ALL
SELECT 'MART_CHANGE_INTELLIGENCE_SUMMARY', COUNT(*) FROM MART_CHANGE_INTELLIGENCE_SUMMARY
UNION ALL
SELECT 'MART_CLOSED_LOOP_OPERATIONS_SUMMARY', COUNT(*) FROM MART_CLOSED_LOOP_OPERATIONS_SUMMARY
UNION ALL
SELECT 'MART_COMMAND_CENTER_SUMMARY', COUNT(*) FROM MART_COMMAND_CENTER_SUMMARY;


SELECT
  'DECISION_SETUP_HEALTH_SCHEMA' AS CHECK_NAME,
  COUNT(*) AS MISSING_COLUMNS,
  IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS STATUS
FROM (
  SELECT COLUMN1::VARCHAR AS COLUMN_NAME
  FROM VALUES
    ('EVENT_ID'), ('EVENT_TS'), ('STATUS'), ('USER_MESSAGE'),
    ('GLOBAL_STATUS'), ('SELECTED_SCOPE_STATUS'), ('CURRENT_SECTION_STATUS'),
    ('SELECTED_PROCEDURE'), ('FALLBACK_USED'), ('CURRENT_PACKET_COUNT'),
    ('SECTIONS_PRESENT'), ('MISSING_SECTIONS'), ('DUPLICATE_CURRENT_KEYS'),
    ('STALE_SECTIONS'), ('DATA_GAP_SECTIONS'), ('MISSING_METRIC_SECTIONS'),
    ('DEGRADED_SECTIONS'), ('INVALID_SECTIONS'), ('WARNING_SECTIONS'),
    ('MAX_PACKET_BYTES'), ('REQUESTED_SCOPE'), ('RESOLVED_SCOPE'),
    ('ADMIN_DETAIL'), ('SUGGESTED_REMEDIATION'), ('ACTOR_ROLE'),
    ('APP_VERSION'), ('PERSISTENCE_STATUS'), ('PERSISTENCE_ERROR'), ('LOAD_TS')
) required_columns
LEFT JOIN INFORMATION_SCHEMA.COLUMNS c
  ON UPPER(c.TABLE_SCHEMA) = UPPER(CURRENT_SCHEMA())
 AND UPPER(c.TABLE_NAME) = 'OVERWATCH_DECISION_SETUP_HEALTH'
 AND UPPER(c.COLUMN_NAME) = required_columns.COLUMN_NAME
WHERE c.COLUMN_NAME IS NULL;

SELECT
  'SECTION_DECISION_CURRENT_OPTIMIZED_LOOKUP_SCHEMA' AS CHECK_NAME,
  COUNT(*) AS MISSING_COLUMNS,
  IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS STATUS
FROM (
  SELECT COLUMN1::VARCHAR AS COLUMN_NAME
  FROM VALUES
    ('SECTION_NAME_NORM'), ('COMPANY_NORM'), ('ENVIRONMENT_NORM'), ('WINDOW_DAYS_NORM'),
    ('SCOPE_PRIORITY'), ('IS_EXACT_SCOPE'), ('IS_ACTIVE'), ('PACKET_BYTES')
) required_columns
LEFT JOIN INFORMATION_SCHEMA.COLUMNS c
  ON UPPER(c.TABLE_SCHEMA) = UPPER(CURRENT_SCHEMA())
 AND UPPER(c.TABLE_NAME) = 'MART_SECTION_DECISION_CURRENT'
 AND UPPER(c.COLUMN_NAME) = required_columns.COLUMN_NAME
WHERE c.COLUMN_NAME IS NULL;

SELECT
  'SECTION_DECISION_CURRENT_FLAT_TABLE' AS CHECK_NAME,
  COUNT(*) AS MISSING_TABLE,
  IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS STATUS
FROM (
  SELECT 'MART_SECTION_DECISION_CURRENT_FLAT' AS TABLE_NAME
) required_table
LEFT JOIN INFORMATION_SCHEMA.TABLES t
  ON UPPER(t.TABLE_SCHEMA) = UPPER(CURRENT_SCHEMA())
 AND UPPER(t.TABLE_NAME) = required_table.TABLE_NAME
WHERE t.TABLE_NAME IS NULL;

SELECT
  'OVERWATCH_OPTIONAL_PERFORMANCE_OPTIMIZATION_FLAGS' AS CHECK_NAME,
  COUNT(*) AS MISSING_SETTINGS,
  IFF(COUNT(*) = 0, 'PASS', 'WARN') AS STATUS
FROM (
  SELECT COLUMN1::VARCHAR AS SETTING_NAME
  FROM VALUES
    ('OVERWATCH_ENABLE_CLUSTER_KEYS'),
    ('OVERWATCH_ENABLE_SEARCH_OPTIMIZATION')
) required_settings
LEFT JOIN OVERWATCH_SETTINGS s
  ON UPPER(s.SETTING_NAME) = required_settings.SETTING_NAME
WHERE s.SETTING_NAME IS NULL;

SELECT
  'OVERWATCH_PERFORMANCE_OPTIMIZATION_AUDIT_TABLE' AS CHECK_NAME,
  COUNT(*) AS MISSING_TABLE,
  IFF(COUNT(*) = 0, 'PASS', 'WARN') AS STATUS
FROM (
  SELECT 'OVERWATCH_PERFORMANCE_OPTIMIZATION_AUDIT' AS TABLE_NAME
) required_table
LEFT JOIN INFORMATION_SCHEMA.TABLES t
  ON UPPER(t.TABLE_SCHEMA) = UPPER(CURRENT_SCHEMA())
 AND UPPER(t.TABLE_NAME) = required_table.TABLE_NAME
WHERE t.TABLE_NAME IS NULL;

SELECT
  'DECISION_REFRESH_AUDIT_SCHEMA' AS CHECK_NAME,
  COUNT(*) AS MISSING_COLUMNS,
  IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS STATUS
FROM (
  SELECT COLUMN1::VARCHAR AS COLUMN_NAME
  FROM VALUES
    ('EVENT_ID'), ('EVENT_TS'), ('REFRESH_MODE'), ('LOAD_STARTED_AT'),
    ('LOAD_FINISHED_AT'), ('ELAPSED_SECONDS'), ('PARENT_ROWS'), ('METRIC_ROWS'),
    ('EXCEPTION_ROWS'), ('ACTION_ROWS'), ('SOURCE_ROWS'), ('CURRENT_PACKET_ROWS'),
    ('LAST_GOOD_ROWS'), ('MAX_PACKET_BYTES'), ('AVG_PACKET_BYTES'),
    ('MAX_SOURCE_ROW_COUNT'), ('MAX_TREND_POINTS'), ('DATA_GAP_COUNT'),
    ('DEGRADED_COUNT'), ('FAILED_SECTION_COUNT'), ('FAST_PRUNED_OPTIONAL_BRANCHES'),
    ('GENERATED_WINDOW_COUNT'), ('GENERATED_SCOPE_COUNT'), ('ERROR_MESSAGE'),
    ('ROWS_BY_STAGE'), ('BYTES_BY_STAGE'), ('LOAD_TS')
) required_columns
LEFT JOIN INFORMATION_SCHEMA.COLUMNS c
  ON UPPER(c.TABLE_SCHEMA) = UPPER(CURRENT_SCHEMA())
 AND UPPER(c.TABLE_NAME) = 'OVERWATCH_DECISION_REFRESH_AUDIT'
 AND UPPER(c.COLUMN_NAME) = required_columns.COLUMN_NAME
WHERE c.COLUMN_NAME IS NULL;




CALL SP_OVERWATCH_LOAD_HOURLY_UNIT('WAREHOUSE_HOURLY', NULL, NULL);
CALL SP_OVERWATCH_LOAD_HOURLY_UNIT('QUERY_HOURLY', NULL, NULL);
CALL SP_OVERWATCH_LOAD_HOURLY_UNIT('QUERY_DETAIL', NULL, NULL);
CALL SP_OVERWATCH_LOAD_HOURLY_UNIT('OBJECT_CHANGE', NULL, NULL);
CALL SP_OVERWATCH_LOAD_HOURLY_UNIT('TASK_RUN', NULL, NULL);
CALL SP_OVERWATCH_LOAD_HOURLY_UNIT('PROCEDURE_RUN', NULL, NULL);
CALL SP_OVERWATCH_LOAD_HOURLY_UNIT('SNAPSHOTS', NULL, NULL);
CALL SP_OVERWATCH_LOAD_HOURLY_UNIT('TASK_CRITICAL_PATH', NULL, NULL);
CALL SP_OVERWATCH_LOAD_CORTEX();
CALL SP_OVERWATCH_REFRESH_CONTROL_ROOM();
CALL SP_OVERWATCH_REFRESH_COST_MONITORING();
CALL SP_OVERWATCH_LOAD_DAILY();
CALL SP_OVERWATCH_REFRESH_EXECUTIVE_OBSERVABILITY();
CALL SP_OVERWATCH_REFRESH_ENTERPRISE_OPERATING_MODEL();
CALL SP_OVERWATCH_REFRESH_PRODUCTION_READINESS();
CALL SP_OVERWATCH_REFRESH_EXECUTIVE_SCORECARD();
CALL SP_OVERWATCH_REFRESH_FORECASTING();
CALL SP_OVERWATCH_REFRESH_CHANGE_INTELLIGENCE();
CALL SP_OVERWATCH_REFRESH_CLOSED_LOOP_OPERATIONS();
CALL SP_OVERWATCH_REFRESH_COMMAND_CENTER();
CALL SP_OVERWATCH_REFRESH_SECTION_COMMAND_BRIEFS();
CALL SP_OVERWATCH_REFRESH_DECISION_BRIEFS_FAST();
CALL SP_OVERWATCH_REFRESH_DECISION_BRIEFS_FULL();
CALL SP_OVERWATCH_BOOTSTRAP_DECISION_BRIEFS();

SELECT
  'SECTION_COMMAND_BRIEF_SECTION_COVERAGE' AS CHECK_NAME,
  COUNT(DISTINCT SECTION_NAME) AS OBSERVED_VALUE,
  IFF(COUNT(DISTINCT SECTION_NAME) = 6, 'PASS', 'FAIL') AS STATUS
FROM MART_SECTION_COMMAND_BRIEF
WHERE SNAPSHOT_TS = (SELECT MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_BRIEF);

SELECT
  'SECTION_COMMAND_BRIEF_PARENT_HAS_METRICS' AS CHECK_NAME,
  COUNT_IF(metric_count = 0) AS PARENTS_WITHOUT_METRICS,
  IFF(COUNT_IF(metric_count = 0) = 0, 'PASS', 'FAIL') AS STATUS
FROM (
  SELECT b.BRIEF_ID, COUNT(m.BRIEF_ID) AS metric_count
  FROM MART_SECTION_COMMAND_BRIEF b
  LEFT JOIN MART_SECTION_COMMAND_METRIC m ON m.BRIEF_ID = b.BRIEF_ID
  WHERE b.SNAPSHOT_TS = (SELECT MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_BRIEF)
  GROUP BY b.BRIEF_ID
);

SELECT
  'SECTION_COMMAND_BRIEF_ORPHAN_CHILD_ROWS' AS CHECK_NAME,
  SUM(ORPHANS) AS ORPHAN_ROWS,
  IFF(SUM(ORPHANS) = 0, 'PASS', 'FAIL') AS STATUS
FROM (
  SELECT COUNT(*) AS ORPHANS FROM MART_SECTION_COMMAND_METRIC c LEFT JOIN MART_SECTION_COMMAND_BRIEF b ON b.BRIEF_ID = c.BRIEF_ID WHERE b.BRIEF_ID IS NULL
  UNION ALL
  SELECT COUNT(*) FROM MART_SECTION_COMMAND_EXCEPTION c LEFT JOIN MART_SECTION_COMMAND_BRIEF b ON b.BRIEF_ID = c.BRIEF_ID WHERE b.BRIEF_ID IS NULL
  UNION ALL
  SELECT COUNT(*) FROM MART_SECTION_COMMAND_ACTION c LEFT JOIN MART_SECTION_COMMAND_BRIEF b ON b.BRIEF_ID = c.BRIEF_ID WHERE b.BRIEF_ID IS NULL
  UNION ALL
  SELECT COUNT(*) FROM MART_SECTION_COMMAND_SOURCE c LEFT JOIN MART_SECTION_COMMAND_BRIEF b ON b.BRIEF_ID = c.BRIEF_ID WHERE b.BRIEF_ID IS NULL
);

SELECT
  'SECTION_COMMAND_BRIEF_FRESHNESS_TARGETS' AS CHECK_NAME,
  COUNT_IF(COALESCE(IS_STALE, FALSE)) AS STALE_ROWS,
  IFF(COUNT_IF(COALESCE(IS_STALE, FALSE)) = 0, 'PASS', 'WARN') AS STATUS
FROM MART_SECTION_COMMAND_BRIEF
WHERE SNAPSHOT_TS = (SELECT MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_BRIEF);

SELECT
  'SECTION_COMMAND_BRIEF_CANONICAL_WINDOWS' AS CHECK_NAME,
  COUNT(*) AS MISSING_WINDOWS,
  IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS STATUS
FROM (
  SELECT s.SECTION_NAME, w.WINDOW_DAYS
  FROM (
    SELECT COLUMN1::VARCHAR AS SECTION_NAME
    FROM VALUES
      ('Executive Landing'), ('DBA Control Room'), ('Alert Center'),
      ('Cost & Contract'), ('Workload Operations'), ('Security Monitoring')
  ) s
  CROSS JOIN (
    SELECT COLUMN1::NUMBER AS WINDOW_DAYS FROM VALUES (1), (7), (14), (30), (60), (90)
  ) w
  LEFT JOIN MART_SECTION_COMMAND_BRIEF b
    ON b.SECTION_NAME = s.SECTION_NAME
   AND b.WINDOW_DAYS = w.WINDOW_DAYS
   AND b.SNAPSHOT_TS = (SELECT MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_BRIEF)
  WHERE b.BRIEF_ID IS NULL
);

SELECT
  'SECTION_COMMAND_BRIEF_SOURCE_COVERAGE_FIELDS' AS CHECK_NAME,
  COUNT_IF(
    REQUIRED_SOURCE_COUNT IS NULL
    OR AVAILABLE_REQUIRED_SOURCE_COUNT IS NULL
    OR REQUIRED_MISSING_SOURCE_COUNT IS NULL
    OR REQUIRED_STALE_SOURCE_COUNT IS NULL
    OR OPTIONAL_SOURCE_COUNT IS NULL
    OR AVAILABLE_OPTIONAL_SOURCE_COUNT IS NULL
    OR OPTIONAL_MISSING_SOURCE_COUNT IS NULL
    OR OPTIONAL_STALE_SOURCE_COUNT IS NULL
    OR SOURCE_COVERAGE_PCT IS NULL
    OR DATA_AVAILABILITY_STATE IS NULL
  ) AS MISSING_COVERAGE_ROWS,
  IFF(COUNT_IF(
    REQUIRED_SOURCE_COUNT IS NULL
    OR AVAILABLE_REQUIRED_SOURCE_COUNT IS NULL
    OR REQUIRED_MISSING_SOURCE_COUNT IS NULL
    OR REQUIRED_STALE_SOURCE_COUNT IS NULL
    OR OPTIONAL_SOURCE_COUNT IS NULL
    OR AVAILABLE_OPTIONAL_SOURCE_COUNT IS NULL
    OR OPTIONAL_MISSING_SOURCE_COUNT IS NULL
    OR OPTIONAL_STALE_SOURCE_COUNT IS NULL
    OR SOURCE_COVERAGE_PCT IS NULL
    OR DATA_AVAILABILITY_STATE IS NULL
  ) = 0, 'PASS', 'FAIL') AS STATUS
FROM MART_SECTION_COMMAND_BRIEF
WHERE SNAPSHOT_TS = (SELECT MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_BRIEF);

SELECT
  'SECTION_COMMAND_BRIEF_TYPED_METRICS' AS CHECK_NAME,
  COUNT_IF(METRIC_NUMERIC_VALUE IS NOT NULL OR METRIC_TEXT_VALUE IS NOT NULL) AS TYPED_METRICS,
  IFF(COUNT_IF(METRIC_NUMERIC_VALUE IS NOT NULL OR METRIC_TEXT_VALUE IS NOT NULL) > 0, 'PASS', 'FAIL') AS STATUS
FROM MART_SECTION_COMMAND_METRIC
WHERE SNAPSHOT_TS = (SELECT MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_METRIC);

SELECT
  'SECTION_COMMAND_BRIEF_METRIC_AVAILABILITY' AS CHECK_NAME,
  COUNT_IF(IS_AVAILABLE IS NULL OR AVAILABILITY_STATE IS NULL OR SOURCE_KEY IS NULL) AS METRICS_MISSING_AVAILABILITY,
  IFF(COUNT_IF(IS_AVAILABLE IS NULL OR AVAILABILITY_STATE IS NULL OR SOURCE_KEY IS NULL) = 0, 'PASS', 'FAIL') AS STATUS
FROM MART_SECTION_COMMAND_METRIC
WHERE SNAPSHOT_TS = (SELECT MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_METRIC);

SELECT
  'SECTION_COMMAND_BRIEF_ROUTE_KEYS' AS CHECK_NAME,
  COUNT_IF(ROUTE_KEY IS NULL OR CTA_LABEL IS NULL) AS MISSING_ROUTE_ROWS,
  IFF(COUNT_IF(ROUTE_KEY IS NULL OR CTA_LABEL IS NULL) = 0, 'PASS', 'FAIL') AS STATUS
FROM MART_SECTION_COMMAND_ACTION
WHERE SNAPSHOT_TS = (SELECT MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_ACTION);

SELECT
  'SECTION_DECISION_CURRENT_ONE_ACTIVE_ROW_PER_KEY' AS CHECK_NAME,
  COUNT(*) AS DUPLICATE_ACTIVE_KEYS,
  IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS STATUS
FROM (
  SELECT SECTION_NAME, COMPANY, ENVIRONMENT, WINDOW_DAYS
  FROM MART_SECTION_DECISION_CURRENT
  WHERE COALESCE(IS_ACTIVE, TRUE)
  GROUP BY SECTION_NAME, COMPANY, ENVIRONMENT, WINDOW_DAYS
  HAVING COUNT(*) > 1
);

SELECT
  'SECTION_DECISION_CURRENT_FLAT_ONE_ACTIVE_ROW_PER_KEY' AS CHECK_NAME,
  COUNT(*) AS DUPLICATE_ACTIVE_KEYS,
  IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS STATUS
FROM (
  SELECT SECTION_NAME, COMPANY, ENVIRONMENT, WINDOW_DAYS
  FROM MART_SECTION_DECISION_CURRENT_FLAT
  WHERE COALESCE(IS_ACTIVE, TRUE)
  GROUP BY SECTION_NAME, COMPANY, ENVIRONMENT, WINDOW_DAYS
  HAVING COUNT(*) > 1
);

SELECT
  'SECTION_DECISION_CURRENT_FLAT_ACTIVE_MATCHES_CURRENT' AS CHECK_NAME,
  COUNT(*) AS MISMATCHED_ACTIVE_KEYS,
  IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS STATUS
FROM (
  SELECT SECTION_NAME, COMPANY, ENVIRONMENT, WINDOW_DAYS
  FROM MART_SECTION_DECISION_CURRENT
  WHERE COALESCE(IS_ACTIVE, TRUE)
  MINUS
  SELECT SECTION_NAME, COMPANY, ENVIRONMENT, WINDOW_DAYS
  FROM MART_SECTION_DECISION_CURRENT_FLAT
  WHERE COALESCE(IS_ACTIVE, TRUE)
  UNION ALL
  SELECT SECTION_NAME, COMPANY, ENVIRONMENT, WINDOW_DAYS
  FROM MART_SECTION_DECISION_CURRENT_FLAT
  WHERE COALESCE(IS_ACTIVE, TRUE)
  MINUS
  SELECT SECTION_NAME, COMPANY, ENVIRONMENT, WINDOW_DAYS
  FROM MART_SECTION_DECISION_CURRENT
  WHERE COALESCE(IS_ACTIVE, TRUE)
);

SELECT
  'SECTION_DECISION_CURRENT_FLAT_REQUIRED_FIELDS' AS CHECK_NAME,
  COUNT_IF(
    SECTION_NAME_NORM IS NULL
    OR COMPANY_NORM IS NULL
    OR ENVIRONMENT_NORM IS NULL
    OR WINDOW_DAYS_NORM IS NULL
    OR BRIEF_ID IS NULL
    OR PACKET_BYTES IS NULL
    OR PACKET_BYTES >= 100000
  ) AS INVALID_ACTIVE_FLAT_ROWS,
  IFF(COUNT_IF(
    SECTION_NAME_NORM IS NULL
    OR COMPANY_NORM IS NULL
    OR ENVIRONMENT_NORM IS NULL
    OR WINDOW_DAYS_NORM IS NULL
    OR BRIEF_ID IS NULL
    OR PACKET_BYTES IS NULL
    OR PACKET_BYTES >= 100000
  ) = 0, 'PASS', 'FAIL') AS STATUS
FROM MART_SECTION_DECISION_CURRENT_FLAT
WHERE COALESCE(IS_ACTIVE, TRUE);

SELECT
  'SECTION_DECISION_CURRENT_PACKET_COVERAGE' AS CHECK_NAME,
  COUNT(DISTINCT SECTION_NAME) AS OBSERVED_SECTIONS,
  IFF(COUNT(DISTINCT SECTION_NAME) = 6 AND COUNT_IF(DECISION_PACKET IS NULL) = 0, 'PASS', 'FAIL') AS STATUS
FROM MART_SECTION_DECISION_CURRENT
WHERE COALESCE(IS_ACTIVE, TRUE);

SELECT
  'SECTION_DECISION_CURRENT_PACKET_SOURCES' AS CHECK_NAME,
  COUNT_IF(DECISION_PACKET:"SOURCES" IS NULL OR ARRAY_SIZE(DECISION_PACKET:"SOURCES") = 0) AS PACKETS_WITHOUT_SOURCES,
  IFF(COUNT_IF(DECISION_PACKET:"SOURCES" IS NULL OR ARRAY_SIZE(DECISION_PACKET:"SOURCES") = 0) = 0, 'PASS', 'FAIL') AS STATUS
FROM MART_SECTION_DECISION_CURRENT
WHERE COALESCE(IS_ACTIVE, TRUE);

WITH required_packet_fields AS (
  SELECT COLUMN1::VARCHAR AS FIELD_NAME
  FROM VALUES
    ('ACCOUNT_BILLED_CREDITS'), ('ACCOUNT_BILLED_COST_USD'), ('ACCOUNT_USED_CREDITS'),
    ('COMPUTE_CREDITS'), ('CLOUD_SERVICES_CREDITS'), ('CLOUD_SERVICES_ADJUSTMENT'),
    ('ACCOUNT_CLOUD_SERVICES_ADJUSTMENT'), ('WAREHOUSE_CREDITS'), ('WAREHOUSE_COST_ESTIMATE_USD'),
    ('WAREHOUSE_COST_USD'), ('SERVICE_OTHER_CREDITS'), ('SERVICE_OTHER_COST_USD'),
    ('BILLING_BRIDGE_DELTA_CREDITS'), ('BILLING_BRIDGE_DELTA_USD'), ('BILLING_BRIDGE_STATUS'),
    ('CORTEX_AI_CREDITS'), ('CORTEX_AI_COST_USD'), ('BILLING_RECONCILIATION_STATUS'),
    ('BILLING_WINDOW_START'), ('BILLING_WINDOW_END'), ('BILLING_WINDOW_COMPLETE'),
    ('BILLING_SOURCE_FRESHNESS_TS'), ('BILLING_LATENCY_NOTE'),
    ('BILLING_RECONCILIATION_WINDOW_START'), ('BILLING_RECONCILIATION_WINDOW_END'),
    ('BILLING_RECONCILIATION_FRESHNESS'), ('SPEND_MOVEMENT_PCT'), ('FORECAST_RUN_RATE_USD')
),
missing_packet_fields AS (
  SELECT p.SECTION_NAME, p.COMPANY, p.ENVIRONMENT, p.WINDOW_DAYS, r.FIELD_NAME
  FROM MART_SECTION_DECISION_CURRENT p
  CROSS JOIN required_packet_fields r
  WHERE COALESCE(p.IS_ACTIVE, TRUE)
    AND NOT ARRAY_CONTAINS(r.FIELD_NAME::VARIANT, OBJECT_KEYS(p.DECISION_PACKET))
)
SELECT
  'SECTION_DECISION_CURRENT_COST_FORMULA_PACKET_FIELDS' AS CHECK_NAME,
  COUNT(*) AS MISSING_PACKET_FIELDS,
  IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS STATUS
FROM missing_packet_fields;

WITH required_flat_columns AS (
  SELECT COLUMN1::VARCHAR AS COLUMN_NAME
  FROM VALUES
    ('ACCOUNT_BILLED_CREDITS'), ('ACCOUNT_BILLED_COST_USD'), ('ACCOUNT_USED_CREDITS'),
    ('COMPUTE_CREDITS'), ('CLOUD_SERVICES_CREDITS'), ('CLOUD_SERVICES_ADJUSTMENT'),
    ('ACCOUNT_CLOUD_SERVICES_ADJUSTMENT'), ('WAREHOUSE_CREDITS'), ('WAREHOUSE_COST_ESTIMATE_USD'),
    ('WAREHOUSE_COST_USD'), ('SERVICE_OTHER_CREDITS'), ('SERVICE_OTHER_COST_USD'),
    ('BILLING_BRIDGE_DELTA_CREDITS'), ('BILLING_BRIDGE_DELTA_USD'), ('BILLING_BRIDGE_STATUS'),
    ('CORTEX_AI_CREDITS'), ('CORTEX_AI_COST_USD'), ('BILLING_RECONCILIATION_STATUS'),
    ('BILLING_WINDOW_START'), ('BILLING_WINDOW_END'), ('BILLING_WINDOW_COMPLETE'),
    ('BILLING_SOURCE_FRESHNESS_TS'), ('BILLING_LATENCY_NOTE'),
    ('BILLING_RECONCILIATION_WINDOW_START'), ('BILLING_RECONCILIATION_WINDOW_END'),
    ('BILLING_RECONCILIATION_FRESHNESS'), ('SPEND_MOVEMENT_PCT'), ('FORECAST_RUN_RATE_USD')
)
SELECT
  'SECTION_DECISION_CURRENT_FLAT_COST_FORMULA_COLUMNS' AS CHECK_NAME,
  COUNT(*) AS MISSING_FLAT_COLUMNS,
  IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS STATUS
FROM required_flat_columns r
LEFT JOIN INFORMATION_SCHEMA.COLUMNS c
  ON UPPER(c.TABLE_SCHEMA) = UPPER(CURRENT_SCHEMA())
 AND UPPER(c.TABLE_NAME) = 'MART_SECTION_DECISION_CURRENT_FLAT'
 AND UPPER(c.COLUMN_NAME) = r.COLUMN_NAME
WHERE c.COLUMN_NAME IS NULL;

WITH current_packets AS (
  SELECT
    SECTION_NAME,
    COMPANY,
    ENVIRONMENT,
    WINDOW_DAYS,
    BRIEF_ID,
    DECISION_PACKET
  FROM MART_SECTION_DECISION_CURRENT
  WHERE COALESCE(IS_ACTIVE, TRUE)
),
source_rows AS (
  SELECT
    SECTION_NAME,
    COMPANY,
    ENVIRONMENT,
    WINDOW_DAYS,
    BRIEF_ID,
    src.value:"SOURCE_KEY"::VARCHAR AS SOURCE_KEY,
    src.value:"SOURCE_OBJECT"::VARCHAR AS SOURCE_OBJECT,
    COALESCE(src.value:"REQUIRED"::BOOLEAN, FALSE) AS REQUIRED,
    COALESCE(src.value:"AVAILABLE"::BOOLEAN, FALSE) AS AVAILABLE,
    COALESCE(src.value:"IS_STALE"::BOOLEAN, FALSE) AS IS_STALE
  FROM current_packets,
  LATERAL FLATTEN(INPUT => DECISION_PACKET:"SOURCES") src
),
flattened AS (
  SELECT
    SECTION_NAME,
    COMPANY,
    ENVIRONMENT,
    WINDOW_DAYS,
    BRIEF_ID,
    COUNT(*) AS SOURCE_ROW_COUNT,
    COUNT_IF(REQUIRED) AS REQUIRED_SOURCE_COUNT,
    COUNT_IF(REQUIRED AND AVAILABLE) AS AVAILABLE_REQUIRED_SOURCE_COUNT,
    COUNT_IF(REQUIRED AND NOT AVAILABLE) AS REQUIRED_MISSING_SOURCE_COUNT,
    COUNT_IF(REQUIRED AND IS_STALE) AS REQUIRED_STALE_SOURCE_COUNT,
    COUNT_IF(NOT REQUIRED) AS OPTIONAL_SOURCE_COUNT,
    COUNT_IF(NOT REQUIRED AND NOT AVAILABLE) AS OPTIONAL_MISSING_SOURCE_COUNT,
    COUNT_IF(NOT REQUIRED AND IS_STALE) AS OPTIONAL_STALE_SOURCE_COUNT,
    COUNT(*) - COUNT(DISTINCT SOURCE_KEY) AS DUPLICATE_SOURCE_KEY_COUNT
  FROM source_rows
  GROUP BY SECTION_NAME, COMPANY, ENVIRONMENT, WINDOW_DAYS, BRIEF_ID
)
SELECT
  'SECTION_DECISION_CURRENT_SOURCE_COUNTER_CONSISTENCY' AS CHECK_NAME,
  COUNT_IF(
    COALESCE(f.SOURCE_ROW_COUNT, 0) = 0
    OR COALESCE(f.REQUIRED_SOURCE_COUNT, 0) <= 0
    OR COALESCE(TRY_TO_NUMBER(p.DECISION_PACKET:"REQUIRED_SOURCE_COUNT"::VARCHAR), -1) <> COALESCE(f.REQUIRED_SOURCE_COUNT, -2)
    OR COALESCE(TRY_TO_NUMBER(p.DECISION_PACKET:"AVAILABLE_REQUIRED_SOURCE_COUNT"::VARCHAR), -1) <> COALESCE(f.AVAILABLE_REQUIRED_SOURCE_COUNT, -2)
    OR COALESCE(TRY_TO_NUMBER(p.DECISION_PACKET:"REQUIRED_MISSING_SOURCE_COUNT"::VARCHAR), -1) <> COALESCE(f.REQUIRED_MISSING_SOURCE_COUNT, -2)
    OR COALESCE(TRY_TO_NUMBER(p.DECISION_PACKET:"REQUIRED_STALE_SOURCE_COUNT"::VARCHAR), -1) <> COALESCE(f.REQUIRED_STALE_SOURCE_COUNT, -2)
    OR COALESCE(TRY_TO_NUMBER(p.DECISION_PACKET:"OPTIONAL_SOURCE_COUNT"::VARCHAR), -1) <> COALESCE(f.OPTIONAL_SOURCE_COUNT, -2)
    OR COALESCE(TRY_TO_NUMBER(p.DECISION_PACKET:"OPTIONAL_MISSING_SOURCE_COUNT"::VARCHAR), -1) <> COALESCE(f.OPTIONAL_MISSING_SOURCE_COUNT, -2)
    OR COALESCE(TRY_TO_NUMBER(p.DECISION_PACKET:"OPTIONAL_STALE_SOURCE_COUNT"::VARCHAR), -1) <> COALESCE(f.OPTIONAL_STALE_SOURCE_COUNT, -2)
    OR COALESCE(f.DUPLICATE_SOURCE_KEY_COUNT, 0) > 0
  ) AS COUNTER_MISMATCHES,
  IFF(COUNT_IF(
    COALESCE(f.SOURCE_ROW_COUNT, 0) = 0
    OR COALESCE(f.REQUIRED_SOURCE_COUNT, 0) <= 0
    OR COALESCE(TRY_TO_NUMBER(p.DECISION_PACKET:"REQUIRED_SOURCE_COUNT"::VARCHAR), -1) <> COALESCE(f.REQUIRED_SOURCE_COUNT, -2)
    OR COALESCE(TRY_TO_NUMBER(p.DECISION_PACKET:"AVAILABLE_REQUIRED_SOURCE_COUNT"::VARCHAR), -1) <> COALESCE(f.AVAILABLE_REQUIRED_SOURCE_COUNT, -2)
    OR COALESCE(TRY_TO_NUMBER(p.DECISION_PACKET:"REQUIRED_MISSING_SOURCE_COUNT"::VARCHAR), -1) <> COALESCE(f.REQUIRED_MISSING_SOURCE_COUNT, -2)
    OR COALESCE(TRY_TO_NUMBER(p.DECISION_PACKET:"REQUIRED_STALE_SOURCE_COUNT"::VARCHAR), -1) <> COALESCE(f.REQUIRED_STALE_SOURCE_COUNT, -2)
    OR COALESCE(TRY_TO_NUMBER(p.DECISION_PACKET:"OPTIONAL_SOURCE_COUNT"::VARCHAR), -1) <> COALESCE(f.OPTIONAL_SOURCE_COUNT, -2)
    OR COALESCE(TRY_TO_NUMBER(p.DECISION_PACKET:"OPTIONAL_MISSING_SOURCE_COUNT"::VARCHAR), -1) <> COALESCE(f.OPTIONAL_MISSING_SOURCE_COUNT, -2)
    OR COALESCE(TRY_TO_NUMBER(p.DECISION_PACKET:"OPTIONAL_STALE_SOURCE_COUNT"::VARCHAR), -1) <> COALESCE(f.OPTIONAL_STALE_SOURCE_COUNT, -2)
    OR COALESCE(f.DUPLICATE_SOURCE_KEY_COUNT, 0) > 0
  ) = 0, 'PASS', 'FAIL') AS STATUS
FROM current_packets p
LEFT JOIN flattened f
  ON f.SECTION_NAME = p.SECTION_NAME
 AND f.COMPANY = p.COMPANY
 AND f.ENVIRONMENT = p.ENVIRONMENT
 AND f.WINDOW_DAYS = p.WINDOW_DAYS
 AND f.BRIEF_ID = p.BRIEF_ID;

WITH current_packets AS (
  SELECT SECTION_NAME, COMPANY, ENVIRONMENT, WINDOW_DAYS, BRIEF_ID, DECISION_PACKET
  FROM MART_SECTION_DECISION_CURRENT
  WHERE COALESCE(IS_ACTIVE, TRUE)
),
source_rollup AS (
  SELECT
    p.SECTION_NAME,
    p.COMPANY,
    p.ENVIRONMENT,
    p.WINDOW_DAYS,
    p.BRIEF_ID,
    LISTAGG(src.value:"SOURCE_OBJECT"::VARCHAR, '; ') WITHIN GROUP (ORDER BY src.value:"SOURCE_KEY"::VARCHAR) AS DERIVED_SOURCE_OBJECTS
  FROM current_packets p,
  LATERAL FLATTEN(INPUT => p.DECISION_PACKET:"SOURCES") src
  GROUP BY p.SECTION_NAME, p.COMPANY, p.ENVIRONMENT, p.WINDOW_DAYS, p.BRIEF_ID
)
SELECT
  'SECTION_DECISION_PARENT_SOURCE_OBJECTS_MATCH_SOURCES' AS CHECK_NAME,
  COUNT_IF(COALESCE(p.DECISION_PACKET:"SOURCE_OBJECTS"::VARCHAR, '') <> COALESCE(r.DERIVED_SOURCE_OBJECTS, '')) AS SOURCE_OBJECT_MISMATCHES,
  IFF(COUNT_IF(COALESCE(p.DECISION_PACKET:"SOURCE_OBJECTS"::VARCHAR, '') <> COALESCE(r.DERIVED_SOURCE_OBJECTS, '')) = 0, 'PASS', 'FAIL') AS STATUS
FROM current_packets p
LEFT JOIN source_rollup r
  ON r.SECTION_NAME = p.SECTION_NAME
 AND r.COMPANY = p.COMPANY
 AND r.ENVIRONMENT = p.ENVIRONMENT
 AND r.WINDOW_DAYS = p.WINDOW_DAYS
 AND r.BRIEF_ID = p.BRIEF_ID;

SELECT
  'SECTION_DECISION_LAST_GOOD_PACKET_COVERAGE' AS CHECK_NAME,
  COUNT(DISTINCT SECTION_NAME) AS OBSERVED_SECTIONS,
  IFF(COUNT(DISTINCT SECTION_NAME) = 6 AND COUNT_IF(DECISION_PACKET IS NULL) = 0, 'PASS', 'WARN') AS STATUS
FROM MART_SECTION_DECISION_LAST_GOOD;

SELECT
  'SECTION_COMMAND_SOURCE_ROWS' AS CHECK_NAME,
  COUNT(*) AS SOURCE_ROWS,
  IFF(COUNT(*) > 0 AND COUNT_IF(REQUIRED IS NULL OR AVAILABLE IS NULL) = 0, 'PASS', 'FAIL') AS STATUS
FROM MART_SECTION_COMMAND_SOURCE
WHERE SNAPSHOT_TS = (SELECT MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_SOURCE);

SELECT
  'SECTION_COMMAND_SOURCE_CONFIG_UNIQUE_SOURCE_KEYS' AS CHECK_NAME,
  COUNT(*) AS DUPLICATE_SOURCE_KEYS,
  IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS STATUS
FROM (
  SELECT SECTION_NAME, SOURCE_KEY
  FROM OVERWATCH_SECTION_COMMAND_SOURCE_CONFIG
  GROUP BY SECTION_NAME, SOURCE_KEY
  HAVING COUNT(*) > 1
);

SELECT
  'SECTION_COMMAND_METRIC_SOURCE_KEYS_CONFIGURED' AS CHECK_NAME,
  COUNT(*) AS UNCONFIGURED_METRIC_SOURCE_KEYS,
  IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS STATUS
FROM MART_SECTION_COMMAND_METRIC m
LEFT JOIN OVERWATCH_SECTION_COMMAND_SOURCE_CONFIG cfg
  ON cfg.SECTION_NAME = m.SECTION_NAME
 AND cfg.SOURCE_KEY = m.SOURCE_KEY
WHERE m.SNAPSHOT_TS = (SELECT MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_METRIC)
  AND cfg.SOURCE_KEY IS NULL;

WITH current_packets AS (
  SELECT SECTION_NAME, COMPANY, ENVIRONMENT, WINDOW_DAYS, BRIEF_ID, DECISION_PACKET
  FROM MART_SECTION_DECISION_CURRENT
  WHERE COALESCE(IS_ACTIVE, TRUE)
),
source_rows AS (
  SELECT
    p.SECTION_NAME,
    p.COMPANY,
    p.ENVIRONMENT,
    p.WINDOW_DAYS,
    p.BRIEF_ID,
    src.value:"SOURCE_KEY"::VARCHAR AS SOURCE_KEY
  FROM current_packets p,
  LATERAL FLATTEN(INPUT => p.DECISION_PACKET:"SOURCES") src
)
SELECT
  'SECTION_DECISION_CURRENT_SOURCE_KEYS_CONFIGURED' AS CHECK_NAME,
  COUNT(*) AS UNCONFIGURED_PACKET_SOURCE_KEYS,
  IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS STATUS
FROM source_rows s
LEFT JOIN OVERWATCH_SECTION_COMMAND_SOURCE_CONFIG cfg
  ON cfg.SECTION_NAME = s.SECTION_NAME
 AND cfg.SOURCE_KEY = s.SOURCE_KEY
WHERE cfg.SOURCE_KEY IS NULL;

SELECT
  'SECTION_COMMAND_SOURCE_ENVIRONMENT_METADATA' AS CHECK_NAME,
  COUNT_IF(
    (LOWER(COALESCE(ENVIRONMENT_MODE, 'not_applicable')) = 'exact' AND NOT COALESCE(SUPPORTS_ENVIRONMENT, FALSE))
    OR (LOWER(COALESCE(ENVIRONMENT_MODE, 'not_applicable')) <> 'exact' AND COALESCE(SUPPORTS_ENVIRONMENT, FALSE))
  ) AS ENVIRONMENT_METADATA_MISMATCHES,
  IFF(COUNT_IF(
    (LOWER(COALESCE(ENVIRONMENT_MODE, 'not_applicable')) = 'exact' AND NOT COALESCE(SUPPORTS_ENVIRONMENT, FALSE))
    OR (LOWER(COALESCE(ENVIRONMENT_MODE, 'not_applicable')) <> 'exact' AND COALESCE(SUPPORTS_ENVIRONMENT, FALSE))
  ) = 0, 'PASS', 'FAIL') AS STATUS
FROM OVERWATCH_SECTION_COMMAND_SOURCE_CONFIG;

SELECT
  'SECTION_COMMAND_SOURCE_TRUST_GAPS' AS CHECK_NAME,
  COUNT_IF(REQUIRED AND NOT AVAILABLE) AS REQUIRED_SOURCE_GAPS,
  IFF(COUNT_IF(REQUIRED AND NOT AVAILABLE) = 0, 'PASS', 'WARN') AS STATUS
FROM MART_SECTION_COMMAND_SOURCE
WHERE SNAPSHOT_TS = (SELECT MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_SOURCE);

SELECT
  'SECTION_COMMAND_REQUIRED_METRIC_KEYS' AS CHECK_NAME,
  COUNT(*) AS MISSING_KEYS,
  IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS STATUS
FROM (
  SELECT * FROM VALUES
    ('Executive Landing','platform_health'), ('Executive Landing','spend_movement_pct'), ('Executive Landing','critical_high_issues'), ('Executive Landing','open_actions'),
    ('Executive Landing','cortex_spend'), ('Executive Landing','cortex_risk'), ('Executive Landing','operational_risk'), ('Executive Landing','security_risk'),
    ('Executive Landing','production_readiness'), ('Executive Landing','data_trust'), ('Executive Landing','verified_value'), ('Executive Landing','monitoring_overhead'),
    ('DBA Control Room','failed_queries'), ('DBA Control Room','pipeline_failures'), ('DBA Control Room','queue_pressure'), ('DBA Control Room','cost_24h'),
    ('DBA Control Room','cortex_cost'), ('DBA Control Room','security_warnings'), ('DBA Control Room','recent_changes'), ('DBA Control Room','overdue_actions'),
    ('DBA Control Room','hottest_warehouse'), ('DBA Control Room','top_dba_risk'),
    ('Alert Center','active_alerts'), ('Alert Center','critical_high'), ('Alert Center','overdue_alerts'), ('Alert Center','cortex_predictive'),
    ('Alert Center','cost_alerts'), ('Alert Center','reliability_alerts'), ('Alert Center','security_alerts'), ('Alert Center','notification_failures'),
    ('Alert Center','unassigned_alerts'), ('Alert Center','open_action_queue'),
    ('Cost & Contract','total_spend'), ('Cost & Contract','spend_movement_pct'), ('Cost & Contract','forecast_run_rate'), ('Cost & Contract','cortex_spend_share'),
    ('Cost & Contract','cortex_spend'), ('Cost & Contract','cortex_predictive_alerts'), ('Cost & Contract','budget_contract_risk'), ('Cost & Contract','top_cost_driver'),
    ('Cost & Contract','verified_savings'), ('Cost & Contract','unverified_savings'), ('Cost & Contract','open_cost_actions'),
    ('Workload Operations','failed_queries'), ('Workload Operations','pipeline_failures'), ('Workload Operations','queue_blocked_pressure'), ('Workload Operations','sla_risk'),
    ('Workload Operations','spill_bytes'), ('Workload Operations','long_running_queries'), ('Workload Operations','hottest_warehouse'), ('Workload Operations','recent_workload_changes'),
    ('Workload Operations','suspended_tasks'), ('Workload Operations','copy_load_failures'),
    ('Security Monitoring','failed_logins'), ('Security Monitoring','mfa_gaps'), ('Security Monitoring','risky_grants'), ('Security Monitoring','sharing_exposure'),
    ('Security Monitoring','privilege_changes'), ('Security Monitoring','security_alerts'), ('Security Monitoring','access_changes'), ('Security Monitoring','unassigned_findings'),
    ('Security Monitoring','overdue_security_actions'), ('Security Monitoring','owner_coverage')
  AS required(SECTION_NAME, METRIC_KEY)
  LEFT JOIN MART_SECTION_COMMAND_METRIC m
    ON m.SECTION_NAME = required.SECTION_NAME
   AND m.METRIC_KEY = required.METRIC_KEY
   AND m.SNAPSHOT_TS = (SELECT MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_METRIC)
  WHERE m.METRIC_KEY IS NULL
);
