-- -----------------------------------------------------------------------------
-- 7. Smoke checks
-- -----------------------------------------------------------------------------

SHOW TASKS LIKE 'OVERWATCH_%' IN SCHEMA DBA_MAINT_DB.OVERWATCH;

SELECT 'FACT_WAREHOUSE_HOURLY' AS TABLE_NAME, COUNT(*) AS ROWS_LOADED FROM FACT_WAREHOUSE_HOURLY
UNION ALL
SELECT 'FACT_QUERY_HOURLY', COUNT(*) FROM FACT_QUERY_HOURLY
UNION ALL
SELECT 'FACT_QUERY_DETAIL_RECENT', COUNT(*) FROM FACT_QUERY_DETAIL_RECENT
UNION ALL
SELECT 'DIM_TABLE_SNAPSHOT', COUNT(*) FROM DIM_TABLE_SNAPSHOT
UNION ALL
SELECT 'FACT_COPY_LOAD_DAILY', COUNT(*) FROM FACT_COPY_LOAD_DAILY
UNION ALL
SELECT 'FACT_COST_DAILY', COUNT(*) FROM FACT_COST_DAILY
UNION ALL
SELECT 'FACT_COST_SOURCE_HEALTH_DAILY', COUNT(*) FROM FACT_COST_SOURCE_HEALTH_DAILY
UNION ALL
SELECT 'FACT_COST_MONITORING_SIGNAL', COUNT(*) FROM FACT_COST_MONITORING_SIGNAL
UNION ALL
SELECT 'FACT_COST_INCIDENT_TIMELINE', COUNT(*) FROM FACT_COST_INCIDENT_TIMELINE
UNION ALL
SELECT 'MART_EXECUTIVE_OBSERVABILITY', COUNT(*) FROM MART_EXECUTIVE_OBSERVABILITY
UNION ALL
SELECT 'MART_DBA_CONTROL_ROOM', COUNT(*) FROM MART_DBA_CONTROL_ROOM
UNION ALL
SELECT 'MART_SECTION_COMMAND_BRIEF', COUNT(*) FROM MART_SECTION_COMMAND_BRIEF
UNION ALL
SELECT 'MART_SECTION_COMMAND_METRIC', COUNT(*) FROM MART_SECTION_COMMAND_METRIC
UNION ALL
SELECT 'MART_SECTION_COMMAND_EXCEPTION', COUNT(*) FROM MART_SECTION_COMMAND_EXCEPTION
UNION ALL
SELECT 'MART_SECTION_COMMAND_ACTION', COUNT(*) FROM MART_SECTION_COMMAND_ACTION
UNION ALL
SELECT 'MART_DATA_TRUST_SUMMARY', COUNT(*) FROM MART_DATA_TRUST_SUMMARY
UNION ALL
SELECT 'MART_OPERATIONAL_OWNER_COVERAGE', COUNT(*) FROM MART_OPERATIONAL_OWNER_COVERAGE
UNION ALL
SELECT 'MART_EXECUTIVE_VALUE_LEDGER', COUNT(*) FROM MART_EXECUTIVE_VALUE_LEDGER
UNION ALL
SELECT 'MART_APP_OBSERVABILITY_SUMMARY', COUNT(*) FROM MART_APP_OBSERVABILITY_SUMMARY
UNION ALL
SELECT 'MART_PRODUCTION_READINESS_SUMMARY', COUNT(*) FROM MART_PRODUCTION_READINESS_SUMMARY
UNION ALL
SELECT 'MART_EXECUTIVE_SCORECARD_SUMMARY', COUNT(*) FROM MART_EXECUTIVE_SCORECARD_SUMMARY
UNION ALL
SELECT 'MART_EXECUTIVE_FORECAST_SUMMARY', COUNT(*) FROM MART_EXECUTIVE_FORECAST_SUMMARY
UNION ALL
SELECT 'MART_CHANGE_INTELLIGENCE_SUMMARY', COUNT(*) FROM MART_CHANGE_INTELLIGENCE_SUMMARY
UNION ALL
SELECT 'MART_CLOSED_LOOP_OPERATIONS_SUMMARY', COUNT(*) FROM MART_CLOSED_LOOP_OPERATIONS_SUMMARY
UNION ALL
SELECT 'MART_COMMAND_CENTER_SUMMARY', COUNT(*) FROM MART_COMMAND_CENTER_SUMMARY;




CALL SP_OVERWATCH_LOAD_HOURLY_UNIT('WAREHOUSE_HOURLY', NULL, NULL);
CALL SP_OVERWATCH_LOAD_HOURLY_UNIT('QUERY_HOURLY', NULL, NULL);
CALL SP_OVERWATCH_LOAD_HOURLY_UNIT('QUERY_DETAIL', NULL, NULL);
CALL SP_OVERWATCH_LOAD_HOURLY_UNIT('OBJECT_CHANGE', NULL, NULL);
CALL SP_OVERWATCH_LOAD_HOURLY_UNIT('TASK_RUN', NULL, NULL);
CALL SP_OVERWATCH_LOAD_HOURLY_UNIT('PROCEDURE_RUN', NULL, NULL);
CALL SP_OVERWATCH_LOAD_HOURLY_UNIT('SNAPSHOTS', NULL, NULL);
CALL SP_OVERWATCH_LOAD_HOURLY_UNIT('TASK_CRITICAL_PATH', NULL, NULL);
CALL SP_OVERWATCH_LOAD_CORTEX();
CALL SP_OVERWATCH_REFRESH_CONTROL_ROOM();
CALL SP_OVERWATCH_REFRESH_COST_MONITORING();
CALL SP_OVERWATCH_LOAD_DAILY();
CALL SP_OVERWATCH_REFRESH_EXECUTIVE_OBSERVABILITY();
CALL SP_OVERWATCH_REFRESH_ENTERPRISE_OPERATING_MODEL();
CALL SP_OVERWATCH_REFRESH_PRODUCTION_READINESS();
CALL SP_OVERWATCH_REFRESH_EXECUTIVE_SCORECARD();
CALL SP_OVERWATCH_REFRESH_FORECASTING();
CALL SP_OVERWATCH_REFRESH_CHANGE_INTELLIGENCE();
CALL SP_OVERWATCH_REFRESH_CLOSED_LOOP_OPERATIONS();
CALL SP_OVERWATCH_REFRESH_COMMAND_CENTER();
CALL SP_OVERWATCH_REFRESH_SECTION_COMMAND_BRIEFS();

SELECT
  'SECTION_COMMAND_BRIEF_SECTION_COVERAGE' AS CHECK_NAME,
  COUNT(DISTINCT SECTION_NAME) AS OBSERVED_VALUE,
  IFF(COUNT(DISTINCT SECTION_NAME) = 6, 'PASS', 'FAIL') AS STATUS
FROM MART_SECTION_COMMAND_BRIEF
WHERE SNAPSHOT_TS = (SELECT MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_BRIEF);

SELECT
  'SECTION_COMMAND_BRIEF_PARENT_HAS_METRICS' AS CHECK_NAME,
  COUNT_IF(metric_count = 0) AS PARENTS_WITHOUT_METRICS,
  IFF(COUNT_IF(metric_count = 0) = 0, 'PASS', 'FAIL') AS STATUS
FROM (
  SELECT b.BRIEF_ID, COUNT(m.BRIEF_ID) AS metric_count
  FROM MART_SECTION_COMMAND_BRIEF b
  LEFT JOIN MART_SECTION_COMMAND_METRIC m ON m.BRIEF_ID = b.BRIEF_ID
  WHERE b.SNAPSHOT_TS = (SELECT MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_BRIEF)
  GROUP BY b.BRIEF_ID
);

SELECT
  'SECTION_COMMAND_BRIEF_ORPHAN_CHILD_ROWS' AS CHECK_NAME,
  SUM(ORPHANS) AS ORPHAN_ROWS,
  IFF(SUM(ORPHANS) = 0, 'PASS', 'FAIL') AS STATUS
FROM (
  SELECT COUNT(*) AS ORPHANS FROM MART_SECTION_COMMAND_METRIC c LEFT JOIN MART_SECTION_COMMAND_BRIEF b ON b.BRIEF_ID = c.BRIEF_ID WHERE b.BRIEF_ID IS NULL
  UNION ALL
  SELECT COUNT(*) FROM MART_SECTION_COMMAND_EXCEPTION c LEFT JOIN MART_SECTION_COMMAND_BRIEF b ON b.BRIEF_ID = c.BRIEF_ID WHERE b.BRIEF_ID IS NULL
  UNION ALL
  SELECT COUNT(*) FROM MART_SECTION_COMMAND_ACTION c LEFT JOIN MART_SECTION_COMMAND_BRIEF b ON b.BRIEF_ID = c.BRIEF_ID WHERE b.BRIEF_ID IS NULL
);

SELECT
  'SECTION_COMMAND_BRIEF_FRESHNESS_TARGETS' AS CHECK_NAME,
  COUNT_IF(COALESCE(IS_STALE, FALSE)) AS STALE_ROWS,
  IFF(COUNT_IF(COALESCE(IS_STALE, FALSE)) = 0, 'PASS', 'WARN') AS STATUS
FROM MART_SECTION_COMMAND_BRIEF
WHERE SNAPSHOT_TS = (SELECT MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_BRIEF);

SELECT
  'SECTION_COMMAND_BRIEF_CANONICAL_WINDOWS' AS CHECK_NAME,
  COUNT(*) AS MISSING_WINDOWS,
  IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS STATUS
FROM (
  SELECT s.SECTION_NAME, w.WINDOW_DAYS
  FROM (
    SELECT COLUMN1::VARCHAR AS SECTION_NAME
    FROM VALUES
      ('Executive Landing'), ('DBA Control Room'), ('Alert Center'),
      ('Cost & Contract'), ('Workload Operations'), ('Security Monitoring')
  ) s
  CROSS JOIN (
    SELECT COLUMN1::NUMBER AS WINDOW_DAYS FROM VALUES (1), (7), (14), (30), (60), (90)
  ) w
  LEFT JOIN MART_SECTION_COMMAND_BRIEF b
    ON b.SECTION_NAME = s.SECTION_NAME
   AND b.WINDOW_DAYS = w.WINDOW_DAYS
   AND b.SNAPSHOT_TS = (SELECT MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_BRIEF)
  WHERE b.BRIEF_ID IS NULL
);

SELECT
  'SECTION_COMMAND_BRIEF_SOURCE_COVERAGE_FIELDS' AS CHECK_NAME,
  COUNT_IF(REQUIRED_SOURCE_COUNT IS NULL OR SOURCE_COVERAGE_PCT IS NULL OR DATA_AVAILABILITY_STATE IS NULL) AS MISSING_COVERAGE_ROWS,
  IFF(COUNT_IF(REQUIRED_SOURCE_COUNT IS NULL OR SOURCE_COVERAGE_PCT IS NULL OR DATA_AVAILABILITY_STATE IS NULL) = 0, 'PASS', 'FAIL') AS STATUS
FROM MART_SECTION_COMMAND_BRIEF
WHERE SNAPSHOT_TS = (SELECT MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_BRIEF);

SELECT
  'SECTION_COMMAND_BRIEF_TYPED_METRICS' AS CHECK_NAME,
  COUNT_IF(METRIC_NUMERIC_VALUE IS NOT NULL OR METRIC_TEXT_VALUE IS NOT NULL) AS TYPED_METRICS,
  IFF(COUNT_IF(METRIC_NUMERIC_VALUE IS NOT NULL OR METRIC_TEXT_VALUE IS NOT NULL) > 0, 'PASS', 'FAIL') AS STATUS
FROM MART_SECTION_COMMAND_METRIC
WHERE SNAPSHOT_TS = (SELECT MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_METRIC);

SELECT
  'SECTION_COMMAND_BRIEF_ROUTE_KEYS' AS CHECK_NAME,
  COUNT_IF(ROUTE_KEY IS NULL OR CTA_LABEL IS NULL) AS MISSING_ROUTE_ROWS,
  IFF(COUNT_IF(ROUTE_KEY IS NULL OR CTA_LABEL IS NULL) = 0, 'PASS', 'FAIL') AS STATUS
FROM MART_SECTION_COMMAND_ACTION
WHERE SNAPSHOT_TS = (SELECT MAX(SNAPSHOT_TS) FROM MART_SECTION_COMMAND_ACTION);
