-- OVERWATCH summary marts for COCO section autoload.
-- These objects are refreshed by setup/tasks and are the only Account Usage
-- backed sources approved for section-summary autoload. Daily UI loaders read
-- these compact marts or the active decision packet, not raw Account Usage.

CREATE TABLE IF NOT EXISTS OVERWATCH_QUERY_DAILY_SUMMARY (
  COMPANY STRING,
  ENVIRONMENT STRING,
  WINDOW_START_DATE DATE,
  WINDOW_END_DATE DATE,
  QUERY_COUNT NUMBER,
  FAILED_QUERY_COUNT NUMBER,
  QUEUED_QUERY_COUNT NUMBER,
  TOTAL_ELAPSED_MS NUMBER,
  BYTES_SCANNED NUMBER,
  CREDITS_ESTIMATE NUMBER(18, 6),
  TOP_WAREHOUSE_NAME STRING,
  TOP_USER_NAME STRING,
  SOURCE_FAMILY STRING DEFAULT 'query_history',
  REFRESH_BOUNDARY STRING DEFAULT 'refresh_fast',
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS OVERWATCH_WAREHOUSE_DAILY_CREDITS (
  COMPANY STRING,
  ENVIRONMENT STRING,
  USAGE_DATE DATE,
  WAREHOUSE_NAME STRING,
  CREDITS_USED NUMBER(18, 6),
  COST_USD NUMBER(18, 2),
  QUERY_COUNT NUMBER,
  QUEUED_SECONDS NUMBER,
  SPILL_BYTES NUMBER,
  SOURCE_FAMILY STRING DEFAULT 'warehouse_metering',
  REFRESH_BOUNDARY STRING DEFAULT 'refresh_fast',
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS OVERWATCH_CORTEX_DAILY_USAGE (
  COMPANY STRING,
  ENVIRONMENT STRING,
  USAGE_DATE DATE,
  USER_NAME STRING,
  USER_DISPLAY_NAME STRING,
  USER_CHART_LABEL STRING,
  SERVICE_TYPE STRING,
  TOTAL_TOKENS NUMBER,
  TOTAL_REQUESTS NUMBER,
  TOTAL_CREDITS NUMBER(18, 6),
  COST_USD NUMBER(18, 2),
  TOKENS_PER_REQUEST NUMBER(18, 6),
  TOKENS_PER_DOLLAR NUMBER(18, 6),
  COST_PER_1K_TOKENS_USD NUMBER(18, 6),
  AI_CREDITS_PER_1K_TOKENS NUMBER(18, 6),
  SOURCE_FAMILY STRING DEFAULT 'cortex_usage',
  REFRESH_BOUNDARY STRING DEFAULT 'refresh_fast',
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS OVERWATCH_USER_DISPLAY_DIM (
  USER_NAME STRING,
  USER_DISPLAY_NAME STRING,
  USER_CHART_LABEL STRING,
  USER_ADMIN_LABEL STRING,
  LOGIN_NAME STRING,
  DISPLAY_NAME STRING,
  NAME STRING,
  SOURCE_FAMILY STRING DEFAULT 'user_display',
  REFRESH_BOUNDARY STRING DEFAULT 'refresh_full',
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS OVERWATCH_LOGIN_SECURITY_DAILY (
  COMPANY STRING,
  ENVIRONMENT STRING,
  EVENT_DATE DATE,
  FAILED_LOGIN_COUNT NUMBER,
  SUCCESS_LOGIN_COUNT NUMBER,
  AFFECTED_USER_COUNT NUMBER,
  MFA_GAP_USER_COUNT NUMBER,
  SUSPICIOUS_IP_COUNT NUMBER,
  SOURCE_FAMILY STRING DEFAULT 'login_security',
  REFRESH_BOUNDARY STRING DEFAULT 'refresh_fast',
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS OVERWATCH_TASK_STATUS_DAILY (
  COMPANY STRING,
  ENVIRONMENT STRING,
  EVENT_DATE DATE,
  FAILED_TASK_COUNT NUMBER,
  FAILED_PROCEDURE_COUNT NUMBER,
  SLA_BREACH_COUNT NUMBER,
  QUEUED_RUN_COUNT NUMBER,
  RECOVERY_ACTION_COUNT NUMBER,
  SOURCE_FAMILY STRING DEFAULT 'task_status',
  REFRESH_BOUNDARY STRING DEFAULT 'refresh_fast',
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS OVERWATCH_SECURITY_POSTURE_DAILY (
  COMPANY STRING,
  ENVIRONMENT STRING,
  EVENT_DATE DATE,
  CRITICAL_FINDING_COUNT NUMBER,
  HIGH_FINDING_COUNT NUMBER,
  MEDIUM_FINDING_COUNT NUMBER,
  CREDENTIAL_EXPIRATION_RISK_COUNT NUMBER,
  EXPIRED_CREDENTIAL_COUNT NUMBER,
  EXPIRING_30D_CREDENTIAL_COUNT NUMBER,
  SOURCE_FAMILY STRING DEFAULT 'security_posture',
  REFRESH_BOUNDARY STRING DEFAULT 'refresh_fast',
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS OVERWATCH_EXECUTIVE_PACKET_CURRENT (
  COMPANY STRING,
  ENVIRONMENT STRING,
  SECTION STRING,
  WINDOW_DAYS NUMBER,
  SUMMARY_JSON VARIANT,
  TOP_FINDINGS_JSON VARIANT,
  TOP_ACTIONS_JSON VARIANT,
  SOURCE_FAMILY STRING DEFAULT 'decision_packet',
  REFRESH_BOUNDARY STRING DEFAULT 'refresh_fast',
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
