-- OVERWATCH summary marts for COCO section autoload.
-- These objects are refreshed by setup/tasks and are the only Account Usage
-- backed sources approved for section-summary autoload. Daily UI loaders read
-- these compact marts or the active decision packet, not raw Account Usage.

CREATE TABLE IF NOT EXISTS OVERWATCH_QUERY_DAILY_SUMMARY (
  COMPANY STRING,
  ENVIRONMENT STRING,
  WINDOW_START_DATE DATE,
  WINDOW_END_DATE DATE,
  QUERY_COUNT NUMBER,
  FAILED_QUERY_COUNT NUMBER,
  QUEUED_QUERY_COUNT NUMBER,
  TOTAL_ELAPSED_MS NUMBER,
  BYTES_SCANNED NUMBER,
  CREDITS_ESTIMATE NUMBER(18, 6),
  TOP_WAREHOUSE_NAME STRING,
  TOP_USER_NAME STRING,
  SOURCE_FAMILY STRING DEFAULT 'query_history',
  REFRESH_BOUNDARY STRING DEFAULT 'refresh_fast',
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS OVERWATCH_WAREHOUSE_DAILY_CREDITS (
  COMPANY STRING,
  ENVIRONMENT STRING,
  USAGE_DATE DATE,
  WAREHOUSE_NAME STRING,
  CREDITS_USED NUMBER(18, 6),
  COST_USD NUMBER(18, 2),
  QUERY_COUNT NUMBER,
  QUEUED_SECONDS NUMBER,
  SPILL_BYTES NUMBER,
  SOURCE_FAMILY STRING DEFAULT 'warehouse_metering',
  REFRESH_BOUNDARY STRING DEFAULT 'refresh_fast',
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS OVERWATCH_CORTEX_DAILY_USAGE (
  COMPANY STRING,
  ENVIRONMENT STRING,
  USAGE_DATE DATE,
  USER_NAME STRING,
  USER_DISPLAY_NAME STRING,
  USER_CHART_LABEL STRING,
  SERVICE_TYPE STRING,
  TOTAL_TOKENS NUMBER,
  TOTAL_REQUESTS NUMBER,
  TOTAL_CREDITS NUMBER(18, 6),
  COST_USD NUMBER(18, 2),
  TOKENS_PER_REQUEST NUMBER(18, 6),
  TOKENS_PER_DOLLAR NUMBER(18, 6),
  COST_PER_1K_TOKENS_USD NUMBER(18, 6),
  AI_CREDITS_PER_1K_TOKENS NUMBER(18, 6),
  SOURCE_FAMILY STRING DEFAULT 'cortex_usage',
  REFRESH_BOUNDARY STRING DEFAULT 'refresh_fast',
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS OVERWATCH_USER_DISPLAY_DIM (
  USER_NAME STRING,
  USER_DISPLAY_NAME STRING,
  USER_CHART_LABEL STRING,
  USER_ADMIN_LABEL STRING,
  LOGIN_NAME STRING,
  DISPLAY_NAME STRING,
  NAME STRING,
  SOURCE_FAMILY STRING DEFAULT 'user_display',
  REFRESH_BOUNDARY STRING DEFAULT 'refresh_full',
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS OVERWATCH_LOGIN_SECURITY_DAILY (
  COMPANY STRING,
  ENVIRONMENT STRING,
  EVENT_DATE DATE,
  FAILED_LOGIN_COUNT NUMBER,
  SUCCESS_LOGIN_COUNT NUMBER,
  AFFECTED_USER_COUNT NUMBER,
  MFA_GAP_USER_COUNT NUMBER,
  SUSPICIOUS_IP_COUNT NUMBER,
  SOURCE_FAMILY STRING DEFAULT 'login_security',
  REFRESH_BOUNDARY STRING DEFAULT 'refresh_fast',
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS OVERWATCH_TASK_STATUS_DAILY (
  COMPANY STRING,
  ENVIRONMENT STRING,
  EVENT_DATE DATE,
  FAILED_TASK_COUNT NUMBER,
  FAILED_PROCEDURE_COUNT NUMBER,
  SLA_BREACH_COUNT NUMBER,
  QUEUED_RUN_COUNT NUMBER,
  RECOVERY_ACTION_COUNT NUMBER,
  SOURCE_FAMILY STRING DEFAULT 'task_status',
  REFRESH_BOUNDARY STRING DEFAULT 'refresh_fast',
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS OVERWATCH_SECURITY_POSTURE_DAILY (
  COMPANY STRING,
  ENVIRONMENT STRING,
  EVENT_DATE DATE,
  CRITICAL_FINDING_COUNT NUMBER,
  HIGH_FINDING_COUNT NUMBER,
  MEDIUM_FINDING_COUNT NUMBER,
  CREDENTIAL_EXPIRATION_RISK_COUNT NUMBER,
  EXPIRED_CREDENTIAL_COUNT NUMBER,
  EXPIRING_30D_CREDENTIAL_COUNT NUMBER,
  SOURCE_FAMILY STRING DEFAULT 'security_posture',
  REFRESH_BOUNDARY STRING DEFAULT 'refresh_fast',
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS OVERWATCH_EXECUTIVE_PACKET_CURRENT (
  COMPANY STRING,
  ENVIRONMENT STRING,
  SECTION STRING,
  WINDOW_DAYS NUMBER,
  SUMMARY_JSON VARIANT,
  TOP_FINDINGS_JSON VARIANT,
  TOP_ACTIONS_JSON VARIANT,
  SOURCE_FAMILY STRING DEFAULT 'decision_packet',
  REFRESH_BOUNDARY STRING DEFAULT 'refresh_fast',
  UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

COMMENT ON TABLE OVERWATCH_QUERY_DAILY_SUMMARY IS
  'COCO compact mart. Source: query history refresh procedure. Grain: company, environment, warehouse/user/query status/window day. Refresh: task-loaded, summary-only, app consumes V_QUERY_DAILY_SUMMARY.';
COMMENT ON TABLE OVERWATCH_WAREHOUSE_DAILY_CREDITS IS
  'COCO compact mart. Source: warehouse metering and query attribution refresh procedures. Grain: company, environment, warehouse, usage date. Refresh: task-loaded, app consumes V_WAREHOUSE_DAILY_CREDITS.';
COMMENT ON TABLE OVERWATCH_CORTEX_DAILY_USAGE IS
  'COCO compact mart. Source: Cortex usage refresh procedure and user display dimension. Grain: company, environment, user/service/date. Refresh: task-loaded with source-health fallback, app consumes V_CORTEX_DAILY_USAGE.';
COMMENT ON TABLE OVERWATCH_USER_DISPLAY_DIM IS
  'COCO compact dimension. Source: governed user display refresh. Grain: stable user key. Refresh: full refresh, app consumes V_USER_DISPLAY_DIM for daily-safe names.';
COMMENT ON TABLE OVERWATCH_LOGIN_SECURITY_DAILY IS
  'COCO compact mart. Source: login security refresh procedure. Grain: company, environment, event date. Refresh: task-loaded, app consumes V_LOGIN_SECURITY_DAILY.';
COMMENT ON TABLE OVERWATCH_TASK_STATUS_DAILY IS
  'COCO compact mart. Source: task/procedure refresh procedure. Grain: company, environment, event date. Refresh: task-loaded, app consumes V_TASK_STATUS_DAILY.';
COMMENT ON TABLE OVERWATCH_SECURITY_POSTURE_DAILY IS
  'COCO compact mart. Source: security posture and credential refresh procedures. Grain: company, environment, event date. Refresh: task-loaded, app consumes V_SECURITY_POSTURE_DAILY.';
COMMENT ON TABLE OVERWATCH_EXECUTIVE_PACKET_CURRENT IS
  'COCO compact packet cache. Source: Decision packet refresh procedure. Grain: company, environment, section, window. Refresh: task-loaded, app consumes V_EXECUTIVE_PACKET_CURRENT.';

CREATE OR REPLACE SECURE VIEW V_QUERY_DAILY_SUMMARY
  COMMENT = 'Daily-safe app view over OVERWATCH_QUERY_DAILY_SUMMARY. Use for first summary loads instead of direct Account Usage scans.'
AS
SELECT
  COMPANY, ENVIRONMENT, WINDOW_START_DATE, WINDOW_END_DATE, QUERY_COUNT,
  FAILED_QUERY_COUNT, QUEUED_QUERY_COUNT, TOTAL_ELAPSED_MS, BYTES_SCANNED,
  CREDITS_ESTIMATE, TOP_WAREHOUSE_NAME, TOP_USER_NAME, SOURCE_FAMILY,
  REFRESH_BOUNDARY, UPDATED_AT
FROM OVERWATCH_QUERY_DAILY_SUMMARY;

CREATE OR REPLACE SECURE VIEW V_WAREHOUSE_DAILY_CREDITS
  COMMENT = 'Daily-safe app view over OVERWATCH_WAREHOUSE_DAILY_CREDITS. Use for Cost Intelligence and Executive first-paint summaries.'
AS
SELECT
  COMPANY, ENVIRONMENT, USAGE_DATE, WAREHOUSE_NAME, CREDITS_USED, COST_USD,
  QUERY_COUNT, QUEUED_SECONDS, SPILL_BYTES, SOURCE_FAMILY, REFRESH_BOUNDARY, UPDATED_AT
FROM OVERWATCH_WAREHOUSE_DAILY_CREDITS;

CREATE OR REPLACE SECURE VIEW V_CORTEX_DAILY_USAGE
  COMMENT = 'Daily-safe app view over OVERWATCH_CORTEX_DAILY_USAGE. Uses friendly user display labels and AI credit pricing already materialized by refresh.'
AS
SELECT
  COMPANY, ENVIRONMENT, USAGE_DATE, USER_NAME, USER_DISPLAY_NAME, USER_CHART_LABEL,
  SERVICE_TYPE, TOTAL_TOKENS, TOTAL_REQUESTS, TOTAL_CREDITS, COST_USD,
  TOKENS_PER_REQUEST, TOKENS_PER_DOLLAR, COST_PER_1K_TOKENS_USD,
  AI_CREDITS_PER_1K_TOKENS, SOURCE_FAMILY, REFRESH_BOUNDARY, UPDATED_AT
FROM OVERWATCH_CORTEX_DAILY_USAGE;

CREATE OR REPLACE SECURE VIEW V_USER_DISPLAY_DIM
  COMMENT = 'Daily-safe app view over OVERWATCH_USER_DISPLAY_DIM. Excludes admin-only raw identifier labels by default.'
AS
SELECT
  USER_NAME, USER_DISPLAY_NAME, USER_CHART_LABEL, LOGIN_NAME, DISPLAY_NAME, NAME,
  SOURCE_FAMILY, REFRESH_BOUNDARY, UPDATED_AT
FROM OVERWATCH_USER_DISPLAY_DIM;

CREATE OR REPLACE SECURE VIEW V_LOGIN_SECURITY_DAILY
  COMMENT = 'Daily-safe app view over OVERWATCH_LOGIN_SECURITY_DAILY. Use for Security first summary loads instead of direct login history scans.'
AS
SELECT
  COMPANY, ENVIRONMENT, EVENT_DATE, FAILED_LOGIN_COUNT, SUCCESS_LOGIN_COUNT,
  AFFECTED_USER_COUNT, MFA_GAP_USER_COUNT, SUSPICIOUS_IP_COUNT,
  SOURCE_FAMILY, REFRESH_BOUNDARY, UPDATED_AT
FROM OVERWATCH_LOGIN_SECURITY_DAILY;

CREATE OR REPLACE SECURE VIEW V_TASK_STATUS_DAILY
  COMMENT = 'Daily-safe app view over OVERWATCH_TASK_STATUS_DAILY. Use for DBA/Workload first summary loads instead of direct task history scans.'
AS
SELECT
  COMPANY, ENVIRONMENT, EVENT_DATE, FAILED_TASK_COUNT, FAILED_PROCEDURE_COUNT,
  SLA_BREACH_COUNT, QUEUED_RUN_COUNT, RECOVERY_ACTION_COUNT,
  SOURCE_FAMILY, REFRESH_BOUNDARY, UPDATED_AT
FROM OVERWATCH_TASK_STATUS_DAILY;

CREATE OR REPLACE SECURE VIEW V_SECURITY_POSTURE_DAILY
  COMMENT = 'Daily-safe app view over OVERWATCH_SECURITY_POSTURE_DAILY. Includes governed credential-expiration risk counts without raw credential identifiers.'
AS
SELECT
  COMPANY, ENVIRONMENT, EVENT_DATE, CRITICAL_FINDING_COUNT, HIGH_FINDING_COUNT,
  MEDIUM_FINDING_COUNT, CREDENTIAL_EXPIRATION_RISK_COUNT, EXPIRED_CREDENTIAL_COUNT,
  EXPIRING_30D_CREDENTIAL_COUNT, SOURCE_FAMILY, REFRESH_BOUNDARY, UPDATED_AT
FROM OVERWATCH_SECURITY_POSTURE_DAILY;

CREATE OR REPLACE SECURE VIEW V_EXECUTIVE_PACKET_CURRENT
  COMMENT = 'Daily-safe app view over OVERWATCH_EXECUTIVE_PACKET_CURRENT. Use for Executive first-paint packet summaries.'
AS
SELECT
  COMPANY, ENVIRONMENT, SECTION, WINDOW_DAYS, SUMMARY_JSON, TOP_FINDINGS_JSON,
  TOP_ACTIONS_JSON, SOURCE_FAMILY, REFRESH_BOUNDARY, UPDATED_AT
FROM OVERWATCH_EXECUTIVE_PACKET_CURRENT;

CREATE OR REPLACE SECURE VIEW V_LEADERSHIP_CREDIT_DAILY
  COMMENT = 'Daily-safe leadership view for Credit Burn Rate and YTD Credit Trend. Source: compact cost and warehouse facts. Grain: company, environment rollup, usage date, service type, warehouse where available.'
AS
SELECT
  COMPANY,
  'ALL'::STRING AS ENVIRONMENT,
  TO_DATE(HOUR_START) AS USAGE_DATE,
  'WAREHOUSE'::STRING AS SERVICE_TYPE,
  WAREHOUSE_NAME,
  SUM(COALESCE(CREDITS_USED, 0)) AS CREDITS_USED,
  SUM(COALESCE(CREDITS_USED_COMPUTE, 0)) AS CREDITS_USED_COMPUTE,
  SUM(COALESCE(CREDITS_USED_CLOUD_SERVICES, 0)) AS CREDITS_USED_CLOUD_SERVICES,
  SUM(COALESCE(EST_COST_USD, 0)) AS ESTIMATED_COST_USD,
  MAX(LOAD_TS) AS UPDATED_AT
FROM FACT_WAREHOUSE_HOURLY
WHERE HOUR_START >= DATEADD('year', -1, CURRENT_DATE())
GROUP BY COMPANY, TO_DATE(HOUR_START), WAREHOUSE_NAME
UNION ALL
SELECT
  COMPANY,
  'ALL'::STRING AS ENVIRONMENT,
  USAGE_DATE,
  COALESCE(NULLIF(SERVICE_TYPE, ''), NULLIF(SERVICE_CATEGORY, ''), 'SERVICE') AS SERVICE_TYPE,
  NULL::STRING AS WAREHOUSE_NAME,
  SUM(COALESCE(CREDITS_USED, 0)) AS CREDITS_USED,
  SUM(COALESCE(CREDITS_USED_COMPUTE, 0)) AS CREDITS_USED_COMPUTE,
  SUM(COALESCE(CREDITS_USED_CLOUD_SERVICES, 0)) AS CREDITS_USED_CLOUD_SERVICES,
  SUM(COALESCE(EST_COST_USD, 0)) AS ESTIMATED_COST_USD,
  MAX(LOAD_TS) AS UPDATED_AT
FROM FACT_COST_DAILY
WHERE USAGE_DATE >= DATEADD('year', -1, CURRENT_DATE())
GROUP BY COMPANY, USAGE_DATE, COALESCE(NULLIF(SERVICE_TYPE, ''), NULLIF(SERVICE_CATEGORY, ''), 'SERVICE');

CREATE OR REPLACE SECURE VIEW V_LEADERSHIP_CREDIT_COMPARISON_24H
  COMMENT = 'Daily-safe leadership view for current 24h credit comparison. Source: compact warehouse hourly facts. Grain: company, warehouse contributor.'
AS
WITH contributor AS (
  SELECT
    COMPANY,
    WAREHOUSE_NAME AS CONTRIBUTOR_NAME,
    SUM(IFF(HOUR_START >= DATEADD('hour', -24, CURRENT_TIMESTAMP()), COALESCE(CREDITS_USED, 0), 0)) AS CURRENT_24H_CREDITS,
    SUM(IFF(HOUR_START < DATEADD('hour', -24, CURRENT_TIMESTAMP()), COALESCE(CREDITS_USED, 0), 0)) AS PRIOR_24H_CREDITS,
    SUM(IFF(HOUR_START >= DATEADD('hour', -24, CURRENT_TIMESTAMP()), COALESCE(EST_COST_USD, 0), 0)) AS CURRENT_24H_COST_USD,
    SUM(IFF(HOUR_START < DATEADD('hour', -24, CURRENT_TIMESTAMP()), COALESCE(EST_COST_USD, 0), 0)) AS PRIOR_24H_COST_USD,
    MAX(LOAD_TS) AS UPDATED_AT
  FROM FACT_WAREHOUSE_HOURLY
  WHERE HOUR_START >= DATEADD('hour', -48, CURRENT_TIMESTAMP())
  GROUP BY COMPANY, WAREHOUSE_NAME
)
SELECT
  COMPANY,
  'ALL'::STRING AS ENVIRONMENT,
  'WAREHOUSE'::STRING AS CONTRIBUTOR_TYPE,
  COALESCE(CONTRIBUTOR_NAME, 'Unassigned warehouse') AS CONTRIBUTOR_NAME,
  CURRENT_24H_CREDITS,
  PRIOR_24H_CREDITS,
  CURRENT_24H_CREDITS - PRIOR_24H_CREDITS AS CREDIT_DELTA,
  IFF(NULLIF(PRIOR_24H_CREDITS, 0) IS NULL, NULL, (CURRENT_24H_CREDITS - PRIOR_24H_CREDITS) / NULLIF(PRIOR_24H_CREDITS, 0)) AS PCT_DELTA,
  CURRENT_24H_COST_USD - PRIOR_24H_COST_USD AS ESTIMATED_COST_DELTA_USD,
  UPDATED_AT
FROM contributor;

CREATE OR REPLACE SECURE VIEW V_LEADERSHIP_LOGIN_SECURITY
  COMMENT = 'Daily-safe leadership view for failed-login and suspicious-login panels. Source: compact login daily facts. Grain: company, environment rollup, date, user, client IP.'
AS
SELECT
  COMPANY,
  'ALL'::STRING AS ENVIRONMENT,
  LOGIN_DATE AS EVENT_DATE,
  TO_TIMESTAMP_NTZ(LOGIN_DATE) AS EVENT_HOUR,
  USER_NAME,
  CLIENT_IP,
  REPORTED_CLIENT_TYPE,
  IFF(COALESCE(FAILURE_COUNT, 0) = 0 AND COALESCE(SUCCESS_COUNT, 0) > 0, TRUE, FALSE) AS IS_SUCCESS,
  NULL::STRING AS ERROR_CODE,
  IFF(COALESCE(FAILURE_COUNT, 0) > 0, 'Failed login aggregate', NULL) AS ERROR_MESSAGE,
  COALESCE(SUCCESS_COUNT, 0) + COALESCE(FAILURE_COUNT, 0) AS LOGIN_COUNT,
  COALESCE(FAILURE_COUNT, 0) AS FAILED_COUNT,
  TO_TIMESTAMP_NTZ(LOGIN_DATE) AS FIRST_SEEN,
  TO_TIMESTAMP_NTZ(LOGIN_DATE) AS LAST_SEEN,
  CASE
    WHEN COALESCE(FAILURE_COUNT, 0) >= 10 THEN 'Many failures for same user or client'
    WHEN COALESCE(FAILURE_COUNT, 0) >= 3 THEN 'Repeated login failures'
    ELSE NULL
  END AS RISK_REASON,
  CASE
    WHEN COALESCE(FAILURE_COUNT, 0) >= 10 THEN 90
    WHEN COALESCE(FAILURE_COUNT, 0) >= 3 THEN 60
    ELSE 0
  END AS RISK_SCORE,
  LOAD_TS AS UPDATED_AT
FROM FACT_LOGIN_DAILY
WHERE LOGIN_DATE >= DATEADD('day', -35, CURRENT_DATE());

CREATE OR REPLACE SECURE VIEW V_LEADERSHIP_QUERY_ERRORS
  COMMENT = 'Daily-safe leadership view for query error frequency and failed-query trend. Source: compact recent query detail. Query text is intentionally excluded.'
AS
SELECT
  COMPANY,
  COALESCE(ENVIRONMENT, 'ALL') AS ENVIRONMENT,
  TO_DATE(START_TIME) AS EVENT_DATE,
  DATE_TRUNC('hour', START_TIME) AS EVENT_HOUR,
  WAREHOUSE_NAME,
  USER_NAME,
  ROLE_NAME,
  DATABASE_NAME,
  SCHEMA_NAME,
  COALESCE(NULLIF(ERROR_CODE, ''), 'UNKNOWN') AS ERROR_CODE,
  LEFT(COALESCE(NULLIF(ERROR_MESSAGE, ''), 'Query failed'), 500) AS ERROR_MESSAGE,
  COUNT(*) AS FAILED_QUERY_COUNT,
  COUNT(*) AS TOTAL_QUERY_COUNT,
  1::FLOAT AS FAILURE_RATE,
  MAX_BY(QUERY_ID, START_TIME) AS LATEST_QUERY_ID,
  MAX(START_TIME) AS LATEST_OCCURRENCE,
  MAX(LOAD_TS) AS UPDATED_AT
FROM FACT_QUERY_DETAIL_RECENT
WHERE START_TIME >= DATEADD('day', -35, CURRENT_TIMESTAMP())
  AND (
    COALESCE(EXECUTION_STATUS, '') ILIKE '%FAIL%'
    OR ERROR_CODE IS NOT NULL
    OR ERROR_MESSAGE IS NOT NULL
  )
GROUP BY
  COMPANY, COALESCE(ENVIRONMENT, 'ALL'), TO_DATE(START_TIME), DATE_TRUNC('hour', START_TIME),
  WAREHOUSE_NAME, USER_NAME, ROLE_NAME, DATABASE_NAME, SCHEMA_NAME,
  COALESCE(NULLIF(ERROR_CODE, ''), 'UNKNOWN'),
  LEFT(COALESCE(NULLIF(ERROR_MESSAGE, ''), 'Query failed'), 500);

CREATE OR REPLACE SECURE VIEW V_LEADERSHIP_STORAGE_DAILY
  COMMENT = 'Daily-safe leadership view for database and failsafe storage growth. Source: compact storage daily facts. Grain: company, environment, date, database.'
AS
WITH storage AS (
  SELECT
    COMPANY,
    COALESCE(ENVIRONMENT, 'ALL') AS ENVIRONMENT,
    SNAPSHOT_DATE AS USAGE_DATE,
    DATABASE_NAME,
    COALESCE(ACTIVE_BYTES, 0) + COALESCE(TIME_TRAVEL_BYTES, 0) AS DATABASE_BYTES,
    COALESCE(FAILSAFE_BYTES, 0) AS FAILSAFE_BYTES,
    COALESCE(ACTIVE_BYTES, 0) + COALESCE(TIME_TRAVEL_BYTES, 0) + COALESCE(FAILSAFE_BYTES, 0)
      + COALESCE(RETAINED_FOR_CLONE_BYTES, 0) + COALESCE(STAGE_BYTES, 0)
      + COALESCE(HYBRID_TABLE_STORAGE_BYTES, 0) + COALESCE(ARCHIVE_STORAGE_COOL_BYTES, 0)
      + COALESCE(ARCHIVE_STORAGE_COLD_BYTES, 0) AS TOTAL_BYTES,
    LOAD_TS AS UPDATED_AT
  FROM FACT_STORAGE_DAILY
  WHERE SNAPSHOT_DATE >= DATEADD('day', -90, CURRENT_DATE())
)
SELECT
  COMPANY,
  ENVIRONMENT,
  USAGE_DATE,
  DATABASE_NAME,
  DATABASE_BYTES,
  FAILSAFE_BYTES,
  TOTAL_BYTES,
  DATABASE_BYTES / POWER(1024, 4) AS DATABASE_TB,
  FAILSAFE_BYTES / POWER(1024, 4) AS FAILSAFE_TB,
  TOTAL_BYTES / POWER(1024, 4) AS TOTAL_TB,
  TOTAL_BYTES - LAG(TOTAL_BYTES) OVER (PARTITION BY COMPANY, ENVIRONMENT, DATABASE_NAME ORDER BY USAGE_DATE) AS DAILY_GROWTH_BYTES,
  IFF(NULLIF(LAG(TOTAL_BYTES) OVER (PARTITION BY COMPANY, ENVIRONMENT, DATABASE_NAME ORDER BY USAGE_DATE), 0) IS NULL,
      NULL,
      (TOTAL_BYTES - LAG(TOTAL_BYTES) OVER (PARTITION BY COMPANY, ENVIRONMENT, DATABASE_NAME ORDER BY USAGE_DATE))
      / NULLIF(LAG(TOTAL_BYTES) OVER (PARTITION BY COMPANY, ENVIRONMENT, DATABASE_NAME ORDER BY USAGE_DATE), 0)) AS DAILY_GROWTH_PCT,
  UPDATED_AT
FROM storage;

CREATE OR REPLACE SECURE VIEW V_LEADERSHIP_CORTEX_CODE_USAGE
  COMMENT = 'Daily-safe leadership view for Cortex Code token and credit adoption. Source: compact Cortex daily usage with friendly user labels.'
AS
SELECT
  COMPANY,
  ENVIRONMENT,
  USAGE_DATE,
  USER_NAME,
  USER_DISPLAY_NAME,
  USER_CHART_LABEL,
  COALESCE(SERVICE_TYPE, 'Cortex Code') AS CLIENT_SOURCE,
  COALESCE(SERVICE_TYPE, 'Cortex Code') AS SERVICE_TYPE,
  NULL::STRING AS MODEL_NAME,
  TOTAL_REQUESTS AS REQUEST_COUNT,
  TOTAL_TOKENS AS TOKEN_COUNT,
  TOTAL_CREDITS AS CREDITS_USED,
  COST_USD AS ESTIMATED_COST_USD,
  UPDATED_AT
FROM OVERWATCH_CORTEX_DAILY_USAGE
WHERE USAGE_DATE >= DATEADD('day', -35, CURRENT_DATE());

CREATE OR REPLACE SECURE VIEW V_LEADERSHIP_ROLE_GRANT_AUDIT
  COMMENT = 'Daily-safe leadership view for TF_O_DEV role/grant auditing. Source: compact grant daily facts. Raw source object names are not exposed.'
AS
SELECT
  COMPANY,
  'ALL'::STRING AS ENVIRONMENT,
  ROLE_NAME,
  GRANTEE_NAME,
  GRANTED_TO AS GRANTEE_TYPE,
  NULL::STRING AS PRIVILEGE,
  GRANTED_TO AS GRANTED_ON,
  'ALFA_EDW_SAN'::STRING AS OBJECT_DATABASE,
  NULL::STRING AS OBJECT_SCHEMA,
  ROLE_NAME AS OBJECT_NAME,
  NULL::STRING AS GRANTED_BY,
  CREATED_ON,
  DELETED_ON,
  IFF(DELETED_ON IS NULL, TRUE, FALSE) AS IS_ACTIVE,
  LOAD_TS AS UPDATED_AT
FROM FACT_GRANT_DAILY
WHERE ROLE_NAME ILIKE 'TF_O_DEV_%';

GRANT SELECT ON VIEW V_QUERY_DAILY_SUMMARY TO ROLE SNOW_ACCOUNTADMINS;
GRANT SELECT ON VIEW V_QUERY_DAILY_SUMMARY TO ROLE SNOW_SYSADMINS;
GRANT SELECT ON VIEW V_WAREHOUSE_DAILY_CREDITS TO ROLE SNOW_ACCOUNTADMINS;
GRANT SELECT ON VIEW V_WAREHOUSE_DAILY_CREDITS TO ROLE SNOW_SYSADMINS;
GRANT SELECT ON VIEW V_CORTEX_DAILY_USAGE TO ROLE SNOW_ACCOUNTADMINS;
GRANT SELECT ON VIEW V_CORTEX_DAILY_USAGE TO ROLE SNOW_SYSADMINS;
GRANT SELECT ON VIEW V_USER_DISPLAY_DIM TO ROLE SNOW_ACCOUNTADMINS;
GRANT SELECT ON VIEW V_USER_DISPLAY_DIM TO ROLE SNOW_SYSADMINS;
GRANT SELECT ON VIEW V_LOGIN_SECURITY_DAILY TO ROLE SNOW_ACCOUNTADMINS;
GRANT SELECT ON VIEW V_LOGIN_SECURITY_DAILY TO ROLE SNOW_SYSADMINS;
GRANT SELECT ON VIEW V_TASK_STATUS_DAILY TO ROLE SNOW_ACCOUNTADMINS;
GRANT SELECT ON VIEW V_TASK_STATUS_DAILY TO ROLE SNOW_SYSADMINS;
GRANT SELECT ON VIEW V_SECURITY_POSTURE_DAILY TO ROLE SNOW_ACCOUNTADMINS;
GRANT SELECT ON VIEW V_SECURITY_POSTURE_DAILY TO ROLE SNOW_SYSADMINS;
GRANT SELECT ON VIEW V_EXECUTIVE_PACKET_CURRENT TO ROLE SNOW_ACCOUNTADMINS;
GRANT SELECT ON VIEW V_EXECUTIVE_PACKET_CURRENT TO ROLE SNOW_SYSADMINS;
GRANT SELECT ON VIEW V_LEADERSHIP_CREDIT_DAILY TO ROLE SNOW_ACCOUNTADMINS;
GRANT SELECT ON VIEW V_LEADERSHIP_CREDIT_DAILY TO ROLE SNOW_SYSADMINS;
GRANT SELECT ON VIEW V_LEADERSHIP_CREDIT_COMPARISON_24H TO ROLE SNOW_ACCOUNTADMINS;
GRANT SELECT ON VIEW V_LEADERSHIP_CREDIT_COMPARISON_24H TO ROLE SNOW_SYSADMINS;
GRANT SELECT ON VIEW V_LEADERSHIP_LOGIN_SECURITY TO ROLE SNOW_ACCOUNTADMINS;
GRANT SELECT ON VIEW V_LEADERSHIP_LOGIN_SECURITY TO ROLE SNOW_SYSADMINS;
GRANT SELECT ON VIEW V_LEADERSHIP_QUERY_ERRORS TO ROLE SNOW_ACCOUNTADMINS;
GRANT SELECT ON VIEW V_LEADERSHIP_QUERY_ERRORS TO ROLE SNOW_SYSADMINS;
GRANT SELECT ON VIEW V_LEADERSHIP_STORAGE_DAILY TO ROLE SNOW_ACCOUNTADMINS;
GRANT SELECT ON VIEW V_LEADERSHIP_STORAGE_DAILY TO ROLE SNOW_SYSADMINS;
GRANT SELECT ON VIEW V_LEADERSHIP_CORTEX_CODE_USAGE TO ROLE SNOW_ACCOUNTADMINS;
GRANT SELECT ON VIEW V_LEADERSHIP_CORTEX_CODE_USAGE TO ROLE SNOW_SYSADMINS;
GRANT SELECT ON VIEW V_LEADERSHIP_ROLE_GRANT_AUDIT TO ROLE SNOW_ACCOUNTADMINS;
GRANT SELECT ON VIEW V_LEADERSHIP_ROLE_GRANT_AUDIT TO ROLE SNOW_SYSADMINS;
