-- OVERWATCH mart setup: 09_validation.sql

-- Run smoke checks and optional initial refresh calls.

-- Run files in numeric order from snowflake/mart_setup/.



USE DATABASE DBA_MAINT_DB;

USE SCHEMA OVERWATCH;



SELECT 'FACT_WAREHOUSE_HOURLY' AS TABLE_NAME, COUNT(*) AS ROWS_LOADED FROM FACT_WAREHOUSE_HOURLY
UNION ALL
SELECT 'FACT_QUERY_HOURLY', COUNT(*) FROM FACT_QUERY_HOURLY
UNION ALL
SELECT 'FACT_QUERY_DETAIL_RECENT', COUNT(*) FROM FACT_QUERY_DETAIL_RECENT
UNION ALL
SELECT 'DIM_TABLE_SNAPSHOT', COUNT(*) FROM DIM_TABLE_SNAPSHOT
UNION ALL
SELECT 'FACT_COPY_LOAD_DAILY', COUNT(*) FROM FACT_COPY_LOAD_DAILY
UNION ALL
SELECT 'FACT_COST_DAILY', COUNT(*) FROM FACT_COST_DAILY
UNION ALL
SELECT 'FACT_COST_SOURCE_HEALTH_DAILY', COUNT(*) FROM FACT_COST_SOURCE_HEALTH_DAILY
UNION ALL
SELECT 'FACT_COST_MONITORING_SIGNAL', COUNT(*) FROM FACT_COST_MONITORING_SIGNAL
UNION ALL
SELECT 'FACT_COST_INCIDENT_TIMELINE', COUNT(*) FROM FACT_COST_INCIDENT_TIMELINE
UNION ALL
SELECT 'MART_EXECUTIVE_OBSERVABILITY', COUNT(*) FROM MART_EXECUTIVE_OBSERVABILITY
UNION ALL
SELECT 'MART_DBA_CONTROL_ROOM', COUNT(*) FROM MART_DBA_CONTROL_ROOM
UNION ALL
SELECT 'MART_DATA_TRUST_SUMMARY', COUNT(*) FROM MART_DATA_TRUST_SUMMARY
UNION ALL
SELECT 'MART_OPERATIONAL_OWNER_COVERAGE', COUNT(*) FROM MART_OPERATIONAL_OWNER_COVERAGE
UNION ALL
SELECT 'MART_EXECUTIVE_VALUE_LEDGER', COUNT(*) FROM MART_EXECUTIVE_VALUE_LEDGER
UNION ALL
SELECT 'MART_APP_OBSERVABILITY_SUMMARY', COUNT(*) FROM MART_APP_OBSERVABILITY_SUMMARY
UNION ALL
SELECT 'MART_PRODUCTION_READINESS_SUMMARY', COUNT(*) FROM MART_PRODUCTION_READINESS_SUMMARY
UNION ALL
SELECT 'MART_EXECUTIVE_SCORECARD_SUMMARY', COUNT(*) FROM MART_EXECUTIVE_SCORECARD_SUMMARY
UNION ALL
SELECT 'MART_EXECUTIVE_FORECAST_SUMMARY', COUNT(*) FROM MART_EXECUTIVE_FORECAST_SUMMARY
UNION ALL
SELECT 'MART_CHANGE_INTELLIGENCE_SUMMARY', COUNT(*) FROM MART_CHANGE_INTELLIGENCE_SUMMARY
UNION ALL
SELECT 'MART_CLOSED_LOOP_OPERATIONS_SUMMARY', COUNT(*) FROM MART_CLOSED_LOOP_OPERATIONS_SUMMARY
UNION ALL
SELECT 'MART_COMMAND_CENTER_SUMMARY', COUNT(*) FROM MART_COMMAND_CENTER_SUMMARY;

CALL SP_OVERWATCH_LOAD_HOURLY();

CALL SP_OVERWATCH_LOAD_CORTEX();

CALL SP_OVERWATCH_REFRESH_CONTROL_ROOM();

CALL SP_OVERWATCH_REFRESH_COST_MONITORING();

CALL SP_OVERWATCH_LOAD_DAILY();

CALL SP_OVERWATCH_REFRESH_EXECUTIVE_OBSERVABILITY();

CALL SP_OVERWATCH_REFRESH_ENTERPRISE_OPERATING_MODEL();

CALL SP_OVERWATCH_REFRESH_PRODUCTION_READINESS();

CALL SP_OVERWATCH_REFRESH_EXECUTIVE_SCORECARD();

CALL SP_OVERWATCH_REFRESH_FORECASTING();

CALL SP_OVERWATCH_REFRESH_CHANGE_INTELLIGENCE();

CALL SP_OVERWATCH_REFRESH_CLOSED_LOOP_OPERATIONS();

CALL SP_OVERWATCH_REFRESH_COMMAND_CENTER();

