-- OVERWATCH owner-routing retirement for ALFA.
--
-- OVERWATCH now uses Finding -> Section/Workflow -> Severity -> Status ->
-- Evidence -> Ticket/Change ID -> Verification/Closure. This migration removes
-- the retired owner-routing columns and source objects from deployed schemas.

USE DATABASE DBA_MAINT_DB;
USE SCHEMA OVERWATCH;

ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE DROP COLUMN IF EXISTS OWNER;
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE DROP COLUMN IF EXISTS OWNER_APPROVAL_STATUS;
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE DROP COLUMN IF EXISTS OWNER_APPROVAL_BY;
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE DROP COLUMN IF EXISTS OWNER_APPROVAL_AT;
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE DROP COLUMN IF EXISTS OWNER_APPROVAL_NOTE;
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE DROP COLUMN IF EXISTS OWNER_EMAIL;
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE DROP COLUMN IF EXISTS ROUTE_EMAIL;
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE DROP COLUMN IF EXISTS REVIEW_PRIMARY;
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE DROP COLUMN IF EXISTS REVIEW_SECONDARY;
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE DROP COLUMN IF EXISTS REVIEW_GROUP;
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE DROP COLUMN IF EXISTS REVIEW_TARGET;
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE DROP COLUMN IF EXISTS ROUTE_SOURCE;
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE DROP COLUMN IF EXISTS ROUTE_EVIDENCE;
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE DROP COLUMN IF EXISTS APPROVAL_ROUTE_READY;
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE DROP COLUMN IF EXISTS ONCALL_PRIMARY;
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE DROP COLUMN IF EXISTS ONCALL_SECONDARY;
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE DROP COLUMN IF EXISTS APPROVAL_GROUP;
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE DROP COLUMN IF EXISTS ESCALATION_TARGET;
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE DROP COLUMN IF EXISTS OWNER_SOURCE;
ALTER TABLE IF EXISTS OVERWATCH_ACTION_QUEUE DROP COLUMN IF EXISTS OWNER_EVIDENCE;

ALTER TABLE IF EXISTS MART_SECTION_COMMAND_EXCEPTION DROP COLUMN IF EXISTS OWNER_ROUTE;
ALTER TABLE IF EXISTS MART_SECTION_COMMAND_EXCEPTION DROP COLUMN IF EXISTS OWNER_GAP;
ALTER TABLE IF EXISTS MART_SECTION_COMMAND_EXCEPTION DROP COLUMN IF EXISTS OWNER_ID;
ALTER TABLE IF EXISTS MART_SECTION_COMMAND_EXCEPTION DROP COLUMN IF EXISTS OWNER_NAME;

ALTER TABLE IF EXISTS FACT_WAREHOUSE_OPERABILITY_DAILY DROP COLUMN IF EXISTS OWNER_APPROVAL_GAP_ROWS;
ALTER TABLE IF EXISTS FACT_SECURITY_OPERABILITY_DAILY DROP COLUMN IF EXISTS OWNER_APPROVAL_GAP_ROWS;
ALTER TABLE IF EXISTS FACT_ACCOUNT_HEALTH_OPERABILITY_DAILY DROP COLUMN IF EXISTS OWNER_APPROVAL_GAP_ROWS;
ALTER TABLE IF EXISTS FACT_CHANGE_CONTROL_OPERABILITY_DAILY DROP COLUMN IF EXISTS OWNER_APPROVAL_GAP_ROWS;
ALTER TABLE IF EXISTS FACT_CHANGE_CONTROL_OPERABILITY_DAILY DROP COLUMN IF EXISTS OWNER;
ALTER TABLE IF EXISTS FACT_CHANGE_CONTROL_OPERABILITY_DAILY DROP COLUMN IF EXISTS ESCALATION_TARGET;

ALTER TABLE IF EXISTS FACT_CHARGEBACK_DAILY DROP COLUMN IF EXISTS COST_OWNER;
ALTER TABLE IF EXISTS FACT_CHARGEBACK_DAILY DROP COLUMN IF EXISTS OWNER_SOURCE;
ALTER TABLE IF EXISTS FACT_CHARGEBACK_DAILY DROP COLUMN IF EXISTS OWNER_EVIDENCE;
ALTER TABLE IF EXISTS FACT_CHARGEBACK_DAILY DROP COLUMN IF EXISTS ROUTE_SOURCE;
ALTER TABLE IF EXISTS FACT_CHARGEBACK_DAILY DROP COLUMN IF EXISTS ROUTE_EVIDENCE;
ALTER TABLE IF EXISTS FACT_CHARGEBACK_DAILY ADD COLUMN IF NOT EXISTS ALLOCATION_SCOPE VARCHAR(300);
ALTER TABLE IF EXISTS FACT_CHARGEBACK_DAILY ADD COLUMN IF NOT EXISTS ALLOCATION_SOURCE VARCHAR(100);
ALTER TABLE IF EXISTS FACT_CHARGEBACK_DAILY ADD COLUMN IF NOT EXISTS ALLOCATION_BASIS VARCHAR(1000);

DELETE FROM OVERWATCH_SECTION_COMMAND_SOURCE_CONFIG
WHERE LOWER(SOURCE_KEY) IN ('owner_coverage');

DROP TABLE IF EXISTS MART_OPERATIONAL_OWNER_COVERAGE;
DROP VIEW IF EXISTS MART_OPERATIONAL_OWNER_COVERAGE;
DROP TABLE IF EXISTS DIM_COST_OWNER_TAG;

INSERT INTO OVERWATCH_SCHEMA_MIGRATION (MIGRATION_VERSION, SOURCE_FILE, APPLIED_AT, STATUS, NOTES)
SELECT
  '2026_07_remove_owner_routing',
  'snowflake/migrations/2026_07_remove_owner_routing.sql',
  CURRENT_TIMESTAMP(),
  'APPLIED',
  'Retired owner-routing columns/objects; app now uses section/workflow/status/evidence verification model.'
WHERE NOT EXISTS (
  SELECT 1
  FROM OVERWATCH_SCHEMA_MIGRATION
  WHERE MIGRATION_VERSION = '2026_07_remove_owner_routing'
);
