"""Sidecar allowlist for admin/setup Snowflake access contracts."""

from __future__ import annotations

DIRECT_SQL_ALLOWLIST = (
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'session.sql',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': '_save_account_health_checklist_snapshot',
 'module': '.overwatch_final/sections/account_health_history.py',
 'owner': 'platform',
 'reason': 'post_click_admin',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'session.sql',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'render_suppression_windows_pane',
 'module': '.overwatch_final/sections/alert_center_admin_suppression_view.py',
 'owner': 'platform',
 'reason': 'post_click_admin',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'session.sql',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'render_alert_history_pane',
 'module': '.overwatch_final/sections/alert_center_history_view.py',
 'owner': 'platform',
 'reason': 'post_click_admin',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'session.sql',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': '_save_change_control_evidence_snapshot',
 'module': '.overwatch_final/sections/change_drift_action_queue.py',
 'owner': 'platform',
 'reason': 'post_click_admin',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'session.sql',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'render_cortex_ai_limits_tool',
 'module': '.overwatch_final/sections/dba_tools_cortex_limits_view.py',
 'owner': 'platform',
 'reason': 'post_click_admin',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'session.sql',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'render_query_kill_list_tool',
 'module': '.overwatch_final/sections/dba_tools_query_kill_view.py',
 'owner': 'platform',
 'reason': 'post_click_admin',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'metadata',
 'budget': 'advanced_diagnostics',
 'call_type': 'session.sql',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': '_table_exists',
 'module': '.overwatch_final/sections/dba_tools_setup.py',
 'owner': 'platform',
 'reason': 'metadata_probe',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'metadata',
 'budget': 'advanced_diagnostics',
 'call_type': 'session.sql',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': '_task_exists',
 'module': '.overwatch_final/sections/dba_tools_setup.py',
 'owner': 'platform',
 'reason': 'metadata_probe',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'session.sql',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'render_task_graph_control_tool',
 'module': '.overwatch_final/sections/dba_tools_task_graph_control_view.py',
 'owner': 'platform',
 'reason': 'post_click_admin',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'session.sql',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'render_warehouse_settings_tool',
 'module': '.overwatch_final/sections/dba_tools_warehouse_settings_view.py',
 'owner': 'platform',
 'reason': 'post_click_admin',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'setup_health',
 'budget': 'admin_setup',
 'call_type': 'session.sql',
 'expected_runtime_context': 'admin_setup',
 'function': '_candidate_procedure_available',
 'module': '.overwatch_final/sections/decision_workspace_bootstrap.py',
 'owner': 'platform',
 'reason': 'setup_health_admin',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'setup_health',
 'budget': 'admin_setup',
 'call_type': 'session.sql',
 'expected_runtime_context': 'admin_setup',
 'function': '_run_call',
 'module': '.overwatch_final/sections/decision_workspace_bootstrap.py',
 'owner': 'platform',
 'reason': 'setup_health_admin',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'setup_health',
 'budget': 'admin_setup',
 'call_type': 'session.sql',
 'expected_runtime_context': 'admin_setup',
 'function': 'detect_decision_setup_version',
 'module': '.overwatch_final/sections/decision_workspace_bootstrap.py',
 'owner': 'platform',
 'reason': 'setup_health_admin',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'setup_health',
 'budget': 'admin_setup',
 'call_type': 'session.sql',
 'expected_runtime_context': 'admin_setup',
 'function': 'validate_decision_bootstrap_output',
 'module': '.overwatch_final/sections/decision_workspace_bootstrap.py',
 'owner': 'platform',
 'reason': 'setup_health_admin',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'setup_health',
 'budget': 'admin_setup',
 'call_type': 'session.sql',
 'expected_runtime_context': 'admin_setup',
 'function': 'persist_decision_setup_health',
 'module': '.overwatch_final/sections/decision_workspace_setup_health.py',
 'owner': 'platform',
 'reason': 'setup_health_admin',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'setup_health',
 'budget': 'admin_setup',
 'call_type': 'session.sql',
 'expected_runtime_context': 'admin_setup',
 'function': 'load_decision_setup_health',
 'module': '.overwatch_final/sections/decision_workspace_setup_health.py',
 'owner': 'platform',
 'reason': 'setup_health_admin',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'setup_health',
 'budget': 'admin_setup',
 'call_type': 'session.sql',
 'expected_runtime_context': 'admin_setup',
 'function': 'load_decision_setup_health_history',
 'module': '.overwatch_final/sections/decision_workspace_setup_health.py',
 'owner': 'platform',
 'reason': 'setup_health_admin',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'session.sql',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': '_live_panel',
 'module': '.overwatch_final/sections/live_monitor.py',
 'owner': 'platform',
 'reason': 'post_click_admin',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'session.sql',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': '_save_security_access_review_snapshot',
 'module': '.overwatch_final/sections/security_posture_access_review.py',
 'owner': 'platform',
 'reason': 'post_click_admin',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'metadata',
 'budget': 'advanced_diagnostics',
 'call_type': 'session.sql',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': '_run_admin_sql_list',
 'module': '.overwatch_final/sections/task_management_common.py',
 'owner': 'platform',
 'reason': 'metadata_probe',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'metadata',
 'budget': 'advanced_diagnostics',
 'call_type': 'session.sql',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': '_current_execution_context',
 'module': '.overwatch_final/sections/task_management_common.py',
 'owner': 'platform',
 'reason': 'metadata_probe',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'session.sql',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'render_task_execute_task',
 'module': '.overwatch_final/sections/task_management_execute_view.py',
 'owner': 'platform',
 'reason': 'post_click_admin',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'session.sql',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': '_save_warehouse_setting_review_snapshot',
 'module': '.overwatch_final/sections/warehouse_health_setting_panels.py',
 'owner': 'platform',
 'reason': 'post_click_admin',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'session.sql',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': '_action_queue_column_names',
 'module': '.overwatch_final/utils/action_queue.py',
 'owner': 'platform',
 'reason': 'post_click_admin',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'session.sql',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'upsert_actions',
 'module': '.overwatch_final/utils/action_queue.py',
 'owner': 'platform',
 'reason': 'post_click_admin',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'session.sql',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'update_action_status_with_evidence',
 'module': '.overwatch_final/utils/action_queue.py',
 'owner': 'platform',
 'reason': 'post_click_admin',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'session.sql',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': '_current_execution_context',
 'module': '.overwatch_final/utils/admin.py',
 'owner': 'platform',
 'reason': 'post_click_admin',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'session.sql',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'log_admin_action',
 'module': '.overwatch_final/utils/admin.py',
 'owner': 'platform',
 'reason': 'post_click_admin',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'session.sql',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'mark_alerts_routed',
 'module': '.overwatch_final/utils/alert_action_queue.py',
 'owner': 'platform',
 'reason': 'post_click_admin',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'session.sql',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'update_alert_rule',
 'module': '.overwatch_final/utils/alert_catalog.py',
 'owner': 'platform',
 'reason': 'post_click_admin',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'session.sql',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'log_alert_digest_delivery',
 'module': '.overwatch_final/utils/alert_delivery.py',
 'owner': 'platform',
 'reason': 'post_click_admin',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'session.sql',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'update_alert_status',
 'module': '.overwatch_final/utils/alert_lifecycle.py',
 'owner': 'platform',
 'reason': 'post_click_admin',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'session.sql',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'acknowledge_alert_escalation',
 'module': '.overwatch_final/utils/alert_lifecycle.py',
 'owner': 'platform',
 'reason': 'post_click_admin',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'session.sql',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': '_quiet_first_paint_query',
 'module': '.overwatch_final/utils/command_board.py',
 'owner': 'platform',
 'reason': 'post_click_admin',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'metadata',
 'budget': 'advanced_diagnostics',
 'call_type': 'session.sql',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'get_available_columns',
 'module': '.overwatch_final/utils/compatibility.py',
 'owner': 'platform',
 'reason': 'metadata_probe',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'metadata',
 'budget': 'advanced_diagnostics',
 'call_type': 'session.sql',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'filter_existing_columns',
 'module': '.overwatch_final/utils/compatibility.py',
 'owner': 'platform',
 'reason': 'metadata_probe',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'metadata',
 'budget': 'advanced_diagnostics',
 'call_type': 'session.sql',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'run_compatibility_checks',
 'module': '.overwatch_final/utils/compatibility.py',
 'owner': 'platform',
 'reason': 'metadata_probe',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'session.sql',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'run_cortex_completion',
 'module': '.overwatch_final/utils/cortex.py',
 'owner': 'platform',
 'reason': 'post_click_admin',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'session.sql',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'log_section_load',
 'module': '.overwatch_final/utils/logging.py',
 'owner': 'platform',
 'reason': 'post_click_admin',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'session.sql',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'log_query_event',
 'module': '.overwatch_final/utils/logging.py',
 'owner': 'platform',
 'reason': 'post_click_admin',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'metadata',
 'budget': 'advanced_diagnostics',
 'call_type': 'session.sql',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'show_to_df',
 'module': '.overwatch_final/utils/metadata.py',
 'owner': 'platform',
 'reason': 'metadata_probe',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'metadata',
 'budget': 'advanced_diagnostics',
 'call_type': 'session.sql',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'load_live_task_runs',
 'module': '.overwatch_final/utils/metadata.py',
 'owner': 'platform',
 'reason': 'metadata_probe',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
)


def _with_cleanup_fields(entry: dict[str, str]) -> dict[str, str]:
    enriched = dict(entry)
    review = enriched.get("expiration_or_review_note") or enriched.get("review_note") or ""
    enriched["expiration_or_review_note"] = review or "Review with the owning admin/setup surface before removal."
    budget = enriched.get("budget", "")
    if budget == "admin_setup":
        active_route = "Settings/Admin Setup Health"
    elif budget == "account_usage_fallback":
        active_route = "Confirmed Account Usage fallback"
    elif budget == "query_preview":
        active_route = "Explicit Query Search SQL preview"
    else:
        active_route = "Explicit advanced diagnostics control"
    enriched.setdefault("active_ui_action_or_admin_route", active_route)
    return enriched


DIRECT_SQL_ALLOWLIST = tuple(_with_cleanup_fields(entry) for entry in DIRECT_SQL_ALLOWLIST)

__all__ = ["DIRECT_SQL_ALLOWLIST"]
