"""Sidecar allowlist for admin/setup Snowflake access contracts."""

from __future__ import annotations

SESSION_OPEN_ALLOWLIST = (
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'refresh_current_role_for_access',
 'module': '.overwatch_final/access_control.py',
 'owner': 'platform',
 'reason': 'admin_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'probe_snowflake_available',
 'module': '.overwatch_final/access_control.py',
 'owner': 'platform',
 'reason': 'admin_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'render',
 'module': '.overwatch_final/sections/adoption_analytics.py',
 'owner': 'platform',
 'reason': 'admin_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'action_session_factory',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': '_load_native_registry',
 'module': '.overwatch_final/sections/alert_center_admin_catalog_view.py',
 'owner': 'platform',
 'reason': 'post_click_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'action_session_factory',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'render_alert_action_queue_routing',
 'module': '.overwatch_final/sections/alert_center_admin_delivery_view.py',
 'owner': 'platform',
 'reason': 'post_click_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'action_session_factory',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'render_suppression_windows_pane',
 'module': '.overwatch_final/sections/alert_center_admin_suppression_view.py',
 'owner': 'platform',
 'reason': 'post_click_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'action_session_factory',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': '_load_suppression_windows',
 'module': '.overwatch_final/sections/alert_center_admin_suppression_view.py',
 'owner': 'platform',
 'reason': 'post_click_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'action_session_factory',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'render_alert_history_pane',
 'module': '.overwatch_final/sections/alert_center_history_view.py',
 'owner': 'platform',
 'reason': 'post_click_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': '_load_change_drift_brief',
 'module': '.overwatch_final/sections/change_drift_brief_view.py',
 'owner': 'platform',
 'reason': 'admin_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'render_change_brief',
 'module': '.overwatch_final/sections/change_drift_brief_view.py',
 'owner': 'platform',
 'reason': 'admin_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': '_load_live_incident_snapshot',
 'module': '.overwatch_final/sections/contention_center.py',
 'owner': 'platform',
 'reason': 'admin_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': '_check_active_locks',
 'module': '.overwatch_final/sections/contention_center.py',
 'owner': 'platform',
 'reason': 'admin_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'render',
 'module': '.overwatch_final/sections/cortex_monitor.py',
 'owner': 'platform',
 'reason': 'admin_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'render',
 'module': '.overwatch_final/sections/cost_center.py',
 'owner': 'platform',
 'reason': 'admin_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': '_load_control_room_evidence',
 'module': '.overwatch_final/sections/dba_control_room/render.py',
 'owner': 'platform',
 'reason': 'post_click_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'render',
 'module': '.overwatch_final/sections/dba_control_room/render.py',
 'owner': 'platform',
 'reason': 'post_click_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'render',
 'module': '.overwatch_final/sections/dba_tools.py',
 'owner': 'platform',
 'reason': 'admin_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'render',
 'module': '.overwatch_final/sections/detailed_diagnosis.py',
 'owner': 'platform',
 'reason': 'admin_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'render',
 'module': '.overwatch_final/sections/live_monitor.py',
 'owner': 'platform',
 'reason': 'admin_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': '_live_panel',
 'module': '.overwatch_final/sections/live_monitor.py',
 'owner': 'platform',
 'reason': 'admin_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': '_query_history_drift_caps',
 'module': '.overwatch_final/sections/object_change_monitor.py',
 'owner': 'platform',
 'reason': 'admin_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'render',
 'module': '.overwatch_final/sections/object_change_monitor.py',
 'owner': 'platform',
 'reason': 'admin_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'render',
 'module': '.overwatch_final/sections/pipeline_health.py',
 'owner': 'platform',
 'reason': 'admin_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'render',
 'module': '.overwatch_final/sections/platform_topology.py',
 'owner': 'platform',
 'reason': 'admin_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'render',
 'module': '.overwatch_final/sections/query_analysis.py',
 'owner': 'platform',
 'reason': 'admin_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'render',
 'module': '.overwatch_final/sections/recommendations.py',
 'owner': 'platform',
 'reason': 'admin_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': '_query_history_columns',
 'module': '.overwatch_final/sections/security_access.py',
 'owner': 'platform',
 'reason': 'admin_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': '_user_column_exprs',
 'module': '.overwatch_final/sections/security_access.py',
 'owner': 'platform',
 'reason': 'admin_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'render',
 'module': '.overwatch_final/sections/security_access.py',
 'owner': 'platform',
 'reason': 'admin_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': '_load_security_brief',
 'module': '.overwatch_final/sections/security_posture_data.py',
 'owner': 'platform',
 'reason': 'post_click_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': '_render_security_exceptions_gate',
 'module': '.overwatch_final/sections/security_posture_overview_view.py',
 'owner': 'platform',
 'reason': 'post_click_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'render_security_overview',
 'module': '.overwatch_final/sections/security_posture_overview_view.py',
 'owner': 'platform',
 'reason': 'post_click_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': '_body',
 'module': '.overwatch_final/sections/security_posture_privilege_sprawl_view.py',
 'owner': 'platform',
 'reason': 'post_click_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'render',
 'module': '.overwatch_final/sections/service_health.py',
 'owner': 'platform',
 'reason': 'admin_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'render',
 'module': '.overwatch_final/sections/stored_proc_tracker.py',
 'owner': 'platform',
 'reason': 'admin_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'render',
 'module': '.overwatch_final/sections/task_management.py',
 'owner': 'platform',
 'reason': 'admin_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'render',
 'module': '.overwatch_final/sections/usage_overview.py',
 'owner': 'platform',
 'reason': 'admin_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': '_quiet_first_paint_query',
 'module': '.overwatch_final/utils/command_board.py',
 'owner': 'platform',
 'reason': 'admin_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': '_query_history_detail_exprs',
 'module': '.overwatch_final/utils/display.py',
 'owner': 'platform',
 'reason': 'admin_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'render_query_drilldown',
 'module': '.overwatch_final/utils/display.py',
 'owner': 'platform',
 'reason': 'admin_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'log_section_load',
 'module': '.overwatch_final/utils/logging.py',
 'owner': 'platform',
 'reason': 'admin_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'log_query_event',
 'module': '.overwatch_final/utils/logging.py',
 'owner': 'platform',
 'reason': 'admin_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
    {'boundary': 'admin',
 'budget': 'advanced_diagnostics',
 'call_type': 'get_session',
 'expected_runtime_context': 'advanced_diagnostics',
 'function': 'render_optimization_advisor',
 'module': '.overwatch_final/utils/optimization_advisor.py',
 'owner': 'platform',
 'reason': 'admin_session',
 'review_note': 'Current admin/setup or post-click diagnostic path; migrated from local marker during Decision '
                'Workspace cleanup.'},
)


def _with_cleanup_fields(entry: dict[str, str]) -> dict[str, str]:
    enriched = dict(entry)
    review = enriched.get("expiration_or_review_note") or enriched.get("review_note") or ""
    enriched["expiration_or_review_note"] = review or "Review with the owning admin/setup surface before removal."
    budget = enriched.get("budget", "")
    if budget == "admin_setup":
        active_route = "Settings/Admin Setup Health"
    elif budget == "account_usage_fallback":
        active_route = "Confirmed Account Usage fallback"
    elif budget == "metadata_probe":
        active_route = "Explicit metadata probe diagnostic"
    else:
        active_route = "Explicit advanced diagnostics control"
    enriched.setdefault("active_ui_action_or_admin_route", active_route)
    enriched.setdefault("deletion_candidate", False)
    return enriched


SESSION_OPEN_ALLOWLIST = tuple(_with_cleanup_fields(entry) for entry in SESSION_OPEN_ALLOWLIST)

__all__ = ["SESSION_OPEN_ALLOWLIST"]
